In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive
Mounted at /content/drive

In [ ]:
import os

PROJECT_DIR = "/content/drive/MyDrive/PhishShieldAI"

os.makedirs(PROJECT_DIR, exist_ok=True)

print("Project directory:")
print(PROJECT_DIR)

print("\nContents:")
print(os.listdir(PROJECT_DIR))

Project directory:
/content/drive/MyDrive/PhishShieldAI

Contents:
['checkpoints', 'datasets', 'models', 'reports', 'experiment_logs']

In [ ]:
import os

folders = [
    "checkpoints/01_dataset_audit",
    "checkpoints/02_preprocessing",
    "checkpoints/03_feature_lock",
    "checkpoints/04_data_split",
    "checkpoints/05_random_forest",
    "checkpoints/06_xgboost",
    "checkpoints/07_mlp",
    "checkpoints/08_resmlp",
    "checkpoints/09_model_comparison",
    "checkpoints/10_final_model",

    "datasets/raw",
    "datasets/processed",
    "datasets/splits",

    "models",
    "reports",
    "experiment_logs"
]

for folder in folders:
    path = os.path.join(PROJECT_DIR, folder)
    os.makedirs(path, exist_ok=True)

print("PhishShield AI directory structure created successfully.")

PhishShield AI directory structure created successfully.

In [ ]:
for root, dirs, files in os.walk(PROJECT_DIR):

    level = root.replace(PROJECT_DIR, "").count(os.sep)
    indent = "    " * level

    print(f"{indent}{os.path.basename(root)}/")

    for file in files:
        print(f"{indent}    {file}")

PhishShieldAI/
    checkpoints/
        01_dataset_audit/
        02_preprocessing/
        03_feature_lock/
        04_data_split/
        05_random_forest/
        06_xgboost/
        07_mlp/
        08_resmlp/
        09_model_comparison/
        10_final_model/
    datasets/
        raw/
        processed/
        splits/
    models/
    reports/
    experiment_logs/

In [ ]:
import pandas as pd
import os

DATASET_PATH = os.path.join(
    PROJECT_DIR,
    "datasets",
    "raw",
    "Phishing_Legitimate_full(4).csv"
)

df = pd.read_csv("/content/Phishing_Legitimate_full.csv")

print("Dataset loaded successfully.")
print("Path:", "/content/Phishing_Legitimate_full.csv")
print("Shape:", df.shape)

Dataset loaded successfully.
Path: /content/Phishing_Legitimate_full.csv
Shape: (10000, 50)

In [ ]:
print("=" * 70)
print("PHISHSHIELD AI — DATASET IDENTITY")
print("=" * 70)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

print("\nColumn names:")
for i, column in enumerate(df.columns, start=1):
    print(f"{i:2d}. {column}")

======================================================================
PHISHSHIELD AI — DATASET IDENTITY
======================================================================
Rows    : 10000
Columns : 50

Column names:
 1. id
 2. NumDots
 3. SubdomainLevel
 4. PathLevel
 5. UrlLength
 6. NumDash
 7. NumDashInHostname
 8. AtSymbol
 9. TildeSymbol
10. NumUnderscore
11. NumPercent
12. NumQueryComponents
13. NumAmpersand
14. NumHash
15. NumNumericChars
16. NoHttps
17. RandomString
18. IpAddress
19. DomainInSubdomains
20. DomainInPaths
21. HttpsInHostname
22. HostnameLength
23. PathLength
24. QueryLength
25. DoubleSlashInPath
26. NumSensitiveWords
27. EmbeddedBrandName
28. PctExtHyperlinks
29. PctExtResourceUrls
30. ExtFavicon
31. InsecureForms
32. RelativeFormAction
33. ExtFormAction
34. AbnormalFormAction
35. PctNullSelfRedirectHyperlinks
36. FrequentDomainNameMismatch
37. FakeLinkInStatusBar
38. RightClickDisabled
39. PopUpWindow
40. SubmitInfoToEmail
41. IframeOrFrame
42. MissingTitle
43. ImagesOnlyInForm
44. SubdomainLevelRT
45. UrlLengthRT
46. PctExtResourceUrlsRT
47. AbnormalExtFormActionR
48. ExtMetaScriptLinkRT
49. PctExtNullSelfRedirectHyperlinksRT
50. CLASS_LABEL

In [ ]:
TARGET_COLUMN = "CLASS_LABEL"
ID_COLUMN = "id"

feature_columns = [
    col for col in df.columns
    if col not in [ID_COLUMN, TARGET_COLUMN]
]

print("ID column:")
print(ID_COLUMN)

print("\nTarget column:")
print(TARGET_COLUMN)

print("\nNumber of feature columns:")
print(len(feature_columns))

print("\nFeatures:")
for i, feature in enumerate(feature_columns, start=1):
    print(f"{i:2d}. {feature}")

ID column:
id

Target column:
CLASS_LABEL

Number of feature columns:
48

Features:
 1. NumDots
 2. SubdomainLevel
 3. PathLevel
 4. UrlLength
 5. NumDash
 6. NumDashInHostname
 7. AtSymbol
 8. TildeSymbol
 9. NumUnderscore
10. NumPercent
11. NumQueryComponents
12. NumAmpersand
13. NumHash
14. NumNumericChars
15. NoHttps
16. RandomString
17. IpAddress
18. DomainInSubdomains
19. DomainInPaths
20. HttpsInHostname
21. HostnameLength
22. PathLength
23. QueryLength
24. DoubleSlashInPath
25. NumSensitiveWords
26. EmbeddedBrandName
27. PctExtHyperlinks
28. PctExtResourceUrls
29. ExtFavicon
30. InsecureForms
31. RelativeFormAction
32. ExtFormAction
33. AbnormalFormAction
34. PctNullSelfRedirectHyperlinks
35. FrequentDomainNameMismatch
36. FakeLinkInStatusBar
37. RightClickDisabled
38. PopUpWindow
39. SubmitInfoToEmail
40. IframeOrFrame
41. MissingTitle
42. ImagesOnlyInForm
43. SubdomainLevelRT
44. UrlLengthRT
45. PctExtResourceUrlsRT
46. AbnormalExtFormActionR
47. ExtMetaScriptLinkRT
48. PctExtNullSelfRedirectHyperlinksRT

In [ ]:
print("=" * 70)
print("DATA TYPES")
print("=" * 70)

print(df.dtypes)

======================================================================
DATA TYPES
======================================================================
id                                      int64
NumDots                                 int64
SubdomainLevel                          int64
PathLevel                               int64
UrlLength                               int64
NumDash                                 int64
NumDashInHostname                       int64
AtSymbol                                int64
TildeSymbol                             int64
NumUnderscore                           int64
NumPercent                              int64
NumQueryComponents                      int64
NumAmpersand                            int64
NumHash                                 int64
NumNumericChars                         int64
NoHttps                                 int64
RandomString                            int64
IpAddress                               int64
DomainInSubdomains                      int64
DomainInPaths                           int64
HttpsInHostname                         int64
HostnameLength                          int64
PathLength                              int64
QueryLength                             int64
DoubleSlashInPath                       int64
NumSensitiveWords                       int64
EmbeddedBrandName                       int64
PctExtHyperlinks                      float64
PctExtResourceUrls                    float64
ExtFavicon                              int64
InsecureForms                           int64
RelativeFormAction                      int64
ExtFormAction                           int64
AbnormalFormAction                      int64
PctNullSelfRedirectHyperlinks         float64
FrequentDomainNameMismatch              int64
FakeLinkInStatusBar                     int64
RightClickDisabled                      int64
PopUpWindow                             int64
SubmitInfoToEmail                       int64
IframeOrFrame                           int64
MissingTitle                            int64
ImagesOnlyInForm                        int64
SubdomainLevelRT                        int64
UrlLengthRT                             int64
PctExtResourceUrlsRT                    int64
AbnormalExtFormActionR                  int64
ExtMetaScriptLinkRT                     int64
PctExtNullSelfRedirectHyperlinksRT      int64
CLASS_LABEL                             int64
dtype: object

In [ ]:
print("\nData type counts:")
print(df.dtypes.value_counts())

Data type counts:
int64      47
float64     3
Name: count, dtype: int64

In [ ]:
missing = df.isnull().sum()

missing_report = pd.DataFrame({
    "Feature": missing.index,
    "Missing_Count": missing.values,
    "Missing_Percentage": (
        missing.values / len(df) * 100
    )
})

missing_report = missing_report.sort_values(
    by="Missing_Count",
    ascending=False
)

print(missing_report.to_string(index=False))

                           Feature  Missing_Count  Missing_Percentage
                                id              0                 0.0
                           NumDots              0                 0.0
                    SubdomainLevel              0                 0.0
                         PathLevel              0                 0.0
                         UrlLength              0                 0.0
                           NumDash              0                 0.0
                 NumDashInHostname              0                 0.0
                          AtSymbol              0                 0.0
                       TildeSymbol              0                 0.0
                     NumUnderscore              0                 0.0
                        NumPercent              0                 0.0
                NumQueryComponents              0                 0.0
                      NumAmpersand              0                 0.0
                           NumHash              0                 0.0
                   NumNumericChars              0                 0.0
                           NoHttps              0                 0.0
                      RandomString              0                 0.0
                         IpAddress              0                 0.0
                DomainInSubdomains              0                 0.0
                     DomainInPaths              0                 0.0
                   HttpsInHostname              0                 0.0
                    HostnameLength              0                 0.0
                        PathLength              0                 0.0
                       QueryLength              0                 0.0
                 DoubleSlashInPath              0                 0.0
                 NumSensitiveWords              0                 0.0
                 EmbeddedBrandName              0                 0.0
                  PctExtHyperlinks              0                 0.0
                PctExtResourceUrls              0                 0.0
                        ExtFavicon              0                 0.0
                     InsecureForms              0                 0.0
                RelativeFormAction              0                 0.0
                     ExtFormAction              0                 0.0
                AbnormalFormAction              0                 0.0
     PctNullSelfRedirectHyperlinks              0                 0.0
        FrequentDomainNameMismatch              0                 0.0
               FakeLinkInStatusBar              0                 0.0
                RightClickDisabled              0                 0.0
                       PopUpWindow              0                 0.0
                 SubmitInfoToEmail              0                 0.0
                     IframeOrFrame              0                 0.0
                      MissingTitle              0                 0.0
                  ImagesOnlyInForm              0                 0.0
                  SubdomainLevelRT              0                 0.0
                       UrlLengthRT              0                 0.0
              PctExtResourceUrlsRT              0                 0.0
            AbnormalExtFormActionR              0                 0.0
               ExtMetaScriptLinkRT              0                 0.0
PctExtNullSelfRedirectHyperlinksRT              0                 0.0
                       CLASS_LABEL              0                 0.0

In [ ]:
print(
    "Total missing values:",
    df.isnull().sum().sum()
)

Total missing values: 0

In [ ]:
print("=" * 70)
print("DUPLICATE AUDIT")
print("=" * 70)

print("Completely duplicated rows:")
print(df.duplicated().sum())

print("\nDuplicated IDs:")
print(df["id"].duplicated().sum())

======================================================================
DUPLICATE AUDIT
======================================================================
Completely duplicated rows:
0

Duplicated IDs:
0

In [ ]:
print("=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)

print(df[TARGET_COLUMN].value_counts())

print("\nPercentage:")
print(
    df[TARGET_COLUMN]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

======================================================================
TARGET DISTRIBUTION
======================================================================
CLASS_LABEL
1    5000
0    5000
Name: count, dtype: int64

Percentage:
CLASS_LABEL
1    50.0
0    50.0
Name: proportion, dtype: float64

In [ ]:
pd.set_option("display.max_columns", None)

display(df.head(10))

,id,NumDots,SubdomainLevel,PathLevel,UrlLength,NumDash,NumDashInHostname,AtSymbol,TildeSymbol,NumUnderscore,NumPercent,NumQueryComponents,NumAmpersand,NumHash,NumNumericChars,NoHttps,RandomString,IpAddress,DomainInSubdomains,DomainInPaths,HttpsInHostname,HostnameLength,PathLength,QueryLength,DoubleSlashInPath,NumSensitiveWords,EmbeddedBrandName,PctExtHyperlinks,PctExtResourceUrls,ExtFavicon,InsecureForms,RelativeFormAction,ExtFormAction,AbnormalFormAction,PctNullSelfRedirectHyperlinks,FrequentDomainNameMismatch,FakeLinkInStatusBar,RightClickDisabled,PopUpWindow,SubmitInfoToEmail,IframeOrFrame,MissingTitle,ImagesOnlyInForm,SubdomainLevelRT,UrlLengthRT,PctExtResourceUrlsRT,AbnormalExtFormActionR,ExtMetaScriptLinkRT,PctExtNullSelfRedirectHyperlinksRT,CLASS_LABEL
0,1,3,1,5,72,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,21,44,0,0,0,0,0.000000,0.250000,1,1,0,0,0,0.000,0,0,0,0,0,0,0,1,1,0,1,1,-1,1,1
1,2,3,1,3,144,0,0,0,0,2,0,2,1,0,41,1,0,0,0,0,0,17,16,103,0,1,0,0.000000,0.000000,0,1,0,0,0,0.000,0,0,0,0,0,0,0,0,1,-1,1,1,1,1,1
2,3,3,1,2,58,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,27,24,0,0,0,0,0.375000,1.000000,1,1,0,0,0,0.000,0,0,0,0,0,0,0,0,1,0,-1,1,-1,0,1
3,4,3,1,6,79,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,22,50,0,0,0,1,1.000000,0.095238,1,1,0,0,0,0.000,1,0,0,0,1,0,0,0,1,-1,1,1,1,-1,1
4,5,3,0,4,46,0,0,0,0,0,0,0,0,0,2,1,1,0,0,1,0,10,29,0,0,0,0,1.000000,1.000000,0,0,0,1,0,0.000,1,0,0,0,0,1,0,0,1,1,-1,0,-1,-1,1
5,6,3,1,1,42,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,23,12,0,0,0,0,0.100000,1.000000,1,1,0,0,0,0.000,0,0,0,0,0,1,1,0,1,1,1,1,-1,1,1
6,7,2,0,5,60,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,17,36,0,0,0,1,0.909091,1.000000,0,1,0,0,0,0.000,1,0,0,0,0,0,0,0,1,0,1,1,-1,-1,1
7,8,1,0,3,30,0,0,0,0,0,0,0,0,0,3,1,1,0,0,1,0,12,11,0,0,0,0,0.000000,0.000000,0,1,0,0,0,0.000,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1
8,9,8,7,2,76,1,1,0,0,0,0,0,0,0,2,1,1,0,1,1,0,65,4,0,0,0,0,0.000000,0.000000,0,1,0,0,0,0.975,0,0,0,0,0,0,0,0,-1,-1,1,1,1,-1,1
9,10,2,0,2,46,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,14,25,0,0,0,1,1.000000,1.000000,1,1,0,0,0,0.000,1,0,0,0,0,0,0,0,1,1,1,1,-1,-1,1

In [ ]:
display(df.tail(10))

,id,NumDots,SubdomainLevel,PathLevel,UrlLength,NumDash,NumDashInHostname,AtSymbol,TildeSymbol,NumUnderscore,NumPercent,NumQueryComponents,NumAmpersand,NumHash,NumNumericChars,NoHttps,RandomString,IpAddress,DomainInSubdomains,DomainInPaths,HttpsInHostname,HostnameLength,PathLength,QueryLength,DoubleSlashInPath,NumSensitiveWords,EmbeddedBrandName,PctExtHyperlinks,PctExtResourceUrls,ExtFavicon,InsecureForms,RelativeFormAction,ExtFormAction,AbnormalFormAction,PctNullSelfRedirectHyperlinks,FrequentDomainNameMismatch,FakeLinkInStatusBar,RightClickDisabled,PopUpWindow,SubmitInfoToEmail,IframeOrFrame,MissingTitle,ImagesOnlyInForm,SubdomainLevelRT,UrlLengthRT,PctExtResourceUrlsRT,AbnormalExtFormActionR,ExtMetaScriptLinkRT,PctExtNullSelfRedirectHyperlinksRT,CLASS_LABEL
9990,9991,3,1,3,48,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,18,23,0,0,0,0,0.000000,0.400000,0,1,0,0,0,0.000000,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0
9991,9992,3,1,2,42,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,17,18,0,0,0,0,0.016949,0.183486,0,1,0,1,0,0.042373,0,0,0,0,0,1,0,0,1,1,1,0,0,1,0
9992,9993,3,1,2,49,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,19,23,0,0,0,0,0.142857,0.454545,0,0,0,0,0,0.000000,0,0,0,0,0,0,0,0,1,1,1,1,0,1,0
9993,9994,2,1,1,45,3,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,17,21,0,0,0,0,0.016129,0.123077,0,1,0,0,0,0.064516,0,0,0,0,0,1,0,0,1,1,1,1,0,1,0
9994,9995,2,1,3,58,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,16,28,6,0,0,0,0.096386,0.144330,0,0,0,0,0,0.000000,0,0,0,0,1,0,0,0,1,0,1,1,0,1,0
9995,9996,3,1,1,50,0,0,0,0,0,0,2,1,0,9,1,0,0,0,0,0,15,10,17,0,0,0,0.096774,0.757143,1,1,0,0,0,0.000000,0,0,0,0,0,0,0,0,1,1,-1,1,0,1,0
9996,9997,2,1,4,59,1,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,19,33,0,0,0,0,0.161290,0.275862,0,1,0,0,0,0.129032,0,0,0,0,0,1,0,0,1,0,0,1,0,1,0
9997,9998,2,1,4,57,0,0,0,0,0,0,0,0,0,6,1,1,0,0,0,0,16,34,0,0,0,0,0.070423,0.500000,0,1,0,0,0,0.056338,0,0,0,0,0,0,0,0,1,0,1,1,0,1,0
9998,9999,3,1,1,49,0,0,0,0,0,0,1,0,0,3,1,0,0,0,0,0,15,13,13,0,0,0,0.166667,0.428571,0,1,1,0,0,0.000000,0,0,0,0,0,1,0,0,1,1,0,1,0,1,0
9999,10000,3,1,2,52,3,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,10,35,0,0,0,0,0.089623,0.042553,0,1,0,0,0,0.004717,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0

In [ ]:
numeric_features = df[feature_columns]

stats = numeric_features.describe().T

display(stats)

,count,mean,std,min,25%,50%,75%,max
NumDots,10000.0,2.445100,1.346836,1.0,2.000000,2.000000,3.000000,21.0
SubdomainLevel,10000.0,0.586800,0.751214,0.0,0.000000,1.000000,1.000000,14.0
PathLevel,10000.0,3.300300,1.863241,0.0,2.000000,3.000000,4.000000,18.0
UrlLength,10000.0,70.264100,33.369877,12.0,48.000000,62.000000,84.000000,253.0
NumDash,10000.0,1.818000,3.106258,0.0,0.000000,0.000000,2.000000,55.0
NumDashInHostname,10000.0,0.138900,0.545744,0.0,0.000000,0.000000,0.000000,9.0
AtSymbol,10000.0,0.000300,0.017319,0.0,0.000000,0.000000,0.000000,1.0
TildeSymbol,10000.0,0.013100,0.113709,0.0,0.000000,0.000000,0.000000,1.0
NumUnderscore,10000.0,0.323200,1.114660,0.0,0.000000,0.000000,0.000000,18.0
NumPercent,10000.0,0.073800,0.622248,0.0,0.000000,0.000000,0.000000,19.0
NumQueryComponents,10000.0,0.458600,1.344793,0.0,0.000000,0.000000,0.000000,23.0
NumAmpersand,10000.0,0.277200,1.117356,0.0,0.000000,0.000000,0.000000,22.0
NumHash,10000.0,0.002300,0.047906,0.0,0.000000,0.000000,0.000000,1.0
NumNumericChars,10000.0,5.810300,9.617877,0.0,0.000000,2.000000,8.000000,111.0
NoHttps,10000.0,0.988800,0.105241,0.0,1.000000,1.000000,1.000000,1.0
RandomString,10000.0,0.525200,0.499390,0.0,0.000000,1.000000,1.000000,1.0
IpAddress,10000.0,0.017200,0.130023,0.0,0.000000,0.000000,0.000000,1.0
DomainInSubdomains,10000.0,0.022200,0.147341,0.0,0.000000,0.000000,0.000000,1.0
DomainInPaths,10000.0,0.428900,0.494944,0.0,0.000000,0.000000,1.000000,1.0
HttpsInHostname,10000.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
HostnameLength,10000.0,18.824300,8.116540,4.0,14.000000,18.000000,22.000000,137.0
PathLength,10000.0,35.564900,24.588502,0.0,18.000000,30.000000,48.000000,161.0
QueryLength,10000.0,8.606500,24.313053,0.0,0.000000,0.000000,0.000000,188.0
DoubleSlashInPath,10000.0,0.000900,0.029988,0.0,0.000000,0.000000,0.000000,1.0
NumSensitiveWords,10000.0,0.109300,0.368737,0.0,0.000000,0.000000,0.000000,3.0
EmbeddedBrandName,10000.0,0.057100,0.232045,0.0,0.000000,0.000000,0.000000,1.0
PctExtHyperlinks,10000.0,0.241334,0.342370,0.0,0.000000,0.071429,0.315874,1.0
PctExtResourceUrls,10000.0,0.392932,0.387292,0.0,0.030303,0.247511,0.785714,1.0
ExtFavicon,10000.0,0.167200,0.373173,0.0,0.000000,0.000000,0.000000,1.0
InsecureForms,10000.0,0.844000,0.362873,0.0,1.000000,1.000000,1.000000,1.0
RelativeFormAction,10000.0,0.248700,0.432281,0.0,0.000000,0.000000,0.000000,1.0
ExtFormAction,10000.0,0.101800,0.302400,0.0,0.000000,0.000000,0.000000,1.0
AbnormalFormAction,10000.0,0.057600,0.232997,0.0,0.000000,0.000000,0.000000,1.0
PctNullSelfRedirectHyperlinks,10000.0,0.136136,0.312413,0.0,0.000000,0.000000,0.047619,1.0
FrequentDomainNameMismatch,10000.0,0.215300,0.411051,0.0,0.000000,0.000000,0.000000,1.0
FakeLinkInStatusBar,10000.0,0.005500,0.073961,0.0,0.000000,0.000000,0.000000,1.0
RightClickDisabled,10000.0,0.014000,0.117496,0.0,0.000000,0.000000,0.000000,1.0
PopUpWindow,10000.0,0.004900,0.069832,0.0,0.000000,0.000000,0.000000,1.0
SubmitInfoToEmail,10000.0,0.128800,0.334995,0.0,0.000000,0.000000,0.000000,1.0
IframeOrFrame,10000.0,0.339600,0.473597,0.0,0.000000,0.000000,1.000000,1.0
MissingTitle,10000.0,0.032200,0.176540,0.0,0.000000,0.000000,0.000000,1.0
ImagesOnlyInForm,10000.0,0.030400,0.171694,0.0,0.000000,0.000000,0.000000,1.0
SubdomainLevelRT,10000.0,0.956600,0.248037,-1.0,1.000000,1.000000,1.000000,1.0
UrlLengthRT,10000.0,0.020200,0.820036,-1.0,-1.000000,0.000000,1.000000,1.0
PctExtResourceUrlsRT,10000.0,0.353300,0.888908,-1.0,-1.000000,1.000000,1.000000,1.0
AbnormalExtFormActionR,10000.0,0.793200,0.521019,-1.0,1.000000,1.000000,1.000000,1.0
ExtMetaScriptLinkRT,10000.0,0.173400,0.755771,-1.0,0.000000,0.000000,1.000000,1.0
PctExtNullSelfRedirectHyperlinksRT,10000.0,0.314100,0.897843,-1.0,-1.000000,1.000000,1.000000,1.0

In [ ]:
unique_report = pd.DataFrame({
    "Feature": feature_columns,
    "Unique_Values": [
        df[col].nunique()
        for col in feature_columns
    ],
    "Min": [
        df[col].min()
        for col in feature_columns
    ],
    "Max": [
        df[col].max()
        for col in feature_columns
    ]
})

display(unique_report)

                               Feature  Unique_Values   Min    Max
0                              NumDots             17   1.0   21.0
1                       SubdomainLevel             13   0.0   14.0
2                            PathLevel             18   0.0   18.0
3                            UrlLength            226  12.0  253.0
4                              NumDash             25   0.0   55.0
5                    NumDashInHostname             10   0.0    9.0
6                             AtSymbol              2   0.0    1.0
7                          TildeSymbol              2   0.0    1.0
8                        NumUnderscore             16   0.0   18.0
9                           NumPercent             14   0.0   19.0
10                  NumQueryComponents             19   0.0   23.0
11                        NumAmpersand             16   0.0   22.0
12                             NumHash              2   0.0    1.0
13                     NumNumericChars             82   0.0  111.0
14                             NoHttps              2   0.0    1.0
15                        RandomString              2   0.0    1.0
16                           IpAddress              2   0.0    1.0
17                  DomainInSubdomains              2   0.0    1.0
18                       DomainInPaths              2   0.0    1.0
19                     HttpsInHostname              1   0.0    0.0
20                      HostnameLength             74   4.0  137.0
21                          PathLength            147   0.0  161.0
22                         QueryLength            164   0.0  188.0
23                   DoubleSlashInPath              2   0.0    1.0
24                   NumSensitiveWords              4   0.0    3.0
25                   EmbeddedBrandName              2   0.0    1.0
26                    PctExtHyperlinks           2510   0.0    1.0
27                  PctExtResourceUrls           1489   0.0    1.0
28                          ExtFavicon              2   0.0    1.0
29                       InsecureForms              2   0.0    1.0
30                  RelativeFormAction              2   0.0    1.0
31                       ExtFormAction              2   0.0    1.0
32                  AbnormalFormAction              2   0.0    1.0
33       PctNullSelfRedirectHyperlinks           1311   0.0    1.0
34          FrequentDomainNameMismatch              2   0.0    1.0
35                 FakeLinkInStatusBar              2   0.0    1.0
36                  RightClickDisabled              2   0.0    1.0
37                         PopUpWindow              2   0.0    1.0
38                   SubmitInfoToEmail              2   0.0    1.0
39                       IframeOrFrame              2   0.0    1.0
40                        MissingTitle              2   0.0    1.0
41                    ImagesOnlyInForm              2   0.0    1.0
42                    SubdomainLevelRT              3  -1.0    1.0
43                         UrlLengthRT              3  -1.0    1.0
44                PctExtResourceUrlsRT              3  -1.0    1.0
45              AbnormalExtFormActionR              3  -1.0    1.0
46                 ExtMetaScriptLinkRT              3  -1.0    1.0
47  PctExtNullSelfRedirectHyperlinksRT              3  -1.0    1.0

In [ ]:
binary_features = []

for feature in feature_columns:

    unique_values = set(df[feature].dropna().unique())

    if unique_values.issubset({0, 1}):
        binary_features.append(feature)

print("Binary features:")
for feature in binary_features:
    print("-", feature)

print("\nNumber of binary features:", len(binary_features))

Binary features:
- AtSymbol
- TildeSymbol
- NumHash
- NoHttps
- RandomString
- IpAddress
- DomainInSubdomains
- DomainInPaths
- HttpsInHostname
- DoubleSlashInPath
- EmbeddedBrandName
- ExtFavicon
- InsecureForms
- RelativeFormAction
- ExtFormAction
- AbnormalFormAction
- FrequentDomainNameMismatch
- FakeLinkInStatusBar
- RightClickDisabled
- PopUpWindow
- SubmitInfoToEmail
- IframeOrFrame
- MissingTitle
- ImagesOnlyInForm

Number of binary features: 24

In [ ]:
constant_features = [
    feature
    for feature in feature_columns
    if df[feature].nunique() <= 1
]

print("Constant features:")
print(constant_features)

print("\nNumber of constant features:")
print(len(constant_features))

Constant features:
['HttpsInHostname']

Number of constant features:
1

In [ ]:
class_summary = {}

for feature in feature_columns:

    class_summary[feature] = {
        "class_0_mean": df.loc[
            df[TARGET_COLUMN] == 0, feature
        ].mean(),

        "class_1_mean": df.loc[
            df[TARGET_COLUMN] == 1, feature
        ].mean(),

        "difference": (
            df.loc[df[TARGET_COLUMN] == 1, feature].mean()
            -
            df.loc[df[TARGET_COLUMN] == 0, feature].mean()
        )
    }

class_summary_df = pd.DataFrame.from_dict(
    class_summary,
    orient="index"
)

class_summary_df = class_summary_df.sort_values(
    "difference",
    key=abs,
    ascending=False
)

display(class_summary_df)

                                    class_0_mean  class_1_mean  difference
UrlLength                              72.749800     67.778400   -4.971400
QueryLength                            10.564200      6.648800   -3.915400
PathLength                             37.436600     33.693200   -3.743400
HostnameLength                         17.451400     20.197200    2.745800
NumDash                                 2.974200      0.661800   -2.312400
PctExtNullSelfRedirectHyperlinksRT      0.799400     -0.171200   -0.970600
PathLevel                               2.872800      3.727800    0.855000
NumDots                                 2.049000      2.841200    0.792200
NumQueryComponents                      0.656800      0.260400   -0.396400
FrequentDomainNameMismatch              0.024600      0.406000    0.381400
NumNumericChars                         5.626400      5.994200    0.367800
UrlLengthRT                            -0.118800      0.159200    0.278000
SubmitInfoToEmail                       0.248600      0.009000   -0.239600
InsecureForms                           0.729200      0.958800    0.229600
IframeOrFrame                           0.451000      0.228200   -0.222800
NumUnderscore                           0.433400      0.213000   -0.220400
PctNullSelfRedirectHyperlinks           0.029044      0.243227    0.214184
AbnormalExtFormActionR                  0.696400      0.890000    0.193600
NumSensitiveWords                       0.015200      0.203400    0.188200
NumAmpersand                            0.368200      0.186200   -0.182000
PctExtHyperlinks                        0.152416      0.330253    0.177837
ExtMetaScriptLinkRT                     0.089400      0.257400    0.168000
NumDashInHostname                       0.056800      0.221000    0.164200
DomainInPaths                           0.487400      0.370400   -0.117000
PctExtResourceUrlsRT                    0.307000      0.399600    0.092600
NumPercent                              0.116400      0.031200   -0.085200
RandomString                            0.567800      0.482600   -0.085200
RelativeFormAction                      0.284400      0.213000   -0.071400
AbnormalFormAction                      0.091400      0.023800   -0.067600
EmbeddedBrandName                       0.024200      0.090000    0.065800
SubdomainLevel                          0.554400      0.619200    0.064800
ExtFormAction                           0.133600      0.070000   -0.063600
ExtFavicon                              0.141400      0.193000    0.051600
MissingTitle                            0.011600      0.052800    0.041200
SubdomainLevelRT                        0.975400      0.937800   -0.037600
IpAddress                               0.000000      0.034400    0.034400
DomainInSubdomains                      0.007400      0.037000    0.029600
TildeSymbol                             0.002200      0.024000    0.021800
RightClickDisabled                      0.005200      0.022800    0.017600
PctExtResourceUrls                      0.401422      0.384442   -0.016980
NoHttps                                 0.996400      0.981200   -0.015200
PopUpWindow                             0.009600      0.000200   -0.009400
NumHash                                 0.000000      0.004600    0.004600
FakeLinkInStatusBar                     0.006600      0.004400   -0.002200
DoubleSlashInPath                       0.000200      0.001600    0.001400
AtSymbol                                0.000600      0.000000   -0.000600
ImagesOnlyInForm                        0.030600      0.030200   -0.000400
HttpsInHostname                         0.000000      0.000000    0.000000

In [ ]:
AUDIT_DIR = os.path.join(
    PROJECT_DIR,
    "checkpoints",
    "01_dataset_audit"
)

os.makedirs(AUDIT_DIR, exist_ok=True)

# Save dataset structure
df.info(
    buf=open(
        os.path.join(
            AUDIT_DIR,
            "dataset_info.txt"
        ),
        "w"
    )
)

# Save descriptive statistics
stats.to_csv(
    os.path.join(
        AUDIT_DIR,
        "descriptive_statistics.csv"
    )
)

# Save missing-value report
missing_report.to_csv(
    os.path.join(
        AUDIT_DIR,
        "missing_values.csv"
    ),
    index=False
)

# Save unique-value report
unique_report.to_csv(
    os.path.join(
        AUDIT_DIR,
        "unique_values.csv"
    ),
    index=False
)

# Save class distribution
df[TARGET_COLUMN].value_counts().to_csv(
    os.path.join(
        AUDIT_DIR,
        "class_distribution.csv"
    )
)

# Save class feature analysis
class_summary_df.to_csv(
    os.path.join(
        AUDIT_DIR,
        "feature_class_analysis.csv"
    )
)

print("Dataset audit checkpoint saved successfully.")
print(AUDIT_DIR)

Dataset audit checkpoint saved successfully.
/content/drive/MyDrive/PhishShieldAI/checkpoints/01_dataset_audit

In [ ]:
# ============================================================
# CELL 17 — SAVE DATASET ANALYSIS CHECKPOINT
# ============================================================

import os
import json
from datetime import datetime

CHECKPOINT_DIR = "/content/drive/MyDrive/PhishShield_AI/checkpoints"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

checkpoint = {
    "stage": "dataset_analysis_completed",

    "dataset_rows": int(df.shape[0]),
    "dataset_columns": int(df.shape[1]),

    "id_column": "id",
    "target_column": "CLASS_LABEL",

    "feature_count": 48,

    "class_distribution": {
        str(k): int(v)
        for k, v in df["CLASS_LABEL"].value_counts().to_dict().items()
    },

    "constant_features": [
        "HttpsInHostname"
    ],

    "missing_values_verified": True,

    "binary_feature_count": 24,

    "dataset_status": "Ready for preprocessing and model development",

    "timestamp": datetime.now().isoformat()
}

checkpoint_path = os.path.join(
    CHECKPOINT_DIR,
    "01_dataset_analysis_checkpoint.json"
)

with open(checkpoint_path, "w") as f:
    json.dump(checkpoint, f, indent=4)

print("=" * 70)
print("PHISHSHIELD AI — CHECKPOINT SAVED")
print("=" * 70)
print(f"Stage      : Dataset Analysis Completed")
print(f"Rows       : {df.shape[0]}")
print(f"Columns    : {df.shape[1]}")
print(f"Features   : 48")
print(f"Target     : CLASS_LABEL")
print(f"Checkpoint : {checkpoint_path}")
print("=" * 70)

======================================================================
PHISHSHIELD AI — CHECKPOINT SAVED
======================================================================
Stage      : Dataset Analysis Completed
Rows       : 10000
Columns    : 50
Features   : 48
Target     : CLASS_LABEL
Checkpoint : /content/drive/MyDrive/PhishShield_AI/checkpoints/01_dataset_analysis_checkpoint.json
======================================================================

In [ ]:
# ============================================================
# CELL 18 — PREPARE FEATURES AND TARGET
# ============================================================

TARGET = "CLASS_LABEL"
ID_COLUMN = "id"
CONSTANT_FEATURE = "HttpsInHostname"

# ------------------------------------------------------------
# Feature columns
# ------------------------------------------------------------

feature_columns = [
    col for col in df.columns
    if col not in [ID_COLUMN, TARGET, CONSTANT_FEATURE]
]

X = df[feature_columns].copy()
y = df[TARGET].copy()

print("=" * 70)
print("PHISHSHIELD AI — MODEL DATA PREPARATION")
print("=" * 70)

print(f"Original dataset columns : {df.shape[1]}")
print(f"ID column removed        : {ID_COLUMN}")
print(f"Constant feature removed: {CONSTANT_FEATURE}")
print(f"Target column            : {TARGET}")
print(f"Final feature count      : {X.shape[1]}")
print(f"Samples                  : {X.shape[0]}")

print("\nClass distribution:")
print(y.value_counts().sort_index())

print("\nFeature columns:")
for i, feature in enumerate(feature_columns, start=1):
    print(f"{i:2}. {feature}")

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

assert ID_COLUMN not in X.columns
assert CONSTANT_FEATURE not in X.columns
assert TARGET not in X.columns
assert X.shape[1] == 47
assert len(X) == len(y)

print("\n" + "=" * 70)
print("VALIDATION PASSED")
print("X shape:", X.shape)
print("y shape:", y.shape)
print("47 model features confirmed")
print("=" * 70)

======================================================================
PHISHSHIELD AI — MODEL DATA PREPARATION
======================================================================
Original dataset columns : 50
ID column removed        : id
Constant feature removed: HttpsInHostname
Target column            : CLASS_LABEL
Final feature count      : 47
Samples                  : 10000

Class distribution:
CLASS_LABEL
0    5000
1    5000
Name: count, dtype: int64

Feature columns:
 1. NumDots
 2. SubdomainLevel
 3. PathLevel
 4. UrlLength
 5. NumDash
 6. NumDashInHostname
 7. AtSymbol
 8. TildeSymbol
 9. NumUnderscore
10. NumPercent
11. NumQueryComponents
12. NumAmpersand
13. NumHash
14. NumNumericChars
15. NoHttps
16. RandomString
17. IpAddress
18. DomainInSubdomains
19. DomainInPaths
20. HostnameLength
21. PathLength
22. QueryLength
23. DoubleSlashInPath
24. NumSensitiveWords
25. EmbeddedBrandName
26. PctExtHyperlinks
27. PctExtResourceUrls
28. ExtFavicon
29. InsecureForms
30. RelativeFormAction
31. ExtFormAction
32. AbnormalFormAction
33. PctNullSelfRedirectHyperlinks
34. FrequentDomainNameMismatch
35. FakeLinkInStatusBar
36. RightClickDisabled
37. PopUpWindow
38. SubmitInfoToEmail
39. IframeOrFrame
40. MissingTitle
41. ImagesOnlyInForm
42. SubdomainLevelRT
43. UrlLengthRT
44. PctExtResourceUrlsRT
45. AbnormalExtFormActionR
46. ExtMetaScriptLinkRT
47. PctExtNullSelfRedirectHyperlinksRT

======================================================================
VALIDATION PASSED
X shape: (10000, 47)
y shape: (10000,)
47 model features confirmed
======================================================================

In [ ]:
# ============================================================
# CELL 19 — TRAIN / VALIDATION / TEST SPLIT
# ============================================================

from sklearn.model_selection import train_test_split

RANDOM_STATE = 42

# ------------------------------------------------------------
# First split:
# 70% Training
# 30% Temporary
# ------------------------------------------------------------

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    stratify=y,
    random_state=RANDOM_STATE
)

# ------------------------------------------------------------
# Second split:
# Temporary 30% -> 15% Validation + 15% Test
# ------------------------------------------------------------

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=RANDOM_STATE
)

# ------------------------------------------------------------
# Display split information
# ------------------------------------------------------------

print("=" * 70)
print("PHISHSHIELD AI — DATASET SPLIT")
print("=" * 70)

print(f"Total samples      : {len(X)}")
print(f"Training samples    : {len(X_train)}")
print(f"Validation samples  : {len(X_val)}")
print(f"Test samples        : {len(X_test)}")

print("\nFeature dimensions:")
print(f"X_train : {X_train.shape}")
print(f"X_val   : {X_val.shape}")
print(f"X_test  : {X_test.shape}")

print("\nTraining class distribution:")
print(y_train.value_counts(normalize=True).sort_index())

print("\nValidation class distribution:")
print(y_val.value_counts(normalize=True).sort_index())

print("\nTest class distribution:")
print(y_test.value_counts(normalize=True).sort_index())

# ------------------------------------------------------------
# Validation checks
# ------------------------------------------------------------

assert X_train.shape == (7000, 47)
assert X_val.shape == (1500, 47)
assert X_test.shape == (1500, 47)

assert y_train.shape == (7000,)
assert y_val.shape == (1500,)
assert y_test.shape == (1500,)

assert set(X_train.columns) == set(X_val.columns)
assert set(X_train.columns) == set(X_test.columns)

print("\n" + "=" * 70)
print("SPLIT VALIDATION PASSED")
print("70% Training | 15% Validation | 15% Test")
print("47 features preserved in all three datasets")
print("=" * 70)

======================================================================
PHISHSHIELD AI — DATASET SPLIT
======================================================================
Total samples      : 10000
Training samples    : 7000
Validation samples  : 1500
Test samples        : 1500

Feature dimensions:
X_train : (7000, 47)
X_val   : (1500, 47)
X_test  : (1500, 47)

Training class distribution:
CLASS_LABEL
0    0.5
1    0.5
Name: proportion, dtype: float64

Validation class distribution:
CLASS_LABEL
0    0.5
1    0.5
Name: proportion, dtype: float64

Test class distribution:
CLASS_LABEL
0    0.5
1    0.5
Name: proportion, dtype: float64

======================================================================
SPLIT VALIDATION PASSED
70% Training | 15% Validation | 15% Test
47 features preserved in all three datasets
======================================================================

In [ ]:
# ============================================================
# CELL 20 — SAVE DATA SPLIT CHECKPOINT
# ============================================================

import os
import json
import joblib
from datetime import datetime

CHECKPOINT_DIR = "/content/drive/MyDrive/PhishShield_AI/checkpoints"
DATA_DIR = "/content/drive/MyDrive/PhishShield_AI/data"

os.makedirs(CHECKPOINT_DIR, exist_ok=True)
os.makedirs(DATA_DIR, exist_ok=True)

# ------------------------------------------------------------
# Save split datasets
# ------------------------------------------------------------

joblib.dump(X_train, os.path.join(DATA_DIR, "X_train.pkl"))
joblib.dump(X_val, os.path.join(DATA_DIR, "X_val.pkl"))
joblib.dump(X_test, os.path.join(DATA_DIR, "X_test.pkl"))

joblib.dump(y_train, os.path.join(DATA_DIR, "y_train.pkl"))
joblib.dump(y_val, os.path.join(DATA_DIR, "y_val.pkl"))
joblib.dump(y_test, os.path.join(DATA_DIR, "y_test.pkl"))

# ------------------------------------------------------------
# Save exact feature order
# ------------------------------------------------------------

feature_order = list(X_train.columns)

joblib.dump(
    feature_order,
    os.path.join(DATA_DIR, "feature_names.pkl")
)

# ------------------------------------------------------------
# Save split metadata
# ------------------------------------------------------------

split_checkpoint = {
    "stage": "data_split_completed",

    "dataset_size": 10000,

    "training_samples": 7000,
    "validation_samples": 1500,
    "test_samples": 1500,

    "feature_count": 47,

    "target": "CLASS_LABEL",

    "removed_columns": [
        "id",
        "HttpsInHostname"
    ],

    "random_state": 42,

    "split_ratio": {
        "train": 0.70,
        "validation": 0.15,
        "test": 0.15
    },

    "stratified": True,

    "class_distribution": {
        "train": {
            "0": int((y_train == 0).sum()),
            "1": int((y_train == 1).sum())
        },
        "validation": {
            "0": int((y_val == 0).sum()),
            "1": int((y_val == 1).sum())
        },
        "test": {
            "0": int((y_test == 0).sum()),
            "1": int((y_test == 1).sum())
        }
    },

    "feature_order": feature_order,

    "timestamp": datetime.now().isoformat()
}

checkpoint_path = os.path.join(
    CHECKPOINT_DIR,
    "02_data_split_checkpoint.json"
)

with open(checkpoint_path, "w") as f:
    json.dump(split_checkpoint, f, indent=4)

# ------------------------------------------------------------
# Final confirmation
# ------------------------------------------------------------

print("=" * 70)
print("PHISHSHIELD AI — DATA SPLIT CHECKPOINT SAVED")
print("=" * 70)

print(f"Training data   : {DATA_DIR}/X_train.pkl")
print(f"Validation data : {DATA_DIR}/X_val.pkl")
print(f"Test data       : {DATA_DIR}/X_test.pkl")
print(f"Feature order   : {DATA_DIR}/feature_names.pkl")
print(f"Checkpoint      : {checkpoint_path}")

print("\nSaved configuration:")
print("  Train      : 7000")
print("  Validation : 1500")
print("  Test       : 1500")
print("  Features   : 47")
print("  Random seed: 42")
print("  Stratified : True")

print("=" * 70)

======================================================================
PHISHSHIELD AI — DATA SPLIT CHECKPOINT SAVED
======================================================================
Training data   : /content/drive/MyDrive/PhishShield_AI/data/X_train.pkl
Validation data : /content/drive/MyDrive/PhishShield_AI/data/X_val.pkl
Test data       : /content/drive/MyDrive/PhishShield_AI/data/X_test.pkl
Feature order   : /content/drive/MyDrive/PhishShield_AI/data/feature_names.pkl
Checkpoint      : /content/drive/MyDrive/PhishShield_AI/checkpoints/02_data_split_checkpoint.json

Saved configuration:
  Train      : 7000
  Validation : 1500
  Test       : 1500
  Features   : 47
  Random seed: 42
  Stratified : True
======================================================================

In [ ]:
# ============================================================
# CELL 21 — BASELINE MODEL: LOGISTIC REGRESSION
# ============================================================

import numpy as np
import joblib

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

# ------------------------------------------------------------
# Create baseline pipeline
# ------------------------------------------------------------

baseline_model = Pipeline([
    ("scaler", StandardScaler()),
    (
        "classifier",
        LogisticRegression(
            max_iter=2000,
            random_state=42
        )
    )
])

# ------------------------------------------------------------
# Train ONLY on training data
# ------------------------------------------------------------

print("=" * 70)
print("PHISHSHIELD AI — LOGISTIC REGRESSION BASELINE")
print("=" * 70)

print("Training baseline model...")

baseline_model.fit(
    X_train,
    y_train
)

print("Training completed.")

# ------------------------------------------------------------
# Validation prediction
# ------------------------------------------------------------

y_val_pred = baseline_model.predict(X_val)
y_val_prob = baseline_model.predict_proba(X_val)[:, 1]

# ------------------------------------------------------------
# Evaluation
# ------------------------------------------------------------

accuracy = accuracy_score(y_val, y_val_pred)
precision = precision_score(y_val, y_val_pred)
recall = recall_score(y_val, y_val_pred)
f1 = f1_score(y_val, y_val_pred)
auc = roc_auc_score(y_val, y_val_prob)

print("\n" + "=" * 70)
print("VALIDATION RESULTS")
print("=" * 70)

print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1-Score  : {f1:.4f}")
print(f"ROC-AUC   : {auc:.4f}")

# ------------------------------------------------------------
# Save baseline model
# ------------------------------------------------------------

MODEL_DIR = "/content/drive/MyDrive/PhishShield_AI/models"
CHECKPOINT_DIR = "/content/drive/MyDrive/PhishShield_AI/checkpoints"

os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

baseline_model_path = os.path.join(
    MODEL_DIR,
    "logistic_regression_baseline.pkl"
)

joblib.dump(
    baseline_model,
    baseline_model_path
)

# ------------------------------------------------------------
# Save baseline results
# ------------------------------------------------------------

baseline_results = {
    "model": "Logistic Regression",
    "stage": "baseline",
    "validation_accuracy": float(accuracy),
    "validation_precision": float(precision),
    "validation_recall": float(recall),
    "validation_f1": float(f1),
    "validation_roc_auc": float(auc),
    "training_samples": len(X_train),
    "validation_samples": len(X_val),
    "feature_count": X_train.shape[1],
    "random_state": 42
}

baseline_checkpoint_path = os.path.join(
    CHECKPOINT_DIR,
    "03_logistic_baseline_checkpoint.json"
)

import json

with open(baseline_checkpoint_path, "w") as f:
    json.dump(baseline_results, f, indent=4)

print("\n" + "=" * 70)
print("BASELINE CHECKPOINT SAVED")
print("=" * 70)

print(f"Model      : {baseline_model_path}")
print(f"Checkpoint : {baseline_checkpoint_path}")

print("=" * 70)

======================================================================
PHISHSHIELD AI — LOGISTIC REGRESSION BASELINE
======================================================================
Training baseline model...
Training completed.

======================================================================
VALIDATION RESULTS
======================================================================
Accuracy  : 0.9513
Precision : 0.9448
Recall    : 0.9587
F1-Score  : 0.9517
ROC-AUC   : 0.9868

======================================================================
BASELINE CHECKPOINT SAVED
======================================================================
Model      : /content/drive/MyDrive/PhishShield_AI/models/logistic_regression_baseline.pkl
Checkpoint : /content/drive/MyDrive/PhishShield_AI/checkpoints/03_logistic_baseline_checkpoint.json
======================================================================

In [ ]:
# ============================================================
# CELL 22 — RANDOM FOREST MODEL
# ============================================================

import os
import json
import joblib

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

MODEL_DIR = "/content/drive/MyDrive/PhishShield_AI/models"
CHECKPOINT_DIR = "/content/drive/MyDrive/PhishShield_AI/checkpoints"

os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# ------------------------------------------------------------
# Create Random Forest
# ------------------------------------------------------------

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

print("=" * 70)
print("PHISHSHIELD AI — RANDOM FOREST")
print("=" * 70)

print("Training Random Forest...")
print("Training samples :", X_train.shape[0])
print("Features         :", X_train.shape[1])
print("Trees            : 300")

# ------------------------------------------------------------
# Train ONLY on training data
# ------------------------------------------------------------

rf_model.fit(
    X_train,
    y_train
)

print("Training completed.")

# ------------------------------------------------------------
# Validation prediction
# ------------------------------------------------------------

y_val_pred_rf = rf_model.predict(X_val)
y_val_prob_rf = rf_model.predict_proba(X_val)[:, 1]

# ------------------------------------------------------------
# Evaluation
# ------------------------------------------------------------

rf_accuracy = accuracy_score(y_val, y_val_pred_rf)
rf_precision = precision_score(y_val, y_val_pred_rf)
rf_recall = recall_score(y_val, y_val_pred_rf)
rf_f1 = f1_score(y_val, y_val_pred_rf)
rf_auc = roc_auc_score(y_val, y_val_prob_rf)

print("\n" + "=" * 70)
print("RANDOM FOREST — VALIDATION RESULTS")
print("=" * 70)

print(f"Accuracy  : {rf_accuracy:.4f}")
print(f"Precision : {rf_precision:.4f}")
print(f"Recall    : {rf_recall:.4f}")
print(f"F1-Score  : {rf_f1:.4f}")
print(f"ROC-AUC   : {rf_auc:.4f}")

# ------------------------------------------------------------
# Compare against baseline
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("COMPARISON WITH LOGISTIC REGRESSION")
print("=" * 70)

print(f"{'Metric':<12} {'Logistic':>12} {'Random Forest':>16}")
print("-" * 42)
print(f"{'Accuracy':<12} {accuracy:>12.4f} {rf_accuracy:>16.4f}")
print(f"{'Precision':<12} {precision:>12.4f} {rf_precision:>16.4f}")
print(f"{'Recall':<12} {recall:>12.4f} {rf_recall:>16.4f}")
print(f"{'F1-Score':<12} {f1:>12.4f} {rf_f1:>16.4f}")
print(f"{'ROC-AUC':<12} {auc:>12.4f} {rf_auc:>16.4f}")

# ------------------------------------------------------------
# Save model
# ------------------------------------------------------------

rf_model_path = os.path.join(
    MODEL_DIR,
    "random_forest.pkl"
)

joblib.dump(
    rf_model,
    rf_model_path
)

# ------------------------------------------------------------
# Save results checkpoint
# ------------------------------------------------------------

rf_results = {
    "model": "Random Forest",
    "stage": "validation",

    "parameters": {
        "n_estimators": 300,
        "max_depth": None,
        "min_samples_split": 2,
        "min_samples_leaf": 1,
        "class_weight": "balanced",
        "random_state": 42
    },

    "validation_accuracy": float(rf_accuracy),
    "validation_precision": float(rf_precision),
    "validation_recall": float(rf_recall),
    "validation_f1": float(rf_f1),
    "validation_roc_auc": float(rf_auc),

    "training_samples": int(X_train.shape[0]),
    "validation_samples": int(X_val.shape[0]),
    "feature_count": int(X_train.shape[1])
}

rf_checkpoint_path = os.path.join(
    CHECKPOINT_DIR,
    "04_random_forest_checkpoint.json"
)

with open(rf_checkpoint_path, "w") as f:
    json.dump(rf_results, f, indent=4)

print("\n" + "=" * 70)
print("RANDOM FOREST CHECKPOINT SAVED")
print("=" * 70)

print(f"Model      : {rf_model_path}")
print(f"Checkpoint : {rf_checkpoint_path}")

print("=" * 70)

======================================================================
PHISHSHIELD AI — RANDOM FOREST
======================================================================
Training Random Forest...
Training samples : 7000
Features         : 47
Trees            : 300
Training completed.

======================================================================
RANDOM FOREST — VALIDATION RESULTS
======================================================================
Accuracy  : 0.9867
Precision : 0.9828
Recall    : 0.9907
F1-Score  : 0.9867
ROC-AUC   : 0.9995

======================================================================
COMPARISON WITH LOGISTIC REGRESSION
======================================================================
Metric           Logistic    Random Forest
------------------------------------------
Accuracy           0.9513           0.9867
Precision          0.9448           0.9828
Recall             0.9587           0.9907
F1-Score           0.9517           0.9867
ROC-AUC            0.9868           0.9995

======================================================================
RANDOM FOREST CHECKPOINT SAVED
======================================================================
Model      : /content/drive/MyDrive/PhishShield_AI/models/random_forest.pkl
Checkpoint : /content/drive/MyDrive/PhishShield_AI/checkpoints/04_random_forest_checkpoint.json
======================================================================

In [ ]:
# ================================================================
# PHISHSHIELD AI — XGBOOST MODEL
# Cell  : 05
# ================================================================

import os
import json
import joblib
import numpy as np

from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

# ================================================================
# PATHS
# ================================================================

BASE_DIR = "/content/drive/MyDrive/PhishShield_AI"

MODEL_DIR = os.path.join(BASE_DIR, "models")
CHECKPOINT_DIR = os.path.join(BASE_DIR, "checkpoints")

os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# ================================================================
# LOAD DATA FROM CHECKPOINT
# ================================================================

X_train = joblib.load(
    os.path.join(BASE_DIR, "data", "X_train.pkl")
)

X_val = joblib.load(
    os.path.join(BASE_DIR, "data", "X_val.pkl")
)

X_test = joblib.load(
    os.path.join(BASE_DIR, "data", "X_test.pkl")
)

feature_names = joblib.load(
    os.path.join(BASE_DIR, "data", "feature_names.pkl")
)

# Target values were created during the split stage.
# Reload them if available.
y_train = joblib.load(
    os.path.join(BASE_DIR, "data", "y_train.pkl")
)

y_val = joblib.load(
    os.path.join(BASE_DIR, "data", "y_val.pkl")
)

y_test = joblib.load(
    os.path.join(BASE_DIR, "data", "y_test.pkl")
)

# ================================================================
# VALIDATION
# ================================================================

assert X_train.shape[1] == 47
assert X_val.shape[1] == 47
assert X_test.shape[1] == 47

assert len(feature_names) == 47

print("=" * 70)
print("PHISHSHIELD AI — XGBOOST MODEL")
print("=" * 70)

print(f"Training samples : {X_train.shape[0]}")
print(f"Validation       : {X_val.shape[0]}")
print(f"Test samples     : {X_test.shape[0]}")
print(f"Features         : {X_train.shape[1]}")

# ================================================================
# MODEL
# ================================================================

model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.9,
    colsample_bytree=0.9,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1
)

# ================================================================
# TRAIN
# ================================================================

print("\nTraining XGBoost...")

model.fit(
    X_train,
    y_train,
    eval_set=[(X_val, y_val)],
    verbose=False
)

print("Training completed.")

# ================================================================
# VALIDATION PREDICTION
# ================================================================

y_val_pred = model.predict(X_val)

y_val_prob = model.predict_proba(X_val)[:, 1]

# ================================================================
# METRICS
# ================================================================

accuracy = accuracy_score(
    y_val,
    y_val_pred
)

precision = precision_score(
    y_val,
    y_val_pred,
    zero_division=0
)

recall = recall_score(
    y_val,
    y_val_pred,
    zero_division=0
)

f1 = f1_score(
    y_val,
    y_val_pred,
    zero_division=0
)

roc_auc = roc_auc_score(
    y_val,
    y_val_prob
)

# ================================================================
# RESULTS
# ================================================================

print("\n" + "=" * 70)
print("XGBOOST — VALIDATION RESULTS")
print("=" * 70)

print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1-Score  : {f1:.4f}")
print(f"ROC-AUC   : {roc_auc:.4f}")

# ================================================================
# SAVE MODEL
# ================================================================

model_path = os.path.join(
    MODEL_DIR,
    "xgboost.pkl"
)

joblib.dump(
    model,
    model_path
)

# ================================================================
# SAVE CHECKPOINT
# ================================================================

checkpoint = {
    "stage": "05_xgboost",
    "model": "XGBClassifier",
    "n_estimators": 300,
    "max_depth": 6,
    "learning_rate": 0.05,
    "features": 47,
    "training_samples": 7000,
    "validation_samples": 1500,
    "test_samples": 1500,
    "random_seed": 42,
    "validation_metrics": {
        "accuracy": float(accuracy),
        "precision": float(precision),
        "recall": float(recall),
        "f1_score": float(f1),
        "roc_auc": float(roc_auc)
    },
    "model_path": model_path
}

checkpoint_path = os.path.join(
    CHECKPOINT_DIR,
    "05_xgboost_checkpoint.json"
)

with open(
    checkpoint_path,
    "w"
) as f:
    json.dump(
        checkpoint,
        f,
        indent=4
    )

# ================================================================
# FINAL OUTPUT
# ================================================================

print("\n" + "=" * 70)
print("XGBOOST CHECKPOINT SAVED")
print("=" * 70)

print(f"Model      : {model_path}")
print(f"Checkpoint : {checkpoint_path}")
print("=" * 70)

======================================================================
PHISHSHIELD AI — XGBOOST MODEL
======================================================================
Training samples : 7000
Validation       : 1500
Test samples     : 1500
Features         : 47

Training XGBoost...
Training completed.

======================================================================
XGBOOST — VALIDATION RESULTS
======================================================================
Accuracy  : 0.9880
Precision : 0.9816
Recall    : 0.9947
F1-Score  : 0.9881
ROC-AUC   : 0.9995

======================================================================
XGBOOST CHECKPOINT SAVED
======================================================================
Model      : /content/drive/MyDrive/PhishShield_AI/models/xgboost.pkl
Checkpoint : /content/drive/MyDrive/PhishShield_AI/checkpoints/05_xgboost_checkpoint.json
======================================================================

In [ ]:
# ================================================================
# PHISHSHIELD AI — MLP MODEL
# ================================================================

import os
import json
import joblib
import numpy as np

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

MODEL_DIR = "/content/drive/MyDrive/PhishShield_AI/models"
CHECKPOINT_DIR = "/content/drive/MyDrive/PhishShield_AI/checkpoints"

os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

print("=" * 70)
print("PHISHSHIELD AI — MLP MODEL")
print("=" * 70)

print(f"Training samples : {X_train.shape[0]}")
print(f"Validation       : {X_val.shape[0]}")
print(f"Test samples     : {X_test.shape[0]}")
print(f"Features         : {X_train.shape[1]}")

# ================================================================
# MLP MODEL
# ================================================================

mlp_model = MLPClassifier(
    hidden_layer_sizes=(128, 64, 32),
    activation="relu",
    solver="adam",
    alpha=0.0001,
    batch_size=32,
    learning_rate="adaptive",
    learning_rate_init=0.001,
    max_iter=300,
    early_stopping=True,
    validation_fraction=0.15,
    n_iter_no_change=20,
    random_state=42
)

print("\nTraining MLP...")

mlp_model.fit(
    X_train,
    y_train
)

print("Training completed.")

# ================================================================
# VALIDATION PREDICTION
# ================================================================

y_val_pred = mlp_model.predict(X_val)
y_val_prob = mlp_model.predict_proba(X_val)[:, 1]

# ================================================================
# VALIDATION METRICS
# ================================================================

accuracy = accuracy_score(y_val, y_val_pred)

precision = precision_score(
    y_val,
    y_val_pred,
    zero_division=0
)

recall = recall_score(
    y_val,
    y_val_pred,
    zero_division=0
)

f1 = f1_score(
    y_val,
    y_val_pred,
    zero_division=0
)

roc_auc = roc_auc_score(
    y_val,
    y_val_prob
)

print("\n" + "=" * 70)
print("MLP — VALIDATION RESULTS")
print("=" * 70)

print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1-Score  : {f1:.4f}")
print(f"ROC-AUC   : {roc_auc:.4f}")

# ================================================================
# SAVE MODEL
# ================================================================

model_path = os.path.join(
    MODEL_DIR,
    "mlp.pkl"
)

joblib.dump(
    mlp_model,
    model_path
)

# ================================================================
# SAVE CHECKPOINT
# ================================================================

checkpoint = {
    "stage": "06_mlp_model",
    "model": "MLPClassifier",
    "hidden_layers": [128, 64, 32],
    "activation": "relu",
    "solver": "adam",
    "training_samples": int(X_train.shape[0]),
    "validation_samples": int(X_val.shape[0]),
    "test_samples": int(X_test.shape[0]),
    "features": int(X_train.shape[1]),
    "random_seed": 42,
    "metrics": {
        "accuracy": float(accuracy),
        "precision": float(precision),
        "recall": float(recall),
        "f1_score": float(f1),
        "roc_auc": float(roc_auc)
    },
    "model_path": model_path
}

checkpoint_path = os.path.join(
    CHECKPOINT_DIR,
    "06_mlp_checkpoint.json"
)

with open(checkpoint_path, "w") as f:
    json.dump(
        checkpoint,
        f,
        indent=4
    )

print("\n" + "=" * 70)
print("MLP CHECKPOINT SAVED")
print("=" * 70)

print(f"Model      : {model_path}")
print(f"Checkpoint : {checkpoint_path}")
print("=" * 70)

======================================================================
PHISHSHIELD AI — MLP MODEL
======================================================================
Training samples : 7000
Validation       : 1500
Test samples     : 1500
Features         : 47

Training MLP...
Training completed.

======================================================================
MLP — VALIDATION RESULTS
======================================================================
Accuracy  : 0.9680
Precision : 0.9631
Recall    : 0.9733
F1-Score  : 0.9682
ROC-AUC   : 0.9932

======================================================================
MLP CHECKPOINT SAVED
======================================================================
Model      : /content/drive/MyDrive/PhishShield_AI/models/mlp.pkl
Checkpoint : /content/drive/MyDrive/PhishShield_AI/checkpoints/06_mlp_checkpoint.json
======================================================================

In [ ]:
# ================================================================
# PHISHSHIELD AI — RESMLP MODEL
# ================================================================

import os
import json
import joblib
import numpy as np
import tensorflow as tf

from tensorflow.keras import Model
from tensorflow.keras.layers import (
    Input,
    Dense,
    Dropout,
    BatchNormalization,
    Add,
    Activation
)
from tensorflow.keras.callbacks import (
    EarlyStopping,
    ModelCheckpoint
)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

# ================================================================
# REPRODUCIBILITY
# ================================================================

SEED = 42

np.random.seed(SEED)
tf.random.set_seed(SEED)

# ================================================================
# DIRECTORIES
# ================================================================

MODEL_DIR = "/content/drive/MyDrive/PhishShield_AI/models"
CHECKPOINT_DIR = "/content/drive/MyDrive/PhishShield_AI/checkpoints"

os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

print("=" * 70)
print("PHISHSHIELD AI — RESMLP MODEL")
print("=" * 70)

print(f"Training samples : {X_train.shape[0]}")
print(f"Validation       : {X_val.shape[0]}")
print(f"Test samples     : {X_test.shape[0]}")
print(f"Features         : {X_train.shape[1]}")

# ================================================================
# CONVERT DATA TO NUMPY
# ================================================================

X_train_np = np.asarray(X_train, dtype=np.float32)
X_val_np   = np.asarray(X_val, dtype=np.float32)
X_test_np  = np.asarray(X_test, dtype=np.float32)

y_train_np = np.asarray(y_train, dtype=np.float32)
y_val_np   = np.asarray(y_val, dtype=np.float32)
y_test_np  = np.asarray(y_test, dtype=np.float32)

# ================================================================
# RESIDUAL BLOCK
# ================================================================

def residual_block(x, units=128, dropout_rate=0.2):

    shortcut = x

    # Main branch
    y = Dense(units)(x)
    y = BatchNormalization()(y)
    y = Activation("relu")(y)
    y = Dropout(dropout_rate)(y)

    y = Dense(units)(y)
    y = BatchNormalization()(y)

    # Residual connection
    y = Add()([shortcut, y])

    y = Activation("relu")(y)

    return y


# ================================================================
# BUILD RESMLP
# ================================================================

inputs = Input(
    shape=(X_train_np.shape[1],),
    name="input_features"
)

# Initial projection
x = Dense(128)(inputs)
x = BatchNormalization()(x)
x = Activation("relu")(x)

# Residual Block 1
x = residual_block(
    x,
    units=128,
    dropout_rate=0.20
)

# Residual Block 2
x = residual_block(
    x,
    units=128,
    dropout_rate=0.20
)

# Classification layers
x = Dense(64)(x)
x = BatchNormalization()(x)
x = Activation("relu")(x)

x = Dropout(0.20)(x)

outputs = Dense(
    1,
    activation="sigmoid",
    name="phishing_probability"
)(x)

resmlp_model = Model(
    inputs=inputs,
    outputs=outputs,
    name="PhishShield_ResMLP"
)

# ================================================================
# COMPILE
# ================================================================

resmlp_model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=0.001
    ),
    loss="binary_crossentropy",
    metrics=[
        "accuracy"
    ]
)

print("\nResMLP architecture:")
resmlp_model.summary()

# ================================================================
# CHECKPOINT FILE
# ================================================================

keras_checkpoint_path = os.path.join(
    MODEL_DIR,
    "resmlp_best.keras"
)

# ================================================================
# CALLBACKS
# ================================================================

early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=15,
    restore_best_weights=True,
    verbose=1
)

model_checkpoint = ModelCheckpoint(
    keras_checkpoint_path,
    monitor="val_loss",
    save_best_only=True,
    verbose=1
)

# ================================================================
# TRAIN
# ================================================================

print("\nTraining ResMLP...")

history = resmlp_model.fit(
    X_train_np,
    y_train_np,
    validation_data=(
        X_val_np,
        y_val_np
    ),
    epochs=100,
    batch_size=32,
    callbacks=[
        early_stopping,
        model_checkpoint
    ],
    verbose=1
)

print("\nResMLP training completed.")

# ================================================================
# VALIDATION PREDICTION
# ================================================================

y_val_prob = resmlp_model.predict(
    X_val_np,
    verbose=0
).ravel()

y_val_pred = (
    y_val_prob >= 0.5
).astype(int)

# ================================================================
# VALIDATION METRICS
# ================================================================

accuracy = accuracy_score(
    y_val_np,
    y_val_pred
)

precision = precision_score(
    y_val_np,
    y_val_pred,
    zero_division=0
)

recall = recall_score(
    y_val_np,
    y_val_pred,
    zero_division=0
)

f1 = f1_score(
    y_val_np,
    y_val_pred,
    zero_division=0
)

roc_auc = roc_auc_score(
    y_val_np,
    y_val_prob
)

# ================================================================
# RESULTS
# ================================================================

print("\n" + "=" * 70)
print("RESMLP — VALIDATION RESULTS")
print("=" * 70)

print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1-Score  : {f1:.4f}")
print(f"ROC-AUC   : {roc_auc:.4f}")

# ================================================================
# SAVE TRAINING HISTORY
# ================================================================

history_path = os.path.join(
    MODEL_DIR,
    "resmlp_history.pkl"
)

joblib.dump(
    history.history,
    history_path
)

# ================================================================
# SAVE FINAL RESMLP MODEL
# ================================================================

final_model_path = os.path.join(
    MODEL_DIR,
    "resmlp.pkl"
)

resmlp_model.save(
    final_model_path
)

# ================================================================
# SAVE CHECKPOINT
# ================================================================

checkpoint = {

    "stage": "07_resmlp_model",

    "model": "ResMLP",

    "architecture": {
        "input_features": int(X_train_np.shape[1]),
        "initial_dense": 128,
        "residual_blocks": 2,
        "residual_units": 128,
        "classification_dense": 64,
        "dropout": 0.20,
        "activation": "relu",
        "optimizer": "Adam",
        "learning_rate": 0.001
    },

    "training": {
        "training_samples": int(X_train_np.shape[0]),
        "validation_samples": int(X_val_np.shape[0]),
        "test_samples": int(X_test_np.shape[0]),
        "features": int(X_train_np.shape[1]),
        "batch_size": 32,
        "maximum_epochs": 100,
        "random_seed": SEED
    },

    "metrics": {
        "accuracy": float(accuracy),
        "precision": float(precision),
        "recall": float(recall),
        "f1_score": float(f1),
        "roc_auc": float(roc_auc)
    },

    "model_path": final_model_path,
    "best_model_path": keras_checkpoint_path,
    "history_path": history_path
}

checkpoint_path = os.path.join(
    CHECKPOINT_DIR,
    "07_resmlp_checkpoint.json"
)

with open(
    checkpoint_path,
    "w"
) as f:

    json.dump(
        checkpoint,
        f,
        indent=4
    )

# ================================================================
# FINAL CHECKPOINT MESSAGE
# ================================================================

print("\n" + "=" * 70)
print("RESMLP CHECKPOINT SAVED")
print("=" * 70)

print(f"Model      : {final_model_path}")
print(f"Best Model : {keras_checkpoint_path}")
print(f"History    : {history_path}")
print(f"Checkpoint : {checkpoint_path}")

print("=" * 70)

======================================================================
PHISHSHIELD AI — RESMLP MODEL
======================================================================
Training samples : 7000
Validation       : 1500
Test samples     : 1500
Features         : 47

ResMLP architecture:

Model: "PhishShield_ResMLP"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_features      │ (None, 47)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 128)       │      6,144 │ input_features[0… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 128)       │        512 │ dense[0][0]       │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation          │ (None, 128)       │          0 │ batch_normalizat… │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 128)       │     16,512 │ activation[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 128)       │        512 │ dense_1[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_1        │ (None, 128)       │          0 │ batch_normalizat… │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 128)       │          0 │ activation_1[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 128)       │     16,512 │ dropout[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 128)       │        512 │ dense_2[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add (Add)           │ (None, 128)       │          0 │ activation[0][0], │
│                     │                   │            │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_2        │ (None, 128)       │          0 │ add[0][0]         │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 128)       │     16,512 │ activation_2[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 128)       │        512 │ dense_3[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_3        │ (None, 128)       │          0 │ batch_normalizat… │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 128)       │          0 │ activation_3[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 128)       │     16,512 │ dropout_1[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 128)       │        512 │ dense_4[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_1 (Add)         │ (None, 128)       │          0 │ activation_2[0][… │
│                     │                   │            │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_4        │ (None, 128)       │          0 │ add_1[0][0]       │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 64)        │      8,256 │ activation_4[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 64)        │        256 │ dense_5[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_5        │ (None, 64)        │          0 │ batch_normalizat… │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_2 (Dropout) │ (None, 64)        │          0 │ activation_5[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ phishing_probabili… │ (None, 1)         │         65 │ dropout_2[0][0]   │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 83,329 (325.50 KB)

 Trainable params: 81,921 (320.00 KB)

 Non-trainable params: 1,408 (5.50 KB)

Training ResMLP...
Epoch 1/100
216/219 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7258 - loss: 0.5412
Epoch 1: val_loss improved from None to 0.32671, saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras

Epoch 1: finished saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras
219/219 ━━━━━━━━━━━━━━━━━━━━ 9s 14ms/step - accuracy: 0.8139 - loss: 0.4025 - val_accuracy: 0.8593 - val_loss: 0.3267
Epoch 2/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8906 - loss: 0.2774
Epoch 2: val_loss improved from 0.32671 to 0.22959, saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras

Epoch 2: finished saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9034 - loss: 0.2487 - val_accuracy: 0.9167 - val_loss: 0.2296
Epoch 3/100
218/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9087 - loss: 0.2223
Epoch 3: val_loss improved from 0.22959 to 0.18133, saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras

Epoch 3: finished saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9189 - loss: 0.2050 - val_accuracy: 0.9313 - val_loss: 0.1813
Epoch 4/100
212/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9244 - loss: 0.1993
Epoch 4: val_loss improved from 0.18133 to 0.16205, saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras

Epoch 4: finished saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9324 - loss: 0.1809 - val_accuracy: 0.9360 - val_loss: 0.1621
Epoch 5/100
218/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9276 - loss: 0.1876
Epoch 5: val_loss improved from 0.16205 to 0.14129, saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras

Epoch 5: finished saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9337 - loss: 0.1710 - val_accuracy: 0.9447 - val_loss: 0.1413
Epoch 6/100
213/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9318 - loss: 0.1747
Epoch 6: val_loss did not improve from 0.14129
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9390 - loss: 0.1599 - val_accuracy: 0.9360 - val_loss: 0.1686
Epoch 7/100
213/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9377 - loss: 0.1654
Epoch 7: val_loss did not improve from 0.14129
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9414 - loss: 0.1545 - val_accuracy: 0.9153 - val_loss: 0.2148
Epoch 8/100
211/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9420 - loss: 0.1516
Epoch 8: val_loss improved from 0.14129 to 0.13841, saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras

Epoch 8: finished saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9466 - loss: 0.1408 - val_accuracy: 0.9407 - val_loss: 0.1384
Epoch 9/100
214/219 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9442 - loss: 0.1460
Epoch 9: val_loss did not improve from 0.13841
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9519 - loss: 0.1345 - val_accuracy: 0.9273 - val_loss: 0.1743
Epoch 10/100
216/219 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9436 - loss: 0.1447
Epoch 10: val_loss did not improve from 0.13841
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9511 - loss: 0.1284 - val_accuracy: 0.9447 - val_loss: 0.1468
Epoch 11/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9490 - loss: 0.1287
Epoch 11: val_loss improved from 0.13841 to 0.13343, saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras

Epoch 11: finished saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9549 - loss: 0.1173 - val_accuracy: 0.9520 - val_loss: 0.1334
Epoch 12/100
214/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9511 - loss: 0.1254
Epoch 12: val_loss did not improve from 0.13343
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9549 - loss: 0.1160 - val_accuracy: 0.9407 - val_loss: 0.1466
Epoch 13/100
216/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9531 - loss: 0.1199
Epoch 13: val_loss did not improve from 0.13343
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9591 - loss: 0.1085 - val_accuracy: 0.9453 - val_loss: 0.1494
Epoch 14/100
215/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9529 - loss: 0.1165
Epoch 14: val_loss did not improve from 0.13343
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9574 - loss: 0.1091 - val_accuracy: 0.9400 - val_loss: 0.2057
Epoch 15/100
215/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9582 - loss: 0.1041
Epoch 15: val_loss did not improve from 0.13343
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9621 - loss: 0.0950 - val_accuracy: 0.9473 - val_loss: 0.1518
Epoch 16/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9566 - loss: 0.1012
Epoch 16: val_loss did not improve from 0.13343
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9621 - loss: 0.0937 - val_accuracy: 0.9500 - val_loss: 0.1415
Epoch 17/100
216/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9656 - loss: 0.0913
Epoch 17: val_loss did not improve from 0.13343
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9680 - loss: 0.0846 - val_accuracy: 0.9407 - val_loss: 0.1779
Epoch 18/100
214/219 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9651 - loss: 0.0876
Epoch 18: val_loss did not improve from 0.13343
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9686 - loss: 0.0805 - val_accuracy: 0.9473 - val_loss: 0.1450
Epoch 19/100
218/219 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9673 - loss: 0.0836
Epoch 19: val_loss did not improve from 0.13343
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9684 - loss: 0.0818 - val_accuracy: 0.9447 - val_loss: 0.1595
Epoch 20/100
209/219 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9665 - loss: 0.0843
Epoch 20: val_loss improved from 0.13343 to 0.13333, saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras

Epoch 20: finished saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9703 - loss: 0.0750 - val_accuracy: 0.9547 - val_loss: 0.1333
Epoch 21/100
217/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9693 - loss: 0.0737
Epoch 21: val_loss did not improve from 0.13333
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9724 - loss: 0.0707 - val_accuracy: 0.9460 - val_loss: 0.1872
Epoch 22/100
211/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9672 - loss: 0.0749
Epoch 22: val_loss did not improve from 0.13333
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9703 - loss: 0.0714 - val_accuracy: 0.9547 - val_loss: 0.1448
Epoch 23/100
211/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9753 - loss: 0.0641
Epoch 23: val_loss improved from 0.13333 to 0.12436, saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras

Epoch 23: finished saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9751 - loss: 0.0628 - val_accuracy: 0.9653 - val_loss: 0.1244
Epoch 24/100
217/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9749 - loss: 0.0650
Epoch 24: val_loss did not improve from 0.12436
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9766 - loss: 0.0629 - val_accuracy: 0.9513 - val_loss: 0.1440
Epoch 25/100
216/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9754 - loss: 0.0625
Epoch 25: val_loss improved from 0.12436 to 0.11380, saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras

Epoch 25: finished saving model to /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9769 - loss: 0.0592 - val_accuracy: 0.9620 - val_loss: 0.1138
Epoch 26/100
213/219 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9762 - loss: 0.0664
Epoch 26: val_loss did not improve from 0.11380
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9771 - loss: 0.0595 - val_accuracy: 0.9573 - val_loss: 0.1235
Epoch 27/100
216/219 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9776 - loss: 0.0575
Epoch 27: val_loss did not improve from 0.11380
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9799 - loss: 0.0517 - val_accuracy: 0.9527 - val_loss: 0.1550
Epoch 28/100
218/219 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9766 - loss: 0.0555
Epoch 28: val_loss did not improve from 0.11380
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9784 - loss: 0.0528 - val_accuracy: 0.9580 - val_loss: 0.1417
Epoch 29/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9805 - loss: 0.0513
Epoch 29: val_loss did not improve from 0.11380
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9807 - loss: 0.0481 - val_accuracy: 0.9427 - val_loss: 0.2141
Epoch 30/100
209/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9805 - loss: 0.0526
Epoch 30: val_loss did not improve from 0.11380
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9794 - loss: 0.0549 - val_accuracy: 0.9620 - val_loss: 0.1359
Epoch 31/100
216/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9799 - loss: 0.0526
Epoch 31: val_loss did not improve from 0.11380
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9800 - loss: 0.0509 - val_accuracy: 0.9540 - val_loss: 0.1358
Epoch 32/100
214/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9812 - loss: 0.0484
Epoch 32: val_loss did not improve from 0.11380
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9816 - loss: 0.0454 - val_accuracy: 0.9187 - val_loss: 0.3075
Epoch 33/100
209/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9847 - loss: 0.0402
Epoch 33: val_loss did not improve from 0.11380
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9851 - loss: 0.0392 - val_accuracy: 0.9407 - val_loss: 0.2283
Epoch 34/100
209/219 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9850 - loss: 0.0435
Epoch 34: val_loss did not improve from 0.11380
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9839 - loss: 0.0424 - val_accuracy: 0.9460 - val_loss: 0.1870
Epoch 35/100
213/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9804 - loss: 0.0482
Epoch 35: val_loss did not improve from 0.11380
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9840 - loss: 0.0407 - val_accuracy: 0.9247 - val_loss: 0.3088
Epoch 36/100
218/219 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9838 - loss: 0.0416
Epoch 36: val_loss did not improve from 0.11380
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9850 - loss: 0.0382 - val_accuracy: 0.9540 - val_loss: 0.1767
Epoch 37/100
217/219 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9853 - loss: 0.0391
Epoch 37: val_loss did not improve from 0.11380
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9864 - loss: 0.0370 - val_accuracy: 0.9647 - val_loss: 0.1303
Epoch 38/100
217/219 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9827 - loss: 0.0468
Epoch 38: val_loss did not improve from 0.11380
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9846 - loss: 0.0402 - val_accuracy: 0.9500 - val_loss: 0.1889
Epoch 39/100
216/219 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9829 - loss: 0.0437
Epoch 39: val_loss did not improve from 0.11380
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9866 - loss: 0.0345 - val_accuracy: 0.9580 - val_loss: 0.1552
Epoch 40/100
211/219 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9895 - loss: 0.0301
Epoch 40: val_loss did not improve from 0.11380
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9893 - loss: 0.0296 - val_accuracy: 0.9467 - val_loss: 0.1773
Epoch 40: early stopping
Restoring model weights from the end of the best epoch: 25.

ResMLP training completed.

======================================================================
RESMLP — VALIDATION RESULTS
======================================================================
Accuracy  : 0.9620
Precision : 0.9565
Recall    : 0.9680
F1-Score  : 0.9622
ROC-AUC   : 0.9923

ValueError: Invalid filepath extension for saving. Please add either a `.keras` extension for the native Keras format (recommended) or a `.h5` extension. Use `model.export(filepath)` if you want to export a SavedModel for use with TFLite/TFServing/etc. Received: filepath=/content/drive/MyDrive/PhishShield_AI/models/resmlp.pkl.

In [ ]:
# ============================================================
# PHISHSHIELD AI — RESUME FROM CHECKPOINTS
# Step 1: Mount Google Drive and inspect saved project files
# ============================================================

from google.colab import drive
import os

drive.mount('/content/drive')

BASE_DIR = "/content/drive/MyDrive/PhishShield_AI"

print("Checking PhishShield AI checkpoint directory...")
print("Base directory:", BASE_DIR)

if os.path.exists(BASE_DIR):
    print("✅ PhishShield_AI directory found")
else:
    raise FileNotFoundError(
        "❌ PhishShield_AI directory was not found in Google Drive."
    )

print("\nProject folders:")
for item in sorted(os.listdir(BASE_DIR)):
    path = os.path.join(BASE_DIR, item)
    if os.path.isdir(path):
        print("📁", item)
    else:
        print("📄", item)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Checking PhishShield AI checkpoint directory...
Base directory: /content/drive/MyDrive/PhishShield_AI
✅ PhishShield_AI directory found

Project folders:
📁 checkpoints
📁 data
📁 models

In [ ]:
# ============================================================
# PHISHSHIELD AI — CHECKPOINT VERIFICATION
# Step 2: Inspect saved files before loading
# ============================================================

import os

CHECKPOINT_DIR = "/content/drive/MyDrive/PhishShield_AI/checkpoints"
DATA_DIR = "/content/drive/MyDrive/PhishShield_AI/data"
MODEL_DIR = "/content/drive/MyDrive/PhishShield_AI/models"

def show_files(folder, title):
    print(f"\n{'=' * 60}")
    print(title)
    print(f"{'=' * 60}")

    if not os.path.exists(folder):
        print("❌ Folder not found:", folder)
        return

    files = sorted(os.listdir(folder))

    if not files:
        print("⚠️ Folder is empty")
        return

    for f in files:
        path = os.path.join(folder, f)
        size_mb = os.path.getsize(path) / (1024 * 1024)
        print(f"📄 {f:<55} {size_mb:.2f} MB")

show_files(CHECKPOINT_DIR, "CHECKPOINTS")
show_files(DATA_DIR, "DATA")
show_files(MODEL_DIR, "MODELS")

print("\n✅ Checkpoint inspection completed.")

============================================================
CHECKPOINTS
============================================================
📄 01_dataset_analysis_checkpoint.json                     0.00 MB
📄 02_data_split_checkpoint.json                           0.00 MB
📄 03_logistic_baseline_checkpoint.json                    0.00 MB
📄 04_random_forest_checkpoint.json                        0.00 MB
📄 05_xgboost_checkpoint.json                              0.00 MB
📄 06_mlp_checkpoint.json                                  0.00 MB

============================================================
DATA
============================================================
📄 X_test.pkl                                              0.55 MB
📄 X_train.pkl                                             2.57 MB
📄 X_val.pkl                                               0.55 MB
📄 feature_names.pkl                                       0.00 MB
📄 y_test.pkl                                              0.05 MB
📄 y_train.pkl                                             0.21 MB
📄 y_val.pkl                                               0.05 MB

============================================================
MODELS
============================================================
📄 logistic_regression_baseline.pkl                        0.00 MB
📄 mlp.pkl                                                 0.39 MB
📄 random_forest.pkl                                       16.25 MB
📄 resmlp_best.keras                                       1.05 MB
📄 resmlp_history.pkl                                      0.00 MB
📄 xgboost.pkl                                             0.71 MB

✅ Checkpoint inspection completed.

In [ ]:
# ============================================================
# PHISHSHIELD AI — CHECKPOINT FORMAT DIAGNOSTIC
# ============================================================

import os
import binascii

BASE_DIR = "/content/drive/MyDrive/PhishShield_AI"
DATA_DIR = os.path.join(BASE_DIR, "data")

files_to_check = [
    "X_train.pkl",
    "X_val.pkl",
    "X_test.pkl",
    "y_train.pkl",
    "y_val.pkl",
    "y_test.pkl",
    "feature_names.pkl"
]

print("=" * 70)
print("CHECKPOINT FILE FORMAT DIAGNOSTIC")
print("=" * 70)

for filename in files_to_check:

    path = os.path.join(DATA_DIR, filename)

    print(f"\n📄 {filename}")

    if not os.path.exists(path):
        print("   ❌ File not found")
        continue

    size = os.path.getsize(path)

    with open(path, "rb") as f:
        header = f.read(16)

    print(f"   Size   : {size:,} bytes")
    print(f"   Header : {binascii.hexlify(header).decode()}")
    print(f"   Bytes  : {header}")

print("\n" + "=" * 70)
print("Diagnostic completed — DO NOT modify the files.")
print("=" * 70)

======================================================================
CHECKPOINT FILE FORMAT DIAGNOSTIC
======================================================================

📄 X_train.pkl
   Size   : 2,690,251 bytes
   Header : 80049562010000000000008c1170616e
   Bytes  : b'\x80\x04\x95b\x01\x00\x00\x00\x00\x00\x00\x8c\x11pan'

📄 X_val.pkl
   Size   : 578,251 bytes
   Header : 80049562010000000000008c1170616e
   Bytes  : b'\x80\x04\x95b\x01\x00\x00\x00\x00\x00\x00\x8c\x11pan'

📄 X_test.pkl
   Size   : 578,251 bytes
   Header : 80049562010000000000008c1170616e
   Bytes  : b'\x80\x04\x95b\x01\x00\x00\x00\x00\x00\x00\x8c\x11pan'

📄 y_train.pkl
   Size   : 224,806 bytes
   Header : 8004957d010000000000008c1270616e
   Bytes  : b'\x80\x04\x95}\x01\x00\x00\x00\x00\x00\x00\x8c\x12pan'

📄 y_val.pkl
   Size   : 48,806 bytes
   Header : 8004957d010000000000008c1270616e
   Bytes  : b'\x80\x04\x95}\x01\x00\x00\x00\x00\x00\x00\x8c\x12pan'

📄 y_test.pkl
   Size   : 48,806 bytes
   Header : 8004957d010000000000008c1270616e
   Bytes  : b'\x80\x04\x95}\x01\x00\x00\x00\x00\x00\x00\x8c\x12pan'

📄 feature_names.pkl
   Size   : 848 bytes
   Header : 80049545030000000000005d94288c07
   Bytes  : b'\x80\x04\x95E\x03\x00\x00\x00\x00\x00\x00]\x94(\x8c\x07'

======================================================================
Diagnostic completed — DO NOT modify the files.
======================================================================

In [ ]:
# ============================================================
# PHISHSHIELD AI — CHECKPOINT FORENSIC DIAGNOSTIC
# IMPORTANT: READ-ONLY. DOES NOT MODIFY ANY FILE.
# ============================================================

import os
import pickle
import pickletools
import joblib

BASE_DIR = "/content/drive/MyDrive/PhishShield_AI"
DATA_DIR = os.path.join(BASE_DIR, "data")

path = os.path.join(DATA_DIR, "X_train.pkl")

print("=" * 70)
print("PHISHSHIELD AI — X_train.pkl FORENSIC CHECK")
print("=" * 70)

# ------------------------------------------------------------
# 1. Basic file information
# ------------------------------------------------------------

file_size = os.path.getsize(path)

print("\n[1] FILE")
print("-" * 70)
print("Path :", path)
print("Size :", file_size, "bytes")

# ------------------------------------------------------------
# 2. Test standard pickle
# ------------------------------------------------------------

print("\n[2] STANDARD PICKLE LOAD")
print("-" * 70)

try:
    with open(path, "rb") as f:
        obj = pickle.load(f)

    print("✅ pickle.load() succeeded")
    print("Type:", type(obj))

except Exception as e:
    print("❌ pickle.load() failed")
    print("Error type:", type(e).__name__)
    print("Error     :", repr(e))

# ------------------------------------------------------------
# 3. Test joblib
# ------------------------------------------------------------

print("\n[3] JOBLIB LOAD")
print("-" * 70)

try:
    obj = joblib.load(path)

    print("✅ joblib.load() succeeded")
    print("Type:", type(obj))

    if hasattr(obj, "shape"):
        print("Shape:", obj.shape)

except Exception as e:
    print("❌ joblib.load() failed")
    print("Error type:", type(e).__name__)
    print("Error     :", repr(e))

# ------------------------------------------------------------
# 4. Inspect pickle opcodes
# ------------------------------------------------------------

print("\n[4] PICKLE OPCODE ANALYSIS")
print("-" * 70)

try:
    with open(path, "rb") as f:
        data = f.read()

    print("Total bytes read:", len(data))

    # Try to disassemble the pickle stream.
    # This is READ-ONLY.
    pickletools.dis(data)

    print("\n✅ Pickle opcode stream completed successfully.")

except Exception as e:
    print("\n❌ Pickle opcode analysis failed")
    print("Error type:", type(e).__name__)
    print("Error     :", repr(e))

# ------------------------------------------------------------
# 5. Search for the first suspicious byte after header
# ------------------------------------------------------------

print("\n[5] RAW BYTE CHECK")
print("-" * 70)

with open(path, "rb") as f:
    data = f.read()

print("First 64 bytes:")
print(data[:64])

print("\nLast 64 bytes:")
print(data[-64:])

print("\n" + "=" * 70)
print("FORENSIC DIAGNOSTIC COMPLETE")
print("NO FILES WERE MODIFIED.")
print("=" * 70)

======================================================================
PHISHSHIELD AI — X_train.pkl FORENSIC CHECK
======================================================================

[1] FILE
----------------------------------------------------------------------
Path : /content/drive/MyDrive/PhishShield_AI/data/X_train.pkl
Size : 2690251 bytes

[2] STANDARD PICKLE LOAD
----------------------------------------------------------------------
❌ pickle.load() failed
Error type: UnpicklingError
Error     : UnpicklingError("invalid load key, '\\x02'.")

[3] JOBLIB LOAD
----------------------------------------------------------------------
✅ joblib.load() succeeded
Type: <class 'pandas.core.frame.DataFrame'>
Shape: (7000, 47)

[4] PICKLE OPCODE ANALYSIS
----------------------------------------------------------------------
Total bytes read: 2690251
    0: \x80 PROTO      4
    2: \x95 FRAME      354
   11: \x8c SHORT_BINUNICODE 'pandas.core.frame'
   30: \x94 MEMOIZE    (as 0)
   31: \x8c SHORT_BINUNICODE 'DataFrame'
   42: \x94 MEMOIZE    (as 1)
   43: \x93 STACK_GLOBAL
   44: \x94 MEMOIZE    (as 2)
   45: )    EMPTY_TUPLE
   46: \x81 NEWOBJ
   47: \x94 MEMOIZE    (as 3)
   48: }    EMPTY_DICT
   49: \x94 MEMOIZE    (as 4)
   50: (    MARK
   51: \x8c     SHORT_BINUNICODE '_mgr'
   57: \x94     MEMOIZE    (as 5)
   58: \x8c     SHORT_BINUNICODE 'pandas.core.internals.managers'
   90: \x94     MEMOIZE    (as 6)
   91: \x8c     SHORT_BINUNICODE 'BlockManager'
  105: \x94     MEMOIZE    (as 7)
  106: \x93     STACK_GLOBAL
  107: \x94     MEMOIZE    (as 8)
  108: \x8c     SHORT_BINUNICODE 'pandas._libs.internals'
  132: \x94     MEMOIZE    (as 9)
  133: \x8c     SHORT_BINUNICODE '_unpickle_block'
  150: \x94     MEMOIZE    (as 10)
  151: \x93     STACK_GLOBAL
  152: \x94     MEMOIZE    (as 11)
  153: \x8c     SHORT_BINUNICODE 'joblib.numpy_pickle'
  174: \x94     MEMOIZE    (as 12)
  175: \x8c     SHORT_BINUNICODE 'NumpyArrayWrapper'
  194: \x94     MEMOIZE    (as 13)
  195: \x93     STACK_GLOBAL
  196: \x94     MEMOIZE    (as 14)
  197: )        EMPTY_TUPLE
  198: \x81     NEWOBJ
  199: \x94     MEMOIZE    (as 15)
  200: }        EMPTY_DICT
  201: \x94     MEMOIZE    (as 16)
  202: (        MARK
  203: \x8c         SHORT_BINUNICODE 'subclass'
  213: \x94         MEMOIZE    (as 17)
  214: \x8c         SHORT_BINUNICODE 'numpy'
  221: \x94         MEMOIZE    (as 18)
  222: \x8c         SHORT_BINUNICODE 'ndarray'
  231: \x94         MEMOIZE    (as 19)
  232: \x93         STACK_GLOBAL
  233: \x94         MEMOIZE    (as 20)
  234: \x8c         SHORT_BINUNICODE 'shape'
  241: \x94         MEMOIZE    (as 21)
  242: K            BININT1    44
  244: M            BININT2    7000
  247: \x86         TUPLE2
  248: \x94         MEMOIZE    (as 22)
  249: \x8c         SHORT_BINUNICODE 'order'
  256: \x94         MEMOIZE    (as 23)
  257: \x8c         SHORT_BINUNICODE 'C'
  260: \x94         MEMOIZE    (as 24)
  261: \x8c         SHORT_BINUNICODE 'dtype'
  268: \x94         MEMOIZE    (as 25)
  269: h            BINGET     18
  271: \x8c         SHORT_BINUNICODE 'dtype'
  278: \x94         MEMOIZE    (as 26)
  279: \x93         STACK_GLOBAL
  280: \x94         MEMOIZE    (as 27)
  281: \x8c         SHORT_BINUNICODE 'i8'
  285: \x94         MEMOIZE    (as 28)
  286: \x89         NEWFALSE
  287: \x88         NEWTRUE
  288: \x87         TUPLE3
  289: \x94         MEMOIZE    (as 29)
  290: R            REDUCE
  291: \x94         MEMOIZE    (as 30)
  292: (            MARK
  293: K                BININT1    3
  295: \x8c             SHORT_BINUNICODE '<'
  298: \x94             MEMOIZE    (as 31)
  299: N                NONE
  300: N                NONE
  301: N                NONE
  302: J                BININT     -1
  307: J                BININT     -1
  312: K                BININT1    0
  314: t                TUPLE      (MARK at 292)
  315: \x94         MEMOIZE    (as 32)
  316: b            BUILD
  317: \x8c         SHORT_BINUNICODE 'allow_mmap'
  329: \x94         MEMOIZE    (as 33)
  330: \x88         NEWTRUE
  331: \x8c         SHORT_BINUNICODE 'numpy_array_alignment_bytes'
  360: \x94         MEMOIZE    (as 34)
  361: K            BININT1    16
  363: u            SETITEMS   (MARK at 202)
  364: b        BUILD

❌ Pickle opcode analysis failed
Error type: ValueError
Error     : ValueError("at position 365, opcode b'\\x02' unknown")

[5] RAW BYTE CHECK
----------------------------------------------------------------------
First 64 bytes:
b'\x80\x04\x95b\x01\x00\x00\x00\x00\x00\x00\x8c\x11pandas.core.frame\x94\x8c\tDataFrame\x94\x93\x94)\x81\x94}\x94(\x8c\x04_mgr\x94\x8c\x1epand'

Last 64 bytes:
b'_metadata\x94]\x94\x8c\x05attrs\x94}\x94\x8c\x06_flags\x94}\x94\x8c\x17allows_duplicate_labels\x94\x88sub.'

======================================================================
FORENSIC DIAGNOSTIC COMPLETE
NO FILES WERE MODIFIED.
======================================================================

In [ ]:
# ============================================================
# PHISHSHIELD AI — CORRECT CHECKPOINT LOADING
# Step 3D: Load Joblib-serialized data checkpoints
# ============================================================

import os
import joblib
import numpy as np

BASE_DIR = "/content/drive/MyDrive/PhishShield_AI"
DATA_DIR = os.path.join(BASE_DIR, "data")

# ------------------------------------------------------------
# Load saved data
# ------------------------------------------------------------

X_train = joblib.load(os.path.join(DATA_DIR, "X_train.pkl"))
X_val   = joblib.load(os.path.join(DATA_DIR, "X_val.pkl"))
X_test  = joblib.load(os.path.join(DATA_DIR, "X_test.pkl"))

y_train = joblib.load(os.path.join(DATA_DIR, "y_train.pkl"))
y_val   = joblib.load(os.path.join(DATA_DIR, "y_val.pkl"))
y_test  = joblib.load(os.path.join(DATA_DIR, "y_test.pkl"))

feature_names = joblib.load(
    os.path.join(DATA_DIR, "feature_names.pkl")
)

# ============================================================
# Verification
# ============================================================

print("=" * 70)
print("PHISHSHIELD AI — CHECKPOINT LOAD VERIFICATION")
print("=" * 70)

print("\nOBJECT TYPES")
print("-" * 70)
print("X_train       :", type(X_train))
print("X_val         :", type(X_val))
print("X_test        :", type(X_test))
print("y_train       :", type(y_train))
print("y_val         :", type(y_val))
print("y_test        :", type(y_test))
print("feature_names :", type(feature_names))

print("\nDATA SHAPES")
print("-" * 70)
print("X_train :", X_train.shape)
print("X_val   :", X_val.shape)
print("X_test  :", X_test.shape)
print("y_train:", y_train.shape)
print("y_val  :", y_val.shape)
print("y_test :", y_test.shape)

print("\nFEATURE CONFIGURATION")
print("-" * 70)
print("Feature count :", len(feature_names))
print("X_train cols  :", X_train.shape[1])
print("X_val cols    :", X_val.shape[1])
print("X_test cols   :", X_test.shape[1])

print("\nCLASS DISTRIBUTION")
print("-" * 70)

print("Train:")
print(y_train.value_counts().sort_index())

print("\nValidation:")
print(y_val.value_counts().sort_index())

print("\nTest:")
print(y_test.value_counts().sort_index())

# ============================================================
# Hard validation
# ============================================================

assert X_train.shape == (7000, 47), "X_train shape mismatch"
assert X_val.shape == (1500, 47), "X_val shape mismatch"
assert X_test.shape == (1500, 47), "X_test shape mismatch"

assert len(y_train) == 7000, "y_train size mismatch"
assert len(y_val) == 1500, "y_val size mismatch"
assert len(y_test) == 1500, "y_test size mismatch"

assert len(feature_names) == 47, "Feature count mismatch"

assert list(X_train.columns) == list(feature_names), \
    "X_train feature order does not match feature_names"

assert list(X_val.columns) == list(feature_names), \
    "X_val feature order does not match feature_names"

assert list(X_test.columns) == list(feature_names), \
    "X_test feature order does not match feature_names"

print("\n" + "=" * 70)
print("✅ CHECKPOINT DATA LOADED")
print("✅ JOBLIB SERIALIZATION CONFIRMED")
print("✅ TRAIN = 7000")
print("✅ VALIDATION = 1500")
print("✅ TEST = 1500")
print("✅ FEATURES = 47")
print("✅ FEATURE ORDER VERIFIED")
print("✅ NO FILES MODIFIED")
print("✅ NO MODEL RETRAINING")
print("=" * 70)

======================================================================
PHISHSHIELD AI — CHECKPOINT LOAD VERIFICATION
======================================================================

OBJECT TYPES
----------------------------------------------------------------------
X_train       : <class 'pandas.core.frame.DataFrame'>
X_val         : <class 'pandas.core.frame.DataFrame'>
X_test        : <class 'pandas.core.frame.DataFrame'>
y_train       : <class 'pandas.core.series.Series'>
y_val         : <class 'pandas.core.series.Series'>
y_test        : <class 'pandas.core.series.Series'>
feature_names : <class 'list'>

DATA SHAPES
----------------------------------------------------------------------
X_train : (7000, 47)
X_val   : (1500, 47)
X_test  : (1500, 47)
y_train: (7000,)
y_val  : (1500,)
y_test : (1500,)

FEATURE CONFIGURATION
----------------------------------------------------------------------
Feature count : 47
X_train cols  : 47
X_val cols    : 47
X_test cols   : 47

CLASS DISTRIBUTION
----------------------------------------------------------------------
Train:
CLASS_LABEL
0    3500
1    3500
Name: count, dtype: int64

Validation:
CLASS_LABEL
0    750
1    750
Name: count, dtype: int64

Test:
CLASS_LABEL
0    750
1    750
Name: count, dtype: int64

======================================================================
✅ CHECKPOINT DATA LOADED
✅ JOBLIB SERIALIZATION CONFIRMED
✅ TRAIN = 7000
✅ VALIDATION = 1500
✅ TEST = 1500
✅ FEATURES = 47
✅ FEATURE ORDER VERIFIED
✅ NO FILES MODIFIED
✅ NO MODEL RETRAINING
======================================================================

In [ ]:
# ============================================================
# PHISHSHIELD AI — MODEL CHECKPOINT VERIFICATION
# Step 4: Load saved ML models
# ============================================================

import os
import joblib

BASE_DIR = "/content/drive/MyDrive/PhishShield_AI"
MODEL_DIR = os.path.join(BASE_DIR, "models")

# ------------------------------------------------------------
# Load saved models
# ------------------------------------------------------------

logistic_model = joblib.load(
    os.path.join(MODEL_DIR, "logistic_regression_baseline.pkl")
)

rf_model = joblib.load(
    os.path.join(MODEL_DIR, "random_forest.pkl")
)

xgb_model = joblib.load(
    os.path.join(MODEL_DIR, "xgboost.pkl")
)

mlp_model = joblib.load(
    os.path.join(MODEL_DIR, "mlp.pkl")
)

# ------------------------------------------------------------
# Display model information
# ------------------------------------------------------------

models = {
    "Logistic Regression": logistic_model,
    "Random Forest": rf_model,
    "XGBoost": xgb_model,
    "MLP": mlp_model
}

print("=" * 70)
print("PHISHSHIELD AI — SAVED MODEL VERIFICATION")
print("=" * 70)

for name, model in models.items():

    print(f"\n{name}")
    print("-" * 70)

    print("Model type:", type(model).__name__)

    # Check feature count when available
    if hasattr(model, "n_features_in_"):
        print("Expected features:", model.n_features_in_)
    else:
        print("Expected features: attribute not available")

    # Check classes when available
    if hasattr(model, "classes_"):
        print("Classes:", model.classes_)

# ------------------------------------------------------------
# Hard feature compatibility check
# ------------------------------------------------------------

for name, model in models.items():

    if hasattr(model, "n_features_in_"):
        assert model.n_features_in_ == 47, (
            f"{name} expects {model.n_features_in_} features, "
            f"but our locked dataset has 47."
        )

print("\n" + "=" * 70)
print("✅ ALL FOUR SAVED ML MODELS LOADED")
print("✅ MODEL FEATURE COMPATIBILITY VERIFIED")
print("✅ ALL MODELS EXPECT 47 FEATURES")
print("✅ NO RETRAINING PERFORMED")
print("=" * 70)

======================================================================
PHISHSHIELD AI — SAVED MODEL VERIFICATION
======================================================================

Logistic Regression
----------------------------------------------------------------------
Model type: Pipeline
Expected features: 47
Classes: [0 1]

Random Forest
----------------------------------------------------------------------
Model type: RandomForestClassifier
Expected features: 47
Classes: [0 1]

XGBoost
----------------------------------------------------------------------
Model type: XGBClassifier
Expected features: 47
Classes: [0 1]

MLP
----------------------------------------------------------------------
Model type: MLPClassifier
Expected features: 47
Classes: [0 1]

======================================================================
✅ ALL FOUR SAVED ML MODELS LOADED
✅ MODEL FEATURE COMPATIBILITY VERIFIED
✅ ALL MODELS EXPECT 47 FEATURES
✅ NO RETRAINING PERFORMED
======================================================================

In [ ]:
# ============================================================
# PHISHSHIELD AI — RESMLP CHECKPOINT VERIFICATION
# Step 4B: Load already-trained ResMLP
# ============================================================

import os
import tensorflow as tf
import joblib

BASE_DIR = "/content/drive/MyDrive/PhishShield_AI"
MODEL_DIR = os.path.join(BASE_DIR, "models")

RESMLP_PATH = os.path.join(MODEL_DIR, "resmlp_best.keras")
HISTORY_PATH = os.path.join(MODEL_DIR, "resmlp_history.pkl")

print("=" * 70)
print("PHISHSHIELD AI — RESMLP CHECKPOINT VERIFICATION")
print("=" * 70)

# ------------------------------------------------------------
# Verify files exist before loading
# ------------------------------------------------------------

assert os.path.exists(RESMLP_PATH), (
    f"ResMLP model not found: {RESMLP_PATH}"
)

assert os.path.exists(HISTORY_PATH), (
    f"ResMLP history not found: {HISTORY_PATH}"
)

print("\nCHECKPOINT FILES")
print("-" * 70)
print("ResMLP model :", RESMLP_PATH)
print("History      :", HISTORY_PATH)

# ------------------------------------------------------------
# Load trained ResMLP
# ------------------------------------------------------------

resmlp_model = tf.keras.models.load_model(RESMLP_PATH)

# Load training history
resmlp_history = joblib.load(HISTORY_PATH)

# ------------------------------------------------------------
# Model verification
# ------------------------------------------------------------

print("\nMODEL INFORMATION")
print("-" * 70)
print("Model type:", type(resmlp_model).__name__)
print("Input shape:", resmlp_model.input_shape)
print("Output shape:", resmlp_model.output_shape)

# ------------------------------------------------------------
# Verify 47 input features
# ------------------------------------------------------------

input_features = resmlp_model.input_shape[-1]

print("Expected input features:", input_features)
print("Locked dataset features :", len(feature_names))

assert input_features == 47, (
    f"ResMLP expects {input_features} features, "
    f"but locked dataset has 47."
)

# ------------------------------------------------------------
# Verify training history
# ------------------------------------------------------------

print("\nTRAINING HISTORY")
print("-" * 70)

if isinstance(resmlp_history, dict):
    print("History keys:", list(resmlp_history.keys()))

    if "loss" in resmlp_history:
        print("Training epochs recorded:", len(resmlp_history["loss"]))

    if "val_loss" in resmlp_history:
        print("Validation epochs recorded:", len(resmlp_history["val_loss"]))

# ------------------------------------------------------------
# Final checkpoint confirmation
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("✅ RESMLP CHECKPOINT LOADED")
print("✅ EXISTING TRAINED MODEL USED")
print("✅ NO RESMLP RETRAINING")
print("✅ INPUT FEATURES = 47")
print("✅ TRAINING HISTORY LOADED")
print("✅ ALL FIVE MODELS ARE NOW AVAILABLE")
print("=" * 70)

======================================================================
PHISHSHIELD AI — RESMLP CHECKPOINT VERIFICATION
======================================================================

CHECKPOINT FILES
----------------------------------------------------------------------
ResMLP model : /content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras
History      : /content/drive/MyDrive/PhishShield_AI/models/resmlp_history.pkl

MODEL INFORMATION
----------------------------------------------------------------------
Model type: Functional
Input shape: (None, 47)
Output shape: (None, 1)
Expected input features: 47
Locked dataset features : 47

TRAINING HISTORY
----------------------------------------------------------------------
History keys: ['accuracy', 'loss', 'val_accuracy', 'val_loss']
Training epochs recorded: 40
Validation epochs recorded: 40

======================================================================
✅ RESMLP CHECKPOINT LOADED
✅ EXISTING TRAINED MODEL USED
✅ NO RESMLP RETRAINING
✅ INPUT FEATURES = 47
✅ TRAINING HISTORY LOADED
✅ ALL FIVE MODELS ARE NOW AVAILABLE
======================================================================

In [ ]:
# ============================================================
# PHISHSHIELD AI — RESMLP TEST EVALUATION
# Step 4B: Evaluate already-trained ResMLP
# ============================================================

import os
import numpy as np
import tensorflow as tf
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

BASE_DIR = "/content/drive/MyDrive/PhishShield_AI"
MODEL_DIR = os.path.join(BASE_DIR, "models")

RESMLP_PATH = os.path.join(MODEL_DIR, "resmlp_best.keras")

# ------------------------------------------------------------
# Load existing trained ResMLP
# ------------------------------------------------------------

resmlp_model = tf.keras.models.load_model(RESMLP_PATH)

# ------------------------------------------------------------
# Prepare test data
# ------------------------------------------------------------

X_test_resmlp = X_test.to_numpy(dtype=np.float32)
y_test_resmlp = y_test.to_numpy().astype(int)

# ------------------------------------------------------------
# Generate probability predictions
# ------------------------------------------------------------

y_prob_resmlp = resmlp_model.predict(
    X_test_resmlp,
    batch_size=32,
    verbose=0
).ravel()

# Convert probabilities to class predictions
y_pred_resmlp = (y_prob_resmlp >= 0.5).astype(int)

# ------------------------------------------------------------
# Calculate metrics
# ------------------------------------------------------------

resmlp_accuracy = accuracy_score(
    y_test_resmlp,
    y_pred_resmlp
)

resmlp_precision = precision_score(
    y_test_resmlp,
    y_pred_resmlp,
    zero_division=0
)

resmlp_recall = recall_score(
    y_test_resmlp,
    y_pred_resmlp,
    zero_division=0
)

resmlp_f1 = f1_score(
    y_test_resmlp,
    y_pred_resmlp,
    zero_division=0
)

resmlp_roc_auc = roc_auc_score(
    y_test_resmlp,
    y_prob_resmlp
)

# ------------------------------------------------------------
# Display results
# ------------------------------------------------------------

print("=" * 70)
print("PHISHSHIELD AI — RESMLP TEST SET RESULTS")
print("=" * 70)

print(f"\nAccuracy  : {resmlp_accuracy:.4f} ({resmlp_accuracy*100:.2f}%)")
print(f"Precision : {resmlp_precision:.4f} ({resmlp_precision*100:.2f}%)")
print(f"Recall    : {resmlp_recall:.4f} ({resmlp_recall*100:.2f}%)")
print(f"F1-Score  : {resmlp_f1:.4f} ({resmlp_f1*100:.2f}%)")
print(f"ROC-AUC   : {resmlp_roc_auc:.4f} ({resmlp_roc_auc*100:.2f}%)")

print("\n" + "=" * 70)
print("✅ SAVED RESMLP MODEL EVALUATED")
print("✅ TEST SET = 1500 SAMPLES")
print("✅ INPUT FEATURES = 47")
print("✅ NO RETRAINING")
print("=" * 70)

======================================================================
PHISHSHIELD AI — RESMLP TEST SET RESULTS
======================================================================

Accuracy  : 0.9633 (96.33%)
Precision : 0.9578 (95.78%)
Recall    : 0.9693 (96.93%)
F1-Score  : 0.9636 (96.36%)
ROC-AUC   : 0.9932 (99.32%)

======================================================================
✅ SAVED RESMLP MODEL EVALUATED
✅ TEST SET = 1500 SAMPLES
✅ INPUT FEATURES = 47
✅ NO RETRAINING
======================================================================

In [ ]:
# ============================================================
# PHISHSHIELD AI — STEP 5B
# RT FEATURE RECONSTRUCTION AUDIT
# READ-ONLY — NO TRAINING / NO FILE MODIFICATION
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ------------------------------------------------------------
# 1. Locate dataset
# ------------------------------------------------------------

dataset_candidates = [
    Path("/content/Phishing_Legitimate_full(4).csv"),
    Path("/content/Phishing_Legitimate_full.csv"),
    Path("/content/drive/MyDrive/PhishShield_AI/data/Phishing_Legitimate_full(4).csv"),
    Path("/content/drive/MyDrive/PhishShield_AI/data/Phishing_Legitimate_full.csv"),
]

dataset_path = next(
    (p for p in dataset_candidates if p.exists()),
    None
)

if dataset_path is None:
    print("❌ Dataset not found.")
    print("\nExpected one of:")
    for p in dataset_candidates:
        print(" ", p)

else:

    print("✅ Dataset:", dataset_path)

    df = pd.read_csv(dataset_path)

    print("Shape:", df.shape)

    # --------------------------------------------------------
    # 2. RT features and their likely raw counterparts
    # --------------------------------------------------------

    pairs = {
        "SubdomainLevelRT": "SubdomainLevel",
        "UrlLengthRT": "UrlLength",
        "PctExtResourceUrlsRT": "PctExtResourceUrls",
        "AbnormalExtFormActionR": "AbnormalFormAction",
        "ExtMetaScriptLinkRT": None,
        "PctExtNullSelfRedirectHyperlinksRT":
            "PctNullSelfRedirectHyperlinks"
    }

    # --------------------------------------------------------
    # 3. Basic value audit
    # --------------------------------------------------------

    print("\n" + "=" * 75)
    print("RT FEATURE VALUE AUDIT")
    print("=" * 75)

    rt_features = list(pairs.keys())

    for feature in rt_features:

        values = sorted(df[feature].dropna().unique().tolist())

        counts = df[feature].value_counts().sort_index()

        print(f"\n{feature}")
        print("-" * 60)
        print("Unique values:", values)

        for value, count in counts.items():
            pct = count / len(df) * 100
            print(f"  {value:>4}: {count:>5} ({pct:6.2f}%)")

    # --------------------------------------------------------
    # 4. Relationship audit
    # --------------------------------------------------------

    print("\n" + "=" * 75)
    print("RAW FEATURE → RT FEATURE RELATIONSHIP")
    print("=" * 75)

    for rt_feature, raw_feature in pairs.items():

        if raw_feature is None:
            print(f"\n⚠️ {rt_feature}")
            print("No direct raw counterpart selected.")
            continue

        print(f"\n{raw_feature}  →  {rt_feature}")
        print("-" * 60)

        # Number of distinct raw values
        raw_unique = df[raw_feature].nunique()

        # Number of distinct RT values
        rt_unique = df[rt_feature].nunique()

        print("Raw unique values:", raw_unique)
        print("RT unique values :", rt_unique)

        # Crosstab
        table = pd.crosstab(
            df[raw_feature],
            df[rt_feature],
            normalize="index"
        )

        print("\nConditional distribution:")
        print(table.round(3).to_string())

        # ----------------------------------------------------
        # Determine whether raw value maps to ONE RT value
        # ----------------------------------------------------

        mapping_counts = (
            df.groupby(raw_feature)[rt_feature]
            .nunique()
        )

        deterministic_rows = (mapping_counts == 1).sum()
        total_rows = len(mapping_counts)

        print(
            f"\nRaw values with deterministic RT mapping: "
            f"{deterministic_rows}/{total_rows}"
        )

        if deterministic_rows == total_rows:
            print("✅ Every raw value maps to exactly one RT value.")
        else:
            print(
                "⚠️ Multiple RT values occur for at least "
                "one raw value."
            )

    # --------------------------------------------------------
    # 5. Special audit for ExtMetaScriptLinkRT
    # --------------------------------------------------------

    print("\n" + "=" * 75)
    print("EXTMETASCRIPTLINKRT AUDIT")
    print("=" * 75)

    print("""
ExtMetaScriptLinkRT has no direct raw counterpart in the
dataset.

We therefore inspect its relationship with:

    PctExtResourceUrls
    PctExtHyperlinks
    PctNullSelfRedirectHyperlinks
    FrequentDomainNameMismatch

No rule will be assumed from this analysis.
""")

    candidate_features = [
        "PctExtResourceUrls",
        "PctExtHyperlinks",
        "PctNullSelfRedirectHyperlinks",
        "FrequentDomainNameMismatch"
    ]

    for feature in candidate_features:

        print(f"\n{feature} → ExtMetaScriptLinkRT")
        print("-" * 60)

        table = pd.crosstab(
            df[feature],
            df["ExtMetaScriptLinkRT"],
            normalize="index"
        )

        print(table.round(3).to_string())

    # --------------------------------------------------------
    # 6. RT feature vs class label
    # --------------------------------------------------------

    print("\n" + "=" * 75)
    print("RT FEATURE vs CLASS LABEL")
    print("=" * 75)

    for feature in rt_features:

        print(f"\n{feature}")
        print("-" * 60)

        table = pd.crosstab(
            df[feature],
            df["CLASS_LABEL"],
            normalize="index"
        )

        print(table.round(3).to_string())

    # --------------------------------------------------------
    # 7. Important conclusion
    # --------------------------------------------------------

    print("\n" + "=" * 75)
    print("STEP 5B COMPLETE")
    print("=" * 75)

    print("""
IMPORTANT:

Do NOT implement any RT rule yet.

Do NOT modify Antigravity backend.

Do NOT retrain XGBoost.

Do NOT replace RT values with 0.

The next implementation decision will be based on the
actual output of this audit.
""")

Streaming output truncated to the last 5000 lines.
0.154639             0.000  1.000  0.000
0.154762             0.000  1.000  0.000
0.154930             0.000  1.000  0.000
0.155172             0.000  0.667  0.333
0.155556             0.000  0.750  0.250
0.156250             0.000  0.600  0.400
0.156522             0.000  1.000  0.000
0.156863             0.000  0.750  0.250
0.157895             0.000  0.900  0.100
0.158730             0.000  1.000  0.000
0.159091             0.000  0.667  0.333
0.160000             0.000  0.786  0.214
0.160377             0.000  1.000  0.000
0.161017             0.000  1.000  0.000
0.161290             0.000  1.000  0.000
0.162162             0.000  1.000  0.000
0.162500             0.000  1.000  0.000
0.162791             0.000  1.000  0.000
0.163265             0.000  1.000  0.000
0.163636             0.000  1.000  0.000
0.164179             0.000  1.000  0.000
0.164706             0.000  1.000  0.000
0.166667             0.011  0.717  0.272
0.167702             0.000  1.000  0.000
0.169014             0.000  1.000  0.000
0.169231             0.000  1.000  0.000
0.169492             0.000  1.000  0.000
0.169811             0.000  1.000  0.000
0.170213             0.000  1.000  0.000
0.170732             0.000  0.800  0.200
0.171053             0.000  1.000  0.000
0.171429             0.000  1.000  0.000
0.172414             0.000  1.000  0.000
0.172840             0.000  1.000  0.000
0.173077             0.000  0.333  0.667
0.173469             1.000  0.000  0.000
0.173913             0.000  0.909  0.091
0.175000             0.000  0.500  0.500
0.175439             0.000  1.000  0.000
0.175676             0.000  1.000  0.000
0.175781             0.000  1.000  0.000
0.175926             0.000  1.000  0.000
0.176471             0.000  0.643  0.357
0.177215             0.000  0.500  0.500
0.177632             0.000  1.000  0.000
0.177778             0.000  1.000  0.000
0.178082             0.000  1.000  0.000
0.178571             0.000  0.909  0.091
0.179104             0.000  1.000  0.000
0.179487             0.000  1.000  0.000
0.179775             0.000  1.000  0.000
0.180000             0.000  1.000  0.000
0.181818             0.024  0.683  0.293
0.183007             0.000  1.000  0.000
0.183486             0.000  1.000  0.000
0.183673             0.000  1.000  0.000
0.184211             0.000  0.000  1.000
0.184397             0.000  1.000  0.000
0.184615             0.000  1.000  0.000
0.185185             0.000  0.600  0.400
0.186047             0.000  0.875  0.125
0.186441             0.000  1.000  0.000
0.187500             0.000  0.944  0.056
0.188406             0.000  1.000  0.000
0.188679             0.000  1.000  0.000
0.188976             0.000  1.000  0.000
0.189189             0.000  1.000  0.000
0.189474             0.000  0.000  1.000
0.189873             1.000  0.000  0.000
0.190217             0.000  1.000  0.000
0.190476             0.000  0.750  0.250
0.191489             0.000  1.000  0.000
0.192308             0.000  0.857  0.143
0.192982             0.000  1.000  0.000
0.193548             0.000  1.000  0.000
0.193878             0.000  1.000  0.000
0.194444             0.000  1.000  0.000
0.194805             0.000  1.000  0.000
0.195652             0.000  0.500  0.500
0.195876             0.000  1.000  0.000
0.196078             0.000  0.750  0.250
0.196262             0.000  1.000  0.000
0.197183             0.000  1.000  0.000
0.197674             0.000  1.000  0.000
0.200000             0.000  0.822  0.178
0.201717             0.000  1.000  0.000
0.202020             0.000  1.000  0.000
0.202128             0.000  1.000  0.000
0.202532             0.000  1.000  0.000
0.202899             0.000  1.000  0.000
0.203390             0.000  1.000  0.000
0.203704             0.000  1.000  0.000
0.204082             0.000  1.000  0.000
0.204420             0.000  1.000  0.000
0.204545             0.000  0.500  0.500
0.205128             0.000  1.000  0.000
0.205479             0.000  1.000  0.000
0.205882             0.000  1.000  0.000
0.206897             0.143  0.857  0.000
0.207317             0.000  1.000  0.000
0.207547             0.000  1.000  0.000
0.208333             0.000  1.000  0.000
0.208791             0.000  1.000  0.000
0.208955             0.000  1.000  0.000
0.209302             0.000  1.000  0.000
0.209677             0.000  1.000  0.000
0.210526             0.000  1.000  0.000
0.211009             0.000  1.000  0.000
0.211538             0.000  0.500  0.500
0.212963             0.000  1.000  0.000
0.213115             0.000  1.000  0.000
0.213483             0.000  1.000  0.000
0.214286             0.000  0.680  0.320
0.215385             0.000  1.000  0.000
0.216216             0.000  1.000  0.000
0.216667             0.500  0.500  0.000
0.217391             0.000  0.500  0.500
0.218182             0.000  1.000  0.000
0.218750             0.000  1.000  0.000
0.219512             0.000  1.000  0.000
0.220000             0.000  1.000  0.000
0.220588             0.000  1.000  0.000
0.222222             0.000  0.885  0.115
0.223140             0.000  1.000  0.000
0.224138             0.000  1.000  0.000
0.224490             0.000  1.000  0.000
0.224719             0.000  1.000  0.000
0.225000             0.000  0.667  0.333
0.225806             0.000  1.000  0.000
0.226415             0.000  1.000  0.000
0.227273             0.100  0.800  0.100
0.228070             0.000  1.000  0.000
0.228571             0.000  1.000  0.000
0.230769             0.000  0.769  0.231
0.231405             0.000  1.000  0.000
0.231579             0.000  1.000  0.000
0.231707             0.000  1.000  0.000
0.231884             0.000  1.000  0.000
0.232143             0.000  1.000  0.000
0.232323             0.000  1.000  0.000
0.233333             0.000  1.000  0.000
0.234043             0.000  1.000  0.000
0.234375             0.000  1.000  0.000
0.234694             0.000  1.000  0.000
0.235294             0.053  0.895  0.053
0.236364             0.000  0.500  0.500
0.236842             0.000  1.000  0.000
0.237288             0.000  1.000  0.000
0.238095             0.000  0.857  0.143
0.238806             0.000  1.000  0.000
0.238938             0.000  1.000  0.000
0.239130             0.000  1.000  0.000
0.240000             0.200  0.800  0.000
0.240741             0.000  1.000  0.000
0.241379             0.000  1.000  0.000
0.241830             0.000  0.000  1.000
0.241935             0.000  1.000  0.000
0.242424             0.000  1.000  0.000
0.243243             0.000  1.000  0.000
0.243478             0.000  1.000  0.000
0.243590             0.000  1.000  0.000
0.243902             0.000  1.000  0.000
0.244186             1.000  0.000  0.000
0.244444             0.000  1.000  0.000
0.244898             0.000  1.000  0.000
0.245283             0.000  1.000  0.000
0.245614             0.000  1.000  0.000
0.245902             0.000  1.000  0.000
0.246154             0.000  1.000  0.000
0.246575             0.000  1.000  0.000
0.248447             0.000  1.000  0.000
0.250000             0.031  0.857  0.112
0.252874             0.000  1.000  0.000
0.253012             0.000  1.000  0.000
0.253731             0.000  1.000  0.000
0.254545             0.000  1.000  0.000
0.254902             0.000  1.000  0.000
0.255319             0.000  1.000  0.000
0.255814             0.000  1.000  0.000
0.256410             0.000  1.000  0.000
0.257143             0.000  1.000  0.000
0.257426             0.000  1.000  0.000
0.257669             0.000  1.000  0.000
0.258065             0.000  1.000  0.000
0.258621             0.000  1.000  0.000
0.258824             0.000  1.000  0.000
0.259259             0.000  0.917  0.083
0.260870             0.000  0.917  0.083
0.261905             0.333  0.667  0.000
0.262295             0.000  1.000  0.000
0.263158             0.000  1.000  0.000
0.263736             0.000  1.000  0.000
0.264151             0.000  1.000  0.000
0.264706             0.000  1.000  0.000
0.265060             0.000  1.000  0.000
0.265306             0.000  1.000  0.000
0.265625             0.000  1.000  0.000
0.266667             0.000  0.700  0.300
0.267606             0.000  1.000  0.000
0.268293             0.000  1.000  0.000
0.268657             0.000  1.000  0.000
0.269231             0.000  1.000  0.000
0.269841             0.000  1.000  0.000
0.269896             0.000  1.000  0.000
0.270270             0.000  1.000  0.000
0.270492             0.000  1.000  0.000
0.270833             0.000  0.667  0.333
0.272727             0.000  0.913  0.087
0.273810             0.000  1.000  0.000
0.274510             0.000  1.000  0.000
0.275000             0.000  1.000  0.000
0.275862             0.000  0.800  0.200
0.276923             0.000  1.000  0.000
0.277108             0.000  1.000  0.000
0.277778             0.000  1.000  0.000
0.278351             0.000  1.000  0.000
0.278481             0.000  1.000  0.000
0.279070             0.000  1.000  0.000
0.280000             0.125  0.875  0.000
0.281250             0.000  1.000  0.000
0.282051             0.000  1.000  0.000
0.282609             0.000  1.000  0.000
0.283019             0.000  1.000  0.000
0.283582             0.000  1.000  0.000
0.285714             0.386  0.557  0.057
0.286486             0.000  1.000  0.000
0.287500             0.000  1.000  0.000
0.288136             0.000  1.000  0.000
0.288462             0.000  1.000  0.000
0.288889             1.000  0.000  0.000
0.289157             0.000  1.000  0.000
0.289474             0.000  1.000  0.000
0.290323             0.000  1.000  0.000
0.290909             0.000  1.000  0.000
0.291667             0.000  1.000  0.000
0.292308             0.000  1.000  0.000
0.292683             0.000  1.000  0.000
0.293103             0.000  1.000  0.000
0.293333             0.000  1.000  0.000
0.294118             0.000  1.000  0.000
0.295455             0.000  1.000  0.000
0.296296             0.000  0.857  0.143
0.297297             0.000  1.000  0.000
0.298013             0.000  1.000  0.000
0.298246             0.000  1.000  0.000
0.298507             0.000  0.000  1.000
0.298701             0.000  1.000  0.000
0.300000             0.062  0.875  0.062
0.301370             0.000  1.000  0.000
0.301724             0.000  1.000  0.000
0.301775             0.000  1.000  0.000
0.301887             0.000  1.000  0.000
0.302326             0.000  1.000  0.000
0.303030             0.000  1.000  0.000
0.304348             0.000  1.000  0.000
0.305556             0.000  1.000  0.000
0.305882             0.000  1.000  0.000
0.306122             0.667  0.333  0.000
0.306452             0.000  1.000  0.000
0.307692             0.000  1.000  0.000
0.309091             0.000  1.000  0.000
0.309524             0.000  1.000  0.000
0.309859             0.000  1.000  0.000
0.310345             0.000  1.000  0.000
0.311111             0.000  1.000  0.000
0.312500             0.000  1.000  0.000
0.313253             0.000  1.000  0.000
0.313725             0.000  1.000  0.000
0.314286             0.000  1.000  0.000
0.314815             0.000  1.000  0.000
0.315789             0.000  0.947  0.053
0.316667             0.000  1.000  0.000
0.317073             0.000  1.000  0.000
0.317308             0.000  1.000  0.000
0.318182             0.000  1.000  0.000
0.319149             0.000  1.000  0.000
0.320000             0.000  0.875  0.125
0.320388             0.000  1.000  0.000
0.320611             0.000  0.000  1.000
0.320755             0.000  1.000  0.000
0.321101             0.000  1.000  0.000
0.321429             0.000  1.000  0.000
0.321839             1.000  0.000  0.000
0.322581             0.000  1.000  0.000
0.323077             0.000  1.000  0.000
0.323353             0.000  1.000  0.000
0.324324             0.000  1.000  0.000
0.324675             0.000  1.000  0.000
0.325000             0.000  0.857  0.143
0.325581             0.000  1.000  0.000
0.326087             0.000  1.000  0.000
0.326531             0.000  1.000  0.000
0.326923             0.000  1.000  0.000
0.327273             0.000  0.000  1.000
0.327434             0.000  1.000  0.000
0.327586             0.000  1.000  0.000
0.327869             0.000  1.000  0.000
0.328125             0.000  1.000  0.000
0.328358             0.000  1.000  0.000
0.328947             0.000  1.000  0.000
0.329268             0.000  1.000  0.000
0.329787             0.000  1.000  0.000
0.330508             0.000  1.000  0.000
0.333333             0.183  0.762  0.055
0.337209             0.000  1.000  0.000
0.338235             0.000  1.000  0.000
0.338462             0.000  1.000  0.000
0.338710             0.000  1.000  0.000
0.339286             0.000  1.000  0.000
0.339623             0.000  1.000  0.000
0.340000             0.000  1.000  0.000
0.340426             0.000  1.000  0.000
0.340909             0.000  1.000  0.000
0.341463             0.000  1.000  0.000
0.342105             0.000  1.000  0.000
0.342466             0.000  1.000  0.000
0.342857             0.125  0.875  0.000
0.343750             0.000  0.833  0.167
0.344262             0.000  1.000  0.000
0.344828             0.000  1.000  0.000
0.346154             0.000  0.667  0.333
0.346939             0.000  1.000  0.000
0.347368             0.000  1.000  0.000
0.347826             0.000  1.000  0.000
0.348485             0.000  1.000  0.000
0.348837             0.000  1.000  0.000
0.350000             0.000  1.000  0.000
0.351351             0.000  1.000  0.000
0.351852             0.000  1.000  0.000
0.352113             0.000  1.000  0.000
0.352941             0.000  1.000  0.000
0.354167             0.000  1.000  0.000
0.354839             0.000  1.000  0.000
0.355556             0.500  0.500  0.000
0.356164             0.000  1.000  0.000
0.357143             0.000  1.000  0.000
0.358209             0.000  1.000  0.000
0.358974             0.000  1.000  0.000
0.359375             0.000  0.750  0.250
0.360000             0.000  1.000  0.000
0.361111             0.000  1.000  0.000
0.361446             0.000  1.000  0.000
0.361702             0.000  1.000  0.000
0.362069             0.000  1.000  0.000
0.363636             0.000  1.000  0.000
0.364583             0.000  1.000  0.000
0.364706             0.000  1.000  0.000
0.365854             0.000  1.000  0.000
0.366667             0.250  0.750  0.000
0.367089             0.000  1.000  0.000
0.368421             0.000  1.000  0.000
0.369231             0.000  1.000  0.000
0.369565             0.000  1.000  0.000
0.370370             0.000  1.000  0.000
0.370968             0.000  1.000  0.000
0.371429             0.000  0.800  0.200
0.372093             0.000  1.000  0.000
0.372881             0.000  1.000  0.000
0.373494             0.000  1.000  0.000
0.375000             0.000  0.950  0.050
0.376147             0.000  1.000  0.000
0.376623             0.000  1.000  0.000
0.377049             0.000  1.000  0.000
0.377778             0.000  1.000  0.000
0.378049             0.000  1.000  0.000
0.378378             0.000  0.000  1.000
0.379310             0.000  1.000  0.000
0.380952             0.000  1.000  0.000
0.381579             0.000  1.000  0.000
0.381818             0.000  1.000  0.000
0.382353             0.000  1.000  0.000
0.383562             0.000  1.000  0.000
0.384106             0.000  1.000  0.000
0.384615             0.043  0.870  0.087
0.385965             0.000  1.000  0.000
0.387097             0.000  1.000  0.000
0.388060             0.000  1.000  0.000
0.388889             0.000  1.000  0.000
0.390244             0.000  1.000  0.000
0.391304             0.000  1.000  0.000
0.392857             0.111  0.889  0.000
0.393443             0.000  1.000  0.000
0.393939             0.000  1.000  0.000
0.394366             0.000  1.000  0.000
0.394737             0.000  1.000  0.000
0.395833             0.000  1.000  0.000
0.396552             0.000  1.000  0.000
0.396825             0.000  1.000  0.000
0.397436             0.000  1.000  0.000
0.397959             0.000  1.000  0.000
0.400000             0.028  0.972  0.000
0.402062             0.000  1.000  0.000
0.403226             0.000  1.000  0.000
0.403846             0.000  1.000  0.000
0.404255             0.000  1.000  0.000
0.404762             0.000  1.000  0.000
0.405405             0.000  1.000  0.000
0.406250             0.000  0.600  0.400
0.407407             0.000  1.000  0.000
0.408163             0.000  1.000  0.000
0.409091             0.000  1.000  0.000
0.410256             0.000  1.000  0.000
0.411765             0.000  1.000  0.000
0.413043             0.000  0.667  0.333
0.413333             0.000  1.000  0.000
0.414634             0.000  1.000  0.000
0.415094             0.000  1.000  0.000
0.415385             0.000  1.000  0.000
0.415584             0.000  1.000  0.000
0.416667             0.067  0.933  0.000
0.417582             0.000  1.000  0.000
0.417910             0.000  1.000  0.000
0.418605             0.000  1.000  0.000
0.418919             0.000  1.000  0.000
0.419355             0.000  1.000  0.000
0.421053             0.000  1.000  0.000
0.421875             0.000  1.000  0.000
0.422018             0.000  1.000  0.000
0.422078             0.000  1.000  0.000
0.423077             0.167  0.833  0.000
0.423729             0.000  1.000  0.000
0.423913             0.000  1.000  0.000
0.424242             0.000  1.000  0.000
0.425000             0.000  1.000  0.000
0.425287             0.000  0.000  1.000
0.425926             0.000  1.000  0.000
0.426230             0.000  1.000  0.000
0.427273             0.000  1.000  0.000
0.428571             0.045  0.909  0.045
0.429487             0.000  1.000  0.000
0.431373             0.000  1.000  0.000
0.431818             0.000  1.000  0.000
0.432432             0.000  1.000  0.000
0.433333             0.000  1.000  0.000
0.433735             0.000  1.000  0.000
0.434783             0.000  1.000  0.000
0.435484             0.000  1.000  0.000
0.436620             0.000  1.000  0.000
0.436782             0.000  1.000  0.000
0.437500             0.000  0.833  0.167
0.438202             0.000  1.000  0.000
0.438596             0.000  0.500  0.500
0.439024             0.000  1.000  0.000
0.440000             0.000  1.000  0.000
0.440559             0.000  1.000  0.000
0.441860             0.000  1.000  0.000
0.442857             0.000  1.000  0.000
0.443038             0.000  1.000  0.000
0.444444             0.000  1.000  0.000
0.446809             0.000  1.000  0.000
0.447368             0.000  1.000  0.000
0.447619             0.000  1.000  0.000
0.448276             0.500  0.500  0.000
0.448718             0.000  1.000  0.000
0.449438             0.000  1.000  0.000
0.450000             0.000  1.000  0.000
0.450980             0.000  1.000  0.000
0.451220             0.000  1.000  0.000
0.451613             0.000  0.750  0.250
0.452381             0.000  0.000  1.000
0.453125             0.000  0.500  0.500
0.454545             0.000  1.000  0.000
0.456140             0.000  1.000  0.000
0.456522             0.000  1.000  0.000
0.457627             0.000  1.000  0.000
0.457831             0.000  1.000  0.000
0.458333             0.000  1.000  0.000
0.459016             0.000  1.000  0.000
0.459459             0.000  1.000  0.000
0.460000             0.000  1.000  0.000
0.460432             0.000  1.000  0.000
0.461538             0.000  1.000  0.000
0.462687             0.000  1.000  0.000
0.462963             0.000  1.000  0.000
0.463768             0.000  1.000  0.000
0.464286             0.000  1.000  0.000
0.465116             0.000  1.000  0.000
0.465517             0.000  1.000  0.000
0.466667             0.000  1.000  0.000
0.467532             0.000  1.000  0.000
0.467626             0.000  1.000  0.000
0.468085             0.000  1.000  0.000
0.468750             0.000  1.000  0.000
0.469697             0.000  1.000  0.000
0.469880             0.000  1.000  0.000
0.470588             0.000  1.000  0.000

In [ ]:
# ============================================================
# PHISHSHIELD AI — STEP 5C
# THRESHOLD DISCOVERY FOR RT FEATURES
# READ-ONLY — NO TRAINING / NO FILE MODIFICATION
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ------------------------------------------------------------
# 1. Locate dataset
# ------------------------------------------------------------

candidates = [
    Path("/content/Phishing_Legitimate_full(4).csv"),
    Path("/content/Phishing_Legitimate_full.csv"),
    Path("/content/drive/MyDrive/PhishShield_AI/data/Phishing_Legitimate_full(4).csv"),
    Path("/content/drive/MyDrive/PhishShield_AI/data/Phishing_Legitimate_full.csv"),
]

dataset_path = next((p for p in candidates if p.exists()), None)

if dataset_path is None:
    print("❌ Dataset not found.")
else:

    df = pd.read_csv(dataset_path)

    print("✅ Dataset loaded:", dataset_path)
    print("Shape:", df.shape)

    # --------------------------------------------------------
    # Function to inspect raw → RT mapping
    # --------------------------------------------------------

    def inspect_mapping(raw_col, rt_col):

        print("\n" + "=" * 80)
        print(f"{raw_col}  →  {rt_col}")
        print("=" * 80)

        grouped = (
            df.groupby(raw_col)[rt_col]
            .agg(
                unique_values=lambda x: sorted(x.unique().tolist()),
                count="size"
            )
            .reset_index()
        )

        # Add deterministic flag
        grouped["deterministic"] = (
            grouped["unique_values"].apply(len) == 1
        )

        print("\nFirst 50 raw values:")
        print(grouped.head(50).to_string(index=False))

        print("\nLast 50 raw values:")
        print(grouped.tail(50).to_string(index=False))

        # ----------------------------------------------------
        # Range of raw values for each RT category
        # ----------------------------------------------------

        print("\n" + "-" * 80)
        print("RAW VALUE RANGE FOR EACH RT CATEGORY")
        print("-" * 80)

        for rt_value in sorted(df[rt_col].unique()):

            subset = df[df[rt_col] == rt_value][raw_col]

            print(
                f"RT = {rt_value:>2} | "
                f"min = {subset.min():>8} | "
                f"max = {subset.max():>8} | "
                f"unique = {subset.nunique():>5} | "
                f"rows = {len(subset):>5}"
            )

        # ----------------------------------------------------
        # Find transitions in sorted raw values
        # ----------------------------------------------------

        print("\n" + "-" * 80)
        print("POTENTIAL TRANSITION POINTS")
        print("-" * 80)

        sorted_df = (
            df[[raw_col, rt_col]]
            .drop_duplicates()
            .sort_values(raw_col)
        )

        previous_rt = None

        transitions = []

        for _, row in sorted_df.iterrows():

            current_raw = row[raw_col]
            current_rt = row[rt_col]

            if previous_rt is not None and current_rt != previous_rt:
                transitions.append(
                    (current_raw, previous_rt, current_rt)
                )

            previous_rt = current_rt

        for transition in transitions[:100]:
            print(
                f"raw={transition[0]} : "
                f"{transition[1]} → {transition[2]}"
            )

        if len(transitions) > 100:
            print(
                f"... {len(transitions) - 100} additional transitions"
            )

        # ----------------------------------------------------
        # Determinism score
        # ----------------------------------------------------

        deterministic_percentage = (
            grouped["deterministic"].mean() * 100
        )

        print("\n" + "-" * 80)
        print(
            f"Deterministic raw-value mapping: "
            f"{deterministic_percentage:.2f}%"
        )

        if deterministic_percentage == 100:
            print(
                "✅ Every raw value has exactly one RT category."
            )
        else:
            print(
                "⚠️ Some raw values occur with multiple RT categories."
            )

    # --------------------------------------------------------
    # Analyze strongest relationships
    # --------------------------------------------------------

    inspect_mapping(
        "UrlLength",
        "UrlLengthRT"
    )

    inspect_mapping(
        "SubdomainLevel",
        "SubdomainLevelRT"
    )

    print("\n" + "=" * 80)
    print("STEP 5C COMPLETE")
    print("=" * 80)

    print("""
No implementation has been performed.

No backend files changed.
No models changed.
No training performed.

Send the complete output before we proceed.
""")

✅ Dataset loaded: /content/Phishing_Legitimate_full.csv
Shape: (10000, 50)

================================================================================
UrlLength  →  UrlLengthRT
================================================================================

First 50 raw values:
 UrlLength unique_values  count  deterministic
        12           [1]      1           True
        13           [1]      1           True
        14           [1]      3           True
        15           [1]      2           True
        17           [1]      3           True
        18           [1]      3           True
        19           [1]      8           True
        20           [1]      8           True
        21           [1]     23           True
        22           [1]     14           True
        23           [1]     16           True
        24           [1]     19           True
        25           [1]     41           True
        26           [1]     34           True
        27           [1]     36           True
        28           [1]     42           True
        29           [1]     49           True
        30           [1]     57           True
        31           [1]     47           True
        32           [1]     84           True
        33           [1]     68           True
        34           [1]     86           True
        35           [1]     82           True
        36           [1]     97           True
        37           [1]    136           True
        38           [1]    131           True
        39           [1]    146           True
        40           [1]    122           True
        41           [1]    131           True
        42           [1]    148           True
        43           [1]    160           True
        44           [1]    147           True
        45           [1]    154           True
        46           [1]    147           True
        47           [1]    189           True
        48           [1]    192           True
        49           [1]    137           True
        50           [1]    182           True
        51           [1]    175           True
        52           [1]    181           True
        53           [1]    163           True
        54           [0]    181           True
        55           [0]    163           True
        56           [0]    165           True
        57           [0]    192           True
        58           [0]    168           True
        59           [0]    182           True
        60           [0]    189           True
        61           [0]    167           True
        62           [0]    166           True

Last 50 raw values:
 UrlLength unique_values  count  deterministic
       189          [-1]      2           True
       190          [-1]      4           True
       191          [-1]     16           True
       192          [-1]      3           True
       194          [-1]      1           True
       195          [-1]      1           True
       196          [-1]      1           True
       197          [-1]      3           True
       198          [-1]      3           True
       199          [-1]      7           True
       200          [-1]      2           True
       201          [-1]      3           True
       202          [-1]      4           True
       203          [-1]      2           True
       204          [-1]      1           True
       205          [-1]      5           True
       206          [-1]      2           True
       208          [-1]      1           True
       210          [-1]      3           True
       211          [-1]      3           True
       212          [-1]      2           True
       213          [-1]     13           True
       215          [-1]      1           True
       216          [-1]      3           True
       217          [-1]      1           True
       218          [-1]      2           True
       219          [-1]      1           True
       220          [-1]      4           True
       221          [-1]      2           True
       222          [-1]      1           True
       223          [-1]      3           True
       224          [-1]      1           True
       225          [-1]      4           True
       226          [-1]      1           True
       228          [-1]      1           True
       229          [-1]      1           True
       231          [-1]      4           True
       236          [-1]      1           True
       237          [-1]      1           True
       240          [-1]      2           True
       241          [-1]      2           True
       242          [-1]      2           True
       244          [-1]      1           True
       245          [-1]      1           True
       247          [-1]      1           True
       248          [-1]      2           True
       249          [-1]      1           True
       251          [-1]      1           True
       252          [-1]      3           True
       253          [-1]      1           True

--------------------------------------------------------------------------------
RAW VALUE RANGE FOR EACH RT CATEGORY
--------------------------------------------------------------------------------
RT = -1 | min =       76 | max =      253 | unique =   163 | rows =  3263
RT =  0 | min =       54 | max =       75 | unique =    22 | rows =  3272
RT =  1 | min =       12 | max =       53 | unique =    41 | rows =  3465

--------------------------------------------------------------------------------
POTENTIAL TRANSITION POINTS
--------------------------------------------------------------------------------
raw=54 : 1 → 0
raw=76 : 0 → -1

--------------------------------------------------------------------------------
Deterministic raw-value mapping: 100.00%
✅ Every raw value has exactly one RT category.

================================================================================
SubdomainLevel  →  SubdomainLevelRT
================================================================================

First 50 raw values:
 SubdomainLevel unique_values  count  deterministic
              0           [1]   4835           True
              1           [1]   4790           True
              2        [0, 1]    272          False
              3       [-1, 0]     22          False
              4          [-1]     30           True
              5          [-1]      6           True
              6          [-1]     26           True
              7          [-1]      7           True
              8          [-1]      5           True
              9          [-1]      3           True
             10          [-1]      1           True
             11          [-1]      2           True
             14          [-1]      1           True

Last 50 raw values:
 SubdomainLevel unique_values  count  deterministic
              0           [1]   4835           True
              1           [1]   4790           True
              2        [0, 1]    272          False
              3       [-1, 0]     22          False
              4          [-1]     30           True
              5          [-1]      6           True
              6          [-1]     26           True
              7          [-1]      7           True
              8          [-1]      5           True
              9          [-1]      3           True
             10          [-1]      1           True
             11          [-1]      2           True
             14          [-1]      1           True

--------------------------------------------------------------------------------
RAW VALUE RANGE FOR EACH RT CATEGORY
--------------------------------------------------------------------------------
RT = -1 | min =        3 | max =       14 | unique =    10 | rows =   100
RT =  0 | min =        2 | max =        3 | unique =     2 | rows =   234
RT =  1 | min =        0 | max =        2 | unique =     3 | rows =  9666

--------------------------------------------------------------------------------
POTENTIAL TRANSITION POINTS
--------------------------------------------------------------------------------
raw=2 : 1 → 0
raw=3 : 0 → -1
raw=3 : -1 → 0
raw=4 : 0 → -1

--------------------------------------------------------------------------------
Deterministic raw-value mapping: 84.62%
⚠️ Some raw values occur with multiple RT categories.

================================================================================
STEP 5C COMPLETE
================================================================================

No implementation has been performed.

No backend files changed.
No models changed.
No training performed.

Send the complete output before we proceed.

In [ ]:
# ============================================================
# PHISHSHIELD AI — STEP 5D
# SUBDOMAINLEVELRT AMBIGUITY ANALYSIS
# READ-ONLY
# ============================================================

import pandas as pd
from pathlib import Path

# ------------------------------------------------------------
# Locate dataset
# ------------------------------------------------------------

candidates = [
    Path("/content/Phishing_Legitimate_full.csv"),
    Path("/content/Phishing_Legitimate_full(4).csv"),
    Path("/content/drive/MyDrive/PhishShield_AI/data/Phishing_Legitimate_full.csv"),
    Path("/content/drive/MyDrive/PhishShield_AI/data/Phishing_Legitimate_full(4).csv"),
]

dataset_path = next((p for p in candidates if p.exists()), None)

if dataset_path is None:

    print("❌ Dataset not found.")

else:

    df = pd.read_csv(dataset_path)

    print("✅ Dataset:", dataset_path)
    print("Shape:", df.shape)

    # --------------------------------------------------------
    # Features most likely to help explain the RT state
    # --------------------------------------------------------

    analysis_features = [
        "SubdomainLevel",
        "SubdomainLevelRT",
        "NumDots",
        "HostnameLength",
        "UrlLength",
        "PathLevel",
        "NumDashInHostname",
        "DomainInSubdomains",
        "DomainInPaths",
        "IpAddress",
        "RandomString",
        "NoHttps",
        "NumSensitiveWords",
        "CLASS_LABEL"
    ]

    # --------------------------------------------------------
    # 1. Raw SubdomainLevel = 2
    # --------------------------------------------------------

    print("\n" + "=" * 85)
    print("SUBDOMAIN LEVEL = 2")
    print("=" * 85)

    subset_2 = df[df["SubdomainLevel"] == 2][analysis_features]

    print(
        "\nRT distribution:"
    )
    print(
        subset_2["SubdomainLevelRT"]
        .value_counts()
        .sort_index()
    )

    print("\nCross-tab with selected features:")

    for feature in [
        "NumDots",
        "HostnameLength",
        "UrlLength",
        "DomainInSubdomains",
        "DomainInPaths",
        "CLASS_LABEL"
    ]:

        print(f"\n{feature} → SubdomainLevelRT")

        print(
            pd.crosstab(
                subset_2[feature],
                subset_2["SubdomainLevelRT"],
                normalize="index"
            )
            .round(3)
            .to_string()
        )

    # --------------------------------------------------------
    # 2. Raw SubdomainLevel = 3
    # --------------------------------------------------------

    print("\n" + "=" * 85)
    print("SUBDOMAIN LEVEL = 3")
    print("=" * 85)

    subset_3 = df[df["SubdomainLevel"] == 3][analysis_features]

    print(
        "\nRT distribution:"
    )
    print(
        subset_3["SubdomainLevelRT"]
        .value_counts()
        .sort_index()
    )

    print("\nCross-tab with selected features:")

    for feature in [
        "NumDots",
        "HostnameLength",
        "UrlLength",
        "DomainInSubdomains",
        "DomainInPaths",
        "CLASS_LABEL"
    ]:

        print(f"\n{feature} → SubdomainLevelRT")

        print(
            pd.crosstab(
                subset_3[feature],
                subset_3["SubdomainLevelRT"],
                normalize="index"
            )
            .round(3)
            .to_string()
        )

    # --------------------------------------------------------
    # 3. Show representative ambiguous rows
    # --------------------------------------------------------

    print("\n" + "=" * 85)
    print("REPRESENTATIVE AMBIGUOUS ROWS")
    print("=" * 85)

    ambiguous = df[
        (
            (df["SubdomainLevel"] == 2) &
            (df["SubdomainLevelRT"].isin([0, 1]))
        )
        |
        (
            (df["SubdomainLevel"] == 3) &
            (df["SubdomainLevelRT"].isin([-1, 0]))
        )
    ][analysis_features]

    print(
        ambiguous
        .sort_values(
            ["SubdomainLevel", "SubdomainLevelRT"]
        )
        .head(100)
        .to_string(index=False)
    )

    # --------------------------------------------------------
    # 4. Summary
    # --------------------------------------------------------

    print("\n" + "=" * 85)
    print("STEP 5D COMPLETE")
    print("=" * 85)

    print("""
No backend modifications.
No model modifications.
No training.

The purpose is to discover what additional feature(s)
explain the ambiguous SubdomainLevelRT values.
""")

✅ Dataset: /content/Phishing_Legitimate_full.csv
Shape: (10000, 50)

=====================================================================================
SUBDOMAIN LEVEL = 2
=====================================================================================

RT distribution:
SubdomainLevelRT
0    231
1     41
Name: count, dtype: int64

Cross-tab with selected features:

NumDots → SubdomainLevelRT
SubdomainLevelRT      0      1
NumDots
3                 0.952  0.048
4                 0.723  0.277
5                 0.703  0.297
6                 1.000  0.000
7                 1.000  0.000
8                 1.000  0.000

HostnameLength → SubdomainLevelRT
SubdomainLevelRT      0      1
HostnameLength
15                1.000  0.000
16                0.750  0.250
17                0.692  0.308
18                0.833  0.167
19                1.000  0.000
20                0.857  0.143
21                0.889  0.111
22                0.727  0.273
23                0.909  0.091
24                1.000  0.000
25                0.929  0.071
26                0.333  0.667
27                0.750  0.250
28                0.857  0.143
29                1.000  0.000
30                0.800  0.200
31                1.000  0.000
32                0.400  0.600
33                0.667  0.333
34                1.000  0.000
35                0.857  0.143
36                1.000  0.000
37                1.000  0.000
39                0.000  1.000
40                0.000  1.000
42                1.000  0.000
43                0.000  1.000
44                1.000  0.000
47                0.000  1.000
49                1.000  0.000
50                1.000  0.000
52                0.000  1.000
55                1.000  0.000
57                1.000  0.000
58                1.000  0.000
66                1.000  0.000

UrlLength → SubdomainLevelRT
SubdomainLevelRT      0      1
UrlLength
32                1.000  0.000
33                1.000  0.000
34                1.000  0.000
35                1.000  0.000
36                1.000  0.000
37                1.000  0.000
38                1.000  0.000
39                0.000  1.000
41                0.667  0.333
42                1.000  0.000
43                1.000  0.000
45                1.000  0.000
46                0.000  1.000
49                0.500  0.500
50                0.500  0.500
51                1.000  0.000
52                1.000  0.000
53                0.500  0.500
54                0.000  1.000
55                0.250  0.750
56                0.000  1.000
57                1.000  0.000
58                1.000  0.000
59                0.500  0.500
60                0.667  0.333
61                1.000  0.000
62                0.500  0.500
63                0.000  1.000
64                0.429  0.571
65                1.000  0.000
66                0.714  0.286
67                0.750  0.250
68                1.000  0.000
70                1.000  0.000
71                0.750  0.250
72                1.000  0.000
73                0.500  0.500
74                1.000  0.000
75                1.000  0.000
76                1.000  0.000
77                1.000  0.000
78                1.000  0.000
79                0.667  0.333
80                0.750  0.250
81                1.000  0.000
82                1.000  0.000
83                0.500  0.500
84                1.000  0.000
85                1.000  0.000
86                1.000  0.000
87                0.667  0.333
91                1.000  0.000
92                1.000  0.000
93                1.000  0.000
95                1.000  0.000
96                1.000  0.000
97                1.000  0.000
98                1.000  0.000
99                1.000  0.000
103               1.000  0.000
105               1.000  0.000
106               1.000  0.000
108               1.000  0.000
109               1.000  0.000
110               1.000  0.000
111               1.000  0.000
112               0.667  0.333
113               1.000  0.000
114               1.000  0.000
115               1.000  0.000
116               1.000  0.000
117               0.000  1.000
118               1.000  0.000
119               1.000  0.000
121               1.000  0.000
125               1.000  0.000
126               1.000  0.000
130               1.000  0.000
131               0.000  1.000
132               1.000  0.000
133               1.000  0.000
134               1.000  0.000
136               1.000  0.000
140               1.000  0.000
143               1.000  0.000
144               1.000  0.000
146               1.000  0.000
147               1.000  0.000
149               1.000  0.000
151               1.000  0.000
155               1.000  0.000
162               1.000  0.000
173               0.000  1.000
178               1.000  0.000
180               1.000  0.000
186               1.000  0.000
196               1.000  0.000
202               1.000  0.000
206               1.000  0.000

DomainInSubdomains → SubdomainLevelRT
SubdomainLevelRT        0      1
DomainInSubdomains
0                   0.787  0.213
1                   0.944  0.056

DomainInPaths → SubdomainLevelRT
SubdomainLevelRT      0      1
DomainInPaths
0                 0.786  0.214
1                 0.904  0.096

CLASS_LABEL → SubdomainLevelRT
SubdomainLevelRT      0      1
CLASS_LABEL
0                 0.956  0.044
1                 0.772  0.228

=====================================================================================
SUBDOMAIN LEVEL = 3
=====================================================================================

RT distribution:
SubdomainLevelRT
-1    19
 0     3
Name: count, dtype: int64

Cross-tab with selected features:

NumDots → SubdomainLevelRT
SubdomainLevelRT     -1      0
NumDots
4                 1.000  0.000
5                 0.769  0.231
6                 1.000  0.000
7                 1.000  0.000

HostnameLength → SubdomainLevelRT
SubdomainLevelRT     -1      0
HostnameLength
22                1.000  0.000
23                1.000  0.000
29                1.000  0.000
30                1.000  0.000
31                1.000  0.000
32                1.000  0.000
33                1.000  0.000
36                1.000  0.000
37                0.667  0.333
39                1.000  0.000
40                1.000  0.000
44                1.000  0.000
45                0.000  1.000
66                1.000  0.000

UrlLength → SubdomainLevelRT
SubdomainLevelRT     -1      0
UrlLength
41                1.000  0.000
48                1.000  0.000
56                1.000  0.000
59                1.000  0.000
61                0.000  1.000
65                1.000  0.000
67                1.000  0.000
72                1.000  0.000
76                0.333  0.667
84                1.000  0.000
91                1.000  0.000
100               1.000  0.000
107               1.000  0.000
129               1.000  0.000
144               1.000  0.000
199               1.000  0.000

DomainInSubdomains → SubdomainLevelRT
SubdomainLevelRT       -1      0
DomainInSubdomains
0                   0.818  0.182
1                   0.909  0.091

DomainInPaths → SubdomainLevelRT
SubdomainLevelRT     -1      0
DomainInPaths
0                 0.833  0.167
1                 1.000  0.000

CLASS_LABEL → SubdomainLevelRT
SubdomainLevelRT     -1      0
CLASS_LABEL
0                 1.000  0.000
1                 0.824  0.176

=====================================================================================
REPRESENTATIVE AMBIGUOUS ROWS
=====================================================================================
 SubdomainLevel  SubdomainLevelRT  NumDots  HostnameLength  UrlLength  PathLevel  NumDashInHostname  DomainInSubdomains  DomainInPaths  IpAddress  RandomString  NoHttps  NumSensitiveWords  CLASS_LABEL
              2                 0        4              17         58          1                  0                   0              0          0             1        1                  0            1
              2                 0        4              28         50          1                  0                   0              0          0             0        1                  0            1
              2                 0        4              32         53          2                  0                   0              0          0             0        1                  0            1
              2                 0        4              33         57          2                  1                   0              0          0             1        1                  0            1
              2                 0        4              35         71          4                  4                   0              0          0             0        1                  1            1
              2                 0        5              19         35          1                  0                   0              0          0             0        1                  0            1
              2                 0        5              36         71          3                  4                   0              1          0             0        1                  0            1
              2                 0        4              25         66          2                  0                   0              0          0             1        1                  0            1
              2                 0        4              25         66          2                  0                   0              0          0             1        1                  0            1
              2                 0        4              25         66          2                  0                   0              0          0             1        1                  0            1
              2                 0        4              25         66          2                  0                   0              0          0             1        1                  0            1
              2                 0        4              50         92          5                  3                   1              0          0             1        1                  1            1
              2                 0        6              19         73          5                  0                   0              0          0             0        1                  1            1
              2                 0        3              15         32          2                  0                   0              0          0             1        1                  0            1
              2                 0        4              36         75          4                  5                   0              1          0             1        1                  0            1
              2                 0        4              17         84          4                  0                   0              0          0             0        1                  2            1
              2                 0        4              36        103          4                  4                   0              1          0             1        1                  1            1
              2                 0        4              15         36          2                  0                   0              1          0             1        1                  0            1
              2                 0        4              36         86          4                  4                   0              1          0             1        1                  0            1
              2                 0        4              18         42          2                  0                   0              0          0             0        1                  1            1
              2                 0        4              15         49          4                  0                   1              1          0             0        1                  2            1
              2                 0        3              25        110          5                  0                   0              0          0             1        1                  0            1
              2                 0        3              25        110          5                  0                   0              0          0             1        1                  0            1
              2                 0        3              25        110          5                  0                   0              0          0             1        1                  0            1
              2                 0        3              32         52          3                  3                   0              0          0             1        1                  0            1
              2                 0        4              49         67          1                  4                   0              0          0             0        0                  0            1
              2                 0        5              17         50          3                  0                   0              0          0             0        1                  0            1
              2                 0        5              17         51          3                  0                   0              0          0             0        1                  0            1
              2                 0        5              15         50          3                  0                   0              1          0             1        1                  1            1
              2                 0        5              15         55          3                  0                   0              1          0             1        1                  1            1
              2                 0        4              20         45          2                  0                   1              0          0             0        1                  0            1
              2                 0        4              17         62          5                  0                   0              0          0             0        1                  0            1
              2                 0        5              15         58          3                  0                   0              1          0             1        1                  1            1
              2                 0        4              15         45          3                  0                   0              1          0             1        1                  0            1
              2                 0        5              29         65          1                  1                   0              0          0             0        1                  1            1
              2                 0        5              29         93          1                  1                   0              0          0             0        1                  1            1
              2                 0        3              58         66          0                  7                   1              0          0             1        1                  1            1
              2                 0        4              35         64          3                  4                   0              1          0             0        1                  1            1
              2                 0        3              24         43          3                  0                   0              0          0             1        1                  0            1
              2                 0        3              57        109          4                  4                   1              1          0             1        1                  0            1
              2                 0        3              57        110          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              57        109          4                  4                   1              1          0             1        1                  0            1
              2                 0        3              57        109          4                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1
              2                 0        3              66        121          5                  4                   1              1          0             1        1                  0            1

In [ ]:
# ============================================================
# PHISHSHIELD AI — STEP 5E
# INTERPRETABLE RULE DISCOVERY FOR SubdomainLevelRT
# READ-ONLY — NO MODEL TRAINING
# ============================================================

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import accuracy_score
from pathlib import Path

# ------------------------------------------------------------
# 1. Load dataset
# ------------------------------------------------------------

candidates = [
    Path("/content/Phishing_Legitimate_full.csv"),
    Path("/content/Phishing_Legitimate_full(4).csv"),
    Path("/content/drive/MyDrive/PhishShield_AI/data/Phishing_Legitimate_full.csv"),
    Path("/content/drive/MyDrive/PhishShield_AI/data/Phishing_Legitimate_full(4).csv"),
]

dataset_path = next((p for p in candidates if p.exists()), None)

if dataset_path is None:
    print("❌ Dataset not found.")
else:

    df = pd.read_csv(dataset_path)

    print("✅ Dataset loaded")
    print("Shape:", df.shape)

    # --------------------------------------------------------
    # 2. IMPORTANT:
    # Never use CLASS_LABEL.
    # Never use SubdomainLevelRT itself.
    # Never use id.
    # --------------------------------------------------------

    candidate_features = [
        "SubdomainLevel",
        "NumDots",
        "HostnameLength",
        "UrlLength",
        "PathLevel",
        "NumDashInHostname",
        "DomainInSubdomains",
        "DomainInPaths",
        "IpAddress",
        "RandomString",
        "NoHttps",
        "NumSensitiveWords",
        "NumDash",
        "NumUnderscore",
        "NumPercent",
        "NumNumericChars"
    ]

    X = df[candidate_features]
    y = df["SubdomainLevelRT"]

    # --------------------------------------------------------
    # 3. Train tiny interpretable trees.
    # This is NOT the phishing model.
    # It is only a rule-discovery experiment.
    # --------------------------------------------------------

    print("\n" + "=" * 90)
    print("RULE DISCOVERY RESULTS")
    print("=" * 90)

    for depth in [1, 2, 3, 4, 5, 6]:

        tree = DecisionTreeClassifier(
            max_depth=depth,
            random_state=42,
            min_samples_leaf=5
        )

        tree.fit(X, y)

        pred = tree.predict(X)

        acc = accuracy_score(y, pred)

        print(
            f"\nDepth {depth}: "
            f"{acc * 100:.4f}% reproduction accuracy"
        )

    # --------------------------------------------------------
    # 4. Inspect the best interpretable tree
    # --------------------------------------------------------

    tree = DecisionTreeClassifier(
        max_depth=6,
        random_state=42,
        min_samples_leaf=5
    )

    tree.fit(X, y)

    pred = tree.predict(X)

    acc = accuracy_score(y, pred)

    print("\n" + "=" * 90)
    print("DEPTH-6 TREE")
    print("=" * 90)

    print(f"Reproduction accuracy: {acc * 100:.4f}%")

    print("\nDiscovered rule structure:\n")

    print(
        export_text(
            tree,
            feature_names=candidate_features,
            decimals=3
        )
    )

    # --------------------------------------------------------
    # 5. Exact mismatch count
    # --------------------------------------------------------

    mismatches = np.sum(pred != y)

    print("\n" + "=" * 90)
    print("MISMATCH ANALYSIS")
    print("=" * 90)

    print("Total rows:", len(y))
    print("Correct:", len(y) - mismatches)
    print("Mismatches:", mismatches)

    # --------------------------------------------------------
    # 6. Check only ambiguous SubdomainLevel values
    # --------------------------------------------------------

    ambiguous_mask = df["SubdomainLevel"].isin([2, 3])

    ambiguous_accuracy = accuracy_score(
        y[ambiguous_mask],
        pred[ambiguous_mask]
    )

    print(
        "\nAccuracy specifically for "
        "SubdomainLevel 2/3:",
        f"{ambiguous_accuracy * 100:.4f}%"
    )

    # --------------------------------------------------------
    # 7. Safety checks
    # --------------------------------------------------------

    print("\n" + "=" * 90)
    print("SAFETY CHECK")
    print("=" * 90)

    print("CLASS_LABEL used:", "CLASS_LABEL" in candidate_features)
    print("Target used as feature:", "SubdomainLevelRT" in candidate_features)
    print("ID used:", "id" in candidate_features)

    print("\nNo backend modified.")
    print("No production model modified.")
    print("No files written.")
    print("No phishing model retrained.")

    print("\nSTEP 5E COMPLETE")

✅ Dataset loaded
Shape: (10000, 50)

==========================================================================================
RULE DISCOVERY RESULTS
==========================================================================================

Depth 1: 98.5900% reproduction accuracy

Depth 2: 99.5600% reproduction accuracy

Depth 3: 99.5600% reproduction accuracy

Depth 4: 99.5600% reproduction accuracy

Depth 5: 99.7000% reproduction accuracy

Depth 6: 99.7200% reproduction accuracy

==========================================================================================
DEPTH-6 TREE
==========================================================================================
Reproduction accuracy: 99.7200%

Discovered rule structure:

|--- SubdomainLevel <= 1.500
|   |--- class: 1
|--- SubdomainLevel >  1.500
|   |--- SubdomainLevel <= 2.500
|   |   |--- NumNumericChars <= 4.500
|   |   |   |--- NumDots <= 3.500
|   |   |   |   |--- PathLevel <= 3.500
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- PathLevel >  3.500
|   |   |   |   |   |--- UrlLength <= 90.000
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- UrlLength >  90.000
|   |   |   |   |   |   |--- class: 0
|   |   |   |--- NumDots >  3.500
|   |   |   |   |--- UrlLength <= 67.500
|   |   |   |   |   |--- HostnameLength <= 21.500
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- HostnameLength >  21.500
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- UrlLength >  67.500
|   |   |   |   |   |--- NumNumericChars <= 0.500
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- NumNumericChars >  0.500
|   |   |   |   |   |   |--- class: 0
|   |   |--- NumNumericChars >  4.500
|   |   |   |--- DomainInPaths <= 0.500
|   |   |   |   |--- HostnameLength <= 38.500
|   |   |   |   |   |--- NumNumericChars <= 39.000
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- NumNumericChars >  39.000
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- HostnameLength >  38.500
|   |   |   |   |   |--- class: 1
|   |   |   |--- DomainInPaths >  0.500
|   |   |   |   |--- class: 0
|   |--- SubdomainLevel >  2.500
|   |   |--- SubdomainLevel <= 3.500
|   |   |   |--- NumNumericChars <= 1.000
|   |   |   |   |--- class: -1
|   |   |   |--- NumNumericChars >  1.000
|   |   |   |   |--- class: -1
|   |   |--- SubdomainLevel >  3.500
|   |   |   |--- class: -1


==========================================================================================
MISMATCH ANALYSIS
==========================================================================================
Total rows: 10000
Correct: 9972
Mismatches: 28

Accuracy specifically for SubdomainLevel 2/3: 90.4762%

==========================================================================================
SAFETY CHECK
==========================================================================================
CLASS_LABEL used: False
Target used as feature: False
ID used: False

No backend modified.
No production model modified.
No files written.
No phishing model retrained.

STEP 5E COMPLETE

In [ ]:
# ============================================================
# PHISHSHIELD AI — STEP 5F
# INSPECT THE 28 SUBDOMAINLEVELRT MISMATCHES
# READ-ONLY
# ============================================================

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from pathlib import Path

# ------------------------------------------------------------
# 1. Load dataset
# ------------------------------------------------------------

candidates = [
    Path("/content/Phishing_Legitimate_full.csv"),
    Path("/content/Phishing_Legitimate_full(4).csv"),
    Path("/content/drive/MyDrive/PhishShield_AI/data/Phishing_Legitimate_full.csv"),
    Path("/content/drive/MyDrive/PhishShield_AI/data/Phishing_Legitimate_full(4).csv"),
]

dataset_path = next((p for p in candidates if p.exists()), None)

if dataset_path is None:
    print("❌ Dataset not found.")

else:

    df = pd.read_csv(dataset_path)

    # --------------------------------------------------------
    # Same candidate features used in Step 5E
    # --------------------------------------------------------

    candidate_features = [
        "SubdomainLevel",
        "NumDots",
        "HostnameLength",
        "UrlLength",
        "PathLevel",
        "NumDashInHostname",
        "DomainInSubdomains",
        "DomainInPaths",
        "IpAddress",
        "RandomString",
        "NoHttps",
        "NumSensitiveWords",
        "NumDash",
        "NumUnderscore",
        "NumPercent",
        "NumNumericChars"
    ]

    X = df[candidate_features]
    y = df["SubdomainLevelRT"]

    # --------------------------------------------------------
    # Recreate EXACT same tree
    # --------------------------------------------------------

    tree = DecisionTreeClassifier(
        max_depth=6,
        random_state=42,
        min_samples_leaf=5
    )

    tree.fit(X, y)

    predicted = tree.predict(X)

    # --------------------------------------------------------
    # Identify mismatches
    # --------------------------------------------------------

    mismatch_mask = predicted != y

    mismatches = df.loc[mismatch_mask].copy()

    mismatches["PredictedRT"] = predicted[mismatch_mask]

    # --------------------------------------------------------
    # Display all 28 mismatches
    # --------------------------------------------------------

    print("=" * 110)
    print("ALL SUBDOMAINLEVELRT MISMATCHES")
    print("=" * 110)

    print("Mismatch count:", len(mismatches))

    # --------------------------------------------------------
    # Show EVERY feature except id and target
    # --------------------------------------------------------

    display_columns = [
        col for col in df.columns
        if col not in ["id", "CLASS_LABEL"]
    ]

    display_columns = (
        ["SubdomainLevel", "SubdomainLevelRT", "PredictedRT"]
        +
        [
            col for col in display_columns
            if col not in [
                "SubdomainLevel",
                "SubdomainLevelRT"
            ]
        ]
    )

    print(
        mismatches[
            display_columns
        ].to_string(index=False)
    )

    # --------------------------------------------------------
    # Separate mismatch groups
    # --------------------------------------------------------

    print("\n" + "=" * 110)
    print("MISMATCH SUMMARY BY SUBDOMAIN LEVEL")
    print("=" * 110)

    print(
        mismatches[
            [
                "SubdomainLevel",
                "SubdomainLevelRT",
                "PredictedRT"
            ]
        ]
        .value_counts()
        .sort_index()
        .to_string()
    )

    # --------------------------------------------------------
    # Compare actual vs predicted RT
    # --------------------------------------------------------

    print("\n" + "=" * 110)
    print("ACTUAL → PREDICTED TRANSITIONS")
    print("=" * 110)

    print(
        pd.crosstab(
            mismatches["SubdomainLevelRT"],
            mismatches["PredictedRT"]
        ).to_string()
    )

    # --------------------------------------------------------
    # Check which existing features differ between
    # correctly classified and incorrectly classified
    # ambiguous rows
    # --------------------------------------------------------

    print("\n" + "=" * 110)
    print("MISMATCH FEATURE STATISTICS")
    print("=" * 110)

    ambiguous = df[
        df["SubdomainLevel"].isin([2, 3])
    ].copy()

    ambiguous["PredictedRT"] = predicted[
        ambiguous.index
    ]

    ambiguous["Mismatch"] = (
        ambiguous["SubdomainLevelRT"]
        != ambiguous["PredictedRT"]
    )

    for feature in candidate_features:

        mismatch_values = ambiguous.loc[
            ambiguous["Mismatch"],
            feature
        ]

        correct_values = ambiguous.loc[
            ~ambiguous["Mismatch"],
            feature
        ]

        if len(mismatch_values) > 0:

            print(
                f"{feature:30s} | "
                f"mismatch mean={mismatch_values.mean():8.3f} | "
                f"correct mean={correct_values.mean():8.3f}"
            )

    print("\n" + "=" * 110)
    print("STEP 5F COMPLETE")
    print("=" * 110)

    print("""
Read-only analysis completed.

No files written.
No backend changes.
No model changes.
No phishing model retraining.

The 28 mismatching rows are now the primary evidence
for determining what information is missing from our
current reconstruction.
""")

==============================================================================================================
ALL SUBDOMAINLEVELRT MISMATCHES
==============================================================================================================
Mismatch count: 28
 SubdomainLevel  SubdomainLevelRT  PredictedRT  NumDots  PathLevel  UrlLength  NumDash  NumDashInHostname  AtSymbol  TildeSymbol  NumUnderscore  NumPercent  NumQueryComponents  NumAmpersand  NumHash  NumNumericChars  NoHttps  RandomString  IpAddress  DomainInSubdomains  DomainInPaths  HttpsInHostname  HostnameLength  PathLength  QueryLength  DoubleSlashInPath  NumSensitiveWords  EmbeddedBrandName  PctExtHyperlinks  PctExtResourceUrls  ExtFavicon  InsecureForms  RelativeFormAction  ExtFormAction  AbnormalFormAction  PctNullSelfRedirectHyperlinks  FrequentDomainNameMismatch  FakeLinkInStatusBar  RightClickDisabled  PopUpWindow  SubmitInfoToEmail  IframeOrFrame  MissingTitle  ImagesOnlyInForm  UrlLengthRT  PctExtResourceUrlsRT  AbnormalExtFormActionR  ExtMetaScriptLinkRT  PctExtNullSelfRedirectHyperlinksRT
              2                 1            0        4          5         62        1                  0         0            0              0           0                   0             0        0                0        1             0          0                   0              0                0              16          39            0                  0                  0                  0          0.000000            0.642857           1              1                   0              0                   0                       1.000000                           0                    0                   0            0                  0              0             0                 0            0                    -1                       1                    0                                  -1
              2                 0            1        4          1         50        0                  0         0            0              0           0                   0             0        0                0        1             0          0                   0              0                0              28          15            0                  0                  0                  0          1.000000            1.000000           0              1                   0              0                   0                       0.000000                           1                    0                   0            0                  0              1             0                 0            1                    -1                       1                    1                                  -1
              2                 0            1        4          2         53        0                  0         0            0              0           0                   0             0        0                0        1             0          0                   0              0                0              32          14            0                  0                  0                  0          0.923077            1.000000           0              1                   0              0                   0                       0.000000                           1                    0                   0            0                  0              0             0                 0            1                     1                       1                   -1                                  -1
              2                 0            1        4          2         57        1                  1         0            0              0           0                   0             0        0                1        1             1          0                   0              0                0              33          17            0                  0                  0                  0          0.972222            0.035294           1              1                   0              0                   0                       0.027778                           0                    0                   0            0                  0              1             0                 0            0                     1                       1                    1                                  -1
              2                 1            0        5          4         63        0                  0         0            0              0           0                   0             0        0                0        1             0          0                   0              1                0              18          38            0                  0                  0                  0          0.833333            0.235294           1              1                   0              0                   0                       0.000000                           0                    0                   0            0                  0              1             0                 0            0                     1                       1                    0                                  -1
              3                 0           -1        5          2         76        0                  0         0            0              0           0                   0             0        0                0        1             1          0                   0              0                0              45          24            0                  0                  1                  0          0.000000            0.000000           0              1                   0              0                   0                       0.000000                           0                    0                   0            0                  0              0             0                 0           -1                     1                       1                    1                                   1
              3                 0           -1        5          2         76        0                  0         0            0              0           0                   0             0        0                0        1             1          0                   0              0                0              45          24            0                  0                  1                  0          0.000000            0.000000           0              1                   0              0                   0                       0.000000                           0                    0                   0            0                  0              0             0                 0           -1                     1                       1                    1                                   1
              2                 0            1        4          5         92        3                  3         0            0              0           0                   0             0        0                5        1             1          0                   1              0                0              50          35            0                  0                  1                  0          0.500000            1.000000           0              1                   0              0                   0                       0.000000                           1                    0                   0            0                  0              0             0                 0           -1                    -1                       1                   -1                                   0
              2                 1            0        5          3        173        2                  0         0            0              2           0                   2             1        0               41        1             0          0                   0              0                0              22          23          120                  0                  2                  0          0.000000            0.000000           0              1                   1              0                   0                       0.000000                           0                    0                   0            0                  0              0             0                 0           -1                     1                       1                    1                                   1
              2                 1            0        4          3         63        0                  0         0            0              0           0                   0             0        0                0        1             1          0                   0              0                0              20          26            9                  0                  0                  0          0.000000            0.000000           0              0                   0              0                   0                       0.000000                           1                    0                   0            0                  0              0             1                 0            0                     1                       1                    1                                   1
              2                 0            1        4          4         84        1                  0         0            0              0           0                   4             0        0                0        1             0          0                   0              0                0              17          28           31                  0                  2                  0          1.000000            1.000000           1              1                   0              0                   0                       0.000000                           1                    0                   0            0                  0              0             0                 0           -1                    -1                       1                   -1                                  -1
              2                 1            0        4          4         55        0                  0         0            0              0           0                   0             0        0                1        1             0          0                   0              1                0              21          27            0                  0                  0                  0          0.000000            0.153846           0              1                   0              0                   0                       0.000000                           0                    0                   0            0                  0              0             0                 0            0                     1                       1                    1                                   1
              2                 1            0        5          2         46        0                  0         0            0              0           0                   0             0        0                0        1             0          0                   0              1                0              17          22            0                  0                  1                  1          0.923077            1.000000           0              1                   0              0                   0                       0.000000                           1                    0                   0            0                  0              0             0                 0            1                     1                       1                   -1                                  -1
              2                 1            0        4          4         54        0                  0         0            0              0           0                   0             0        0                0        1             0          0                   0              1                0              18          29            0                  0                  0                  0          0.833333            0.235294           1              1                   0              0                   0                       0.083333                           0                    0                   0            0                  0              1             0                 0            0                     1                       1                    0                                  -1
              2                 0            1        4          1         67        4                  4         0            0              0           0                   0             0        0               11        0             0          0                   0              0                0              49          10            0                  0                  0                  0          0.000000            0.000000           0              0                   0              0                   0                       0.000000                           0                    0                   0            0                  0              1             0                 0            0                     1                       1                    1                                   1
              2                 1            0        4          3         50        1                  0         0            0              0           0                   0             0        0                0        1             0          0                   0              0                0              17          26            0                  0                  0                  0          1.000000            1.000000           0              1                   0              1                   0                       0.000000                           1                    0                   0            0                  0              1             0                 0            1                    -1                       0                   -1                                  -1
              2                 1            0        4          3         50        1                  0         0            0              0           0                   0             0        0                0        1             0          0                   0              1                0              17          26            0                  0                  0                  0          1.000000            1.000000           0              1                   0              1                   0                       0.000000                           1                    0                   0            0                  0              1             0                 0            1                    -1                       0                   -1                                  -1
              3                 0           -1        5          3         61        3                  3         0            0              0           0                   0             0        0                0        1             0          0                   1              0                0              37          17            0                  0                  0                  0          0.000000            0.000000           0              1                   0              0                   0                       0.000000                           0                    0                   0            0                  0              0             0                 0            0                     1                       1                    1                                   1
              2                 1            0        3          4         64        1                  1         0            0              0           0                   0             0        0                0        1             1          0                   0              1                0              33          24            0                  0                  0                  0          0.000000            0.000000           0              1                   0              0                   0                       1.000000                           0                    0                   0            0                  0              0             0                 1            0                     1                       1                    1                                  -1
              2                 0            1        4          4         73        0                  0         0            0              0           0                   0             0        0                0        1             0          0                   1              0                0              33          33            0                  0                  0                  0          0.923077            1.000000           0              1                   0              0                   0                       0.000000                           1                    0                   0            0                  0              0             0                 0            0                     1                       1                   -1                                  -1
              2                 0            1        8          3        126        0                  0         0            0              0           0                   2             1        0                0        1             1          0                   1              0                0              28          24           66                  0                  2                  0          1.000000            0.500000           1              1                   0              0                   0                       0.000000                           1                    0                   0            0                  0              0             0                 0           -1                     1                       1                    0                                  -1
              2                 0            1        4          6         77        0                  0         0            0              0           0                   0             0        0                0        1             0          0                   0              1                0              28          42            0                  0                  0                  0          0.066667            0.076923           0              1                   1              0                   0                       0.866667                           0                    0                   0            0                  0              0             0                 0           -1                     1                       1                    1                                  -1
              2                 0            1        5          4        146        0                  0         0            0              7           0                   1             0        0                0        1             1          0                   1              1                0              16          33           89                  0                  0                  0          0.676471            0.000000           0              1                   0              0                   0                       0.000000                           0                    0                   0            0                  0              0             0                 0           -1                     1                       1                    1                                  -1

In [ ]:
# ============================================================
# PHISHSHIELD AI — STEP 5H FIX
# FIND EXISTING CHECKPOINT FILES
# NO TRAINING / NO MODIFICATION
# ============================================================

import os

ROOT = "/content/drive/MyDrive"

print("=" * 70)
print("SEARCHING GOOGLE DRIVE FOR PHISHSHIELD CHECKPOINTS")
print("=" * 70)

targets = {
    "feature_names": [],
    "xgboost": [],
    "random_forest": [],
    "resmlp": []
}

for root, dirs, files in os.walk(ROOT):
    # Skip common unnecessary folders
    dirs[:] = [d for d in dirs if d not in {
        ".cache", ".config", "node_modules", ".git"
    }]

    for file in files:
        path = os.path.join(root, file)
        name = file.lower()

        if "feature" in name and "name" in name:
            targets["feature_names"].append(path)

        if "xgboost" in name:
            targets["xgboost"].append(path)

        if "random_forest" in name or "randomforest" in name:
            targets["random_forest"].append(path)

        if "resmlp" in name:
            targets["resmlp"].append(path)

print("\n--- FEATURE NAMES FILES ---")
for p in targets["feature_names"]:
    print(p)

print("\n--- XGBOOST FILES ---")
for p in targets["xgboost"]:
    print(p)

print("\n--- RANDOM FOREST FILES ---")
for p in targets["random_forest"]:
    print(p)

print("\n--- RESMLP FILES ---")
for p in targets["resmlp"]:
    print(p)

print("\n" + "=" * 70)
print("SEARCH COMPLETE")
print("=" * 70)

if not any(targets.values()):
    print("WARNING: No expected checkpoint files were found.")
else:
    print("Checkpoint files found. Do NOT retrain.")

======================================================================
SEARCHING GOOGLE DRIVE FOR PHISHSHIELD CHECKPOINTS
======================================================================

--- FEATURE NAMES FILES ---
/content/drive/MyDrive/PhishShield_old/checkpoints/feature_names.json
/content/drive/MyDrive/PhishShield_old/production/feature_names.json
/content/drive/MyDrive/PhishShield_AI/data/feature_names.pkl

--- XGBOOST FILES ---
/content/drive/MyDrive/Colab Notebooks/BA_Week5_Parkinson’s_disease_XGboost.ipynb
/content/drive/MyDrive/Colab Notebooks/Copy of BA_Week5_Parkinson’s_disease_XGboost.ipynb
/content/drive/MyDrive/Week5_XG_Boost/BA_Week5_Parkinson’s_disease_XGboost.ipynb
/content/drive/MyDrive/PhishShield_old/checkpoints/xgboost_confusion_matrix.csv
/content/drive/MyDrive/PhishShield_old/checkpoints/xgboost_detailed_confusion_matrix.csv
/content/drive/MyDrive/PhishShield_old/checkpoints/xgboost_detailed_classification_report.csv
/content/drive/MyDrive/PhishShield_old/checkpoints/xgboost_detailed_validation.json
/content/drive/MyDrive/PhishShield_old/checkpoints/xgboost_feature_importance.csv
/content/drive/MyDrive/PhishShield_old/checkpoints/xgboost_feature_importance.json
/content/drive/MyDrive/PhishShield_old/models/xgboost_pipeline.joblib
/content/drive/MyDrive/PhishShield_old/results/xgboost_results.csv
/content/drive/MyDrive/PhishShield_old/results/xgboost_detailed_validation.csv
/content/drive/MyDrive/PhishShield_old/figures/xgboost_feature_importance.png
/content/drive/MyDrive/PhishShield_old/production/xgboost_pipeline.joblib
/content/drive/MyDrive/PhishShield_AI/checkpoints/05_xgboost_checkpoint.json
/content/drive/MyDrive/PhishShield_AI/models/xgboost.pkl

--- RANDOM FOREST FILES ---
/content/drive/MyDrive/PhishShield_old/checkpoints/random_forest_confusion_matrix.csv
/content/drive/MyDrive/PhishShield_old/models/random_forest_pipeline.joblib
/content/drive/MyDrive/PhishShield_old/results/random_forest_results.csv
/content/drive/MyDrive/PhishShield_AI/checkpoints/04_random_forest_checkpoint.json
/content/drive/MyDrive/PhishShield_AI/models/random_forest.pkl

--- RESMLP FILES ---
/content/drive/MyDrive/PhishShield_old/checkpoints/resmlp_confusion_matrix.csv
/content/drive/MyDrive/PhishShield_old/checkpoints/resmlp_classification_report.csv
/content/drive/MyDrive/PhishShield_old/checkpoints/resmlp_summary.json
/content/drive/MyDrive/PhishShield_old/models/resmlp_pipeline.joblib
/content/drive/MyDrive/PhishShield_old/results/resmlp_results.csv
/content/drive/MyDrive/PhishShield_AI/models/resmlp_best.keras
/content/drive/MyDrive/PhishShield_AI/models/resmlp_history.pkl

======================================================================
SEARCH COMPLETE
======================================================================
Checkpoint files found. Do NOT retrain.

In [ ]:
# ============================================================
# PHISHSHIELD AI — STEP 5H
# VERIFY FROZEN XGBOOST MODEL + EXACT FEATURE CONTRACT
# NO TRAINING
# ============================================================

import os
import joblib
import json
import numpy as np

BASE = "/content/drive/MyDrive/PhishShield_AI"
MODEL_DIR = os.path.join(BASE, "models")
DATA_DIR = os.path.join(BASE, "data")
CHECKPOINT_DIR = os.path.join(BASE, "checkpoints")

os.makedirs(CHECKPOINT_DIR, exist_ok=True)

FEATURE_PATH = os.path.join(DATA_DIR, "feature_names.pkl")
XGB_PATH = os.path.join(MODEL_DIR, "xgboost.pkl")

# ------------------------------------------------------------
# 1. Verify files
# ------------------------------------------------------------
assert os.path.exists(FEATURE_PATH), f"Missing: {FEATURE_PATH}"
assert os.path.exists(XGB_PATH), f"Missing: {XGB_PATH}"

print("Feature file :", FEATURE_PATH)
print("XGBoost file :", XGB_PATH)

# ------------------------------------------------------------
# 2. Load frozen artifacts
# ------------------------------------------------------------
feature_names = joblib.load(FEATURE_PATH)
xgb_model = joblib.load(XGB_PATH)

if isinstance(feature_names, np.ndarray):
    feature_names = feature_names.tolist()

feature_names = list(feature_names)

print("\nLoaded feature count:", len(feature_names))
print("Model type:", type(xgb_model).__name__)

# ------------------------------------------------------------
# 3. Expected 47-feature contract
# ------------------------------------------------------------
EXPECTED_FEATURES = [
    "NumDots",
    "SubdomainLevel",
    "PathLevel",
    "UrlLength",
    "NumDash",
    "NumDashInHostname",
    "AtSymbol",
    "TildeSymbol",
    "NumUnderscore",
    "NumPercent",
    "NumQueryComponents",
    "NumAmpersand",
    "NumHash",
    "NumNumericChars",
    "NoHttps",
    "RandomString",
    "IpAddress",
    "DomainInSubdomains",
    "DomainInPaths",
    "HostnameLength",
    "PathLength",
    "QueryLength",
    "DoubleSlashInPath",
    "NumSensitiveWords",
    "EmbeddedBrandName",
    "PctExtHyperlinks",
    "PctExtResourceUrls",
    "ExtFavicon",
    "InsecureForms",
    "RelativeFormAction",
    "ExtFormAction",
    "AbnormalFormAction",
    "PctNullSelfRedirectHyperlinks",
    "FrequentDomainNameMismatch",
    "FakeLinkInStatusBar",
    "RightClickDisabled",
    "PopUpWindow",
    "SubmitInfoToEmail",
    "IframeOrFrame",
    "MissingTitle",
    "ImagesOnlyInForm",
    "SubdomainLevelRT",
    "UrlLengthRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

# ------------------------------------------------------------
# 4. Exact contract validation
# ------------------------------------------------------------
assert len(EXPECTED_FEATURES) == 47

if feature_names == EXPECTED_FEATURES:
    print("\n[PASS] Feature names and order EXACTLY match 47-feature contract.")
else:
    print("\n[FAIL] Feature contract mismatch!")

    print("\nExpected:")
    for i, f in enumerate(EXPECTED_FEATURES):
        print(i, f)

    print("\nLoaded:")
    for i, f in enumerate(feature_names):
        print(i, f)

    raise ValueError("Feature contract mismatch. STOP.")

# ------------------------------------------------------------
# 5. Verify model input size
# ------------------------------------------------------------
if hasattr(xgb_model, "n_features_in_"):
    print("\nModel n_features_in_:", xgb_model.n_features_in_)
    assert xgb_model.n_features_in_ == 47, \
        f"Expected 47 model features, got {xgb_model.n_features_in_}"
else:
    print("\nWARNING: Model has no n_features_in_ attribute.")

# ------------------------------------------------------------
# 6. Verify feature_names_in_ if available
# ------------------------------------------------------------
if hasattr(xgb_model, "feature_names_in_"):
    model_feature_names = list(xgb_model.feature_names_in_)

    if model_feature_names == EXPECTED_FEATURES:
        print("[PASS] Model feature_names_in_ matches exactly.")
    else:
        print("[WARNING] Model feature_names_in_ differs.")
        print("Model feature count:", len(model_feature_names))

# ------------------------------------------------------------
# 7. RT feature identification
# ------------------------------------------------------------
RT_FEATURES = [
    "SubdomainLevelRT",
    "UrlLengthRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

print("\nRuntime/RT features:")
for f in RT_FEATURES:
    print(" -", f)

# ------------------------------------------------------------
# 8. Save frozen contract checkpoint
# ------------------------------------------------------------
contract = {
    "project": "PhishShield AI",
    "stage": "5H",
    "model": "XGBoost",
    "model_path": XGB_PATH,
    "feature_names_path": FEATURE_PATH,
    "feature_count": len(feature_names),
    "feature_names": feature_names,
    "rt_features": RT_FEATURES,
    "training_performed": False,
    "model_frozen": True
}

CONTRACT_PATH = os.path.join(
    CHECKPOINT_DIR,
    "step_5H_frozen_xgboost_contract.json"
)

with open(CONTRACT_PATH, "w") as f:
    json.dump(contract, f, indent=2)

print("\n" + "=" * 70)
print("STEP 5H COMPLETE")
print("=" * 70)
print("Frozen model verified.")
print("47-feature contract verified.")
print("No training performed.")
print("Checkpoint saved:")
print(CONTRACT_PATH)

Feature file : /content/drive/MyDrive/PhishShield_AI/data/feature_names.pkl
XGBoost file : /content/drive/MyDrive/PhishShield_AI/models/xgboost.pkl

Loaded feature count: 47
Model type: XGBClassifier

[PASS] Feature names and order EXACTLY match 47-feature contract.

Model n_features_in_: 47
[PASS] Model feature_names_in_ matches exactly.

Runtime/RT features:
 - SubdomainLevelRT
 - UrlLengthRT
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

======================================================================
STEP 5H COMPLETE
======================================================================
Frozen model verified.
47-feature contract verified.
No training performed.
Checkpoint saved:
/content/drive/MyDrive/PhishShield_AI/checkpoints/step_5H_frozen_xgboost_contract.json

In [ ]:
# ============================================================
# PHISHSHIELD AI — STEP 5I
# PRODUCTION-SAFE URL FEATURE EXTRACTOR
#
# IMPORTANT:
# - NO TRAINING
# - NO MODEL MODIFICATION
# - NO SILENT missing-feature -> 0 fallback
# - Exact 47-feature contract
# - UrlLengthRT is implemented from verified dataset rule
# - Other unresolved RT features remain explicitly UNKNOWN
# ============================================================

import os
import re
import json
import math
import joblib
import numpy as np
import pandas as pd
from urllib.parse import urlparse, parse_qs

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------
BASE = "/content/drive/MyDrive/PhishShield_AI"
DATA_DIR = os.path.join(BASE, "data")
CHECKPOINT_DIR = os.path.join(BASE, "checkpoints")
PRODUCTION_DIR = os.path.join(BASE, "production")

os.makedirs(CHECKPOINT_DIR, exist_ok=True)
os.makedirs(PRODUCTION_DIR, exist_ok=True)

FEATURE_PATH = os.path.join(DATA_DIR, "feature_names.pkl")

feature_names = joblib.load(FEATURE_PATH)
feature_names = list(feature_names)

assert len(feature_names) == 47

# ------------------------------------------------------------
# Known RT status
# ------------------------------------------------------------
KNOWN_RT = {
    "UrlLengthRT": True,
    "SubdomainLevelRT": False,
    "PctExtResourceUrlsRT": False,
    "AbnormalExtFormActionR": False,
    "ExtMetaScriptLinkRT": False,
    "PctExtNullSelfRedirectHyperlinksRT": False
}

# ------------------------------------------------------------
# Common sensitive / suspicious words
# NOTE:
# This is an explicit rule set, not a learned model.
# ------------------------------------------------------------
SENSITIVE_WORDS = {
    "login", "signin", "sign-in", "verify", "verification",
    "account", "update", "secure", "security", "confirm",
    "confirmation", "password", "credential", "bank",
    "banking", "wallet", "payment", "billing", "invoice",
    "recover", "recovery", "unlock", "authenticate",
    "authentication", "authorize", "authorization", "bonus",
    "gift", "free", "reward", "prize", "claim", "urgent",
    "suspend", "suspended", "limited", "alert", "support"
}

BRANDS = {
    "google", "microsoft", "apple", "amazon", "paypal",
    "facebook", "instagram", "linkedin", "netflix",
    "github", "outlook", "office365", "dropbox"
}

# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------
def safe_ratio(a, b):
    if b == 0:
        return 0.0
    return float(a) / float(b)


def hostname_parts(hostname):
    if not hostname:
        return []

    return [
        p for p in hostname.lower().split(".")
        if p
    ]


def is_ip_address(hostname):
    if not hostname:
        return 0

    # IPv4
    ipv4 = r"^(?:\d{1,3}\.){3}\d{1,3}$"

    if re.match(ipv4, hostname):
        return 1

    # Basic IPv6 detection
    if ":" in hostname:
        return 1

    return 0


def normalize_url(url):
    url = str(url).strip()

    if not url:
        return ""

    if not re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*://", url):
        url = "http://" + url

    return url


def get_url_components(url):
    normalized = normalize_url(url)
    parsed = urlparse(normalized)

    hostname = parsed.hostname or ""
    path = parsed.path or ""
    query = parsed.query or ""

    return normalized, parsed, hostname, path, query


def count_sensitive_words(text):
    text = str(text).lower()

    tokens = re.findall(r"[a-zA-Z0-9_-]+", text)

    return sum(
        1 for token in tokens
        if token in SENSITIVE_WORDS
    )


def contains_brand(hostname, path, query):
    text = f"{hostname} {path} {query}".lower()

    return int(
        any(
            re.search(rf"\b{re.escape(brand)}\b", text)
            for brand in BRANDS
        )
    )


# ------------------------------------------------------------
# Verified deterministic UrlLengthRT rule
#
# Dataset audit:
# 12–53  -> 1
# 54–75  -> 0
# 76–253 -> -1
# ------------------------------------------------------------
def url_length_rt(url_length):
    if 12 <= url_length <= 53:
        return 1

    if 54 <= url_length <= 75:
        return 0

    if 76 <= url_length <= 253:
        return -1

    # Outside observed training range:
    # DO NOT silently guess.
    return None


# ------------------------------------------------------------
# Main extractor
# ------------------------------------------------------------
def extract_url_features(url):
    normalized, parsed, hostname, path, query = get_url_components(url)

    full_url = normalized
    hostname_lower = hostname.lower()

    # -----------------------------
    # Basic URL structure
    # -----------------------------
    host_parts = hostname_parts(hostname)

    subdomain_level = max(len(host_parts) - 2, 0)

    path_parts = [
        p for p in path.split("/")
        if p
    ]

    query_components = parse_qs(query)

    # -----------------------------
    # Hostname / URL counts
    # -----------------------------
    num_dots = full_url.count(".")

    num_dash = full_url.count("-")

    num_dash_hostname = hostname.count("-")

    num_underscore = full_url.count("_")

    num_percent = full_url.count("%")

    num_ampersand = full_url.count("&")

    num_hash = full_url.count("#")

    num_numeric = sum(
        c.isdigit()
        for c in full_url
    )

    # -----------------------------
    # Special characters
    # -----------------------------
    at_symbol = int("@" in full_url)

    tilde_symbol = int("~" in full_url)

    # -----------------------------
    # HTTPS
    # -----------------------------
    no_https = int(
        parsed.scheme.lower() != "https"
    )

    # -----------------------------
    # IP address
    # -----------------------------
    ip_address = is_ip_address(hostname)

    # -----------------------------
    # Random-string heuristic
    #
    # Explicit heuristic:
    # long high-entropy-looking hostname
    # token / random-looking subdomain.
    # -----------------------------
    random_string = 0

    host_tokens = re.split(r"[.\-_]", hostname_lower)

    for token in host_tokens:
        if len(token) >= 12:
            letters = sum(c.isalpha() for c in token)
            digits = sum(c.isdigit() for c in token)

            if letters > 0 and digits > 0:
                random_string = 1
                break

    # -----------------------------
    # Domain position heuristics
    # -----------------------------
    domain_in_subdomains = int(
        any(
            brand in host_parts[:-2]
            for brand in BRANDS
        )
    )

    domain_in_paths = int(
        any(
            brand in path.lower()
            for brand in BRANDS
        )
    )

    # -----------------------------
    # Length features
    # -----------------------------
    hostname_length = len(hostname)

    path_length = len(path)

    query_length = len(query)

    url_length = len(full_url)

    # -----------------------------
    # Double slash after scheme
    # -----------------------------
    after_scheme = re.sub(
        r"^[a-zA-Z][a-zA-Z0-9+.-]*://",
        "",
        full_url
    )

    double_slash_path = int(
        "//" in after_scheme
    )

    # -----------------------------
    # Sensitive words
    # -----------------------------
    num_sensitive_words = count_sensitive_words(
        f"{hostname} {path} {query}"
    )

    embedded_brand_name = contains_brand(
        hostname,
        path,
        query
    )

    # --------------------------------------------------------
    # Features that require HTML/document inspection
    #
    # We DO NOT invent values here.
    # They are marked unavailable.
    # --------------------------------------------------------
    unavailable_html = {
        "PctExtHyperlinks": None,
        "PctExtResourceUrls": None,
        "ExtFavicon": None,
        "InsecureForms": None,
        "RelativeFormAction": None,
        "ExtFormAction": None,
        "AbnormalFormAction": None,
        "PctNullSelfRedirectHyperlinks": None,
        "FrequentDomainNameMismatch": None,
        "FakeLinkInStatusBar": None,
        "RightClickDisabled": None,
        "PopUpWindow": None,
        "SubmitInfoToEmail": None,
        "IframeOrFrame": None,
        "MissingTitle": None,
        "ImagesOnlyInForm": None,
    }

    # --------------------------------------------------------
    # RT features
    # --------------------------------------------------------
    rt_values = {
        "SubdomainLevelRT": None,
        "UrlLengthRT": url_length_rt(url_length),
        "PctExtResourceUrlsRT": None,
        "AbnormalExtFormActionR": None,
        "ExtMetaScriptLinkRT": None,
        "PctExtNullSelfRedirectHyperlinksRT": None
    }

    # --------------------------------------------------------
    # Build dictionary
    # --------------------------------------------------------
    features = {
        "NumDots": num_dots,
        "SubdomainLevel": subdomain_level,
        "PathLevel": len(path_parts),
        "UrlLength": url_length,
        "NumDash": num_dash,
        "NumDashInHostname": num_dash_hostname,
        "AtSymbol": at_symbol,
        "TildeSymbol": tilde_symbol,
        "NumUnderscore": num_underscore,
        "NumPercent": num_percent,
        "NumQueryComponents": len(query_components),
        "NumAmpersand": num_ampersand,
        "NumHash": num_hash,
        "NumNumericChars": num_numeric,
        "NoHttps": no_https,
        "RandomString": random_string,
        "IpAddress": ip_address,
        "DomainInSubdomains": domain_in_subdomains,
        "DomainInPaths": domain_in_paths,
        "HostnameLength": hostname_length,
        "PathLength": path_length,
        "QueryLength": query_length,
        "DoubleSlashInPath": double_slash_path,
        "NumSensitiveWords": num_sensitive_words,
        "EmbeddedBrandName": embedded_brand_name,
    }

    features.update(unavailable_html)
    features.update(rt_values)

    # --------------------------------------------------------
    # STRICT 47-feature validation
    # --------------------------------------------------------
    missing = [
        f for f in feature_names
        if f not in features
    ]

    unknown = [
        f for f in feature_names
        if features.get(f) is None
    ]

    extra = [
        f for f in features
        if f not in feature_names
    ]

    if missing:
        raise ValueError(
            f"Missing feature keys: {missing}"
        )

    if extra:
        raise ValueError(
            f"Unexpected feature keys: {extra}"
        )

    return {
        "url": url,
        "normalized_url": normalized,
        "features": features,
        "missing_features": missing,
        "unknown_features": unknown
    }


# ------------------------------------------------------------
# Save extractor checkpoint
# ------------------------------------------------------------
EXTRACTOR_CHECKPOINT = os.path.join(
    CHECKPOINT_DIR,
    "step_5I_feature_extractor_contract.json"
)

checkpoint = {
    "stage": "5I",
    "feature_count": 47,
    "feature_names": feature_names,
    "known_rt_features": [
        k for k, v in KNOWN_RT.items() if v
    ],
    "unresolved_rt_features": [
        k for k, v in KNOWN_RT.items() if not v
    ],
    "strict_missing_feature_policy": True,
    "silent_zero_fallback": False,
    "training_performed": False,
    "model_modified": False
}

with open(EXTRACTOR_CHECKPOINT, "w") as f:
    json.dump(checkpoint, f, indent=2)

print("=" * 70)
print("STEP 5I EXTRACTOR CREATED")
print("=" * 70)
print("Feature contract :", len(feature_names))
print("Known RT         :", [k for k,v in KNOWN_RT.items() if v])
print("Unresolved RT    :", [k for k,v in KNOWN_RT.items() if not v])
print("Silent 0 fallback: DISABLED")
print("Training         : NO")
print("Model modified   : NO")
print()
print("Checkpoint:")
print(EXTRACTOR_CHECKPOINT)
print("=" * 70)

# ------------------------------------------------------------
# Controlled sanity test
# ------------------------------------------------------------
TEST_URL = "https://www.google.com"

result = extract_url_features(TEST_URL)

print("\nSANITY TEST:", TEST_URL)
print("Total features generated:", len(result["features"]))
print("Missing features:", result["missing_features"])
print("Unknown features:", result["unknown_features"])

print("\nGenerated feature values:")
for name in feature_names:
    print(f"{name:45s} : {result['features'][name]}")

print("\nIMPORTANT:")
print("This extractor is NOT connected to XGBoost yet.")
print("No prediction was performed.")

======================================================================
STEP 5I EXTRACTOR CREATED
======================================================================
Feature contract : 47
Known RT         : ['UrlLengthRT']
Unresolved RT    : ['SubdomainLevelRT', 'PctExtResourceUrlsRT', 'AbnormalExtFormActionR', 'ExtMetaScriptLinkRT', 'PctExtNullSelfRedirectHyperlinksRT']
Silent 0 fallback: DISABLED
Training         : NO
Model modified   : NO

Checkpoint:
/content/drive/MyDrive/PhishShield_AI/checkpoints/step_5I_feature_extractor_contract.json
======================================================================

SANITY TEST: https://www.google.com
Total features generated: 47
Missing features: []
Unknown features: ['PctExtHyperlinks', 'PctExtResourceUrls', 'ExtFavicon', 'InsecureForms', 'RelativeFormAction', 'ExtFormAction', 'AbnormalFormAction', 'PctNullSelfRedirectHyperlinks', 'FrequentDomainNameMismatch', 'FakeLinkInStatusBar', 'RightClickDisabled', 'PopUpWindow', 'SubmitInfoToEmail', 'IframeOrFrame', 'MissingTitle', 'ImagesOnlyInForm', 'SubdomainLevelRT', 'PctExtResourceUrlsRT', 'AbnormalExtFormActionR', 'ExtMetaScriptLinkRT', 'PctExtNullSelfRedirectHyperlinksRT']

Generated feature values:
NumDots                                       : 2
SubdomainLevel                                : 1
PathLevel                                     : 0
UrlLength                                     : 22
NumDash                                       : 0
NumDashInHostname                             : 0
AtSymbol                                      : 0
TildeSymbol                                   : 0
NumUnderscore                                 : 0
NumPercent                                    : 0
NumQueryComponents                            : 0
NumAmpersand                                  : 0
NumHash                                       : 0
NumNumericChars                               : 0
NoHttps                                       : 0
RandomString                                  : 0
IpAddress                                     : 0
DomainInSubdomains                            : 0
DomainInPaths                                 : 0
HostnameLength                                : 14
PathLength                                    : 0
QueryLength                                   : 0
DoubleSlashInPath                             : 0
NumSensitiveWords                             : 0
EmbeddedBrandName                             : 1
PctExtHyperlinks                              : None
PctExtResourceUrls                            : None
ExtFavicon                                    : None
InsecureForms                                 : None
RelativeFormAction                            : None
ExtFormAction                                 : None
AbnormalFormAction                            : None
PctNullSelfRedirectHyperlinks                 : None
FrequentDomainNameMismatch                    : None
FakeLinkInStatusBar                           : None
RightClickDisabled                            : None
PopUpWindow                                   : None
SubmitInfoToEmail                             : None
IframeOrFrame                                 : None
MissingTitle                                  : None
ImagesOnlyInForm                              : None
SubdomainLevelRT                              : None
UrlLengthRT                                   : 1
PctExtResourceUrlsRT                          : None
AbnormalExtFormActionR                        : None
ExtMetaScriptLinkRT                           : None
PctExtNullSelfRedirectHyperlinksRT            : None

IMPORTANT:
This extractor is NOT connected to XGBoost yet.
No prediction was performed.

In [ ]:
# ============================================================
# PHISHSHIELD AI — STEP 5J
# HTML FEATURE EXTRACTOR
#
# NO TRAINING
# NO MODEL MODIFICATION
# NO PREDICTION
#
# Generates the 16 HTML-derived features from live HTML.
# ============================================================

import os
import re
import json
import math
import requests
import numpy as np
from urllib.parse import urljoin, urlparse

BASE = "/content/drive/MyDrive/PhishShield_AI"
CHECKPOINT_DIR = os.path.join(BASE, "checkpoints")
PRODUCTION_DIR = os.path.join(BASE, "production")

os.makedirs(CHECKPOINT_DIR, exist_ok=True)
os.makedirs(PRODUCTION_DIR, exist_ok=True)

# ------------------------------------------------------------
# HTML parser
# ------------------------------------------------------------
from bs4 import BeautifulSoup

# ------------------------------------------------------------
# Feature list
# ------------------------------------------------------------
HTML_FEATURES = [
    "PctExtHyperlinks",
    "PctExtResourceUrls",
    "ExtFavicon",
    "InsecureForms",
    "RelativeFormAction",
    "ExtFormAction",
    "AbnormalFormAction",
    "PctNullSelfRedirectHyperlinks",
    "FrequentDomainNameMismatch",
    "FakeLinkInStatusBar",
    "RightClickDisabled",
    "PopUpWindow",
    "SubmitInfoToEmail",
    "IframeOrFrame",
    "MissingTitle",
    "ImagesOnlyInForm"
]

# ------------------------------------------------------------
# Safe request
# ------------------------------------------------------------
def fetch_html(url, timeout=10):
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 Chrome/131 Safari/537.36"
        )
    }

    response = requests.get(
        url,
        headers=headers,
        timeout=timeout,
        allow_redirects=True
    )

    response.raise_for_status()

    return response.url, response.text


# ------------------------------------------------------------
# URL/domain helpers
# ------------------------------------------------------------
def registered_domain(hostname):
    """
    Lightweight domain comparison.
    Uses the last two labels for normal domains.

    This intentionally does not claim to reproduce the
    original dataset's exact domain parser.
    """
    if not hostname:
        return ""

    hostname = hostname.lower().strip(".")

    parts = hostname.split(".")

    if len(parts) <= 2:
        return hostname

    return ".".join(parts[-2:])


def is_external(target_url, base_url):
    if not target_url:
        return False

    target = urlparse(target_url)
    base = urlparse(base_url)

    if target.scheme and target.scheme not in ("http", "https"):
        return False

    target_host = target.hostname or ""
    base_host = base.hostname or ""

    if not target_host:
        return False

    return (
        registered_domain(target_host)
        != registered_domain(base_host)
    )


# ------------------------------------------------------------
# Percentage helper
# ------------------------------------------------------------
def percentage(numerator, denominator):
    if denominator == 0:
        return 0.0

    return float(numerator) / float(denominator)


# ------------------------------------------------------------
# Main HTML extractor
# ------------------------------------------------------------
def extract_html_features(html, page_url):

    soup = BeautifulSoup(
        html,
        "html.parser"
    )

    page = urlparse(page_url)

    page_domain = registered_domain(
        page.hostname or ""
    )

    # ========================================================
    # 1. Hyperlinks
    # ========================================================
    links = soup.find_all("a")

    total_links = len(links)

    external_links = 0

    null_self_redirect_links = 0

    domain_mismatch_links = 0

    for a in links:

        href = a.get("href")

        if href is None:
            continue

        href = str(href).strip()

        # Null / self redirect
        if (
            href == ""
            or href == "#"
            or href.lower().startswith("javascript:void")
            or href.lower().startswith("javascript:;")
        ):
            null_self_redirect_links += 1

        absolute = urljoin(page_url, href)

        parsed_target = urlparse(absolute)

        target_host = parsed_target.hostname or ""

        if target_host:

            target_domain = registered_domain(
                target_host
            )

            if target_domain != page_domain:
                external_links += 1
                domain_mismatch_links += 1

    pct_ext_hyperlinks = percentage(
        external_links,
        total_links
    )

    pct_null_self_redirect = percentage(
        null_self_redirect_links,
        total_links
    )

    # ========================================================
    # 2. External resources
    # ========================================================
    resources = []

    # script src
    resources.extend(
        [
            tag.get("src")
            for tag in soup.find_all("script")
            if tag.get("src")
        ]
    )

    # img src
    resources.extend(
        [
            tag.get("src")
            for tag in soup.find_all("img")
            if tag.get("src")
        ]
    )

    # link href
    resources.extend(
        [
            tag.get("href")
            for tag in soup.find_all("link")
            if tag.get("href")
        ]
    )

    # iframe src
    resources.extend(
        [
            tag.get("src")
            for tag in soup.find_all("iframe")
            if tag.get("src")
        ]
    )

    external_resources = 0

    for resource in resources:

        absolute = urljoin(
            page_url,
            str(resource)
        )

        if is_external(
            absolute,
            page_url
        ):
            external_resources += 1

    pct_ext_resources = percentage(
        external_resources,
        len(resources)
    )

    # ========================================================
    # 3. Favicon
    # ========================================================
    favicon_links = []

    for link in soup.find_all("link"):

        rel = link.get("rel", [])

        if isinstance(rel, str):
            rel = [rel]

        rel_text = " ".join(rel).lower()

        if "icon" in rel_text:
            favicon_links.append(
                link.get("href")
            )

    ext_favicon = 0

    for href in favicon_links:

        if href:

            absolute = urljoin(
                page_url,
                href
            )

            if is_external(
                absolute,
                page_url
            ):
                ext_favicon = 1
                break

    # ========================================================
    # 4. Forms
    # ========================================================
    forms = soup.find_all("form")

    insecure_forms = 0
    relative_form_action = 0
    external_form_action = 0
    abnormal_form_action = 0

    for form in forms:

        action = form.get("action")

        if action is None:
            action = ""

        action = str(action).strip()

        # Insecure HTTP form
        if action.lower().startswith("http://"):
            insecure_forms += 1

        # Relative action
        parsed_action = urlparse(action)

        if (
            action != ""
            and not parsed_action.scheme
            and not parsed_action.netloc
        ):
            relative_form_action += 1

        # Absolute/external action
        absolute_action = urljoin(
            page_url,
            action
        )

        if action:

            if is_external(
                absolute_action,
                page_url
            ):
                external_form_action += 1

        # Abnormal action
        if (
            action == ""
            or action.lower() == "about:blank"
            or action.lower().startswith("javascript:")
        ):
            abnormal_form_action += 1

    # ========================================================
    # 5. Domain mismatch
    # ========================================================
    frequent_domain_mismatch = 0

    if total_links > 0:

        mismatch_ratio = percentage(
            domain_mismatch_links,
            total_links
        )

        # Explicit heuristic.
        # Not claimed to be the original dataset rule.
        if mismatch_ratio >= 0.50:
            frequent_domain_mismatch = 1

    # ========================================================
    # 6. Fake status-bar links
    # ========================================================
    fake_status_bar = 0

    for tag in soup.find_all(
        attrs={"onmouseover": True}
    ):

        script = str(
            tag.get("onmouseover")
        ).lower()

        if (
            "window.status" in script
            or "status=" in script
        ):
            fake_status_bar = 1
            break

    # ========================================================
    # 7. Right-click disabled
    # ========================================================
    right_click_disabled = 0

    page_scripts = soup.find_all("script")

    for script in page_scripts:

        text = script.get_text(
            " ",
            strip=True
        ).lower()

        if (
            "contextmenu" in text
            or "oncontextmenu" in text
        ):
            right_click_disabled = 1
            break

    # ========================================================
    # 8. Pop-up window
    # ========================================================
    popup_window = 0

    for script in page_scripts:

        text = script.get_text(
            " ",
            strip=True
        ).lower()

        if (
            "window.open(" in text
            or "window.open (" in text
        ):
            popup_window = 1
            break

    # ========================================================
    # 9. Submit information to email
    # ========================================================
    submit_info_email = 0

    for form in forms:

        action = str(
            form.get("action", "")
        ).lower()

        if action.startswith(
            "mailto:"
        ):
            submit_info_email = 1
            break

    # ========================================================
    # 10. Iframe / frame
    # ========================================================
    iframe_or_frame = int(
        bool(
            soup.find("iframe")
            or soup.find("frame")
            or soup.find("frameset")
        )
    )

    # ========================================================
    # 11. Missing title
    # ========================================================
    missing_title = int(
        soup.find("title") is None
    )

    # ========================================================
    # 12. Images-only-in-form
    #
    # Conservative structural heuristic:
    # if forms exist and a form contains images but no
    # meaningful textual/input controls.
    # ========================================================
    images_only_form = 0

    for form in forms:

        images = form.find_all("img")

        inputs = form.find_all(
            ["input", "button", "textarea", "select"]
        )

        text = form.get_text(
            " ",
            strip=True
        )

        if (
            images
            and not inputs
            and not text
        ):
            images_only_form = 1
            break

    # ========================================================
    # Return
    # ========================================================
    features = {
        "PctExtHyperlinks": pct_ext_hyperlinks,
        "PctExtResourceUrls": pct_ext_resources,
        "ExtFavicon": ext_favicon,
        "InsecureForms": insecure_forms,
        "RelativeFormAction": relative_form_action,
        "ExtFormAction": external_form_action,
        "AbnormalFormAction": abnormal_form_action,
        "PctNullSelfRedirectHyperlinks": pct_null_self_redirect,
        "FrequentDomainNameMismatch": frequent_domain_mismatch,
        "FakeLinkInStatusBar": fake_status_bar,
        "RightClickDisabled": right_click_disabled,
        "PopUpWindow": popup_window,
        "SubmitInfoToEmail": submit_info_email,
        "IframeOrFrame": iframe_or_frame,
        "MissingTitle": missing_title,
        "ImagesOnlyInForm": images_only_form
    }

    return features


# ------------------------------------------------------------
# Controlled live test
# ------------------------------------------------------------
TEST_URL = "https://www.google.com"

print("=" * 70)
print("STEP 5J — LIVE HTML EXTRACTION TEST")
print("=" * 70)

try:

    final_url, html = fetch_html(
        TEST_URL
    )

    print("Requested URL :", TEST_URL)
    print("Final URL     :", final_url)
    print("HTML length   :", len(html))

    html_features = extract_html_features(
        html,
        final_url
    )

    print("\nHTML FEATURES GENERATED:")

    for name in HTML_FEATURES:
        print(
            f"{name:45s} : "
            f"{html_features[name]}"
        )

    missing = [
        f
        for f in HTML_FEATURES
        if f not in html_features
    ]

    print("\nMissing HTML features:", missing)

    assert len(html_features) == 16
    assert not missing

    # --------------------------------------------------------
    # Save test checkpoint
    # --------------------------------------------------------
    checkpoint = {
        "stage": "5J",
        "test_url": TEST_URL,
        "final_url": final_url,
        "html_length": len(html),
        "feature_count": len(html_features),
        "features": html_features,
        "training_performed": False,
        "model_modified": False
    }

    checkpoint_path = os.path.join(
        CHECKPOINT_DIR,
        "step_5J_html_extractor_test.json"
    )

    with open(
        checkpoint_path,
        "w"
    ) as f:
        json.dump(
            checkpoint,
            f,
            indent=2
        )

    print("\n" + "=" * 70)
    print("STEP 5J TEST COMPLETE")
    print("=" * 70)
    print("16 HTML features generated.")
    print("No training performed.")
    print("No model modified.")
    print("Checkpoint:")
    print(checkpoint_path)

except Exception as e:

    print("\nHTML extraction failed:")
    print(type(e).__name__, ":", e)
    print(
        "\nDO NOT connect XGBoost yet."
    )

======================================================================
STEP 5J — LIVE HTML EXTRACTION TEST
======================================================================
Requested URL : https://www.google.com
Final URL     : https://www.google.com/
HTML length   : 224457

HTML FEATURES GENERATED:
PctExtHyperlinks                              : 0.1111111111111111
PctExtResourceUrls                            : 0.6
ExtFavicon                                    : 1
InsecureForms                                 : 0
RelativeFormAction                            : 1
ExtFormAction                                 : 0
AbnormalFormAction                            : 0
PctNullSelfRedirectHyperlinks                 : 0.0
FrequentDomainNameMismatch                    : 0
FakeLinkInStatusBar                           : 0
RightClickDisabled                            : 0
PopUpWindow                                   : 0
SubmitInfoToEmail                             : 0
IframeOrFrame                                 : 0
MissingTitle                                  : 0
ImagesOnlyInForm                              : 0

Missing HTML features: []

======================================================================
STEP 5J TEST COMPLETE
======================================================================
16 HTML features generated.
No training performed.
No model modified.
Checkpoint:
/content/drive/MyDrive/PhishShield_AI/checkpoints/step_5J_html_extractor_test.json

In [ ]:
# ============================================================
# PHISHSHIELD AI — STEP 5K
# COMBINE URL + HTML FEATURES
#
# NO TRAINING
# NO PREDICTION
# NO MODEL MODIFICATION
# ============================================================

import os
import json
import joblib
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------
BASE = "/content/drive/MyDrive/PhishShield_AI"
DATA_DIR = os.path.join(BASE, "data")
CHECKPOINT_DIR = os.path.join(BASE, "checkpoints")

FEATURE_PATH = os.path.join(
    DATA_DIR,
    "feature_names.pkl"
)

feature_names = list(
    joblib.load(FEATURE_PATH)
)

assert len(feature_names) == 47

# ------------------------------------------------------------
# Verify required functions exist from previous cells
# ------------------------------------------------------------
assert "extract_url_features" in globals(), \
    "extract_url_features() not found. Run Step 5I first."

assert "extract_html_features" in globals(), \
    "extract_html_features() not found. Run Step 5J first."

# ------------------------------------------------------------
# Test URL
# ------------------------------------------------------------
TEST_URL = "https://www.google.com"

print("=" * 70)
print("STEP 5K — COMBINED FEATURE PIPELINE AUDIT")
print("=" * 70)

# ------------------------------------------------------------
# 1. URL features
# ------------------------------------------------------------
url_result = extract_url_features(
    TEST_URL
)

url_features = url_result["features"]

print("\nURL extractor:")
print("Features:", len(url_features))
print("Unknown:", url_result["unknown_features"])

# ------------------------------------------------------------
# 2. Fetch HTML
# ------------------------------------------------------------
final_url, html = fetch_html(
    TEST_URL
)

print("\nHTML fetch:")
print("Final URL :", final_url)
print("HTML size :", len(html))

# ------------------------------------------------------------
# 3. HTML features
# ------------------------------------------------------------
html_features = extract_html_features(
    html,
    final_url
)

print("\nHTML extractor:")
print("Features:", len(html_features))

# ------------------------------------------------------------
# 4. Merge
# ------------------------------------------------------------
combined = dict(url_features)

for name, value in html_features.items():
    combined[name] = value

# ------------------------------------------------------------
# 5. Strict contract validation
# ------------------------------------------------------------
missing = [
    f
    for f in feature_names
    if f not in combined
]

extra = [
    f
    for f in combined
    if f not in feature_names
]

unknown = [
    f
    for f in feature_names
    if combined[f] is None
]

print("\n" + "-" * 70)
print("CONTRACT AUDIT")
print("-" * 70)

print("Expected features :", len(feature_names))
print("Generated features:", len(combined))
print("Missing           :", len(missing))
print("Extra             :", len(extra))
print("Unknown           :", len(unknown))

if missing:
    print("\nMissing:")
    for f in missing:
        print(" -", f)

if extra:
    print("\nExtra:")
    for f in extra:
        print(" -", f)

if unknown:
    print("\nUnknown:")
    for f in unknown:
        print(" -", f)

# ------------------------------------------------------------
# 6. Identify unresolved RT features
# ------------------------------------------------------------
RT_FEATURES = [
    "SubdomainLevelRT",
    "UrlLengthRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

unresolved_rt = [
    f
    for f in RT_FEATURES
    if combined.get(f) is None
]

print("\n" + "-" * 70)
print("RT FEATURE STATUS")
print("-" * 70)

for f in RT_FEATURES:
    value = combined.get(f)

    if value is None:
        status = "UNRESOLVED"
    else:
        status = "AVAILABLE"

    print(
        f"{f:45s} : {value!s:8s} [{status}]"
    )

# ------------------------------------------------------------
# 7. Show final feature vector in EXACT model order
# ------------------------------------------------------------
ordered_values = [
    combined[f]
    for f in feature_names
]

print("\n" + "-" * 70)
print("FINAL 47-FEATURE ORDER CHECK")
print("-" * 70)

for i, (name, value) in enumerate(
    zip(feature_names, ordered_values)
):
    print(
        f"{i:02d} | {name:45s} | {value}"
    )

# ------------------------------------------------------------
# 8. Save combined audit checkpoint
# ------------------------------------------------------------
checkpoint = {
    "stage": "5K",
    "test_url": TEST_URL,
    "final_url": final_url,
    "html_length": len(html),

    "expected_feature_count": 47,
    "generated_feature_count": len(combined),

    "missing_features": missing,
    "extra_features": extra,
    "unknown_features": unknown,

    "rt_features": RT_FEATURES,
    "unresolved_rt_features": unresolved_rt,

    "feature_order": feature_names,
    "combined_features": {
        k: (
            None
            if pd.isna(v)
            else v
        )
        for k, v in combined.items()
    },

    "training_performed": False,
    "prediction_performed": False,
    "model_modified": False
}

checkpoint_path = os.path.join(
    CHECKPOINT_DIR,
    "step_5K_combined_feature_audit.json"
)

with open(
    checkpoint_path,
    "w"
) as f:
    json.dump(
        checkpoint,
        f,
        indent=2
    )

print("\n" + "=" * 70)
print("STEP 5K COMPLETE")
print("=" * 70)

print("Checkpoint:")
print(checkpoint_path)

print("\nIMPORTANT:")
print("XGBoost prediction was NOT performed.")
print("Model was NOT modified.")
print("Training was NOT performed.")

if unresolved_rt:
    print("\nNEXT DECISION:")
    print(
        "5 RT features are still unresolved. "
        "We must resolve/handle them before production prediction."
    )
else:
    print(
        "\nALL 47 FEATURES ARE AVAILABLE."
    )

======================================================================
STEP 5K — COMBINED FEATURE PIPELINE AUDIT
======================================================================

URL extractor:
Features: 47
Unknown: ['PctExtHyperlinks', 'PctExtResourceUrls', 'ExtFavicon', 'InsecureForms', 'RelativeFormAction', 'ExtFormAction', 'AbnormalFormAction', 'PctNullSelfRedirectHyperlinks', 'FrequentDomainNameMismatch', 'FakeLinkInStatusBar', 'RightClickDisabled', 'PopUpWindow', 'SubmitInfoToEmail', 'IframeOrFrame', 'MissingTitle', 'ImagesOnlyInForm', 'SubdomainLevelRT', 'PctExtResourceUrlsRT', 'AbnormalExtFormActionR', 'ExtMetaScriptLinkRT', 'PctExtNullSelfRedirectHyperlinksRT']

HTML fetch:
Final URL : https://www.google.com/
HTML size : 216639

HTML extractor:
Features: 16

----------------------------------------------------------------------
CONTRACT AUDIT
----------------------------------------------------------------------
Expected features : 47
Generated features: 47
Missing           : 0
Extra             : 0
Unknown           : 5

Unknown:
 - SubdomainLevelRT
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

----------------------------------------------------------------------
RT FEATURE STATUS
----------------------------------------------------------------------
SubdomainLevelRT                              : None     [UNRESOLVED]
UrlLengthRT                                   : 1        [AVAILABLE]
PctExtResourceUrlsRT                          : None     [UNRESOLVED]
AbnormalExtFormActionR                        : None     [UNRESOLVED]
ExtMetaScriptLinkRT                           : None     [UNRESOLVED]
PctExtNullSelfRedirectHyperlinksRT            : None     [UNRESOLVED]

----------------------------------------------------------------------
FINAL 47-FEATURE ORDER CHECK
----------------------------------------------------------------------
00 | NumDots                                       | 2
01 | SubdomainLevel                                | 1
02 | PathLevel                                     | 0
03 | UrlLength                                     | 22
04 | NumDash                                       | 0
05 | NumDashInHostname                             | 0
06 | AtSymbol                                      | 0
07 | TildeSymbol                                   | 0
08 | NumUnderscore                                 | 0
09 | NumPercent                                    | 0
10 | NumQueryComponents                            | 0
11 | NumAmpersand                                  | 0
12 | NumHash                                       | 0
13 | NumNumericChars                               | 0
14 | NoHttps                                       | 0
15 | RandomString                                  | 0
16 | IpAddress                                     | 0
17 | DomainInSubdomains                            | 0
18 | DomainInPaths                                 | 0
19 | HostnameLength                                | 14
20 | PathLength                                    | 0
21 | QueryLength                                   | 0
22 | DoubleSlashInPath                             | 0
23 | NumSensitiveWords                             | 0
24 | EmbeddedBrandName                             | 1
25 | PctExtHyperlinks                              | 0.1111111111111111
26 | PctExtResourceUrls                            | 0.6
27 | ExtFavicon                                    | 1
28 | InsecureForms                                 | 0
29 | RelativeFormAction                            | 1
30 | ExtFormAction                                 | 0
31 | AbnormalFormAction                            | 0
32 | PctNullSelfRedirectHyperlinks                 | 0.0
33 | FrequentDomainNameMismatch                    | 0
34 | FakeLinkInStatusBar                           | 0
35 | RightClickDisabled                            | 0
36 | PopUpWindow                                   | 0
37 | SubmitInfoToEmail                             | 0
38 | IframeOrFrame                                 | 0
39 | MissingTitle                                  | 0
40 | ImagesOnlyInForm                              | 0
41 | SubdomainLevelRT                              | None
42 | UrlLengthRT                                   | 1
43 | PctExtResourceUrlsRT                          | None
44 | AbnormalExtFormActionR                        | None
45 | ExtMetaScriptLinkRT                           | None
46 | PctExtNullSelfRedirectHyperlinksRT            | None

======================================================================
STEP 5K COMPLETE
======================================================================
Checkpoint:
/content/drive/MyDrive/PhishShield_AI/checkpoints/step_5K_combined_feature_audit.json

IMPORTANT:
XGBoost prediction was NOT performed.
Model was NOT modified.
Training was NOT performed.

NEXT DECISION:
5 RT features are still unresolved. We must resolve/handle them before production prediction.

In [ ]:
# ============================================================
# PHISHSHIELD AI — STEP 5L
# EMPIRICAL RT FEATURE RULE DISCOVERY
#
# PURPOSE:
#   Investigate whether the 5 unresolved RT features can be
#   reproduced from the other 47-feature dataset information.
#
# STRICT SAFETY:
#   - CLASS_LABEL NOT USED
#   - id NOT USED
#   - No model training
#   - No XGBoost modification
#   - No production extractor modification
#   - No prediction
# ============================================================

import os
import json
import joblib
import numpy as np
import pandas as pd

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import accuracy_score

print("=" * 70)
print("STEP 5L — EMPIRICAL RT FEATURE RULE DISCOVERY")
print("=" * 70)

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------
BASE = "/content/drive/MyDrive/PhishShield_AI"
DATA_DIR = os.path.join(BASE, "data")
CHECKPOINT_DIR = os.path.join(BASE, "checkpoints")

# ------------------------------------------------------------
# Locate dataset
# ------------------------------------------------------------
possible_paths = [
    "/content/Phishing_Legitimate_full(4).csv",
    "/content/drive/MyDrive/PhishShield_AI/data/Phishing_Legitimate_full(4).csv",
    "/content/Phishing_Legitimate_full.csv"
]

DATA_PATH = None

for p in possible_paths:
    if os.path.exists(p):
        DATA_PATH = p
        break

if DATA_PATH is None:
    raise FileNotFoundError(
        "Dataset CSV not found in expected locations."
    )

print("\nDataset:")
print(DATA_PATH)

df = pd.read_csv(DATA_PATH)

print("Shape:", df.shape)

# ------------------------------------------------------------
# Verify dataset contract
# ------------------------------------------------------------
TARGET = "CLASS_LABEL"
ID_COL = "id"

RT_FEATURES = [
    "SubdomainLevelRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

for col in RT_FEATURES:
    assert col in df.columns, f"Missing RT column: {col}"

assert TARGET in df.columns
assert ID_COL in df.columns

# ------------------------------------------------------------
# IMPORTANT:
# Remove target, ID, and ALL RT columns from predictors.
#
# This prevents one RT feature from trivially reproducing
# another RT feature and keeps the discovery focused on
# the original URL/HTML features.
# ------------------------------------------------------------
EXCLUDED = [
    TARGET,
    ID_COL,
    "SubdomainLevelRT",
    "UrlLengthRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

candidate_features = [
    c for c in df.columns
    if c not in EXCLUDED
]

X = df[candidate_features].copy()

print("\nCandidate predictor count:", len(candidate_features))

# ------------------------------------------------------------
# Remove constant columns if any
# ------------------------------------------------------------
constant_cols = [
    c for c in X.columns
    if X[c].nunique(dropna=False) <= 1
]

if constant_cols:
    print("\nConstant candidate columns removed:")
    for c in constant_cols:
        print(" -", c)

    X = X.drop(columns=constant_cols)

candidate_features = list(X.columns)

# ------------------------------------------------------------
# Cross-validation configuration
# ------------------------------------------------------------
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

results = {}

# ------------------------------------------------------------
# Rule discovery for each unresolved RT feature
# ------------------------------------------------------------
for target_rt in RT_FEATURES:

    print("\n" + "=" * 70)
    print("TARGET RT:", target_rt)
    print("=" * 70)

    y = df[target_rt]

    print("\nDistribution:")
    print(
        y.value_counts()
         .sort_index()
         .to_dict()
    )

    depth_results = []

    # --------------------------------------------------------
    # Test shallow/interpretable trees first
    # --------------------------------------------------------
    for depth in range(1, 7):

        tree = DecisionTreeClassifier(
            max_depth=depth,
            min_samples_leaf=5,
            random_state=42
        )

        scores = cross_val_score(
            tree,
            X,
            y,
            cv=cv,
            scoring="accuracy",
            n_jobs=-1
        )

        mean_score = scores.mean()
        std_score = scores.std()

        depth_results.append({
            "depth": depth,
            "cv_accuracy_mean": float(mean_score),
            "cv_accuracy_std": float(std_score)
        })

        print(
            f"depth={depth} | "
            f"CV accuracy={mean_score:.6f} "
            f"+/- {std_score:.6f}"
        )

    # --------------------------------------------------------
    # Best depth based on CV accuracy
    # --------------------------------------------------------
    best_result = max(
        depth_results,
        key=lambda x: x["cv_accuracy_mean"]
    )

    best_depth = best_result["depth"]

    best_tree = DecisionTreeClassifier(
        max_depth=best_depth,
        min_samples_leaf=5,
        random_state=42
    )

    best_tree.fit(X, y)

    # --------------------------------------------------------
    # Feature importance
    # --------------------------------------------------------
    importance = pd.Series(
        best_tree.feature_importances_,
        index=candidate_features
    ).sort_values(
        ascending=False
    )

    important_features = (
        importance[
            importance > 0
        ]
        .head(10)
    )

    print("\nTop features used by best tree:")

    if len(important_features) == 0:
        print("  None")
    else:
        for feature, value in important_features.items():
            print(
                f"  {feature:45s}: {value:.6f}"
            )

    # --------------------------------------------------------
    # Store result
    # --------------------------------------------------------
    results[target_rt] = {
        "distribution": {
            str(k): int(v)
            for k, v in y.value_counts().sort_index().items()
        },

        "depth_results": depth_results,

        "best_depth": int(best_depth),

        "best_cv_accuracy": float(
            best_result["cv_accuracy_mean"]
        ),

        "best_cv_std": float(
            best_result["cv_accuracy_std"]
        ),

        "top_features": {
            str(feature): float(value)
            for feature, value in important_features.items()
        }
    }

# ------------------------------------------------------------
# Save checkpoint
# ------------------------------------------------------------
checkpoint = {
    "stage": "5L",

    "dataset_path": DATA_PATH,
    "dataset_shape": list(df.shape),

    "target_used_for_discovery": RT_FEATURES,

    "forbidden_columns": [
        TARGET,
        ID_COL
    ],

    "rt_columns_excluded_from_predictors": RT_FEATURES,

    "candidate_feature_count": len(candidate_features),

    "candidate_features": candidate_features,

    "results": results,

    "training_performed": False,
    "production_model_modified": False,
    "production_extractor_modified": False,
    "prediction_performed": False
}

checkpoint_path = os.path.join(
    CHECKPOINT_DIR,
    "step_5L_rt_rule_discovery.json"
)

with open(
    checkpoint_path,
    "w"
) as f:
    json.dump(
        checkpoint,
        f,
        indent=2
    )

# ------------------------------------------------------------
# Final summary
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("STEP 5L COMPLETE")
print("=" * 70)

print("\nRT reproduction summary:")

for rt, result in results.items():

    print(
        f"{rt:45s} | "
        f"best depth={result['best_depth']} | "
        f"CV accuracy={result['best_cv_accuracy']:.6f}"
    )

print("\nCheckpoint:")
print(checkpoint_path)

print("\nSAFETY CHECK:")
print("CLASS_LABEL was NOT used as a predictor.")
print("id was NOT used as a predictor.")
print("RT features were excluded from predictors.")
print("No XGBoost model was loaded or modified.")
print("No production extractor was modified.")
print("No phishing prediction was performed.")

======================================================================
STEP 5L — EMPIRICAL RT FEATURE RULE DISCOVERY
======================================================================

Dataset:
/content/Phishing_Legitimate_full.csv
Shape: (10000, 50)

Candidate predictor count: 42

Constant candidate columns removed:
 - HttpsInHostname

======================================================================
TARGET RT: SubdomainLevelRT
======================================================================

Distribution:
{-1: 100, 0: 234, 1: 9666}
depth=1 | CV accuracy=0.985900 +/- 0.000800
depth=2 | CV accuracy=0.995600 +/- 0.001158
depth=3 | CV accuracy=0.995600 +/- 0.001158
depth=4 | CV accuracy=0.995700 +/- 0.001077
depth=5 | CV accuracy=0.996200 +/- 0.000980
depth=6 | CV accuracy=0.996300 +/- 0.001400

Top features used by best tree:
  SubdomainLevel                               : 0.931002
  NumNumericChars                              : 0.022608
  NumDots                                      : 0.011701
  HostnameLength                               : 0.010170
  ExtFormAction                                : 0.009908
  MissingTitle                                 : 0.009179
  PctExtHyperlinks                             : 0.002538
  PctNullSelfRedirectHyperlinks                : 0.001739
  PathLength                                   : 0.000624
  QueryLength                                  : 0.000531

======================================================================
TARGET RT: PctExtResourceUrlsRT
======================================================================

Distribution:
{-1: 2808, 0: 851, 1: 6341}
depth=1 | CV accuracy=0.842700 +/- 0.004434
depth=2 | CV accuracy=0.845300 +/- 0.004411
depth=3 | CV accuracy=0.846700 +/- 0.004297
depth=4 | CV accuracy=0.875800 +/- 0.006306
depth=5 | CV accuracy=0.883200 +/- 0.008310
depth=6 | CV accuracy=0.881100 +/- 0.009346

Top features used by best tree:
  PctExtResourceUrls                           : 0.838162
  PctExtHyperlinks                             : 0.130487
  IframeOrFrame                                : 0.012143
  PctNullSelfRedirectHyperlinks                : 0.010636
  MissingTitle                                 : 0.005091
  NumDash                                      : 0.001410
  NumDots                                      : 0.001042
  PathLength                                   : 0.000733
  NumSensitiveWords                            : 0.000296

======================================================================
TARGET RT: AbnormalExtFormActionR
======================================================================

Distribution:
{-1: 537, 0: 994, 1: 8469}
depth=1 | CV accuracy=0.946300 +/- 0.000245
depth=2 | CV accuracy=0.997600 +/- 0.000860
depth=3 | CV accuracy=0.997800 +/- 0.001030
depth=4 | CV accuracy=0.998000 +/- 0.001183
depth=5 | CV accuracy=0.997900 +/- 0.001319
depth=6 | CV accuracy=0.998100 +/- 0.001393

Top features used by best tree:
  ExtFormAction                                : 0.627175
  AbnormalFormAction                           : 0.366311
  PctExtHyperlinks                             : 0.002388
  PctExtResourceUrls                           : 0.002030
  UrlLength                                    : 0.001346
  QueryLength                                  : 0.000638
  ExtFavicon                                   : 0.000112

======================================================================
TARGET RT: ExtMetaScriptLinkRT
======================================================================

Distribution:
{-1: 2139, 0: 3988, 1: 3873}
depth=1 | CV accuracy=0.656900 +/- 0.008363
depth=2 | CV accuracy=0.818300 +/- 0.006462
depth=3 | CV accuracy=0.835800 +/- 0.004864
depth=4 | CV accuracy=0.851800 +/- 0.003516
depth=5 | CV accuracy=0.855000 +/- 0.005983
depth=6 | CV accuracy=0.859500 +/- 0.005413

Top features used by best tree:
  PctExtResourceUrls                           : 0.816335
  PctNullSelfRedirectHyperlinks                : 0.060647
  IframeOrFrame                                : 0.026785
  IpAddress                                    : 0.021349
  PctExtHyperlinks                             : 0.019323
  FrequentDomainNameMismatch                   : 0.016009
  MissingTitle                                 : 0.013710
  PathLength                                   : 0.004879
  NumNumericChars                              : 0.004541
  NumDash                                      : 0.004242

======================================================================
TARGET RT: PctExtNullSelfRedirectHyperlinksRT
======================================================================

Distribution:
{-1: 2953, 0: 953, 1: 6094}
depth=1 | CV accuracy=0.787100 +/- 0.001068
depth=2 | CV accuracy=0.971500 +/- 0.003347
depth=3 | CV accuracy=0.982600 +/- 0.004283
depth=4 | CV accuracy=0.984200 +/- 0.002112
depth=5 | CV accuracy=0.989700 +/- 0.000812
depth=6 | CV accuracy=0.991200 +/- 0.001249

Top features used by best tree:
  PctExtHyperlinks                             : 0.565079
  PctNullSelfRedirectHyperlinks                : 0.434866
  PathLength                                   : 0.000055

======================================================================
STEP 5L COMPLETE
======================================================================

RT reproduction summary:
SubdomainLevelRT                              | best depth=6 | CV accuracy=0.996300
PctExtResourceUrlsRT                          | best depth=5 | CV accuracy=0.883200
AbnormalExtFormActionR                        | best depth=6 | CV accuracy=0.998100
ExtMetaScriptLinkRT                           | best depth=6 | CV accuracy=0.859500
PctExtNullSelfRedirectHyperlinksRT            | best depth=6 | CV accuracy=0.991200

Checkpoint:
/content/drive/MyDrive/PhishShield_AI/checkpoints/step_5L_rt_rule_discovery.json

SAFETY CHECK:
CLASS_LABEL was NOT used as a predictor.
id was NOT used as a predictor.
RT features were excluded from predictors.
No XGBoost model was loaded or modified.
No production extractor was modified.
No phishing prediction was performed.

In [ ]:
# ============================================================
# STEP 5J — SAFE CHECKPOINT SAVE
# ============================================================

import json
import numpy as np

def make_json_serializable(obj):
    """Convert NumPy/Pandas values into native Python JSON types."""

    if isinstance(obj, dict):
        return {
            str(k): make_json_serializable(v)
            for k, v in obj.items()
        }

    if isinstance(obj, (list, tuple)):
        return [make_json_serializable(v) for v in obj]

    if isinstance(obj, np.integer):
        return int(obj)

    if isinstance(obj, np.floating):
        return float(obj)

    if isinstance(obj, np.bool_):
        return bool(obj)

    if isinstance(obj, np.ndarray):
        return obj.tolist()

    return obj


# Convert checkpoint completely to native Python types
checkpoint_safe = make_json_serializable(checkpoint)

# Save checkpoint
checkpoint_path = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints/"
    "step_5J_html_extractor_test.json"
)

with open(checkpoint_path, "w") as f:
    json.dump(checkpoint_safe, f, indent=2)

print("=" * 60)
print("STEP 5J CHECKPOINT SAVED SUCCESSFULLY")
print("=" * 60)
print(f"Checkpoint: {checkpoint_path}")

# Verify that the file can actually be read back
with open(checkpoint_path, "r") as f:
    verified_checkpoint = json.load(f)

print("[PASS] JSON checkpoint verified successfully.")
print(f"Top-level keys: {list(verified_checkpoint.keys())}")

============================================================
STEP 5J CHECKPOINT SAVED SUCCESSFULLY
============================================================
Checkpoint: /content/drive/MyDrive/PhishShield_AI/checkpoints/step_5J_html_extractor_test.json
[PASS] JSON checkpoint verified successfully.
Top-level keys: ['stage', 'dataset', 'purpose', 'class_label_used', 'id_used', 'model_loaded', 'training_performed', 'prediction_performed', 'results']

In [ ]:
# ============================================================
# STEP 5K — LIVE FEATURE EXTRACTOR VALIDATION
# ============================================================
# Purpose:
#   Validate URL + HTML feature extraction on multiple
#   real-world URLs before connecting to the frozen XGBoost model.
#
# IMPORTANT:
#   - NO training
#   - NO retraining
#   - NO model modification
#   - NO prediction
#   - NO silent zero filling
# ============================================================

import json
import os
import traceback

# ------------------------------------------------------------
# Test URLs
# ------------------------------------------------------------

TEST_URLS = {
    "Google": "https://www.google.com",
    "Microsoft": "https://www.microsoft.com",
    "GitHub": "https://github.com",
    "Python": "https://www.python.org"
}

# ------------------------------------------------------------
# Expected 47-feature contract
# ------------------------------------------------------------

EXPECTED_FEATURES = [
    "NumDots",
    "SubdomainLevel",
    "PathLevel",
    "UrlLength",
    "NumDash",
    "NumDashInHostname",
    "AtSymbol",
    "TildeSymbol",
    "NumUnderscore",
    "NumPercent",
    "NumQueryComponents",
    "NumAmpersand",
    "NumHash",
    "NumNumericChars",
    "NoHttps",
    "RandomString",
    "IpAddress",
    "DomainInSubdomains",
    "DomainInPaths",
    "HostnameLength",
    "PathLength",
    "QueryLength",
    "DoubleSlashInPath",
    "NumSensitiveWords",
    "EmbeddedBrandName",
    "PctExtHyperlinks",
    "PctExtResourceUrls",
    "ExtFavicon",
    "InsecureForms",
    "RelativeFormAction",
    "ExtFormAction",
    "AbnormalFormAction",
    "PctNullSelfRedirectHyperlinks",
    "FrequentDomainNameMismatch",
    "FakeLinkInStatusBar",
    "RightClickDisabled",
    "PopUpWindow",
    "SubmitInfoToEmail",
    "IframeOrFrame",
    "MissingTitle",
    "ImagesOnlyInForm",
    "SubdomainLevelRT",
    "UrlLengthRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

# ------------------------------------------------------------
# Known unresolved features from Step 5I / 5J
# ------------------------------------------------------------

KNOWN_UNRESOLVED = {
    "SubdomainLevelRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
}

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

validation_results = {}

print("=" * 70)
print("STEP 5K — LIVE FEATURE EXTRACTOR VALIDATION")
print("=" * 70)

for site_name, url in TEST_URLS.items():

    print(f"\n{'-' * 70}")
    print(f"Testing: {site_name}")
    print(f"URL    : {url}")
    print("-" * 70)

    try:
        # ----------------------------------------------------
        # URL features
        # ----------------------------------------------------
        url_features = extract_url_features(url)

        # ----------------------------------------------------
        # HTML fetch
        # ----------------------------------------------------
        html = fetch_html(url)

        if html is None or len(html.strip()) == 0:
            raise RuntimeError("HTML fetch returned empty content.")

        # ----------------------------------------------------
        # HTML features
        # ----------------------------------------------------
        html_features = extract_html_features(
            html,
            url
        )

        # ----------------------------------------------------
        # Merge WITHOUT overwriting existing values
        # ----------------------------------------------------
        combined = {}

        for key, value in url_features.items():
            combined[key] = value

        for key, value in html_features.items():

            if key in combined and combined[key] is not None:
                print(f"[WARNING] Duplicate feature preserved from URL extractor: {key}")
            else:
                combined[key] = value

        # ----------------------------------------------------
        # Check feature contract
        # ----------------------------------------------------
        generated_features = set(combined.keys())
        expected_features = set(EXPECTED_FEATURES)

        missing = sorted(expected_features - generated_features)
        extra = sorted(generated_features - expected_features)

        none_features = sorted([
            key for key in EXPECTED_FEATURES
            if key in combined and combined[key] is None
        ])

        generated_count = len(generated_features)

        # ----------------------------------------------------
        # Check ordering separately
        # ----------------------------------------------------
        ordered_vector = [
            combined.get(feature)
            for feature in EXPECTED_FEATURES
        ]

        order_length_ok = len(ordered_vector) == 47

        # ----------------------------------------------------
        # Report
        # ----------------------------------------------------
        print(f"HTML bytes/chars fetched : {len(html)}")
        print(f"Generated feature keys   : {generated_count}")
        print(f"Expected feature keys    : 47")
        print(f"Missing features         : {len(missing)}")
        print(f"Extra features           : {len(extra)}")
        print(f"None-valued features     : {len(none_features)}")
        print(f"47-feature vector length  : {len(ordered_vector)}")

        if missing:
            print("\n[MISSING]")
            for feature in missing:
                print(f"  - {feature}")

        if extra:
            print("\n[EXTRA]")
            for feature in extra:
                print(f"  - {feature}")

        if none_features:
            print("\n[NONE-VALUED FEATURES]")
            for feature in none_features:
                marker = " [KNOWN UNRESOLVED]" if feature in KNOWN_UNRESOLVED else ""
                print(f"  - {feature}{marker}")

        # ----------------------------------------------------
        # Important safety checks
        # ----------------------------------------------------

        unexpected_none = sorted(
            set(none_features) - KNOWN_UNRESOLVED
        )

        if unexpected_none:
            print("\n[WARNING] Unexpected None-valued features:")
            for feature in unexpected_none:
                print(f"  - {feature}")

        if (
            generated_count == 47
            and
            len(missing) == 0
            and
            len(extra) == 0
            and
            order_length_ok
        ):
            print("\n[PASS] Exact 47-feature contract generated.")

        else:
            print("\n[FAIL] Exact 47-feature contract NOT satisfied.")

        validation_results[site_name] = {
            "url": url,
            "html_length": len(html),
            "generated_feature_count": generated_count,
            "expected_feature_count": 47,
            "missing_features": missing,
            "extra_features": extra,
            "none_features": none_features,
            "unexpected_none_features": unexpected_none,
            "vector_length": len(ordered_vector),
            "exact_contract": (
                generated_count == 47
                and len(missing) == 0
                and len(extra) == 0
                and order_length_ok
            )
        }

    except Exception as e:

        print("\n[ERROR]")
        print(type(e).__name__, ":", str(e))

        traceback.print_exc(limit=2)

        validation_results[site_name] = {
            "url": url,
            "error": type(e).__name__,
            "error_message": str(e)
        }


# ============================================================
# SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("STEP 5K SUMMARY")
print("=" * 70)

for site_name, result in validation_results.items():

    if "error" in result:
        print(f"[ERROR] {site_name}")
        continue

    status = "PASS" if result["exact_contract"] else "CHECK"

    print(
        f"[{status}] {site_name}: "
        f"{result['generated_feature_count']}/47 features, "
        f"None={len(result['none_features'])}, "
        f"Missing={len(result['missing_features'])}"
    )


# ============================================================
# DRIVE CHECKPOINT
# ============================================================

checkpoint_dir = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints"
)

os.makedirs(checkpoint_dir, exist_ok=True)

checkpoint_path = os.path.join(
    checkpoint_dir,
    "step_5K_live_feature_validation.json"
)

checkpoint = {
    "stage": "5K",
    "purpose": "Live validation of URL and HTML feature extractor",
    "training_performed": False,
    "retraining_performed": False,
    "prediction_performed": False,
    "model_modified": False,
    "expected_feature_count": 47,
    "known_unresolved_features": sorted(KNOWN_UNRESOLVED),
    "test_urls": TEST_URLS,
    "results": validation_results
}


# Convert NumPy values if any appear
def make_json_serializable(obj):

    import numpy as np

    if isinstance(obj, dict):
        return {
            str(k): make_json_serializable(v)
            for k, v in obj.items()
        }

    if isinstance(obj, (list, tuple)):
        return [
            make_json_serializable(v)
            for v in obj
        ]

    if isinstance(obj, np.integer):
        return int(obj)

    if isinstance(obj, np.floating):
        return float(obj)

    if isinstance(obj, np.bool_):
        return bool(obj)

    if isinstance(obj, np.ndarray):
        return obj.tolist()

    return obj


checkpoint_safe = make_json_serializable(checkpoint)

with open(checkpoint_path, "w") as f:
    json.dump(
        checkpoint_safe,
        f,
        indent=2
    )


# ------------------------------------------------------------
# Verify checkpoint
# ------------------------------------------------------------

with open(checkpoint_path, "r") as f:
    verified_checkpoint = json.load(f)

print("\n" + "=" * 70)
print("STEP 5K CHECKPOINT SAVED")
print("=" * 70)
print(f"Checkpoint: {checkpoint_path}")
print("[PASS] Checkpoint JSON verified successfully.")
print("=" * 70)

======================================================================
STEP 5K — LIVE FEATURE EXTRACTOR VALIDATION
======================================================================

----------------------------------------------------------------------
Testing: Google
URL    : https://www.google.com
----------------------------------------------------------------------

[ERROR]
AttributeError : 'tuple' object has no attribute 'strip'

----------------------------------------------------------------------
Testing: Microsoft
URL    : https://www.microsoft.com
----------------------------------------------------------------------

Traceback (most recent call last):
  File "/tmp/ipykernel_580/334518480.py", line 125, in <cell line: 0>
    if html is None or len(html.strip()) == 0:
                           ^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'strip'
Traceback (most recent call last):
  File "/tmp/ipykernel_580/334518480.py", line 125, in <cell line: 0>
    if html is None or len(html.strip()) == 0:
                           ^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'strip'

[ERROR]
AttributeError : 'tuple' object has no attribute 'strip'

----------------------------------------------------------------------
Testing: GitHub
URL    : https://github.com
----------------------------------------------------------------------

[ERROR]
AttributeError : 'tuple' object has no attribute 'strip'

----------------------------------------------------------------------
Testing: Python
URL    : https://www.python.org
----------------------------------------------------------------------

[ERROR]
AttributeError : 'tuple' object has no attribute 'strip'

======================================================================
STEP 5K SUMMARY
======================================================================
[ERROR] Google
[ERROR] Microsoft
[ERROR] GitHub
[ERROR] Python

======================================================================
STEP 5K CHECKPOINT SAVED
======================================================================
Checkpoint: /content/drive/MyDrive/PhishShield_AI/checkpoints/step_5K_live_feature_validation.json
[PASS] Checkpoint JSON verified successfully.
======================================================================

Traceback (most recent call last):
  File "/tmp/ipykernel_580/334518480.py", line 125, in <cell line: 0>
    if html is None or len(html.strip()) == 0:
                           ^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'strip'
Traceback (most recent call last):
  File "/tmp/ipykernel_580/334518480.py", line 125, in <cell line: 0>
    if html is None or len(html.strip()) == 0:
                           ^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'strip'

In [ ]:
# ============================================================
# STEP 5K-A — INSPECT fetch_html() RETURN CONTRACT
# ============================================================

TEST_URL = "https://www.google.com"

print("=" * 70)
print("STEP 5K-A — fetch_html() RETURN CONTRACT")
print("=" * 70)

try:
    result = fetch_html(TEST_URL)

    print("Return type:", type(result))
    print("Is tuple  :", isinstance(result, tuple))

    if isinstance(result, tuple):
        print("Tuple length:", len(result))

        for i, item in enumerate(result):
            print(f"\nTuple item [{i}]")
            print("  Type :", type(item))

            if isinstance(item, str):
                print("  Length:", len(item))
                print("  Preview:", repr(item[:200]))
            else:
                print("  Value :", repr(item))

    elif isinstance(result, str):
        print("String length:", len(result))
        print("Preview:", repr(result[:200]))

    else:
        print("Value:", repr(result))

except Exception as e:
    print("\n[ERROR]")
    print(type(e).__name__, ":", str(e))

print("\n" + "=" * 70)
print("END STEP 5K-A")
print("=" * 70)

======================================================================
STEP 5K-A — fetch_html() RETURN CONTRACT
======================================================================
Return type: <class 'tuple'>
Is tuple  : True
Tuple length: 2

Tuple item [0]
  Type : <class 'str'>
  Length: 23
  Preview: 'https://www.google.com/'

Tuple item [1]
  Type : <class 'str'>
  Length: 223941
  Preview: '<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta charset="UTF-8"><meta content="origin" name="referrer"><link href="//www.gstatic.com/images/branding/search'

======================================================================
END STEP 5K-A
======================================================================

In [ ]:
# ============================================================
# STEP 5K — LIVE FEATURE EXTRACTOR VALIDATION
# CORRECTED FOR fetch_html() -> (final_url, html)
# ============================================================

import json
import os
import traceback
import numpy as np

# ------------------------------------------------------------
# Test URLs
# ------------------------------------------------------------

TEST_URLS = {
    "Google": "https://www.google.com",
    "Microsoft": "https://www.microsoft.com",
    "GitHub": "https://github.com",
    "Python": "https://www.python.org"
}

# ------------------------------------------------------------
# Frozen 47-feature contract
# ------------------------------------------------------------

EXPECTED_FEATURES = [
    "NumDots",
    "SubdomainLevel",
    "PathLevel",
    "UrlLength",
    "NumDash",
    "NumDashInHostname",
    "AtSymbol",
    "TildeSymbol",
    "NumUnderscore",
    "NumPercent",
    "NumQueryComponents",
    "NumAmpersand",
    "NumHash",
    "NumNumericChars",
    "NoHttps",
    "RandomString",
    "IpAddress",
    "DomainInSubdomains",
    "DomainInPaths",
    "HostnameLength",
    "PathLength",
    "QueryLength",
    "DoubleSlashInPath",
    "NumSensitiveWords",
    "EmbeddedBrandName",
    "PctExtHyperlinks",
    "PctExtResourceUrls",
    "ExtFavicon",
    "InsecureForms",
    "RelativeFormAction",
    "ExtFormAction",
    "AbnormalFormAction",
    "PctNullSelfRedirectHyperlinks",
    "FrequentDomainNameMismatch",
    "FakeLinkInStatusBar",
    "RightClickDisabled",
    "PopUpWindow",
    "SubmitInfoToEmail",
    "IframeOrFrame",
    "MissingTitle",
    "ImagesOnlyInForm",
    "SubdomainLevelRT",
    "UrlLengthRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

# ------------------------------------------------------------
# Known unresolved features
# ------------------------------------------------------------

KNOWN_UNRESOLVED = {
    "SubdomainLevelRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
}

# ------------------------------------------------------------
# Results container
# ------------------------------------------------------------

validation_results = {}

print("=" * 70)
print("STEP 5K — LIVE FEATURE EXTRACTOR VALIDATION")
print("=" * 70)

for site_name, url in TEST_URLS.items():

    print(f"\n{'-' * 70}")
    print(f"Testing: {site_name}")
    print(f"URL    : {url}")
    print("-" * 70)

    try:

        # ----------------------------------------------------
        # URL features
        # ----------------------------------------------------

        url_features = extract_url_features(url)

        # ----------------------------------------------------
        # IMPORTANT:
        # fetch_html() returns:
        #     (final_url, html)
        # ----------------------------------------------------

        final_url, html = fetch_html(url)

        if html is None or not isinstance(html, str):
            raise RuntimeError(
                f"HTML response is invalid. "
                f"Received type: {type(html)}"
            )

        if len(html.strip()) == 0:
            raise RuntimeError("HTML fetch returned empty content.")

        # ----------------------------------------------------
        # HTML features
        # ----------------------------------------------------

        html_features = extract_html_features(
            html,
            final_url
        )

        # ----------------------------------------------------
        # Merge URL + HTML features
        # ----------------------------------------------------

        combined = {}

        for key, value in url_features.items():
            combined[key] = value

        for key, value in html_features.items():

            if key in combined:
                if combined[key] is not None:
                    print(
                        f"[WARNING] Duplicate feature: {key} "
                        f"(URL value preserved)"
                    )
                    continue

            combined[key] = value

        # ----------------------------------------------------
        # Contract validation
        # ----------------------------------------------------

        generated_features = set(combined.keys())
        expected_features = set(EXPECTED_FEATURES)

        missing = sorted(
            expected_features - generated_features
        )

        extra = sorted(
            generated_features - expected_features
        )

        none_features = sorted([
            feature
            for feature in EXPECTED_FEATURES
            if combined.get(feature) is None
        ])

        unexpected_none = sorted(
            set(none_features) - KNOWN_UNRESOLVED
        )

        # ----------------------------------------------------
        # Ordered 47-feature vector
        # ----------------------------------------------------

        ordered_vector = [
            combined.get(feature)
            for feature in EXPECTED_FEATURES
        ]

        # ----------------------------------------------------
        # Print results
        # ----------------------------------------------------

        print(f"Final URL               : {final_url}")
        print(f"HTML characters         : {len(html)}")
        print(f"Generated feature keys  : {len(generated_features)}")
        print(f"Expected feature keys   : 47")
        print(f"Missing features        : {len(missing)}")
        print(f"Extra features          : {len(extra)}")
        print(f"None-valued features    : {len(none_features)}")
        print(f"Vector length           : {len(ordered_vector)}")

        if missing:
            print("\n[MISSING FEATURES]")
            for feature in missing:
                print(f"  - {feature}")

        if extra:
            print("\n[EXTRA FEATURES]")
            for feature in extra:
                print(f"  - {feature}")

        if none_features:
            print("\n[NONE-VALUED FEATURES]")
            for feature in none_features:

                if feature in KNOWN_UNRESOLVED:
                    print(
                        f"  - {feature} "
                        f"[KNOWN UNRESOLVED]"
                    )
                else:
                    print(
                        f"  - {feature} "
                        f"[UNEXPECTED]"
                    )

        if unexpected_none:
            print("\n[WARNING] Unexpected None values:")
            for feature in unexpected_none:
                print(f"  - {feature}")

        exact_contract = (
            len(generated_features) == 47
            and len(missing) == 0
            and len(extra) == 0
            and len(ordered_vector) == 47
        )

        if exact_contract:
            print(
                "\n[PASS] Exact 47-feature KEY contract generated."
            )
        else:
            print(
                "\n[CHECK] 47-feature contract needs further work."
            )

        # ----------------------------------------------------
        # Save result
        # ----------------------------------------------------

        validation_results[site_name] = {
            "requested_url": url,
            "final_url": final_url,
            "html_length": len(html),
            "generated_feature_count": len(generated_features),
            "expected_feature_count": 47,
            "missing_features": missing,
            "extra_features": extra,
            "none_features": none_features,
            "unexpected_none_features": unexpected_none,
            "vector_length": len(ordered_vector),
            "exact_contract": exact_contract
        }

    except Exception as e:

        print("\n[ERROR]")
        print(type(e).__name__, ":", str(e))
        traceback.print_exc(limit=2)

        validation_results[site_name] = {
            "requested_url": url,
            "error": type(e).__name__,
            "error_message": str(e)
        }


# ============================================================
# SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("STEP 5K SUMMARY")
print("=" * 70)

for site_name, result in validation_results.items():

    if "error" in result:
        print(f"[ERROR] {site_name}")
    else:
        print(
            f"[{'PASS' if result['exact_contract'] else 'CHECK'}] "
            f"{site_name}: "
            f"{result['generated_feature_count']}/47 keys, "
            f"None={len(result['none_features'])}, "
            f"Missing={len(result['missing_features'])}"
        )


# ============================================================
# DRIVE CHECKPOINT
# ============================================================

checkpoint_dir = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints"
)

os.makedirs(checkpoint_dir, exist_ok=True)

checkpoint_path = os.path.join(
    checkpoint_dir,
    "step_5K_live_feature_validation.json"
)

checkpoint = {
    "stage": "5K",
    "purpose": (
        "Live validation of URL and HTML feature extractor"
    ),
    "training_performed": False,
    "retraining_performed": False,
    "prediction_performed": False,
    "model_modified": False,
    "expected_feature_count": 47,
    "known_unresolved_features": sorted(
        KNOWN_UNRESOLVED
    ),
    "fetch_html_contract": "(final_url, html)",
    "test_urls": TEST_URLS,
    "results": validation_results
}


# ------------------------------------------------------------
# Safe JSON conversion
# ------------------------------------------------------------

def make_json_serializable(obj):

    if isinstance(obj, dict):
        return {
            str(k): make_json_serializable(v)
            for k, v in obj.items()
        }

    if isinstance(obj, (list, tuple)):
        return [
            make_json_serializable(v)
            for v in obj
        ]

    if isinstance(obj, np.integer):
        return int(obj)

    if isinstance(obj, np.floating):
        return float(obj)

    if isinstance(obj, np.bool_):
        return bool(obj)

    if isinstance(obj, np.ndarray):
        return obj.tolist()

    return obj


checkpoint_safe = make_json_serializable(checkpoint)

with open(checkpoint_path, "w") as f:
    json.dump(
        checkpoint_safe,
        f,
        indent=2
    )


# ------------------------------------------------------------
# Verify checkpoint
# ------------------------------------------------------------

with open(checkpoint_path, "r") as f:
    verified_checkpoint = json.load(f)

print("\n" + "=" * 70)
print("STEP 5K CHECKPOINT SAVED")
print("=" * 70)
print(f"Checkpoint: {checkpoint_path}")
print("[PASS] Checkpoint JSON verified successfully.")
print("=" * 70)

======================================================================
STEP 5K — LIVE FEATURE EXTRACTOR VALIDATION
======================================================================

----------------------------------------------------------------------
Testing: Google
URL    : https://www.google.com
----------------------------------------------------------------------
Final URL               : https://www.google.com/
HTML characters         : 225327
Generated feature keys  : 21
Expected feature keys   : 47
Missing features        : 31
Extra features          : 5
None-valued features    : 31
Vector length           : 47

[MISSING FEATURES]
  - AbnormalExtFormActionR
  - AtSymbol
  - DomainInPaths
  - DomainInSubdomains
  - DoubleSlashInPath
  - EmbeddedBrandName
  - ExtMetaScriptLinkRT
  - HostnameLength
  - IpAddress
  - NoHttps
  - NumAmpersand
  - NumDash
  - NumDashInHostname
  - NumDots
  - NumHash
  - NumNumericChars
  - NumPercent
  - NumQueryComponents
  - NumSensitiveWords
  - NumUnderscore
  - PathLength
  - PathLevel
  - PctExtNullSelfRedirectHyperlinksRT
  - PctExtResourceUrlsRT
  - QueryLength
  - RandomString
  - SubdomainLevel
  - SubdomainLevelRT
  - TildeSymbol
  - UrlLength
  - UrlLengthRT

[EXTRA FEATURES]
  - features
  - missing_features
  - normalized_url
  - unknown_features
  - url

[NONE-VALUED FEATURES]
  - AbnormalExtFormActionR [KNOWN UNRESOLVED]
  - AtSymbol [UNEXPECTED]
  - DomainInPaths [UNEXPECTED]
  - DomainInSubdomains [UNEXPECTED]
  - DoubleSlashInPath [UNEXPECTED]
  - EmbeddedBrandName [UNEXPECTED]
  - ExtMetaScriptLinkRT [KNOWN UNRESOLVED]
  - HostnameLength [UNEXPECTED]
  - IpAddress [UNEXPECTED]
  - NoHttps [UNEXPECTED]
  - NumAmpersand [UNEXPECTED]
  - NumDash [UNEXPECTED]
  - NumDashInHostname [UNEXPECTED]
  - NumDots [UNEXPECTED]
  - NumHash [UNEXPECTED]
  - NumNumericChars [UNEXPECTED]
  - NumPercent [UNEXPECTED]
  - NumQueryComponents [UNEXPECTED]
  - NumSensitiveWords [UNEXPECTED]
  - NumUnderscore [UNEXPECTED]
  - PathLength [UNEXPECTED]
  - PathLevel [UNEXPECTED]
  - PctExtNullSelfRedirectHyperlinksRT [KNOWN UNRESOLVED]
  - PctExtResourceUrlsRT [KNOWN UNRESOLVED]
  - QueryLength [UNEXPECTED]
  - RandomString [UNEXPECTED]
  - SubdomainLevel [UNEXPECTED]
  - SubdomainLevelRT [KNOWN UNRESOLVED]
  - TildeSymbol [UNEXPECTED]
  - UrlLength [UNEXPECTED]
  - UrlLengthRT [UNEXPECTED]

[WARNING] Unexpected None values:
  - AtSymbol
  - DomainInPaths
  - DomainInSubdomains
  - DoubleSlashInPath
  - EmbeddedBrandName
  - HostnameLength
  - IpAddress
  - NoHttps
  - NumAmpersand
  - NumDash
  - NumDashInHostname
  - NumDots
  - NumHash
  - NumNumericChars
  - NumPercent
  - NumQueryComponents
  - NumSensitiveWords
  - NumUnderscore
  - PathLength
  - PathLevel
  - QueryLength
  - RandomString
  - SubdomainLevel
  - TildeSymbol
  - UrlLength
  - UrlLengthRT

[CHECK] 47-feature contract needs further work.

----------------------------------------------------------------------
Testing: Microsoft
URL    : https://www.microsoft.com
----------------------------------------------------------------------
Final URL               : https://www.microsoft.com/
HTML characters         : 201253
Generated feature keys  : 21
Expected feature keys   : 47
Missing features        : 31
Extra features          : 5
None-valued features    : 31
Vector length           : 47

[MISSING FEATURES]
  - AbnormalExtFormActionR
  - AtSymbol
  - DomainInPaths
  - DomainInSubdomains
  - DoubleSlashInPath
  - EmbeddedBrandName
  - ExtMetaScriptLinkRT
  - HostnameLength
  - IpAddress
  - NoHttps
  - NumAmpersand
  - NumDash
  - NumDashInHostname
  - NumDots
  - NumHash
  - NumNumericChars
  - NumPercent
  - NumQueryComponents
  - NumSensitiveWords
  - NumUnderscore
  - PathLength
  - PathLevel
  - PctExtNullSelfRedirectHyperlinksRT
  - PctExtResourceUrlsRT
  - QueryLength
  - RandomString
  - SubdomainLevel
  - SubdomainLevelRT
  - TildeSymbol
  - UrlLength
  - UrlLengthRT

[EXTRA FEATURES]
  - features
  - missing_features
  - normalized_url
  - unknown_features
  - url

[NONE-VALUED FEATURES]
  - AbnormalExtFormActionR [KNOWN UNRESOLVED]
  - AtSymbol [UNEXPECTED]
  - DomainInPaths [UNEXPECTED]
  - DomainInSubdomains [UNEXPECTED]
  - DoubleSlashInPath [UNEXPECTED]
  - EmbeddedBrandName [UNEXPECTED]
  - ExtMetaScriptLinkRT [KNOWN UNRESOLVED]
  - HostnameLength [UNEXPECTED]
  - IpAddress [UNEXPECTED]
  - NoHttps [UNEXPECTED]
  - NumAmpersand [UNEXPECTED]
  - NumDash [UNEXPECTED]
  - NumDashInHostname [UNEXPECTED]
  - NumDots [UNEXPECTED]
  - NumHash [UNEXPECTED]
  - NumNumericChars [UNEXPECTED]
  - NumPercent [UNEXPECTED]
  - NumQueryComponents [UNEXPECTED]
  - NumSensitiveWords [UNEXPECTED]
  - NumUnderscore [UNEXPECTED]
  - PathLength [UNEXPECTED]
  - PathLevel [UNEXPECTED]
  - PctExtNullSelfRedirectHyperlinksRT [KNOWN UNRESOLVED]
  - PctExtResourceUrlsRT [KNOWN UNRESOLVED]
  - QueryLength [UNEXPECTED]
  - RandomString [UNEXPECTED]
  - SubdomainLevel [UNEXPECTED]
  - SubdomainLevelRT [KNOWN UNRESOLVED]
  - TildeSymbol [UNEXPECTED]
  - UrlLength [UNEXPECTED]
  - UrlLengthRT [UNEXPECTED]

[WARNING] Unexpected None values:
  - AtSymbol
  - DomainInPaths
  - DomainInSubdomains
  - DoubleSlashInPath
  - EmbeddedBrandName
  - HostnameLength
  - IpAddress
  - NoHttps
  - NumAmpersand
  - NumDash
  - NumDashInHostname
  - NumDots
  - NumHash
  - NumNumericChars
  - NumPercent
  - NumQueryComponents
  - NumSensitiveWords
  - NumUnderscore
  - PathLength
  - PathLevel
  - QueryLength
  - RandomString
  - SubdomainLevel
  - TildeSymbol
  - UrlLength
  - UrlLengthRT

[CHECK] 47-feature contract needs further work.

----------------------------------------------------------------------
Testing: GitHub
URL    : https://github.com
----------------------------------------------------------------------
Final URL               : https://github.com/
HTML characters         : 573358
Generated feature keys  : 21
Expected feature keys   : 47
Missing features        : 31
Extra features          : 5
None-valued features    : 31
Vector length           : 47

[MISSING FEATURES]
  - AbnormalExtFormActionR
  - AtSymbol
  - DomainInPaths
  - DomainInSubdomains
  - DoubleSlashInPath
  - EmbeddedBrandName
  - ExtMetaScriptLinkRT
  - HostnameLength
  - IpAddress
  - NoHttps
  - NumAmpersand
  - NumDash
  - NumDashInHostname
  - NumDots
  - NumHash
  - NumNumericChars
  - NumPercent
  - NumQueryComponents
  - NumSensitiveWords
  - NumUnderscore
  - PathLength
  - PathLevel
  - PctExtNullSelfRedirectHyperlinksRT
  - PctExtResourceUrlsRT
  - QueryLength
  - RandomString
  - SubdomainLevel
  - SubdomainLevelRT
  - TildeSymbol
  - UrlLength
  - UrlLengthRT

[EXTRA FEATURES]
  - features
  - missing_features
  - normalized_url
  - unknown_features
  - url

[NONE-VALUED FEATURES]
  - AbnormalExtFormActionR [KNOWN UNRESOLVED]
  - AtSymbol [UNEXPECTED]
  - DomainInPaths [UNEXPECTED]
  - DomainInSubdomains [UNEXPECTED]
  - DoubleSlashInPath [UNEXPECTED]
  - EmbeddedBrandName [UNEXPECTED]
  - ExtMetaScriptLinkRT [KNOWN UNRESOLVED]
  - HostnameLength [UNEXPECTED]
  - IpAddress [UNEXPECTED]
  - NoHttps [UNEXPECTED]
  - NumAmpersand [UNEXPECTED]
  - NumDash [UNEXPECTED]
  - NumDashInHostname [UNEXPECTED]
  - NumDots [UNEXPECTED]
  - NumHash [UNEXPECTED]
  - NumNumericChars [UNEXPECTED]
  - NumPercent [UNEXPECTED]
  - NumQueryComponents [UNEXPECTED]
  - NumSensitiveWords [UNEXPECTED]
  - NumUnderscore [UNEXPECTED]
  - PathLength [UNEXPECTED]
  - PathLevel [UNEXPECTED]
  - PctExtNullSelfRedirectHyperlinksRT [KNOWN UNRESOLVED]
  - PctExtResourceUrlsRT [KNOWN UNRESOLVED]
  - QueryLength [UNEXPECTED]
  - RandomString [UNEXPECTED]
  - SubdomainLevel [UNEXPECTED]
  - SubdomainLevelRT [KNOWN UNRESOLVED]
  - TildeSymbol [UNEXPECTED]
  - UrlLength [UNEXPECTED]
  - UrlLengthRT [UNEXPECTED]

[WARNING] Unexpected None values:
  - AtSymbol
  - DomainInPaths
  - DomainInSubdomains
  - DoubleSlashInPath
  - EmbeddedBrandName
  - HostnameLength
  - IpAddress
  - NoHttps
  - NumAmpersand
  - NumDash
  - NumDashInHostname
  - NumDots
  - NumHash
  - NumNumericChars
  - NumPercent
  - NumQueryComponents
  - NumSensitiveWords
  - NumUnderscore
  - PathLength
  - PathLevel
  - QueryLength
  - RandomString
  - SubdomainLevel
  - TildeSymbol
  - UrlLength
  - UrlLengthRT

[CHECK] 47-feature contract needs further work.

----------------------------------------------------------------------
Testing: Python
URL    : https://www.python.org
----------------------------------------------------------------------
Final URL               : https://www.python.org/
HTML characters         : 52291
Generated feature keys  : 21
Expected feature keys   : 47
Missing features        : 31
Extra features          : 5
None-valued features    : 31
Vector length           : 47

[MISSING FEATURES]
  - AbnormalExtFormActionR
  - AtSymbol
  - DomainInPaths
  - DomainInSubdomains
  - DoubleSlashInPath
  - EmbeddedBrandName
  - ExtMetaScriptLinkRT
  - HostnameLength
  - IpAddress
  - NoHttps
  - NumAmpersand
  - NumDash
  - NumDashInHostname
  - NumDots
  - NumHash
  - NumNumericChars
  - NumPercent
  - NumQueryComponents
  - NumSensitiveWords
  - NumUnderscore
  - PathLength
  - PathLevel
  - PctExtNullSelfRedirectHyperlinksRT
  - PctExtResourceUrlsRT
  - QueryLength
  - RandomString
  - SubdomainLevel
  - SubdomainLevelRT
  - TildeSymbol
  - UrlLength
  - UrlLengthRT

[EXTRA FEATURES]
  - features
  - missing_features
  - normalized_url
  - unknown_features
  - url

[NONE-VALUED FEATURES]
  - AbnormalExtFormActionR [KNOWN UNRESOLVED]
  - AtSymbol [UNEXPECTED]
  - DomainInPaths [UNEXPECTED]
  - DomainInSubdomains [UNEXPECTED]
  - DoubleSlashInPath [UNEXPECTED]
  - EmbeddedBrandName [UNEXPECTED]
  - ExtMetaScriptLinkRT [KNOWN UNRESOLVED]
  - HostnameLength [UNEXPECTED]
  - IpAddress [UNEXPECTED]
  - NoHttps [UNEXPECTED]
  - NumAmpersand [UNEXPECTED]
  - NumDash [UNEXPECTED]
  - NumDashInHostname [UNEXPECTED]
  - NumDots [UNEXPECTED]
  - NumHash [UNEXPECTED]
  - NumNumericChars [UNEXPECTED]
  - NumPercent [UNEXPECTED]
  - NumQueryComponents [UNEXPECTED]
  - NumSensitiveWords [UNEXPECTED]
  - NumUnderscore [UNEXPECTED]
  - PathLength [UNEXPECTED]
  - PathLevel [UNEXPECTED]
  - PctExtNullSelfRedirectHyperlinksRT [KNOWN UNRESOLVED]
  - PctExtResourceUrlsRT [KNOWN UNRESOLVED]
  - QueryLength [UNEXPECTED]
  - RandomString [UNEXPECTED]
  - SubdomainLevel [UNEXPECTED]
  - SubdomainLevelRT [KNOWN UNRESOLVED]
  - TildeSymbol [UNEXPECTED]
  - UrlLength [UNEXPECTED]
  - UrlLengthRT [UNEXPECTED]

[WARNING] Unexpected None values:
  - AtSymbol
  - DomainInPaths
  - DomainInSubdomains
  - DoubleSlashInPath
  - EmbeddedBrandName
  - HostnameLength
  - IpAddress
  - NoHttps
  - NumAmpersand
  - NumDash
  - NumDashInHostname
  - NumDots
  - NumHash
  - NumNumericChars
  - NumPercent
  - NumQueryComponents
  - NumSensitiveWords
  - NumUnderscore
  - PathLength
  - PathLevel
  - QueryLength
  - RandomString
  - SubdomainLevel
  - TildeSymbol
  - UrlLength
  - UrlLengthRT

[CHECK] 47-feature contract needs further work.

======================================================================
STEP 5K SUMMARY
======================================================================
[CHECK] Google: 21/47 keys, None=31, Missing=31
[CHECK] Microsoft: 21/47 keys, None=31, Missing=31
[CHECK] GitHub: 21/47 keys, None=31, Missing=31
[CHECK] Python: 21/47 keys, None=31, Missing=31

======================================================================
STEP 5K CHECKPOINT SAVED
======================================================================
Checkpoint: /content/drive/MyDrive/PhishShield_AI/checkpoints/step_5K_live_feature_validation.json
[PASS] Checkpoint JSON verified successfully.
======================================================================

In [ ]:
# ============================================================
# STEP 5K-B — INSPECT extract_url_features() RETURN CONTRACT
# ============================================================

TEST_URL = "https://www.google.com"

print("=" * 70)
print("STEP 5K-B — extract_url_features() RETURN CONTRACT")
print("=" * 70)

try:

    result = extract_url_features(TEST_URL)

    print("Return type:", type(result))

    if isinstance(result, dict):

        print("Top-level keys:")
        for key in result.keys():
            print(f"  - {key}")

        print("\nTop-level value types:")

        for key, value in result.items():

            print(f"\n[{key}]")
            print("  Type:", type(value))

            if isinstance(value, dict):

                print("  Number of entries:", len(value))

                print("  First entries:")

                for i, (k, v) in enumerate(value.items()):

                    print(
                        f"    {k}: "
                        f"{repr(v)} "
                        f"(type={type(v).__name__})"
                    )

                    if i >= 9:
                        break

            elif isinstance(value, (list, tuple)):

                print("  Length:", len(value))
                print("  Preview:", repr(value[:10]))

            elif isinstance(value, str):

                print("  Length:", len(value))
                print("  Preview:", repr(value[:200]))

            else:

                print("  Value:", repr(value))

    else:

        print("Unexpected return value:")
        print(repr(result))

except Exception as e:

    print("\n[ERROR]")
    print(type(e).__name__, ":", str(e))

print("\n" + "=" * 70)
print("END STEP 5K-B")
print("=" * 70)

======================================================================
STEP 5K-B — extract_url_features() RETURN CONTRACT
======================================================================
Return type: <class 'dict'>
Top-level keys:
  - url
  - normalized_url
  - features
  - missing_features
  - unknown_features

Top-level value types:

[url]
  Type: <class 'str'>
  Length: 22
  Preview: 'https://www.google.com'

[normalized_url]
  Type: <class 'str'>
  Length: 22
  Preview: 'https://www.google.com'

[features]
  Type: <class 'dict'>
  Number of entries: 47
  First entries:
    NumDots: 2 (type=int)
    SubdomainLevel: 1 (type=int)
    PathLevel: 0 (type=int)
    UrlLength: 22 (type=int)
    NumDash: 0 (type=int)
    NumDashInHostname: 0 (type=int)
    AtSymbol: 0 (type=int)
    TildeSymbol: 0 (type=int)
    NumUnderscore: 0 (type=int)
    NumPercent: 0 (type=int)

[missing_features]
  Type: <class 'list'>
  Length: 0
  Preview: []

[unknown_features]
  Type: <class 'list'>
  Length: 21
  Preview: ['PctExtHyperlinks', 'PctExtResourceUrls', 'ExtFavicon', 'InsecureForms', 'RelativeFormAction', 'ExtFormAction', 'AbnormalFormAction', 'PctNullSelfRedirectHyperlinks', 'FrequentDomainNameMismatch', 'FakeLinkInStatusBar']

======================================================================
END STEP 5K-B
======================================================================

In [ ]:
# ============================================================
# STEP 5K — LIVE FEATURE EXTRACTOR VALIDATION
# FINAL CORRECTED VERSION
# ============================================================
# IMPORTANT:
#   - NO training
#   - NO retraining
#   - NO prediction
#   - NO model modification
# ============================================================

import json
import os
import traceback
import numpy as np

TEST_URLS = {
    "Google": "https://www.google.com",
    "Microsoft": "https://www.microsoft.com",
    "GitHub": "https://github.com",
    "Python": "https://www.python.org"
}

EXPECTED_FEATURES = [
    "NumDots",
    "SubdomainLevel",
    "PathLevel",
    "UrlLength",
    "NumDash",
    "NumDashInHostname",
    "AtSymbol",
    "TildeSymbol",
    "NumUnderscore",
    "NumPercent",
    "NumQueryComponents",
    "NumAmpersand",
    "NumHash",
    "NumNumericChars",
    "NoHttps",
    "RandomString",
    "IpAddress",
    "DomainInSubdomains",
    "DomainInPaths",
    "HostnameLength",
    "PathLength",
    "QueryLength",
    "DoubleSlashInPath",
    "NumSensitiveWords",
    "EmbeddedBrandName",
    "PctExtHyperlinks",
    "PctExtResourceUrls",
    "ExtFavicon",
    "InsecureForms",
    "RelativeFormAction",
    "ExtFormAction",
    "AbnormalFormAction",
    "PctNullSelfRedirectHyperlinks",
    "FrequentDomainNameMismatch",
    "FakeLinkInStatusBar",
    "RightClickDisabled",
    "PopUpWindow",
    "SubmitInfoToEmail",
    "IframeOrFrame",
    "MissingTitle",
    "ImagesOnlyInForm",
    "SubdomainLevelRT",
    "UrlLengthRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

KNOWN_UNRESOLVED = {
    "SubdomainLevelRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
}

validation_results = {}

print("=" * 70)
print("STEP 5K — LIVE FEATURE EXTRACTOR VALIDATION")
print("=" * 70)

for site_name, url in TEST_URLS.items():

    print(f"\n{'-' * 70}")
    print(f"Testing: {site_name}")
    print(f"URL    : {url}")
    print("-" * 70)

    try:

        # ====================================================
        # 1. URL FEATURE EXTRACTION
        # ====================================================

        url_result = extract_url_features(url)

        if not isinstance(url_result, dict):
            raise TypeError(
                "extract_url_features() did not return a dictionary."
            )

        # IMPORTANT:
        # The actual 47 URL features are inside:
        # url_result["features"]
        # ====================================================

        url_features = url_result.get("features")

        if not isinstance(url_features, dict):
            raise TypeError(
                "extract_url_features()['features'] "
                "is not a dictionary."
            )

        url_missing = url_result.get(
            "missing_features",
            []
        )

        url_unknown = url_result.get(
            "unknown_features",
            []
        )

        print(
            f"URL extractor generated : "
            f"{len(url_features)} feature entries"
        )

        print(
            f"URL extractor missing   : "
            f"{len(url_missing)}"
        )

        print(
            f"URL extractor unknown   : "
            f"{len(url_unknown)}"
        )

        # ====================================================
        # 2. FETCH HTML
        # ====================================================

        final_url, html = fetch_html(url)

        if not isinstance(html, str):
            raise TypeError(
                f"HTML must be str, got {type(html)}"
            )

        if len(html.strip()) == 0:
            raise RuntimeError(
                "Fetched HTML is empty."
            )

        print(
            f"Final URL               : {final_url}"
        )

        print(
            f"HTML characters         : {len(html)}"
        )

        # ====================================================
        # 3. HTML FEATURE EXTRACTION
        # ====================================================

        html_features = extract_html_features(
            html,
            final_url
        )

        if not isinstance(html_features, dict):
            raise TypeError(
                "extract_html_features() did not return a dictionary."
            )

        print(
            f"HTML extractor keys     : "
            f"{len(html_features)}"
        )

        # ====================================================
        # 4. MERGE ACTUAL FEATURE DICTIONARIES
        # ====================================================

        combined = {}

        # URL features
        for key, value in url_features.items():
            combined[key] = value

        # HTML features
        duplicate_keys = []

        for key, value in html_features.items():

            if key in combined:
                duplicate_keys.append(key)
                continue

            combined[key] = value

        # ====================================================
        # 5. CONTRACT CHECK
        # ====================================================

        generated = set(combined.keys())
        expected = set(EXPECTED_FEATURES)

        missing = sorted(
            expected - generated
        )

        extra = sorted(
            generated - expected
        )

        none_features = sorted([
            feature
            for feature in EXPECTED_FEATURES
            if combined.get(feature) is None
        ])

        unexpected_none = sorted(
            set(none_features) - KNOWN_UNRESOLVED
        )

        # ====================================================
        # 6. ORDERED VECTOR
        # ====================================================

        ordered_vector = [
            combined.get(feature)
            for feature in EXPECTED_FEATURES
        ]

        # ====================================================
        # 7. REPORT
        # ====================================================

        print(
            f"Combined feature keys   : "
            f"{len(generated)}"
        )

        print(
            f"Expected feature keys   : 47"
        )

        print(
            f"Missing features        : "
            f"{len(missing)}"
        )

        print(
            f"Extra features          : "
            f"{len(extra)}"
        )

        print(
            f"None-valued features    : "
            f"{len(none_features)}"
        )

        print(
            f"Vector length           : "
            f"{len(ordered_vector)}"
        )

        if duplicate_keys:
            print("\n[DUPLICATE KEYS]")
            for key in duplicate_keys:
                print(f"  - {key}")

        if missing:
            print("\n[MISSING FEATURES]")
            for feature in missing:
                print(f"  - {feature}")

        if extra:
            print("\n[EXTRA FEATURES]")
            for feature in extra:
                print(f"  - {feature}")

        if none_features:
            print("\n[NONE-VALUED FEATURES]")

            for feature in none_features:

                if feature in KNOWN_UNRESOLVED:
                    print(
                        f"  - {feature} "
                        f"[KNOWN UNRESOLVED]"
                    )
                else:
                    print(
                        f"  - {feature} "
                        f"[UNEXPECTED]"
                    )

        if unexpected_none:

            print(
                "\n[WARNING] Unexpected None values:"
            )

            for feature in unexpected_none:
                print(f"  - {feature}")

        exact_keys = (
            len(generated) == 47
            and len(missing) == 0
            and len(extra) == 0
            and len(ordered_vector) == 47
        )

        if exact_keys:

            print(
                "\n[PASS] Exact 47-feature KEY contract generated."
            )

        else:

            print(
                "\n[CHECK] Exact 47-feature KEY contract "
                "still needs work."
            )

        # ====================================================
        # 8. SAVE RESULT
        # ====================================================

        validation_results[site_name] = {
            "requested_url": url,
            "final_url": final_url,

            "url_extractor_feature_count": len(
                url_features
            ),

            "url_extractor_missing": url_missing,
            "url_extractor_unknown": url_unknown,

            "html_feature_count": len(
                html_features
            ),

            "combined_feature_count": len(
                generated
            ),

            "expected_feature_count": 47,

            "missing_features": missing,
            "extra_features": extra,

            "none_features": none_features,
            "unexpected_none_features": (
                unexpected_none
            ),

            "vector_length": len(
                ordered_vector
            ),

            "exact_47_feature_keys": exact_keys
        }

    except Exception as e:

        print("\n[ERROR]")
        print(
            type(e).__name__,
            ":",
            str(e)
        )

        traceback.print_exc(limit=2)

        validation_results[site_name] = {
            "requested_url": url,
            "error": type(e).__name__,
            "error_message": str(e)
        }


# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("STEP 5K SUMMARY")
print("=" * 70)

for site_name, result in validation_results.items():

    if "error" in result:

        print(
            f"[ERROR] {site_name}"
        )

    else:

        status = (
            "PASS"
            if result["exact_47_feature_keys"]
            else "CHECK"
        )

        print(
            f"[{status}] {site_name}: "
            f"{result['combined_feature_count']}/47 keys, "
            f"None={len(result['none_features'])}, "
            f"Missing={len(result['missing_features'])}"
        )


# ============================================================
# DRIVE CHECKPOINT
# ============================================================

checkpoint_dir = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints"
)

os.makedirs(
    checkpoint_dir,
    exist_ok=True
)

checkpoint_path = os.path.join(
    checkpoint_dir,
    "step_5K_live_feature_validation.json"
)

checkpoint = {
    "stage": "5K",
    "purpose": (
        "Live validation of URL and HTML feature extractors"
    ),
    "training_performed": False,
    "retraining_performed": False,
    "prediction_performed": False,
    "model_modified": False,

    "expected_feature_count": 47,

    "fetch_html_contract": (
        "(final_url, html)"
    ),

    "url_extractor_contract": (
        "result['features'] contains feature dictionary"
    ),

    "known_unresolved_features": sorted(
        KNOWN_UNRESOLVED
    ),

    "test_urls": TEST_URLS,

    "results": validation_results
}


# ============================================================
# SAFE JSON SERIALIZATION
# ============================================================

def make_json_serializable(obj):

    if isinstance(obj, dict):
        return {
            str(k): make_json_serializable(v)
            for k, v in obj.items()
        }

    if isinstance(obj, (list, tuple)):
        return [
            make_json_serializable(v)
            for v in obj
        ]

    if isinstance(obj, np.integer):
        return int(obj)

    if isinstance(obj, np.floating):
        return float(obj)

    if isinstance(obj, np.bool_):
        return bool(obj)

    if isinstance(obj, np.ndarray):
        return obj.tolist()

    return obj


checkpoint_safe = make_json_serializable(
    checkpoint
)

with open(
    checkpoint_path,
    "w"
) as f:

    json.dump(
        checkpoint_safe,
        f,
        indent=2
    )


# ============================================================
# VERIFY CHECKPOINT
# ============================================================

with open(
    checkpoint_path,
    "r"
) as f:

    verified_checkpoint = json.load(f)

print("\n" + "=" * 70)
print("STEP 5K CHECKPOINT SAVED")
print("=" * 70)

print(
    f"Checkpoint: {checkpoint_path}"
)

print(
    "[PASS] Checkpoint JSON verified successfully."
)

print("=" * 70)

======================================================================
STEP 5K — LIVE FEATURE EXTRACTOR VALIDATION
======================================================================

----------------------------------------------------------------------
Testing: Google
URL    : https://www.google.com
----------------------------------------------------------------------
URL extractor generated : 47 feature entries
URL extractor missing   : 0
URL extractor unknown   : 21
Final URL               : https://www.google.com/
HTML characters         : 223616
HTML extractor keys     : 16
Combined feature keys   : 47
Expected feature keys   : 47
Missing features        : 0
Extra features          : 0
None-valued features    : 21
Vector length           : 47

[DUPLICATE KEYS]
  - PctExtHyperlinks
  - PctExtResourceUrls
  - ExtFavicon
  - InsecureForms
  - RelativeFormAction
  - ExtFormAction
  - AbnormalFormAction
  - PctNullSelfRedirectHyperlinks
  - FrequentDomainNameMismatch
  - FakeLinkInStatusBar
  - RightClickDisabled
  - PopUpWindow
  - SubmitInfoToEmail
  - IframeOrFrame
  - MissingTitle
  - ImagesOnlyInForm

[NONE-VALUED FEATURES]
  - AbnormalExtFormActionR [KNOWN UNRESOLVED]
  - AbnormalFormAction [UNEXPECTED]
  - ExtFavicon [UNEXPECTED]
  - ExtFormAction [UNEXPECTED]
  - ExtMetaScriptLinkRT [KNOWN UNRESOLVED]
  - FakeLinkInStatusBar [UNEXPECTED]
  - FrequentDomainNameMismatch [UNEXPECTED]
  - IframeOrFrame [UNEXPECTED]
  - ImagesOnlyInForm [UNEXPECTED]
  - InsecureForms [UNEXPECTED]
  - MissingTitle [UNEXPECTED]
  - PctExtHyperlinks [UNEXPECTED]
  - PctExtNullSelfRedirectHyperlinksRT [KNOWN UNRESOLVED]
  - PctExtResourceUrls [UNEXPECTED]
  - PctExtResourceUrlsRT [KNOWN UNRESOLVED]
  - PctNullSelfRedirectHyperlinks [UNEXPECTED]
  - PopUpWindow [UNEXPECTED]
  - RelativeFormAction [UNEXPECTED]
  - RightClickDisabled [UNEXPECTED]
  - SubdomainLevelRT [KNOWN UNRESOLVED]
  - SubmitInfoToEmail [UNEXPECTED]

[WARNING] Unexpected None values:
  - AbnormalFormAction
  - ExtFavicon
  - ExtFormAction
  - FakeLinkInStatusBar
  - FrequentDomainNameMismatch
  - IframeOrFrame
  - ImagesOnlyInForm
  - InsecureForms
  - MissingTitle
  - PctExtHyperlinks
  - PctExtResourceUrls
  - PctNullSelfRedirectHyperlinks
  - PopUpWindow
  - RelativeFormAction
  - RightClickDisabled
  - SubmitInfoToEmail

[PASS] Exact 47-feature KEY contract generated.

----------------------------------------------------------------------
Testing: Microsoft
URL    : https://www.microsoft.com
----------------------------------------------------------------------
URL extractor generated : 47 feature entries
URL extractor missing   : 0
URL extractor unknown   : 21
Final URL               : https://www.microsoft.com/
HTML characters         : 201253
HTML extractor keys     : 16
Combined feature keys   : 47
Expected feature keys   : 47
Missing features        : 0
Extra features          : 0
None-valued features    : 21
Vector length           : 47

[DUPLICATE KEYS]
  - PctExtHyperlinks
  - PctExtResourceUrls
  - ExtFavicon
  - InsecureForms
  - RelativeFormAction
  - ExtFormAction
  - AbnormalFormAction
  - PctNullSelfRedirectHyperlinks
  - FrequentDomainNameMismatch
  - FakeLinkInStatusBar
  - RightClickDisabled
  - PopUpWindow
  - SubmitInfoToEmail
  - IframeOrFrame
  - MissingTitle
  - ImagesOnlyInForm

[NONE-VALUED FEATURES]
  - AbnormalExtFormActionR [KNOWN UNRESOLVED]
  - AbnormalFormAction [UNEXPECTED]
  - ExtFavicon [UNEXPECTED]
  - ExtFormAction [UNEXPECTED]
  - ExtMetaScriptLinkRT [KNOWN UNRESOLVED]
  - FakeLinkInStatusBar [UNEXPECTED]
  - FrequentDomainNameMismatch [UNEXPECTED]
  - IframeOrFrame [UNEXPECTED]
  - ImagesOnlyInForm [UNEXPECTED]
  - InsecureForms [UNEXPECTED]
  - MissingTitle [UNEXPECTED]
  - PctExtHyperlinks [UNEXPECTED]
  - PctExtNullSelfRedirectHyperlinksRT [KNOWN UNRESOLVED]
  - PctExtResourceUrls [UNEXPECTED]
  - PctExtResourceUrlsRT [KNOWN UNRESOLVED]
  - PctNullSelfRedirectHyperlinks [UNEXPECTED]
  - PopUpWindow [UNEXPECTED]
  - RelativeFormAction [UNEXPECTED]
  - RightClickDisabled [UNEXPECTED]
  - SubdomainLevelRT [KNOWN UNRESOLVED]
  - SubmitInfoToEmail [UNEXPECTED]

[WARNING] Unexpected None values:
  - AbnormalFormAction
  - ExtFavicon
  - ExtFormAction
  - FakeLinkInStatusBar
  - FrequentDomainNameMismatch
  - IframeOrFrame
  - ImagesOnlyInForm
  - InsecureForms
  - MissingTitle
  - PctExtHyperlinks
  - PctExtResourceUrls
  - PctNullSelfRedirectHyperlinks
  - PopUpWindow
  - RelativeFormAction
  - RightClickDisabled
  - SubmitInfoToEmail

[PASS] Exact 47-feature KEY contract generated.

----------------------------------------------------------------------
Testing: GitHub
URL    : https://github.com
----------------------------------------------------------------------
URL extractor generated : 47 feature entries
URL extractor missing   : 0
URL extractor unknown   : 21
Final URL               : https://github.com/
HTML characters         : 573352
HTML extractor keys     : 16
Combined feature keys   : 47
Expected feature keys   : 47
Missing features        : 0
Extra features          : 0
None-valued features    : 21
Vector length           : 47

[DUPLICATE KEYS]
  - PctExtHyperlinks
  - PctExtResourceUrls
  - ExtFavicon
  - InsecureForms
  - RelativeFormAction
  - ExtFormAction
  - AbnormalFormAction
  - PctNullSelfRedirectHyperlinks
  - FrequentDomainNameMismatch
  - FakeLinkInStatusBar
  - RightClickDisabled
  - PopUpWindow
  - SubmitInfoToEmail
  - IframeOrFrame
  - MissingTitle
  - ImagesOnlyInForm

[NONE-VALUED FEATURES]
  - AbnormalExtFormActionR [KNOWN UNRESOLVED]
  - AbnormalFormAction [UNEXPECTED]
  - ExtFavicon [UNEXPECTED]
  - ExtFormAction [UNEXPECTED]
  - ExtMetaScriptLinkRT [KNOWN UNRESOLVED]
  - FakeLinkInStatusBar [UNEXPECTED]
  - FrequentDomainNameMismatch [UNEXPECTED]
  - IframeOrFrame [UNEXPECTED]
  - ImagesOnlyInForm [UNEXPECTED]
  - InsecureForms [UNEXPECTED]
  - MissingTitle [UNEXPECTED]
  - PctExtHyperlinks [UNEXPECTED]
  - PctExtNullSelfRedirectHyperlinksRT [KNOWN UNRESOLVED]
  - PctExtResourceUrls [UNEXPECTED]
  - PctExtResourceUrlsRT [KNOWN UNRESOLVED]
  - PctNullSelfRedirectHyperlinks [UNEXPECTED]
  - PopUpWindow [UNEXPECTED]
  - RelativeFormAction [UNEXPECTED]
  - RightClickDisabled [UNEXPECTED]
  - SubdomainLevelRT [KNOWN UNRESOLVED]
  - SubmitInfoToEmail [UNEXPECTED]

[WARNING] Unexpected None values:
  - AbnormalFormAction
  - ExtFavicon
  - ExtFormAction
  - FakeLinkInStatusBar
  - FrequentDomainNameMismatch
  - IframeOrFrame
  - ImagesOnlyInForm
  - InsecureForms
  - MissingTitle
  - PctExtHyperlinks
  - PctExtResourceUrls
  - PctNullSelfRedirectHyperlinks
  - PopUpWindow
  - RelativeFormAction
  - RightClickDisabled
  - SubmitInfoToEmail

[PASS] Exact 47-feature KEY contract generated.

----------------------------------------------------------------------
Testing: Python
URL    : https://www.python.org
----------------------------------------------------------------------
URL extractor generated : 47 feature entries
URL extractor missing   : 0
URL extractor unknown   : 21
Final URL               : https://www.python.org/
HTML characters         : 52291
HTML extractor keys     : 16
Combined feature keys   : 47
Expected feature keys   : 47
Missing features        : 0
Extra features          : 0
None-valued features    : 21
Vector length           : 47

[DUPLICATE KEYS]
  - PctExtHyperlinks
  - PctExtResourceUrls
  - ExtFavicon
  - InsecureForms
  - RelativeFormAction
  - ExtFormAction
  - AbnormalFormAction
  - PctNullSelfRedirectHyperlinks
  - FrequentDomainNameMismatch
  - FakeLinkInStatusBar
  - RightClickDisabled
  - PopUpWindow
  - SubmitInfoToEmail
  - IframeOrFrame
  - MissingTitle
  - ImagesOnlyInForm

[NONE-VALUED FEATURES]
  - AbnormalExtFormActionR [KNOWN UNRESOLVED]
  - AbnormalFormAction [UNEXPECTED]
  - ExtFavicon [UNEXPECTED]
  - ExtFormAction [UNEXPECTED]
  - ExtMetaScriptLinkRT [KNOWN UNRESOLVED]
  - FakeLinkInStatusBar [UNEXPECTED]
  - FrequentDomainNameMismatch [UNEXPECTED]
  - IframeOrFrame [UNEXPECTED]
  - ImagesOnlyInForm [UNEXPECTED]
  - InsecureForms [UNEXPECTED]
  - MissingTitle [UNEXPECTED]
  - PctExtHyperlinks [UNEXPECTED]
  - PctExtNullSelfRedirectHyperlinksRT [KNOWN UNRESOLVED]
  - PctExtResourceUrls [UNEXPECTED]
  - PctExtResourceUrlsRT [KNOWN UNRESOLVED]
  - PctNullSelfRedirectHyperlinks [UNEXPECTED]
  - PopUpWindow [UNEXPECTED]
  - RelativeFormAction [UNEXPECTED]
  - RightClickDisabled [UNEXPECTED]
  - SubdomainLevelRT [KNOWN UNRESOLVED]
  - SubmitInfoToEmail [UNEXPECTED]

[WARNING] Unexpected None values:
  - AbnormalFormAction
  - ExtFavicon
  - ExtFormAction
  - FakeLinkInStatusBar
  - FrequentDomainNameMismatch
  - IframeOrFrame
  - ImagesOnlyInForm
  - InsecureForms
  - MissingTitle
  - PctExtHyperlinks
  - PctExtResourceUrls
  - PctNullSelfRedirectHyperlinks
  - PopUpWindow
  - RelativeFormAction
  - RightClickDisabled
  - SubmitInfoToEmail

[PASS] Exact 47-feature KEY contract generated.

======================================================================
STEP 5K SUMMARY
======================================================================
[PASS] Google: 47/47 keys, None=21, Missing=0
[PASS] Microsoft: 47/47 keys, None=21, Missing=0
[PASS] GitHub: 47/47 keys, None=21, Missing=0
[PASS] Python: 47/47 keys, None=21, Missing=0

======================================================================
STEP 5K CHECKPOINT SAVED
======================================================================
Checkpoint: /content/drive/MyDrive/PhishShield_AI/checkpoints/step_5K_live_feature_validation.json
[PASS] Checkpoint JSON verified successfully.
======================================================================

In [ ]:
# ============================================================
# STEP 5L — INSPECT HTML FEATURE EXTRACTOR RETURN VALUES
# ============================================================

TEST_URL = "https://www.google.com"

print("=" * 70)
print("STEP 5L — HTML FEATURE EXTRACTOR DIAGNOSTIC")
print("=" * 70)

try:

    # --------------------------------------------------------
    # Fetch page
    # --------------------------------------------------------

    final_url, html = fetch_html(TEST_URL)

    print("Final URL:", final_url)
    print("HTML length:", len(html))

    # --------------------------------------------------------
    # Run HTML extractor directly
    # --------------------------------------------------------

    html_result = extract_html_features(
        html,
        final_url
    )

    print("\nReturn type:", type(html_result))

    if not isinstance(html_result, dict):
        raise TypeError(
            "extract_html_features() did not return a dictionary."
        )

    print(
        "Number of returned keys:",
        len(html_result)
    )

    # --------------------------------------------------------
    # Print every feature and its actual value
    # --------------------------------------------------------

    print("\n" + "-" * 70)
    print("HTML FEATURE VALUES")
    print("-" * 70)

    for key, value in html_result.items():

        print(
            f"{key:<38} "
            f"value={repr(value):<15} "
            f"type={type(value).__name__}"
        )

    # --------------------------------------------------------
    # Count None
    # --------------------------------------------------------

    none_features = [
        key
        for key, value in html_result.items()
        if value is None
    ]

    non_none_features = [
        key
        for key, value in html_result.items()
        if value is not None
    ]

    print("\n" + "-" * 70)
    print("DIAGNOSTIC SUMMARY")
    print("-" * 70)

    print(
        "Total HTML features :",
        len(html_result)
    )

    print(
        "Non-None features   :",
        len(non_none_features)
    )

    print(
        "None features       :",
        len(none_features)
    )

    print("\nNone-valued features:")

    for feature in none_features:
        print("  -", feature)

    # --------------------------------------------------------
    # Check for unexpected return structures
    # --------------------------------------------------------

    print("\n" + "-" * 70)
    print("FEATURE VALUE TYPES")
    print("-" * 70)

    value_types = {}

    for key, value in html_result.items():

        value_type = type(value).__name__

        value_types.setdefault(
            value_type,
            []
        ).append(key)

    for value_type, features in value_types.items():

        print(
            f"\n{value_type}: {len(features)} feature(s)"
        )

        for feature in features:
            print(
                f"  - {feature}"
            )

except Exception as e:

    print("\n[ERROR]")
    print(
        type(e).__name__,
        ":",
        str(e)
    )

print("\n" + "=" * 70)
print("END STEP 5L")
print("=" * 70)

======================================================================
STEP 5L — HTML FEATURE EXTRACTOR DIAGNOSTIC
======================================================================
Final URL: https://www.google.com/
HTML length: 224241

Return type: <class 'dict'>
Number of returned keys: 16

----------------------------------------------------------------------
HTML FEATURE VALUES
----------------------------------------------------------------------
PctExtHyperlinks                       value=0.1111111111111111 type=float
PctExtResourceUrls                     value=0.6             type=float
ExtFavicon                             value=1               type=int
InsecureForms                          value=0               type=int
RelativeFormAction                     value=1               type=int
ExtFormAction                          value=0               type=int
AbnormalFormAction                     value=0               type=int
PctNullSelfRedirectHyperlinks          value=0.0             type=float
FrequentDomainNameMismatch             value=0               type=int
FakeLinkInStatusBar                    value=0               type=int
RightClickDisabled                     value=0               type=int
PopUpWindow                            value=0               type=int
SubmitInfoToEmail                      value=0               type=int
IframeOrFrame                          value=0               type=int
MissingTitle                           value=0               type=int
ImagesOnlyInForm                       value=0               type=int

----------------------------------------------------------------------
DIAGNOSTIC SUMMARY
----------------------------------------------------------------------
Total HTML features : 16
Non-None features   : 16
None features       : 0

None-valued features:

----------------------------------------------------------------------
FEATURE VALUE TYPES
----------------------------------------------------------------------

float: 3 feature(s)
  - PctExtHyperlinks
  - PctExtResourceUrls
  - PctNullSelfRedirectHyperlinks

int: 13 feature(s)
  - ExtFavicon
  - InsecureForms
  - RelativeFormAction
  - ExtFormAction
  - AbnormalFormAction
  - FrequentDomainNameMismatch
  - FakeLinkInStatusBar
  - RightClickDisabled
  - PopUpWindow
  - SubmitInfoToEmail
  - IframeOrFrame
  - MissingTitle
  - ImagesOnlyInForm

======================================================================
END STEP 5L
======================================================================

In [ ]:
# ============================================================
# STEP 5M — CORRECTED URL + HTML FEATURE MERGE
# ============================================================
# Purpose:
#   Verify that HTML-derived values correctly replace
#   URL-extractor placeholders (None).
#
# IMPORTANT:
#   NO training
#   NO retraining
#   NO prediction
#   NO model modification
# ============================================================

import json
import os
import traceback
import numpy as np

TEST_URLS = {
    "Google": "https://www.google.com",
    "Microsoft": "https://www.microsoft.com",
    "GitHub": "https://github.com",
    "Python": "https://www.python.org"
}

EXPECTED_FEATURES = [
    "NumDots",
    "SubdomainLevel",
    "PathLevel",
    "UrlLength",
    "NumDash",
    "NumDashInHostname",
    "AtSymbol",
    "TildeSymbol",
    "NumUnderscore",
    "NumPercent",
    "NumQueryComponents",
    "NumAmpersand",
    "NumHash",
    "NumNumericChars",
    "NoHttps",
    "RandomString",
    "IpAddress",
    "DomainInSubdomains",
    "DomainInPaths",
    "HostnameLength",
    "PathLength",
    "QueryLength",
    "DoubleSlashInPath",
    "NumSensitiveWords",
    "EmbeddedBrandName",
    "PctExtHyperlinks",
    "PctExtResourceUrls",
    "ExtFavicon",
    "InsecureForms",
    "RelativeFormAction",
    "ExtFormAction",
    "AbnormalFormAction",
    "PctNullSelfRedirectHyperlinks",
    "FrequentDomainNameMismatch",
    "FakeLinkInStatusBar",
    "RightClickDisabled",
    "PopUpWindow",
    "SubmitInfoToEmail",
    "IframeOrFrame",
    "MissingTitle",
    "ImagesOnlyInForm",
    "SubdomainLevelRT",
    "UrlLengthRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

KNOWN_UNRESOLVED = {
    "SubdomainLevelRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
}

HTML_FEATURES = {
    "PctExtHyperlinks",
    "PctExtResourceUrls",
    "ExtFavicon",
    "InsecureForms",
    "RelativeFormAction",
    "ExtFormAction",
    "AbnormalFormAction",
    "PctNullSelfRedirectHyperlinks",
    "FrequentDomainNameMismatch",
    "FakeLinkInStatusBar",
    "RightClickDisabled",
    "PopUpWindow",
    "SubmitInfoToEmail",
    "IframeOrFrame",
    "MissingTitle",
    "ImagesOnlyInForm"
}

validation_results = {}

print("=" * 70)
print("STEP 5M — CORRECTED FEATURE MERGE VALIDATION")
print("=" * 70)

for site_name, url in TEST_URLS.items():

    print(f"\n{'-' * 70}")
    print(f"Testing: {site_name}")
    print(f"URL    : {url}")
    print("-" * 70)

    try:

        # ====================================================
        # 1. URL FEATURES
        # ====================================================

        url_result = extract_url_features(url)

        url_features = url_result["features"]

        # ====================================================
        # 2. FETCH HTML
        # ====================================================

        final_url, html = fetch_html(url)

        # ====================================================
        # 3. HTML FEATURES
        # ====================================================

        html_features = extract_html_features(
            html,
            final_url
        )

        # ====================================================
        # 4. CORRECT MERGE
        # ====================================================
        #
        # Rule:
        #   - Keep URL feature if it has a real value.
        #   - If URL feature is None and HTML provides a value,
        #     replace it with HTML value.
        #
        # ====================================================

        combined = dict(url_features)

        replaced_none = []

        for key, html_value in html_features.items():

            if key not in combined:

                combined[key] = html_value

            elif combined[key] is None:

                combined[key] = html_value

                replaced_none.append(key)

            # If URL already has a real value,
            # preserve the URL value.

        # ====================================================
        # 5. CONTRACT CHECK
        # ====================================================

        generated = set(combined.keys())
        expected = set(EXPECTED_FEATURES)

        missing = sorted(
            expected - generated
        )

        extra = sorted(
            generated - expected
        )

        none_features = sorted([
            feature
            for feature in EXPECTED_FEATURES
            if combined.get(feature) is None
        ])

        unexpected_none = sorted(
            set(none_features) - KNOWN_UNRESOLVED
        )

        # ====================================================
        # 6. ORDERED MODEL VECTOR
        # ====================================================

        ordered_vector = [
            combined[feature]
            for feature in EXPECTED_FEATURES
        ]

        # ====================================================
        # 7. PRINT
        # ====================================================

        print(
            f"URL features          : {len(url_features)}"
        )

        print(
            f"HTML features         : {len(html_features)}"
        )

        print(
            f"None values replaced  : {len(replaced_none)}"
        )

        print(
            f"Combined features     : {len(generated)}/47"
        )

        print(
            f"Missing               : {len(missing)}"
        )

        print(
            f"Extra                 : {len(extra)}"
        )

        print(
            f"Remaining None        : {len(none_features)}"
        )

        print(
            f"Vector length         : {len(ordered_vector)}"
        )

        if replaced_none:

            print(
                "\n[HTML VALUES USED TO REPLACE URL None]"
            )

            for feature in replaced_none:
                print(
                    f"  - {feature} = "
                    f"{repr(combined[feature])}"
                )

        if none_features:

            print(
                "\n[REMAINING NONE FEATURES]"
            )

            for feature in none_features:

                if feature in KNOWN_UNRESOLVED:
                    print(
                        f"  - {feature} "
                        f"[KNOWN RT UNRESOLVED]"
                    )
                else:
                    print(
                        f"  - {feature} "
                        f"[UNEXPECTED]"
                    )

        if missing:

            print(
                "\n[MISSING FEATURES]"
            )

            for feature in missing:
                print(f"  - {feature}")

        if extra:

            print(
                "\n[EXTRA FEATURES]"
            )

            for feature in extra:
                print(f"  - {feature}")

        # ====================================================
        # 8. SAFETY CHECK
        # ====================================================

        unexpected_none_ok = (
            len(unexpected_none) == 0
        )

        structural_ok = (
            len(generated) == 47
            and len(missing) == 0
            and len(extra) == 0
            and len(ordered_vector) == 47
        )

        if structural_ok and unexpected_none_ok:

            print(
                "\n[PASS] Merge is structurally correct."
            )

        else:

            print(
                "\n[CHECK] Merge still needs investigation."
            )

        # ====================================================
        # 9. SAVE RESULTS
        # ====================================================

        validation_results[site_name] = {
            "requested_url": url,
            "final_url": final_url,

            "url_feature_count": len(url_features),
            "html_feature_count": len(html_features),

            "replaced_none_features": replaced_none,

            "combined_feature_count": len(generated),

            "missing_features": missing,
            "extra_features": extra,

            "none_features": none_features,
            "unexpected_none_features": unexpected_none,

            "vector_length": len(ordered_vector),

            "structural_contract_pass": structural_ok,
            "unexpected_none_pass": unexpected_none_ok
        }

    except Exception as e:

        print("\n[ERROR]")
        print(
            type(e).__name__,
            ":",
            str(e)
        )

        traceback.print_exc(limit=2)

        validation_results[site_name] = {
            "requested_url": url,
            "error": type(e).__name__,
            "error_message": str(e)
        }


# ============================================================
# SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("STEP 5M SUMMARY")
print("=" * 70)

for site_name, result in validation_results.items():

    if "error" in result:

        print(
            f"[ERROR] {site_name}"
        )

    else:

        passed = (
            result["structural_contract_pass"]
            and result["unexpected_none_pass"]
        )

        print(
            f"[{'PASS' if passed else 'CHECK'}] "
            f"{site_name}: "
            f"{result['combined_feature_count']}/47, "
            f"None={len(result['none_features'])}, "
            f"Missing={len(result['missing_features'])}"
        )


# ============================================================
# DRIVE CHECKPOINT
# ============================================================

checkpoint_dir = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints"
)

os.makedirs(
    checkpoint_dir,
    exist_ok=True
)

checkpoint_path = os.path.join(
    checkpoint_dir,
    "step_5M_corrected_feature_merge.json"
)

checkpoint = {
    "stage": "5M",
    "purpose": (
        "Validate corrected URL + HTML feature merging"
    ),
    "training_performed": False,
    "retraining_performed": False,
    "prediction_performed": False,
    "model_modified": False,

    "expected_feature_count": 47,

    "merge_rule": (
        "HTML value replaces URL value only when "
        "URL value is None"
    ),

    "known_unresolved_features": sorted(
        KNOWN_UNRESOLVED
    ),

    "test_urls": TEST_URLS,

    "results": validation_results
}


# ============================================================
# JSON SAFE SAVE
# ============================================================

def make_json_serializable(obj):

    if isinstance(obj, dict):

        return {
            str(k): make_json_serializable(v)
            for k, v in obj.items()
        }

    if isinstance(obj, (list, tuple)):

        return [
            make_json_serializable(v)
            for v in obj
        ]

    if isinstance(obj, np.integer):
        return int(obj)

    if isinstance(obj, np.floating):
        return float(obj)

    if isinstance(obj, np.bool_):
        return bool(obj)

    if isinstance(obj, np.ndarray):
        return obj.tolist()

    return obj


checkpoint_safe = make_json_serializable(
    checkpoint
)

with open(
    checkpoint_path,
    "w"
) as f:

    json.dump(
        checkpoint_safe,
        f,
        indent=2
    )


# ============================================================
# VERIFY CHECKPOINT
# ============================================================

with open(
    checkpoint_path,
    "r"
) as f:

    verified_checkpoint = json.load(f)

print("\n" + "=" * 70)
print("STEP 5M CHECKPOINT SAVED")
print("=" * 70)

print(
    f"Checkpoint: {checkpoint_path}"
)

print(
    "[PASS] Checkpoint JSON verified successfully."
)

print("=" * 70)

======================================================================
STEP 5M — CORRECTED FEATURE MERGE VALIDATION
======================================================================

----------------------------------------------------------------------
Testing: Google
URL    : https://www.google.com
----------------------------------------------------------------------
URL features          : 47
HTML features         : 16
None values replaced  : 16
Combined features     : 47/47
Missing               : 0
Extra                 : 0
Remaining None        : 5
Vector length         : 47

[HTML VALUES USED TO REPLACE URL None]
  - PctExtHyperlinks = 0.1111111111111111
  - PctExtResourceUrls = 0.6
  - ExtFavicon = 1
  - InsecureForms = 0
  - RelativeFormAction = 1
  - ExtFormAction = 0
  - AbnormalFormAction = 0
  - PctNullSelfRedirectHyperlinks = 0.0
  - FrequentDomainNameMismatch = 0
  - FakeLinkInStatusBar = 0
  - RightClickDisabled = 0
  - PopUpWindow = 0
  - SubmitInfoToEmail = 0
  - IframeOrFrame = 0
  - MissingTitle = 0
  - ImagesOnlyInForm = 0

[REMAINING NONE FEATURES]
  - AbnormalExtFormActionR [KNOWN RT UNRESOLVED]
  - ExtMetaScriptLinkRT [KNOWN RT UNRESOLVED]
  - PctExtNullSelfRedirectHyperlinksRT [KNOWN RT UNRESOLVED]
  - PctExtResourceUrlsRT [KNOWN RT UNRESOLVED]
  - SubdomainLevelRT [KNOWN RT UNRESOLVED]

[PASS] Merge is structurally correct.

----------------------------------------------------------------------
Testing: Microsoft
URL    : https://www.microsoft.com
----------------------------------------------------------------------
URL features          : 47
HTML features         : 16
None values replaced  : 16
Combined features     : 47/47
Missing               : 0
Extra                 : 0
Remaining None        : 5
Vector length         : 47

[HTML VALUES USED TO REPLACE URL None]
  - PctExtHyperlinks = 0.07079646017699115
  - PctExtResourceUrls = 0.6666666666666666
  - ExtFavicon = 0
  - InsecureForms = 0
  - RelativeFormAction = 0
  - ExtFormAction = 0
  - AbnormalFormAction = 0
  - PctNullSelfRedirectHyperlinks = 0.017699115044247787
  - FrequentDomainNameMismatch = 0
  - FakeLinkInStatusBar = 0
  - RightClickDisabled = 0
  - PopUpWindow = 0
  - SubmitInfoToEmail = 0
  - IframeOrFrame = 0
  - MissingTitle = 0
  - ImagesOnlyInForm = 0

[REMAINING NONE FEATURES]
  - AbnormalExtFormActionR [KNOWN RT UNRESOLVED]
  - ExtMetaScriptLinkRT [KNOWN RT UNRESOLVED]
  - PctExtNullSelfRedirectHyperlinksRT [KNOWN RT UNRESOLVED]
  - PctExtResourceUrlsRT [KNOWN RT UNRESOLVED]
  - SubdomainLevelRT [KNOWN RT UNRESOLVED]

[PASS] Merge is structurally correct.

----------------------------------------------------------------------
Testing: GitHub
URL    : https://github.com
----------------------------------------------------------------------
URL features          : 47
HTML features         : 16
None values replaced  : 16
Combined features     : 47/47
Missing               : 0
Extra                 : 0
Remaining None        : 5
Vector length         : 47

[HTML VALUES USED TO REPLACE URL None]
  - PctExtHyperlinks = 0.09929078014184398
  - PctExtResourceUrls = 0.9225806451612903
  - ExtFavicon = 1
  - InsecureForms = 0
  - RelativeFormAction = 2
  - ExtFormAction = 0
  - AbnormalFormAction = 0
  - PctNullSelfRedirectHyperlinks = 0.02127659574468085
  - FrequentDomainNameMismatch = 0
  - FakeLinkInStatusBar = 0
  - RightClickDisabled = 0
  - PopUpWindow = 0
  - SubmitInfoToEmail = 0
  - IframeOrFrame = 0
  - MissingTitle = 0
  - ImagesOnlyInForm = 0

[REMAINING NONE FEATURES]
  - AbnormalExtFormActionR [KNOWN RT UNRESOLVED]
  - ExtMetaScriptLinkRT [KNOWN RT UNRESOLVED]
  - PctExtNullSelfRedirectHyperlinksRT [KNOWN RT UNRESOLVED]
  - PctExtResourceUrlsRT [KNOWN RT UNRESOLVED]
  - SubdomainLevelRT [KNOWN RT UNRESOLVED]

[PASS] Merge is structurally correct.

----------------------------------------------------------------------
Testing: Python
URL    : https://www.python.org
----------------------------------------------------------------------
URL features          : 47
HTML features         : 16
None values replaced  : 16
Combined features     : 47/47
Missing               : 0
Extra                 : 0
Remaining None        : 5
Vector length         : 47

[HTML VALUES USED TO REPLACE URL None]
  - PctExtHyperlinks = 0.22325581395348837
  - PctExtResourceUrls = 0.25925925925925924
  - ExtFavicon = 0
  - InsecureForms = 0
  - RelativeFormAction = 1
  - ExtFormAction = 0
  - AbnormalFormAction = 0
  - PctNullSelfRedirectHyperlinks = 0.023255813953488372
  - FrequentDomainNameMismatch = 0
  - FakeLinkInStatusBar = 0
  - RightClickDisabled = 0
  - PopUpWindow = 0
  - SubmitInfoToEmail = 0
  - IframeOrFrame = 0
  - MissingTitle = 0
  - ImagesOnlyInForm = 0

[REMAINING NONE FEATURES]
  - AbnormalExtFormActionR [KNOWN RT UNRESOLVED]
  - ExtMetaScriptLinkRT [KNOWN RT UNRESOLVED]
  - PctExtNullSelfRedirectHyperlinksRT [KNOWN RT UNRESOLVED]
  - PctExtResourceUrlsRT [KNOWN RT UNRESOLVED]
  - SubdomainLevelRT [KNOWN RT UNRESOLVED]

[PASS] Merge is structurally correct.

======================================================================
STEP 5M SUMMARY
======================================================================
[PASS] Google: 47/47, None=5, Missing=0
[PASS] Microsoft: 47/47, None=5, Missing=0
[PASS] GitHub: 47/47, None=5, Missing=0
[PASS] Python: 47/47, None=5, Missing=0

======================================================================
STEP 5M CHECKPOINT SAVED
======================================================================
Checkpoint: /content/drive/MyDrive/PhishShield_AI/checkpoints/step_5M_corrected_feature_merge.json
[PASS] Checkpoint JSON verified successfully.
======================================================================

In [ ]:
# ============================================================
# STEP 5N — RT FEATURE INVESTIGATION
# ============================================================
# Purpose:
#   Investigate the five unresolved runtime-transformed (RT)
#   features using the original 10,000-row dataset.
#
# IMPORTANT:
#   NO model training
#   NO retraining
#   NO prediction
#   NO model modification
#   NO target-based rule implementation
#
# We are looking for reproducible structural relationships,
# not inventing rules merely to fill missing values.
# ============================================================

import os
import json
import joblib
import numpy as np
import pandas as pd

# ============================================================
# PATHS
# ============================================================

DATASET_PATH = "/content/Phishing_Legitimate_full.csv"

CHECKPOINT_DIR = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints"
)

os.makedirs(
    CHECKPOINT_DIR,
    exist_ok=True
)

CHECKPOINT_PATH = os.path.join(
    CHECKPOINT_DIR,
    "step_5N_rt_feature_investigation.json"
)

# ============================================================
# LOAD DATASET
# ============================================================

df = pd.read_csv(DATASET_PATH)

print("=" * 75)
print("STEP 5N — RT FEATURE INVESTIGATION")
print("=" * 75)

print("\nDataset shape:", df.shape)

# ============================================================
# FIVE UNRESOLVED RT FEATURES
# ============================================================

RT_FEATURES = [
    "SubdomainLevelRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

# ============================================================
# RELATED RAW FEATURES
# ============================================================

CANDIDATE_GROUPS = {

    "SubdomainLevelRT": [
        "SubdomainLevel",
        "NumDots",
        "HostnameLength",
        "UrlLength",
        "NumDashInHostname",
        "DomainInSubdomains",
        "DomainInPaths",
        "PathLevel",
        "NumNumericChars"
    ],

    "PctExtResourceUrlsRT": [
        "PctExtResourceUrls",
        "PctExtHyperlinks",
        "ExtFavicon",
        "IframeOrFrame",
        "NumDots",
        "HostnameLength",
        "UrlLength"
    ],

    "AbnormalExtFormActionR": [
        "AbnormalFormAction",
        "ExtFormAction",
        "RelativeFormAction",
        "InsecureForms",
        "PctExtHyperlinks",
        "PctExtResourceUrls",
        "HostnameLength",
        "UrlLength"
    ],

    "ExtMetaScriptLinkRT": [
        "PctExtResourceUrls",
        "PctExtHyperlinks",
        "PctNullSelfRedirectHyperlinks",
        "ExtFavicon",
        "IframeOrFrame",
        "FrequentDomainNameMismatch",
        "HostnameLength",
        "UrlLength"
    ],

    "PctExtNullSelfRedirectHyperlinksRT": [
        "PctExtHyperlinks",
        "PctNullSelfRedirectHyperlinks",
        "FrequentDomainNameMismatch",
        "PctExtResourceUrls",
        "NumDots",
        "HostnameLength",
        "UrlLength"
    ]
}

# ============================================================
# VERIFY COLUMNS
# ============================================================

print("\n" + "-" * 75)
print("COLUMN AVAILABILITY")
print("-" * 75)

for feature in RT_FEATURES:

    print(
        f"{feature:40s} "
        f"present={feature in df.columns}"
    )

print("\nTarget present:",
      "CLASS_LABEL" in df.columns)

print("ID present:",
      "id" in df.columns)

# ============================================================
# INVESTIGATION RESULTS
# ============================================================

results = {}

# ============================================================
# FUNCTION: GROUP DISTRIBUTION
# ============================================================

def group_distribution(
    data,
    group_col,
    target_col="CLASS_LABEL"
):

    table = (
        data.groupby(
            group_col,
            dropna=False
        )[target_col]
        .agg(
            count="size",
            class1_rate="mean"
        )
        .reset_index()
    )

    return table


# ============================================================
# 1. SUBDOMAINLEVELRT
# ============================================================

print("\n" + "=" * 75)
print("1. SubdomainLevelRT")
print("=" * 75)

feature = "SubdomainLevelRT"

print("\nOverall value counts:")
print(
    df[feature]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nCross-tab with SubdomainLevel:")
sub_table = pd.crosstab(
    df["SubdomainLevel"],
    df[feature]
)

print(sub_table)

print("\nDetailed conditional distribution:")
sub_cond = pd.crosstab(
    df["SubdomainLevel"],
    df[feature],
    normalize="index"
).round(4)

print(sub_cond)

# Candidate continuous relationships
for candidate in [
    "NumDots",
    "HostnameLength",
    "UrlLength",
    "NumDashInHostname",
    "DomainInSubdomains",
    "DomainInPaths",
    "PathLevel",
    "NumNumericChars"
]:

    grouped = (
        df.groupby(feature)[candidate]
        .agg(
            count="size",
            mean="mean",
            median="median",
            min="min",
            max="max"
        )
        .round(4)
    )

    print(
        f"\n{feature} vs {candidate}:"
    )

    print(grouped)

results[feature] = {
    "value_counts": df[feature]
        .value_counts(dropna=False)
        .sort_index()
        .to_dict(),

    "subdomain_crosstab":
        sub_table.to_dict(),

    "subdomain_conditional":
        sub_cond.to_dict()
}

# ============================================================
# 2. PctExtResourceUrlsRT
# ============================================================

print("\n" + "=" * 75)
print("2. PctExtResourceUrlsRT")
print("=" * 75)

feature = "PctExtResourceUrlsRT"

print("\nOverall value counts:")
print(
    df[feature]
    .value_counts(dropna=False)
    .sort_index()
)

for candidate in CANDIDATE_GROUPS[feature]:

    print(
        f"\n--- {candidate} ---"
    )

    print(
        df.groupby(feature)[candidate]
        .agg(
            count="size",
            mean="mean",
            median="median",
            min="min",
            max="max"
        )
        .round(4)
    )

print("\nConditional distribution by PctExtResourceUrls:")

resource_bins = pd.cut(
    df["PctExtResourceUrls"],
    bins=[
        -0.000001,
        0,
        0.25,
        0.50,
        0.75,
        1.000001
    ],
    include_lowest=True
)

resource_cross = pd.crosstab(
    resource_bins,
    df[feature],
    normalize="index"
).round(4)

print(resource_cross)

results[feature] = {
    "value_counts": df[feature]
        .value_counts(dropna=False)
        .sort_index()
        .to_dict(),

    "resource_cross":
        resource_cross.to_dict()
}

# ============================================================
# 3. AbnormalExtFormActionR
# ============================================================

print("\n" + "=" * 75)
print("3. AbnormalExtFormActionR")
print("=" * 75)

feature = "AbnormalExtFormActionR"

print("\nOverall value counts:")
print(
    df[feature]
    .value_counts(dropna=False)
    .sort_index()
)

for candidate in CANDIDATE_GROUPS[feature]:

    print(
        f"\n--- {candidate} ---"
    )

    print(
        df.groupby(feature)[candidate]
        .agg(
            count="size",
            mean="mean",
            median="median",
            min="min",
            max="max"
        )
        .round(4)
    )

print("\nCross-tab with form features:")

form_cols = [
    "AbnormalFormAction",
    "ExtFormAction",
    "RelativeFormAction",
    "InsecureForms"
]

for col in form_cols:

    print(
        f"\n{col}:"
    )

    print(
        pd.crosstab(
            df[col],
            df[feature],
            normalize="index"
        ).round(4)
    )

results[feature] = {
    "value_counts": df[feature]
        .value_counts(dropna=False)
        .sort_index()
        .to_dict()
}

# ============================================================
# 4. ExtMetaScriptLinkRT
# ============================================================

print("\n" + "=" * 75)
print("4. ExtMetaScriptLinkRT")
print("=" * 75)

feature = "ExtMetaScriptLinkRT"

print("\nOverall value counts:")
print(
    df[feature]
    .value_counts(dropna=False)
    .sort_index()
)

for candidate in CANDIDATE_GROUPS[feature]:

    print(
        f"\n--- {candidate} ---"
    )

    print(
        df.groupby(feature)[candidate]
        .agg(
            count="size",
            mean="mean",
            median="median",
            min="min",
            max="max"
        )
        .round(4)
    )

print(
    "\nCross-tab with major percentage features:"
)

for col in [
    "PctExtResourceUrls",
    "PctExtHyperlinks",
    "PctNullSelfRedirectHyperlinks"
]:

    print(
        f"\n{col}:"
    )

    print(
        pd.crosstab(
            pd.cut(
                df[col],
                bins=5,
                duplicates="drop"
            ),
            df[feature],
            normalize="index"
        ).round(4)
    )

results[feature] = {
    "value_counts": df[feature]
        .value_counts(dropna=False)
        .sort_index()
        .to_dict()
}

# ============================================================
# 5. PctExtNullSelfRedirectHyperlinksRT
# ============================================================

print("\n" + "=" * 75)
print("5. PctExtNullSelfRedirectHyperlinksRT")
print("=" * 75)

feature = "PctExtNullSelfRedirectHyperlinksRT"

print("\nOverall value counts:")
print(
    df[feature]
    .value_counts(dropna=False)
    .sort_index()
)

for candidate in CANDIDATE_GROUPS[feature]:

    print(
        f"\n--- {candidate} ---"
    )

    print(
        df.groupby(feature)[candidate]
        .agg(
            count="size",
            mean="mean",
            median="median",
            min="min",
            max="max"
        )
        .round(4)
    )

print(
    "\nCross-tab with PctNullSelfRedirectHyperlinks:"
)

null_bins = pd.cut(
    df["PctNullSelfRedirectHyperlinks"],
    bins=[
        -0.000001,
        0,
        0.05,
        0.10,
        0.25,
        0.50,
        1.000001
    ],
    include_lowest=True
)

null_cross = pd.crosstab(
    null_bins,
    df[feature],
    normalize="index"
).round(4)

print(null_cross)

results[feature] = {
    "value_counts": df[feature]
        .value_counts(dropna=False)
        .sort_index()
        .to_dict(),

    "null_cross":
        null_cross.to_dict()
}

# ============================================================
# 6. CORRELATION MATRIX
# ============================================================

print("\n" + "=" * 75)
print("RT ↔ CANDIDATE CORRELATIONS")
print("=" * 75)

all_candidates = sorted(
    set(
        candidate
        for candidates in CANDIDATE_GROUPS.values()
        for candidate in candidates
    )
)

correlation_table = pd.DataFrame(
    index=RT_FEATURES,
    columns=all_candidates,
    dtype=float
)

for rt_feature in RT_FEATURES:

    for candidate in CANDIDATE_GROUPS[rt_feature]:

        correlation_table.loc[
            rt_feature,
            candidate
        ] = (
            df[rt_feature]
            .corr(df[candidate])
        )

print(
    correlation_table.round(4)
)

# ============================================================
# 7. UNIQUE COMBINATION ANALYSIS
# ============================================================

print("\n" + "=" * 75)
print("RT FEATURE COMBINATION ANALYSIS")
print("=" * 75)

for rt_feature in RT_FEATURES:

    candidates = CANDIDATE_GROUPS[rt_feature]

    subset = df[
        [rt_feature] + candidates
    ].copy()

    unique_count = (
        subset
        .drop_duplicates()
        .shape[0]
    )

    print(
        f"\n{rt_feature}"
    )

    print(
        f"Rows                 : {len(df)}"
    )

    print(
        f"Unique combinations  : {unique_count}"
    )

    print(
        f"Deterministic mapping "
        f"possible from exact candidate tuple: "
        f"{'YES' if unique_count < len(df) else 'NO'}"
    )

# ============================================================
# 8. TARGET EXCLUSION SAFETY
# ============================================================

print("\n" + "=" * 75)
print("SAFETY CHECK")
print("=" * 75)

for rt_feature in RT_FEATURES:

    candidates = CANDIDATE_GROUPS[rt_feature]

    forbidden = [
        c
        for c in candidates
        if c in [
            "CLASS_LABEL",
            "id"
        ]
    ]

    print(
        f"{rt_feature:40s} "
        f"target/id used={len(forbidden) > 0}"
    )

# ============================================================
# 9. CHECKPOINT
# ============================================================

checkpoint = {
    "stage": "5N",
    "purpose": (
        "Investigate unresolved runtime-transformed "
        "features without model training or prediction."
    ),

    "dataset_path": DATASET_PATH,
    "dataset_rows": int(len(df)),
    "dataset_columns": int(len(df.columns)),

    "training_performed": False,
    "retraining_performed": False,
    "prediction_performed": False,
    "model_modified": False,

    "rt_features_investigated": RT_FEATURES,

    "candidate_groups": CANDIDATE_GROUPS,

    "results": results,

    "correlations": (
        correlation_table
        .replace({np.nan: None})
        .to_dict()
    )
}

def json_safe(obj):

    if isinstance(obj, dict):

        return {
            str(k): json_safe(v)
            for k, v in obj.items()
        }

    if isinstance(obj, (list, tuple)):

        return [
            json_safe(v)
            for v in obj
        ]

    if isinstance(obj, np.integer):
        return int(obj)

    if isinstance(obj, np.floating):

        if np.isnan(obj):
            return None

        return float(obj)

    if isinstance(obj, np.bool_):
        return bool(obj)

    if isinstance(obj, np.ndarray):
        return obj.tolist()

    return obj

checkpoint = json_safe(checkpoint)

with open(
    CHECKPOINT_PATH,
    "w"
) as f:

    json.dump(
        checkpoint,
        f,
        indent=2
    )

# ============================================================
# VERIFY CHECKPOINT
# ============================================================

with open(
    CHECKPOINT_PATH,
    "r"
) as f:

    verified = json.load(f)

print("\n" + "=" * 75)
print("STEP 5N CHECKPOINT SAVED")
print("=" * 75)

print(
    "Checkpoint:",
    CHECKPOINT_PATH
)

print(
    "[PASS] JSON checkpoint verified."
)

print(
    "No training performed."
)

print(
    "No prediction performed."
)

print(
    "No model modified."
)

print("=" * 75)
print("END STEP 5N")
print("=" * 75)

===========================================================================
STEP 5N — RT FEATURE INVESTIGATION
===========================================================================

Dataset shape: (10000, 50)

---------------------------------------------------------------------------
COLUMN AVAILABILITY
---------------------------------------------------------------------------
SubdomainLevelRT                         present=True
PctExtResourceUrlsRT                     present=True
AbnormalExtFormActionR                   present=True
ExtMetaScriptLinkRT                      present=True
PctExtNullSelfRedirectHyperlinksRT       present=True

Target present: True
ID present: True

===========================================================================
1. SubdomainLevelRT
===========================================================================

Overall value counts:
SubdomainLevelRT
-1     100
 0     234
 1    9666
Name: count, dtype: int64

Cross-tab with SubdomainLevel:
SubdomainLevelRT  -1    0     1
SubdomainLevel
0                  0    0  4835
1                  0    0  4790
2                  0  231    41
3                 19    3     0
4                 30    0     0
5                  6    0     0
6                 26    0     0
7                  7    0     0
8                  5    0     0
9                  3    0     0
10                 1    0     0
11                 2    0     0
14                 1    0     0

Detailed conditional distribution:
SubdomainLevelRT      -1       0       1
SubdomainLevel
0                 0.0000  0.0000  1.0000
1                 0.0000  0.0000  1.0000
2                 0.0000  0.8493  0.1507
3                 0.8636  0.1364  0.0000
4                 1.0000  0.0000  0.0000
5                 1.0000  0.0000  0.0000
6                 1.0000  0.0000  0.0000
7                 1.0000  0.0000  0.0000
8                 1.0000  0.0000  0.0000
9                 1.0000  0.0000  0.0000
10                1.0000  0.0000  0.0000
11                1.0000  0.0000  0.0000
14                1.0000  0.0000  0.0000

SubdomainLevelRT vs NumDots:
                  count    mean  median  min  max
SubdomainLevelRT
-1                  100  6.8200     6.0    4   16
 0                  234  3.6154     3.0    3    8
 1                 9666  2.3715     2.0    1   21

SubdomainLevelRT vs HostnameLength:
                  count     mean  median  min  max
SubdomainLevelRT
-1                  100  51.6000    46.0   22  137
 0                  234  36.1923    29.0   15   66
 1                 9666  18.0648    17.0    4   80

SubdomainLevelRT vs UrlLength:
                  count     mean  median  min  max
SubdomainLevelRT
-1                  100  95.9600    88.0   41  200
 0                  234  95.5299   105.0   32  206
 1                 9666  69.3866    62.0   12  253

SubdomainLevelRT vs NumDashInHostname:
                  count    mean  median  min  max
SubdomainLevelRT
-1                  100  0.9000     0.0    0    6
 0                  234  1.5684     0.0    0    7
 1                 9666  0.0964     0.0    0    9

SubdomainLevelRT vs DomainInSubdomains:
                  count    mean  median  min  max
SubdomainLevelRT
-1                  100  0.8200     1.0    0    1
 0                  234  0.4402     0.0    0    1
 1                 9666  0.0038     0.0    0    1

SubdomainLevelRT vs DomainInPaths:
                  count    mean  median  min  max
SubdomainLevelRT
-1                  100  0.4600     0.0    0    1
 0                  234  0.5641     1.0    0    1
 1                 9666  0.4253     0.0    0    1

SubdomainLevelRT vs PathLevel:
                  count    mean  median  min  max
SubdomainLevelRT
-1                  100  3.2800     3.0    1   10
 0                  234  3.8077     4.0    0   14
 1                 9666  3.2882     3.0    0   18

SubdomainLevelRT vs NumNumericChars:
                  count     mean  median  min  max
SubdomainLevelRT
-1                  100   9.2100     6.0    0   68
 0                  234  11.6923     9.0    0   53
 1                 9666   5.6327     2.0    0  111

===========================================================================
2. PctExtResourceUrlsRT
===========================================================================

Overall value counts:
PctExtResourceUrlsRT
-1    2808
 0     851
 1    6341
Name: count, dtype: int64

--- PctExtResourceUrls ---
                      count    mean  median   min     max
PctExtResourceUrlsRT
-1                     2808  0.8794  0.9811  0.04  1.0000
 0                      851  0.4375  0.4146  0.00  0.9565
 1                     6341  0.1715  0.0769  0.00  1.0000

--- PctExtHyperlinks ---
                      count    mean  median  min  max
PctExtResourceUrlsRT
-1                     2808  0.3931  0.2000  0.0  1.0
 0                      851  0.2320  0.1402  0.0  1.0
 1                     6341  0.1754  0.0308  0.0  1.0

--- ExtFavicon ---
                      count    mean  median  min  max
PctExtResourceUrlsRT
-1                     2808  0.3693     0.0    0    1
 0                      851  0.1105     0.0    0    1
 1                     6341  0.0853     0.0    0    1

--- IframeOrFrame ---
                      count    mean  median  min  max
PctExtResourceUrlsRT
-1                     2808  0.4868     0.0    0    1
 0                      851  0.6486     1.0    0    1
 1                     6341  0.2329     0.0    0    1

--- NumDots ---
                      count    mean  median  min  max
PctExtResourceUrlsRT
-1                     2808  2.4099     2.0    1   16
 0                      851  2.0047     2.0    1    7
 1                     6341  2.5198     2.0    1   21

--- HostnameLength ---
                      count     mean  median  min  max
PctExtResourceUrlsRT
-1                     2808  18.4160    18.0    6   94
 0                      851  18.1046    17.0    5   42
 1                     6341  19.1017    18.0    4  137

--- UrlLength ---
                      count     mean  median  min  max
PctExtResourceUrlsRT
-1                     2808  69.8889    64.0   14  253
 0                      851  72.0364    68.0   13  204
 1                     6341  70.1924    61.0   12  252

Conditional distribution by PctExtResourceUrls:
PctExtResourceUrlsRT      -1       0       1
PctExtResourceUrls
(-0.001001, 0.0]      0.0000  0.0004  0.9996
(0.0, 0.25]           0.0072  0.0495  0.9433
(0.25, 0.5]           0.1010  0.2988  0.6003
(0.5, 0.75]           0.4908  0.3061  0.2031
(0.75, 1.0]           0.8357  0.0233  0.1410

===========================================================================
3. AbnormalExtFormActionR
===========================================================================

Overall value counts:
AbnormalExtFormActionR
-1     537
 0     994
 1    8469
Name: count, dtype: int64

--- AbnormalFormAction ---
                        count    mean  median  min  max
AbnormalExtFormActionR
-1                        537  1.0000     1.0    1    1
 0                        994  0.0392     0.0    0    1
 1                       8469  0.0000     0.0    0    0

--- ExtFormAction ---
                        count    mean  median  min  max
AbnormalExtFormActionR
-1                        537  0.0447     0.0    0    1
 0                        994  1.0000     1.0    1    1
 1                       8469  0.0000     0.0    0    0

--- RelativeFormAction ---
                        count    mean  median  min  max
AbnormalExtFormActionR
-1                        537  1.0000     1.0    1    1
 0                        994  0.2012     0.0    0    1
 1                       8469  0.2066     0.0    0    1

--- InsecureForms ---
                        count    mean  median  min  max
AbnormalExtFormActionR
-1                        537  0.9926     1.0    0    1
 0                        994  0.8954     1.0    0    1
 1                       8469  0.8286     1.0    0    1

--- PctExtHyperlinks ---
                        count    mean  median  min  max
AbnormalExtFormActionR
-1                        537  0.1805  0.0847  0.0  1.0
 0                        994  0.3925  0.2248  0.0  1.0
 1                       8469  0.2275  0.0556  0.0  1.0

--- PctExtResourceUrls ---
                        count    mean  median  min  max
AbnormalExtFormActionR
-1                        537  0.4385  0.3333  0.0  1.0
 0                        994  0.5922  0.6132  0.0  1.0
 1                       8469  0.3667  0.2000  0.0  1.0

--- HostnameLength ---
                        count     mean  median  min  max
AbnormalExtFormActionR
-1                        537  17.9479    17.0    5   83
 0                        994  18.9789    18.0    6   84
 1                       8469  18.8617    17.0    4  137

--- UrlLength ---
                        count     mean  median  min  max
AbnormalExtFormActionR
-1                        537  73.2998    67.0   14  218
 0                        994  71.4205    64.0   14  240
 1                       8469  69.9359    62.0   12  253

Cross-tab with form features:

AbnormalFormAction:
AbnormalExtFormActionR      -1       0       1
AbnormalFormAction
0                       0.0000  0.1013  0.8987
1                       0.9323  0.0677  0.0000

ExtFormAction:
AbnormalExtFormActionR      -1       0       1
ExtFormAction
0                       0.0571  0.0000  0.9429
1                       0.0236  0.9764  0.0000

RelativeFormAction:
AbnormalExtFormActionR      -1       0       1
RelativeFormAction
0                       0.0000  0.1057  0.8943
1                       0.2159  0.0804  0.7037

InsecureForms:
AbnormalExtFormActionR      -1       0       1
InsecureForms
0                       0.0026  0.0667  0.9308
1                       0.0632  0.1055  0.8314

===========================================================================
4. ExtMetaScriptLinkRT
===========================================================================

Overall value counts:
ExtMetaScriptLinkRT
-1    2139
 0    3988
 1    3873
Name: count, dtype: int64

--- PctExtResourceUrls ---
                     count    mean  median     min  max
ExtMetaScriptLinkRT
-1                    2139  0.9316  1.0000  0.0053  1.0
 0                    3988  0.3771  0.3158  0.0000  1.0
 1                    3873  0.1118  0.0000  0.0000  1.0

--- PctExtHyperlinks ---
                     count    mean  median  min  max
ExtMetaScriptLinkRT
-1                    2139  0.5325  0.5552  0.0  1.0
 0                    3988  0.2124  0.1144  0.0  1.0
 1                    3873  0.1103  0.0000  0.0  1.0

--- PctNullSelfRedirectHyperlinks ---
                     count    mean  median  min  max
ExtMetaScriptLinkRT
-1                    2139  0.0879  0.0000  0.0  1.0
 0                    3988  0.0561  0.0028  0.0  1.0
 1                    3873  0.2452  0.0000  0.0  1.0

--- ExtFavicon ---
                     count    mean  median  min  max
ExtMetaScriptLinkRT
-1                    2139  0.3754     0.0    0    1
 0                    3988  0.1815     0.0    0    1
 1                    3873  0.0374     0.0    0    1

--- IframeOrFrame ---
                     count    mean  median  min  max
ExtMetaScriptLinkRT
-1                    2139  0.3104     0.0    0    1
 0                    3988  0.4804     0.0    0    1
 1                    3873  0.2107     0.0    0    1

--- FrequentDomainNameMismatch ---
                     count    mean  median  min  max
ExtMetaScriptLinkRT
-1                    2139  0.6199     1.0    0    1
 0                    3988  0.0657     0.0    0    1
 1                    3873  0.1459     0.0    0    1

--- HostnameLength ---
                     count     mean  median  min  max
ExtMetaScriptLinkRT
-1                    2139  18.2422    17.0    4   84
 0                    3988  17.8511    17.0    6  137
 1                    3873  20.1479    18.0    5  115

--- UrlLength ---
                     count     mean  median  min  max
ExtMetaScriptLinkRT
-1                    2139  66.0173    60.0   12  251
 0                    3988  74.8741    68.0   15  253
 1                    3873  67.8626    60.0   19  240

Cross-tab with major percentage features:

PctExtResourceUrls:
ExtMetaScriptLinkRT      -1       0       1
PctExtResourceUrls
(-0.001, 0.2]        0.0055  0.2672  0.7273
(0.2, 0.4]           0.0572  0.8871  0.0558
(0.4, 0.6]           0.0488  0.9010  0.0502
(0.6, 0.8]           0.0975  0.6229  0.2796
(0.8, 1.0]           0.7966  0.1516  0.0518

PctExtHyperlinks:
ExtMetaScriptLinkRT      -1       0       1
PctExtHyperlinks
(-0.001, 0.2]        0.1189  0.3928  0.4883
(0.2, 0.4]           0.1685  0.6851  0.1464
(0.4, 0.6]           0.2674  0.5487  0.1838
(0.6, 0.8]           0.3527  0.4643  0.1830
(0.8, 1.0]           0.6347  0.1960  0.1694

PctNullSelfRedirectHyperlinks:
ExtMetaScriptLinkRT                -1       0       1
PctNullSelfRedirectHyperlinks
(-0.001, 0.2]                  0.2249  0.4397  0.3354
(0.2, 0.4]                     0.3440  0.4560  0.2000
(0.4, 0.6]                     0.0968  0.2742  0.6290
(0.6, 0.8]                     0.3968  0.3175  0.2857
(0.8, 1.0]                     0.1111  0.0907  0.7982

===========================================================================
5. PctExtNullSelfRedirectHyperlinksRT
===========================================================================

Overall value counts:
PctExtNullSelfRedirectHyperlinksRT
-1    2953
 0     953
 1    6094
Name: count, dtype: int64

--- PctExtHyperlinks ---
                                    count    mean  median  min     max
PctExtNullSelfRedirectHyperlinksRT
-1                                   2953  0.5617  0.8462  0.0  1.0000
 0                                    953  0.3723  0.3750  0.0  0.6667
 1                                   6094  0.0656  0.0343  0.0  0.3099

--- PctNullSelfRedirectHyperlinks ---
                                    count    mean  median  min     max
PctExtNullSelfRedirectHyperlinksRT
-1                                   2953  0.4086  0.0682  0.0  1.0000
 0                                    953  0.0623  0.0120  0.0  0.6667
 1                                   6094  0.0157  0.0000  0.0  0.3037

--- FrequentDomainNameMismatch ---
                                    count    mean  median  min  max
PctExtNullSelfRedirectHyperlinksRT
-1                                   2953  0.5689     1.0    0    1
 0                                    953  0.1522     0.0    0    1
 1                                   6094  0.0538     0.0    0    1

--- PctExtResourceUrls ---
                                    count    mean  median  min  max
PctExtNullSelfRedirectHyperlinksRT
-1                                   2953  0.5525  0.7857  0.0  1.0
 0                                    953  0.4871  0.4444  0.0  1.0
 1                                   6094  0.3009  0.1724  0.0  1.0

--- NumDots ---
                                    count    mean  median  min  max
PctExtNullSelfRedirectHyperlinksRT
-1                                   2953  2.7985     3.0    1   15
 0                                    953  2.2067     2.0    1   11
 1                                   6094  2.3111     2.0    1   21

--- HostnameLength ---
                                    count     mean  median  min  max
PctExtNullSelfRedirectHyperlinksRT
-1                                   2953  20.6983    18.0    4  137
 0                                    953  18.2109    17.0    6   66
 1                                   6094  18.0121    17.0    5  115

--- UrlLength ---
                                    count     mean  median  min  max
PctExtNullSelfRedirectHyperlinksRT
-1                                   2953  62.1382    57.0   12  251
 0                                    953  75.7272    69.0   18  231
 1                                   6094  73.3474    65.0   14  253

Cross-tab with PctNullSelfRedirectHyperlinks:
PctExtNullSelfRedirectHyperlinksRT      -1       0       1
PctNullSelfRedirectHyperlinks
(-0.001001, 0.0]                    0.2400  0.0723  0.6877
(0.0, 0.05]                         0.0371  0.1446  0.8182
(0.05, 0.1]                         0.1969  0.1508  0.6523
(0.1, 0.25]                         0.2596  0.2426  0.4979
(0.25, 0.5]                         0.5246  0.4344  0.0410
(0.5, 1.0]                          0.9891  0.0109  0.0000

===========================================================================
RT ↔ CANDIDATE CORRELATIONS
===========================================================================
                                    AbnormalFormAction  DomainInPaths  \
SubdomainLevelRT                                   NaN        -0.0308
PctExtResourceUrlsRT                               NaN            NaN
AbnormalExtFormActionR                         -0.8188            NaN
ExtMetaScriptLinkRT                                NaN            NaN
PctExtNullSelfRedirectHyperlinksRT                 NaN            NaN

                                    DomainInSubdomains  ExtFavicon  \
SubdomainLevelRT                               -0.7043         NaN
PctExtResourceUrlsRT                               NaN     -0.3276
AbnormalExtFormActionR                             NaN         NaN
ExtMetaScriptLinkRT                                NaN     -0.3361
PctExtNullSelfRedirectHyperlinksRT                 NaN         NaN

                                    ExtFormAction  FrequentDomainNameMismatch  \
SubdomainLevelRT                              NaN                         NaN
PctExtResourceUrlsRT                          NaN                         NaN
AbnormalExtFormActionR                    -0.5278                         NaN
ExtMetaScriptLinkRT                           NaN                     -0.3652
PctExtNullSelfRedirectHyperlinksRT            NaN                     -0.5496

                                    HostnameLength  IframeOrFrame  \
SubdomainLevelRT                           -0.5275            NaN
PctExtResourceUrlsRT                        0.0403        -0.2589
AbnormalExtFormActionR                      0.0186            NaN
ExtMetaScriptLinkRT                         0.1039        -0.1221
PctExtNullSelfRedirectHyperlinksRT         -0.1439            NaN

                                    InsecureForms  NumDashInHostname  NumDots  \
SubdomainLevelRT                              NaN            -0.3596  -0.3439
PctExtResourceUrlsRT                          NaN                NaN   0.0478
AbnormalExtFormActionR                    -0.1114                NaN      NaN
ExtMetaScriptLinkRT                           NaN                NaN      NaN
PctExtNullSelfRedirectHyperlinksRT            NaN                NaN  -0.1538

                                    NumNumericChars  PathLevel  \
SubdomainLevelRT                            -0.0862    -0.0248
PctExtResourceUrlsRT                            NaN        NaN
AbnormalExtFormActionR                          NaN        NaN
ExtMetaScriptLinkRT                             NaN        NaN
PctExtNullSelfRedirectHyperlinksRT              NaN        NaN

                                    PctExtHyperlinks  PctExtResourceUrls  \
SubdomainLevelRT                                 NaN                 NaN
PctExtResourceUrlsRT                         -0.2774             -0.8047
AbnormalExtFormActionR                       -0.0476             -0.1224
ExtMetaScriptLinkRT                          -0.4369             -0.7657
PctExtNullSelfRedirectHyperlinksRT           -0.6562             -0.2969

                                    PctNullSelfRedirectHyperlinks  \
SubdomainLevelRT                                              NaN
PctExtResourceUrlsRT                                          NaN
AbnormalExtFormActionR                                        NaN
ExtMetaScriptLinkRT                                        0.2227
PctExtNullSelfRedirectHyperlinksRT                        -0.5487


In [ ]:
# ============================================================
# STEP 5O — EXACT RT MAPPING CONSISTENCY TEST
# ============================================================
# Purpose:
#   Determine whether each unresolved RT feature can be
#   reproduced exactly from its candidate features.
#
# IMPORTANT:
#   CLASS_LABEL is NOT used.
#   id is NOT used.
#   NO model training.
#   NO prediction.
#   NO model modification.
#
# A candidate mapping is considered deterministic only if:
#
#   identical candidate feature tuple
#             ↓
#   always produces the same RT value
#
# ============================================================

import os
import json
import numpy as np
import pandas as pd

print("=" * 75)
print("STEP 5O — EXACT RT MAPPING CONSISTENCY TEST")
print("=" * 75)

# ============================================================
# RT FEATURES
# ============================================================

RT_FEATURES = [
    "SubdomainLevelRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

# ============================================================
# CANDIDATE GROUPS
# ============================================================

CANDIDATE_GROUPS = {

    "SubdomainLevelRT": [
        "SubdomainLevel",
        "NumDots",
        "HostnameLength",
        "UrlLength",
        "NumDashInHostname",
        "DomainInSubdomains",
        "DomainInPaths",
        "PathLevel",
        "NumNumericChars"
    ],

    "PctExtResourceUrlsRT": [
        "PctExtResourceUrls",
        "PctExtHyperlinks",
        "ExtFavicon",
        "IframeOrFrame",
        "NumDots",
        "HostnameLength",
        "UrlLength"
    ],

    "AbnormalExtFormActionR": [
        "AbnormalFormAction",
        "ExtFormAction",
        "RelativeFormAction",
        "InsecureForms",
        "PctExtHyperlinks",
        "PctExtResourceUrls",
        "HostnameLength",
        "UrlLength"
    ],

    "ExtMetaScriptLinkRT": [
        "PctExtResourceUrls",
        "PctExtHyperlinks",
        "PctNullSelfRedirectHyperlinks",
        "ExtFavicon",
        "IframeOrFrame",
        "FrequentDomainNameMismatch",
        "HostnameLength",
        "UrlLength"
    ],

    "PctExtNullSelfRedirectHyperlinksRT": [
        "PctExtHyperlinks",
        "PctNullSelfRedirectHyperlinks",
        "FrequentDomainNameMismatch",
        "PctExtResourceUrls",
        "NumDots",
        "HostnameLength",
        "UrlLength"
    ]
}

# ============================================================
# LOAD DATASET
# ============================================================

DATASET_PATH = "/content/Phishing_Legitimate_full.csv"

df = pd.read_csv(DATASET_PATH)

print("\nDataset:", df.shape)

# ============================================================
# RESULTS
# ============================================================

all_results = {}

# ============================================================
# EXACT CONSISTENCY FUNCTION
# ============================================================

def analyze_exact_mapping(
    data,
    rt_feature,
    candidates
):

    subset = data[
        candidates + [rt_feature]
    ].copy()

    # --------------------------------------------------------
    # Group identical candidate tuples
    # --------------------------------------------------------

    grouped = (
        subset
        .groupby(
            candidates,
            dropna=False
        )[rt_feature]
        .agg(
            rows="size",
            unique_rt="nunique"
        )
        .reset_index()
    )

    # --------------------------------------------------------
    # Conflicting groups:
    # same candidate tuple but multiple RT values
    # --------------------------------------------------------

    conflicts = grouped[
        grouped["unique_rt"] > 1
    ].copy()

    # --------------------------------------------------------
    # Number of rows belonging to conflicting groups
    # --------------------------------------------------------

    if len(conflicts) > 0:

        conflict_keys = conflicts[
            candidates
        ]

        conflicting_rows = subset.merge(
            conflict_keys,
            on=candidates,
            how="inner"
        )

    else:

        conflicting_rows = pd.DataFrame(
            columns=subset.columns
        )

    total_rows = len(subset)

    conflict_row_count = len(
        conflicting_rows
    )

    consistent_row_count = (
        total_rows - conflict_row_count
    )

    exact_consistency = (
        consistent_row_count / total_rows
        if total_rows > 0
        else 0
    )

    # --------------------------------------------------------
    # Unique candidate combinations
    # --------------------------------------------------------

    unique_candidate_count = len(grouped)

    # --------------------------------------------------------
    # Number of completely consistent groups
    # --------------------------------------------------------

    consistent_group_count = len(
        grouped[
            grouped["unique_rt"] == 1
        ]
    )

    # --------------------------------------------------------
    # Majority-value reconstruction accuracy
    # --------------------------------------------------------

    majority_map = (
        subset
        .groupby(
            candidates,
            dropna=False
        )[rt_feature]
        .agg(
            lambda x: x.value_counts().index[0]
        )
        .reset_index(
            name="predicted_rt"
        )
    )

    reconstructed = subset.merge(
        majority_map,
        on=candidates,
        how="left"
    )

    reconstruction_accuracy = (
        reconstructed["predicted_rt"]
        == reconstructed[rt_feature]
    ).mean()

    return {
        "total_rows": int(total_rows),

        "unique_candidate_combinations":
            int(unique_candidate_count),

        "consistent_combinations":
            int(consistent_group_count),

        "conflicting_combinations":
            int(len(conflicts)),

        "conflicting_rows":
            int(conflict_row_count),

        "exact_row_consistency":
            float(exact_consistency),

        "majority_reconstruction_accuracy":
            float(reconstruction_accuracy),

        "conflicts": conflicts,

        "conflicting_rows_df":
            conflicting_rows
    }


# ============================================================
# RUN ALL FIVE
# ============================================================

for rt_feature in RT_FEATURES:

    candidates = CANDIDATE_GROUPS[
        rt_feature
    ]

    print("\n" + "=" * 75)
    print(rt_feature)
    print("=" * 75)

    print("\nCandidate features:")

    for c in candidates:
        print(" -", c)

    result = analyze_exact_mapping(
        df,
        rt_feature,
        candidates
    )

    all_results[rt_feature] = result

    print(
        "\nTotal rows:",
        result["total_rows"]
    )

    print(
        "Unique candidate combinations:",
        result["unique_candidate_combinations"]
    )

    print(
        "Consistent combinations:",
        result["consistent_combinations"]
    )

    print(
        "Conflicting combinations:",
        result["conflicting_combinations"]
    )

    print(
        "Rows in conflicting combinations:",
        result["conflicting_rows"]
    )

    print(
        "Exact row consistency:",
        f"{result['exact_row_consistency'] * 100:.4f}%"
    )

    print(
        "Majority reconstruction accuracy:",
        f"{result['majority_reconstruction_accuracy'] * 100:.4f}%"
    )

    # --------------------------------------------------------
    # Show first conflicts
    # --------------------------------------------------------

    if len(result["conflicts"]) > 0:

        print(
            "\nFIRST CONFLICTING CANDIDATE COMBINATIONS:"
        )

        display(
            result["conflicts"]
            .head(10)
        )

    else:

        print(
            "\n[PASS] No conflicting candidate combinations."
        )


# ============================================================
# SPECIAL TEST — SUBDOMAIN LEVEL 2 AND 3
# ============================================================

print("\n" + "=" * 75)
print("SPECIAL ANALYSIS — SUBDOMAIN LEVEL 2 / 3")
print("=" * 75)

for level in [2, 3]:

    subset = df[
        df["SubdomainLevel"] == level
    ]

    print(
        f"\nSubdomainLevel = {level}"
    )

    print(
        "Rows:",
        len(subset)
    )

    print(
        subset[
            [
                "SubdomainLevel",
                "NumDots",
                "HostnameLength",
                "UrlLength",
                "NumDashInHostname",
                "DomainInSubdomains",
                "DomainInPaths",
                "PathLevel",
                "NumNumericChars",
                "SubdomainLevelRT"
            ]
        ]
        .sort_values(
            "SubdomainLevelRT"
        )
        .head(30)
        .to_string(index=False)
    )


# ============================================================
# SAFETY CHECK
# ============================================================

print("\n" + "=" * 75)
print("SAFETY CHECK")
print("=" * 75)

for rt_feature in RT_FEATURES:

    candidates = CANDIDATE_GROUPS[
        rt_feature
    ]

    unsafe = [
        x for x in candidates
        if x in ["CLASS_LABEL", "id"]
    ]

    print(
        f"{rt_feature:40s} "
        f"CLASS_LABEL/id used = {len(unsafe) > 0}"
    )


# ============================================================
# CHECKPOINT SUMMARY
# ============================================================

summary = {}

for rt_feature, result in all_results.items():

    summary[rt_feature] = {
        "total_rows":
            result["total_rows"],

        "unique_candidate_combinations":
            result["unique_candidate_combinations"],

        "consistent_combinations":
            result["consistent_combinations"],

        "conflicting_combinations":
            result["conflicting_combinations"],

        "conflicting_rows":
            result["conflicting_rows"],

        "exact_row_consistency":
            result["exact_row_consistency"],

        "majority_reconstruction_accuracy":
            result["majority_reconstruction_accuracy"]
    }


# ============================================================
# CHECKPOINT
# ============================================================

CHECKPOINT_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints/"
    "step_5O_exact_rt_mapping_test.json"
)

checkpoint = {
    "stage": "5O",

    "purpose": (
        "Test exact deterministic reproducibility "
        "of unresolved RT features from candidate "
        "non-target features."
    ),

    "dataset_rows": int(len(df)),

    "training_performed": False,
    "retraining_performed": False,
    "prediction_performed": False,
    "model_modified": False,

    "target_used_for_mapping": False,
    "id_used_for_mapping": False,

    "candidate_groups": CANDIDATE_GROUPS,

    "results": summary
}


def json_safe(obj):

    if isinstance(obj, dict):

        return {
            str(k): json_safe(v)
            for k, v in obj.items()
        }

    if isinstance(obj, (list, tuple)):

        return [
            json_safe(v)
            for v in obj
        ]

    if isinstance(obj, np.integer):
        return int(obj)

    if isinstance(obj, np.floating):

        if np.isnan(obj):
            return None

        return float(obj)

    if isinstance(obj, np.bool_):
        return bool(obj)

    if isinstance(obj, np.ndarray):
        return obj.tolist()

    return obj


checkpoint = json_safe(
    checkpoint
)

with open(
    CHECKPOINT_PATH,
    "w"
) as f:

    json.dump(
        checkpoint,
        f,
        indent=2
    )

# ============================================================
# VERIFY
# ============================================================

with open(
    CHECKPOINT_PATH,
    "r"
) as f:

    verified = json.load(f)

print("\n" + "=" * 75)
print("STEP 5O CHECKPOINT SAVED")
print("=" * 75)

print(
    "Checkpoint:",
    CHECKPOINT_PATH
)

print(
    "[PASS] Checkpoint JSON verified successfully."
)

print(
    "No training performed."
)

print(
    "No prediction performed."
)

print(
    "No model modified."
)

print("=" * 75)
print("END STEP 5O")
print("=" * 75)

===========================================================================
STEP 5O — EXACT RT MAPPING CONSISTENCY TEST
===========================================================================

Dataset: (10000, 50)

===========================================================================
SubdomainLevelRT
===========================================================================

Candidate features:
 - SubdomainLevel
 - NumDots
 - HostnameLength
 - UrlLength
 - NumDashInHostname
 - DomainInSubdomains
 - DomainInPaths
 - PathLevel
 - NumNumericChars

Total rows: 10000
Unique candidate combinations: 9123
Consistent combinations: 9123
Conflicting combinations: 0
Rows in conflicting combinations: 0
Exact row consistency: 100.0000%
Majority reconstruction accuracy: 100.0000%

[PASS] No conflicting candidate combinations.

===========================================================================
PctExtResourceUrlsRT
===========================================================================

Candidate features:
 - PctExtResourceUrls
 - PctExtHyperlinks
 - ExtFavicon
 - IframeOrFrame
 - NumDots
 - HostnameLength
 - UrlLength

Total rows: 10000
Unique candidate combinations: 8917
Consistent combinations: 8916
Conflicting combinations: 1
Rows in conflicting combinations: 2
Exact row consistency: 99.9800%
Majority reconstruction accuracy: 99.9900%

FIRST CONFLICTING CANDIDATE COMBINATIONS:

,PctExtResourceUrls,PctExtHyperlinks,ExtFavicon,IframeOrFrame,NumDots,HostnameLength,UrlLength,rows,unique_rt
7503,1.0,0.0,0,0,2,15,47,2,2

===========================================================================
AbnormalExtFormActionR
===========================================================================

Candidate features:
 - AbnormalFormAction
 - ExtFormAction
 - RelativeFormAction
 - InsecureForms
 - PctExtHyperlinks
 - PctExtResourceUrls
 - HostnameLength
 - UrlLength

Total rows: 10000
Unique candidate combinations: 8730
Consistent combinations: 8730
Conflicting combinations: 0
Rows in conflicting combinations: 0
Exact row consistency: 100.0000%
Majority reconstruction accuracy: 100.0000%

[PASS] No conflicting candidate combinations.

===========================================================================
ExtMetaScriptLinkRT
===========================================================================

Candidate features:
 - PctExtResourceUrls
 - PctExtHyperlinks
 - PctNullSelfRedirectHyperlinks
 - ExtFavicon
 - IframeOrFrame
 - FrequentDomainNameMismatch
 - HostnameLength
 - UrlLength

Total rows: 10000
Unique candidate combinations: 8753
Consistent combinations: 8739
Conflicting combinations: 14
Rows in conflicting combinations: 31
Exact row consistency: 99.6900%
Majority reconstruction accuracy: 99.8600%

FIRST CONFLICTING CANDIDATE COMBINATIONS:

,PctExtResourceUrls,PctExtHyperlinks,PctNullSelfRedirectHyperlinks,ExtFavicon,IframeOrFrame,FrequentDomainNameMismatch,HostnameLength,UrlLength,rows,unique_rt
357,0.0,0.0,0.0,0,0,0,18,85,2,2
7390,1.0,0.0,0.0,0,0,1,14,42,2,2
8312,1.0,1.0,0.0,0,0,1,12,67,2,2
8398,1.0,1.0,0.0,0,0,1,19,41,2,2
8410,1.0,1.0,0.0,0,0,1,20,47,2,2
8497,1.0,1.0,0.0,0,1,1,13,57,2,2
8563,1.0,1.0,0.0,0,1,1,20,42,2,2
8572,1.0,1.0,0.0,0,1,1,20,52,2,2
8573,1.0,1.0,0.0,0,1,1,20,53,4,2
8577,1.0,1.0,0.0,0,1,1,20,57,2,2

===========================================================================
PctExtNullSelfRedirectHyperlinksRT
===========================================================================

Candidate features:
 - PctExtHyperlinks
 - PctNullSelfRedirectHyperlinks
 - FrequentDomainNameMismatch
 - PctExtResourceUrls
 - NumDots
 - HostnameLength
 - UrlLength

Total rows: 10000
Unique candidate combinations: 9003
Consistent combinations: 9003
Conflicting combinations: 0
Rows in conflicting combinations: 0
Exact row consistency: 100.0000%
Majority reconstruction accuracy: 100.0000%

[PASS] No conflicting candidate combinations.

===========================================================================
SPECIAL ANALYSIS — SUBDOMAIN LEVEL 2 / 3
===========================================================================

SubdomainLevel = 2
Rows: 272
 SubdomainLevel  NumDots  HostnameLength  UrlLength  NumDashInHostname  DomainInSubdomains  DomainInPaths  PathLevel  NumNumericChars  SubdomainLevelRT
              2        4              26        180                  0                   0              0          4               24                 0
              2        4              29         67                  0                   0              1          3               10                 0
              2        3              19         86                  0                   0              1         10               11                 0
              2        3              28         97                  0                   0              1          8                8                 0
              2        3              19         81                  0                   0              1          8                7                 0
              2        3              27         86                  0                   0              1          6                8                 0
              2        3              29         80                  0                   0              1          8                6                 0
              2        5              24        196                  0                   0              0          4               53                 0
              2        3              37        126                  0                   0              1         12                0                 0
              2        4              17         79                  0                   0              1          5                4                 0
              2        5              16        146                  0                   1              1          4                0                 0
              2        4              20         84                  0                   0              0          1                2                 0
              2        5              16         70                  0                   1              0          2                1                 0
              2        4              25        130                  0                   0              0          2                5                 0
              2        3              22         78                  0                   0              0          2                0                 0
              2        3              24        125                  0                   0              1         14                0                 0
              2        4              22        118                  0                   0              0          1                5                 0
              2        3              22        147                  0                   0              0          5               11                 0
              2        3              22        130                  0                   0              1          4                0                 0
              2        5              21         64                  0                   0              0          2                4                 0
              2        3              24         78                  0                   1              0          2                8                 0
              2        4              24         70                  0                   0              0          2                8                 0
              2        3              34         76                  0                   0              1          3                5                 0
              2        3              25         80                  0                   0              1          6                0                 0
              2        3              23        118                  0                   0              0          4               14                 0
              2        5              22        134                  0                   0              0          2                7                 0
              2        5              29         62                  0                   0              0          1                5                 0
              2        3              18         72                  0                   0              1          3                0                 0
              2        5              20         98                  0                   1              1          2                8                 0
              2        4              23         68                  1                   0              0          3                4                 0

SubdomainLevel = 3
Rows: 22
 SubdomainLevel  NumDots  HostnameLength  UrlLength  NumDashInHostname  DomainInSubdomains  DomainInPaths  PathLevel  NumNumericChars  SubdomainLevelRT
              3        5              37         72                  4                   1              0          2               13                -1
              3        6              32         59                  0                   1              0          2                0                -1
              3        4              44        100                  0                   0              0          5               25                -1
              3        7              31        199                  0                   1              1         10               24                -1
              3        4              66        107                  4                   1              0          2               22                -1
              3        4              32         56                  0                   1              1          4                3                -1
              3        5              33         84                  0                   1              0          3                4                -1
              3        5              37         65                  1                   1              0          2                0                -1
              3        6              32         84                  0                   0              1          6                0                -1
              3        5              40         91                  4                   0              0          5               23                -1
              3        5              36         59                  0                   1              0          2                7                -1
              3        5              36         65                  0                   1              0          2                7                -1
              3        5              23         41                  0                   0              0          1                3                -1
              3        4              30         76                  0                   0              0          4               10                -1
              3        4              22        129                  0                   0              0          1                5                -1
              3        5              22         48                  0                   0              0          2                2                -1
              3        4              29        144                  0                   1              0          2                5                -1
              3        5              39         84                  1                   0              1          1                8                -1
              3        5              29         67                  0                   0              0          1               15                -1
              3        5              45         76                  0                   0              0          2                0                 0
              3        5              37         61                  3                   1              0          3                0                 0
              3        5              45         76                  0                   0              0          2                0                 0

===========================================================================
SAFETY CHECK
===========================================================================
SubdomainLevelRT                         CLASS_LABEL/id used = False
PctExtResourceUrlsRT                     CLASS_LABEL/id used = False
AbnormalExtFormActionR                   CLASS_LABEL/id used = False
ExtMetaScriptLinkRT                      CLASS_LABEL/id used = False
PctExtNullSelfRedirectHyperlinksRT       CLASS_LABEL/id used = False

===========================================================================
STEP 5O CHECKPOINT SAVED
===========================================================================
Checkpoint: /content/drive/MyDrive/PhishShield_AI/checkpoints/step_5O_exact_rt_mapping_test.json
[PASS] Checkpoint JSON verified successfully.
No training performed.
No prediction performed.
No model modified.
===========================================================================
END STEP 5O
===========================================================================

In [ ]:
# ============================================================
# STEP 5P — FIND ADDITIONAL DISCRIMINATORS FOR RT CONFLICTS
# ============================================================

import os
import json
import pandas as pd
import numpy as np

print("=" * 75)
print("STEP 5P — FIND ADDITIONAL DISCRIMINATORS FOR RT CONFLICTS")
print("=" * 75)

# ------------------------------------------------------------
# 1. Load dataset
# ------------------------------------------------------------
DATA_PATH = "/content/Phishing_Legitimate_full.csv"

df = pd.read_csv(DATA_PATH)

print(f"\nDataset shape: {df.shape}")

# ------------------------------------------------------------
# 2. Define RT targets and the candidate features already tested
# ------------------------------------------------------------
rt_targets = [
    "PctExtResourceUrlsRT",
    "ExtMetaScriptLinkRT"
]

candidate_features = {
    "PctExtResourceUrlsRT": [
        "PctExtResourceUrls",
        "PctExtHyperlinks",
        "ExtFavicon",
        "IframeOrFrame",
        "NumDots",
        "HostnameLength",
        "UrlLength"
    ],

    "ExtMetaScriptLinkRT": [
        "PctExtResourceUrls",
        "PctExtHyperlinks",
        "PctNullSelfRedirectHyperlinks",
        "ExtFavicon",
        "IframeOrFrame",
        "FrequentDomainNameMismatch",
        "HostnameLength",
        "UrlLength"
    ]
}

# Never use target or ID for reconstruction
EXCLUDED = {
    "CLASS_LABEL",
    "id",
    "PctExtResourceUrlsRT",
    "ExtMetaScriptLinkRT"
}

# ------------------------------------------------------------
# 3. Find exact conflicting combinations
# ------------------------------------------------------------
conflict_rows = {}

for target in rt_targets:

    print("\n" + "=" * 75)
    print(f"ANALYSING: {target}")
    print("=" * 75)

    cols = candidate_features[target]

    grouped = (
        df.groupby(cols, dropna=False)[target]
        .nunique()
        .reset_index(name="unique_rt")
    )

    conflicts = grouped[grouped["unique_rt"] > 1].copy()

    print(f"Conflicting candidate combinations: {len(conflicts)}")

    if len(conflicts) == 0:
        print("[PASS] No conflicts.")
        conflict_rows[target] = pd.DataFrame()
        continue

    # --------------------------------------------------------
    # Recover the actual rows belonging to conflicting groups
    # --------------------------------------------------------
    conflict_key = conflicts[cols].copy()

    merged = df.merge(
        conflict_key,
        on=cols,
        how="inner"
    )

    conflict_rows[target] = merged.copy()

    print(f"Rows involved in conflicts: {len(merged)}")
    print(f"Unique RT values: {sorted(merged[target].unique().tolist())}")

    print("\nConflicting rows:")
    display(
        merged[
            [target] + cols +
            [c for c in df.columns
             if c not in EXCLUDED
             and c not in cols
             and c != target]
        ].head(50)
    )

# ------------------------------------------------------------
# 4. Search ALL other features for exact discrimination
# ------------------------------------------------------------
print("\n" + "=" * 75)
print("SEARCHING ALL OTHER FEATURES FOR EXACT DISCRIMINATORS")
print("=" * 75)

discriminator_results = {}

for target in rt_targets:

    conflict_df = conflict_rows[target]

    if conflict_df.empty:
        discriminator_results[target] = []
        continue

    tested = set(candidate_features[target])

    remaining_features = [
        c for c in df.columns
        if c not in EXCLUDED
        and c not in tested
    ]

    print("\n" + "-" * 75)
    print(f"Target: {target}")
    print(f"Remaining features to test: {len(remaining_features)}")

    results = []

    for feature in remaining_features:

        # For each individual feature, check whether
        # feature value uniquely determines the RT value
        temp = (
            conflict_df.groupby(feature, dropna=False)[target]
            .nunique()
        )

        conflicting_values = int((temp > 1).sum())

        # Number of unique feature values
        unique_values = int(temp.shape[0])

        # Number of perfectly consistent groups
        consistent_values = int((temp == 1).sum())

        if conflicting_values == 0:
            results.append({
                "feature": feature,
                "unique_values": unique_values,
                "consistent_values": consistent_values,
                "conflicting_values": conflicting_values,
                "exact": True
            })

    discriminator_results[target] = results

    if results:
        print("\n[FOUND] Exact single-feature discriminators:")
        for r in results:
            print(
                f" - {r['feature']} "
                f"(unique values={r['unique_values']})"
            )
    else:
        print("\n[INFO] No single remaining feature perfectly separates the conflict.")

# ------------------------------------------------------------
# 5. Search pairs of remaining features
# ------------------------------------------------------------
print("\n" + "=" * 75)
print("SEARCHING FEATURE PAIRS")
print("=" * 75)

pair_results = {}

for target in rt_targets:

    conflict_df = conflict_rows[target]

    if conflict_df.empty:
        pair_results[target] = []
        continue

    tested = set(candidate_features[target])

    remaining_features = [
        c for c in df.columns
        if c not in EXCLUDED
        and c not in tested
    ]

    results = []

    # Test every pair.
    for i in range(len(remaining_features)):
        for j in range(i + 1, len(remaining_features)):

            f1 = remaining_features[i]
            f2 = remaining_features[j]

            temp = (
                conflict_df.groupby(
                    [f1, f2],
                    dropna=False
                )[target]
                .nunique()
            )

            if (temp > 1).sum() == 0:

                results.append({
                    "feature_1": f1,
                    "feature_2": f2,
                    "unique_combinations": int(temp.shape[0]),
                    "exact": True
                })

    pair_results[target] = results

    print("\n" + "-" * 75)
    print(f"Target: {target}")

    if results:
        print(f"[FOUND] Exact feature pairs: {len(results)}")

        for r in results[:20]:
            print(
                f" - {r['feature_1']} + {r['feature_2']} "
                f"(unique combinations={r['unique_combinations']})"
            )
    else:
        print("[INFO] No exact feature pair found.")

# ------------------------------------------------------------
# 6. Final summary
# ------------------------------------------------------------
print("\n" + "=" * 75)
print("STEP 5P SUMMARY")
print("=" * 75)

for target in rt_targets:

    print(f"\n{target}")

    single = discriminator_results.get(target, [])
    pairs = pair_results.get(target, [])

    print(f"Exact single-feature discriminators: {len(single)}")
    print(f"Exact feature pairs: {len(pairs)}")

    if single:
        print("Single-feature candidates:")
        for r in single:
            print("  ", r["feature"])

    if pairs:
        print("Pair candidates:")
        for r in pairs[:10]:
            print(
                "  ",
                r["feature_1"],
                "+",
                r["feature_2"]
            )

# ------------------------------------------------------------
# 7. Save checkpoint
# ------------------------------------------------------------
checkpoint_dir = "/content/drive/MyDrive/PhishShield_AI/checkpoints"
os.makedirs(checkpoint_dir, exist_ok=True)

checkpoint_path = os.path.join(
    checkpoint_dir,
    "step_5P_rt_discriminator_search.json"
)

checkpoint = {
    "stage": "Step 5P",
    "dataset_shape": list(df.shape),
    "targets": rt_targets,
    "class_label_used": False,
    "id_used": False,
    "training_performed": False,
    "prediction_performed": False,
    "model_modified": False,
    "conflict_counts": {
        target: int(len(conflict_rows[target]))
        for target in rt_targets
    },
    "single_feature_discriminators": {
        target: [
            r["feature"]
            for r in discriminator_results[target]
        ]
        for target in rt_targets
    },
    "feature_pair_discriminators": {
        target: [
            [r["feature_1"], r["feature_2"]]
            for r in pair_results[target]
        ]
        for target in rt_targets
    }
}

with open(checkpoint_path, "w") as f:
    json.dump(checkpoint, f, indent=2)

# Verify checkpoint
with open(checkpoint_path, "r") as f:
    verified = json.load(f)

print("\n" + "=" * 75)
print("STEP 5P CHECKPOINT SAVED")
print("=" * 75)
print(f"Checkpoint: {checkpoint_path}")
print("[PASS] JSON checkpoint verified successfully.")
print("No training performed.")
print("No prediction performed.")
print("No model modified.")
print("=" * 75)
print("END STEP 5P")
print("=" * 75)

===========================================================================
STEP 5P — FIND ADDITIONAL DISCRIMINATORS FOR RT CONFLICTS
===========================================================================

Dataset shape: (10000, 50)

===========================================================================
ANALYSING: PctExtResourceUrlsRT
===========================================================================
Conflicting candidate combinations: 1
Rows involved in conflicts: 2
Unique RT values: [-1, 1]

Conflicting rows:

,PctExtResourceUrlsRT,PctExtResourceUrls,PctExtHyperlinks,ExtFavicon,IframeOrFrame,NumDots,HostnameLength,UrlLength,SubdomainLevel,PathLevel,...,FakeLinkInStatusBar,RightClickDisabled,PopUpWindow,SubmitInfoToEmail,MissingTitle,ImagesOnlyInForm,SubdomainLevelRT,UrlLengthRT,AbnormalExtFormActionR,PctExtNullSelfRedirectHyperlinksRT
0,-1,1.0,0.0,0,0,2,15,47,0,3,...,0,0,0,0,0,0,1,1,1,1
1,1,1.0,0.0,0,0,2,15,47,0,3,...,0,0,0,0,0,0,1,1,1,-1

===========================================================================
ANALYSING: ExtMetaScriptLinkRT
===========================================================================
Conflicting candidate combinations: 14
Rows involved in conflicts: 31
Unique RT values: [-1, 0, 1]

Conflicting rows:

,ExtMetaScriptLinkRT,PctExtResourceUrls,PctExtHyperlinks,PctNullSelfRedirectHyperlinks,ExtFavicon,IframeOrFrame,FrequentDomainNameMismatch,HostnameLength,UrlLength,NumDots,...,FakeLinkInStatusBar,RightClickDisabled,PopUpWindow,SubmitInfoToEmail,MissingTitle,ImagesOnlyInForm,SubdomainLevelRT,UrlLengthRT,AbnormalExtFormActionR,PctExtNullSelfRedirectHyperlinksRT
0,-1,1.0,1.0,0.0,0,1,1,22,54,3,...,0,0,0,0,0,0,1,0,0,-1
1,-1,1.0,1.0,0.0,0,1,1,13,57,3,...,0,0,0,0,0,0,1,0,1,-1
2,-1,1.0,1.0,0.0,0,1,1,20,52,2,...,0,0,0,0,0,0,1,1,1,-1
3,-1,1.0,1.0,0.0,0,1,1,22,58,3,...,0,0,0,0,0,0,1,0,0,-1
4,1,0.0,0.0,0.0,0,0,0,18,85,1,...,0,0,0,0,0,0,1,-1,1,1
5,-1,1.0,1.0,0.0,0,1,1,22,63,3,...,0,0,0,0,0,0,1,0,0,-1
6,-1,1.0,1.0,0.0,0,0,1,19,41,2,...,0,0,0,0,0,0,1,1,1,-1
7,-1,1.0,1.0,0.0,0,1,1,20,57,3,...,0,0,0,0,0,0,1,0,0,-1
8,1,1.0,0.0,0.0,0,0,1,14,42,4,...,0,0,0,0,1,0,1,1,1,1
9,-1,1.0,0.0,0.0,0,0,1,14,42,3,...,0,0,0,0,0,0,1,1,0,1
10,-1,1.0,1.0,0.0,0,0,1,12,67,5,...,0,0,0,0,0,0,1,0,1,-1
11,1,1.0,1.0,0.0,0,1,1,13,57,4,...,0,0,0,0,1,0,1,0,0,-1
12,-1,1.0,1.0,0.0,0,1,1,20,53,4,...,0,0,0,0,0,0,1,1,0,-1
13,-1,1.0,1.0,0.0,0,1,1,20,53,4,...,0,0,0,0,0,0,1,1,0,-1
14,-1,1.0,1.0,0.0,0,1,1,20,53,4,...,0,0,0,0,0,0,1,1,0,-1
15,1,1.0,1.0,0.0,0,1,1,20,57,4,...,0,0,0,0,0,0,1,0,0,-1
16,1,1.0,1.0,0.0,0,1,1,20,53,4,...,0,0,0,0,0,0,1,1,0,-1
17,1,1.0,1.0,0.0,0,1,1,20,52,4,...,0,0,0,0,0,0,1,1,0,-1
18,-1,1.0,1.0,0.0,0,0,1,20,47,3,...,0,0,0,0,0,0,1,1,1,-1
19,1,1.0,1.0,0.0,0,0,1,12,67,4,...,0,0,0,0,0,0,1,0,0,-1
20,1,1.0,1.0,0.0,0,1,1,22,63,3,...,0,0,0,0,0,0,1,0,0,-1
21,1,1.0,1.0,0.0,0,1,1,22,58,3,...,0,0,0,0,0,0,1,0,1,-1
22,1,1.0,1.0,0.0,0,1,1,22,54,3,...,0,0,0,0,0,0,1,0,1,-1
23,1,1.0,1.0,0.0,0,1,1,22,58,3,...,0,0,0,0,0,0,1,0,1,-1
24,1,1.0,1.0,0.0,0,1,1,22,55,3,...,0,0,0,0,0,0,1,0,0,-1
25,-1,1.0,1.0,0.0,0,1,1,20,42,2,...,0,0,0,0,0,0,1,1,1,-1
26,-1,1.0,1.0,0.0,0,1,1,22,55,2,...,0,0,0,0,0,0,1,0,1,-1
27,1,1.0,1.0,0.0,0,1,1,20,42,3,...,0,0,0,0,1,0,1,1,1,-1
28,1,1.0,1.0,0.0,0,0,1,20,47,2,...,0,0,0,0,0,0,1,1,1,-1
29,0,0.0,0.0,0.0,0,0,0,18,85,5,...,0,0,0,0,0,0,0,-1,1,1
30,1,1.0,1.0,0.0,0,0,1,19,41,3,...,0,0,0,0,0,0,1,1,1,-1

===========================================================================
SEARCHING ALL OTHER FEATURES FOR EXACT DISCRIMINATORS
===========================================================================

---------------------------------------------------------------------------
Target: PctExtResourceUrlsRT
Remaining features to test: 39

[FOUND] Exact single-feature discriminators:
 - RandomString (unique values=2)
 - PctNullSelfRedirectHyperlinks (unique values=2)
 - PctExtNullSelfRedirectHyperlinksRT (unique values=2)

---------------------------------------------------------------------------
Target: ExtMetaScriptLinkRT
Remaining features to test: 38

[INFO] No single remaining feature perfectly separates the conflict.

===========================================================================
SEARCHING FEATURE PAIRS
===========================================================================

---------------------------------------------------------------------------
Target: PctExtResourceUrlsRT
[FOUND] Exact feature pairs: 111
 - SubdomainLevel + RandomString (unique combinations=2)
 - SubdomainLevel + PctNullSelfRedirectHyperlinks (unique combinations=2)
 - SubdomainLevel + PctExtNullSelfRedirectHyperlinksRT (unique combinations=2)
 - PathLevel + RandomString (unique combinations=2)
 - PathLevel + PctNullSelfRedirectHyperlinks (unique combinations=2)
 - PathLevel + PctExtNullSelfRedirectHyperlinksRT (unique combinations=2)
 - NumDash + RandomString (unique combinations=2)
 - NumDash + PctNullSelfRedirectHyperlinks (unique combinations=2)
 - NumDash + PctExtNullSelfRedirectHyperlinksRT (unique combinations=2)
 - NumDashInHostname + RandomString (unique combinations=2)
 - NumDashInHostname + PctNullSelfRedirectHyperlinks (unique combinations=2)
 - NumDashInHostname + PctExtNullSelfRedirectHyperlinksRT (unique combinations=2)
 - AtSymbol + RandomString (unique combinations=2)
 - AtSymbol + PctNullSelfRedirectHyperlinks (unique combinations=2)
 - AtSymbol + PctExtNullSelfRedirectHyperlinksRT (unique combinations=2)
 - TildeSymbol + RandomString (unique combinations=2)
 - TildeSymbol + PctNullSelfRedirectHyperlinks (unique combinations=2)
 - TildeSymbol + PctExtNullSelfRedirectHyperlinksRT (unique combinations=2)
 - NumUnderscore + RandomString (unique combinations=2)
 - NumUnderscore + PctNullSelfRedirectHyperlinks (unique combinations=2)

---------------------------------------------------------------------------
Target: ExtMetaScriptLinkRT
[INFO] No exact feature pair found.

===========================================================================
STEP 5P SUMMARY
===========================================================================

PctExtResourceUrlsRT
Exact single-feature discriminators: 3
Exact feature pairs: 111
Single-feature candidates:
   RandomString
   PctNullSelfRedirectHyperlinks
   PctExtNullSelfRedirectHyperlinksRT
Pair candidates:
   SubdomainLevel + RandomString
   SubdomainLevel + PctNullSelfRedirectHyperlinks
   SubdomainLevel + PctExtNullSelfRedirectHyperlinksRT
   PathLevel + RandomString
   PathLevel + PctNullSelfRedirectHyperlinks
   PathLevel + PctExtNullSelfRedirectHyperlinksRT
   NumDash + RandomString
   NumDash + PctNullSelfRedirectHyperlinks
   NumDash + PctExtNullSelfRedirectHyperlinksRT
   NumDashInHostname + RandomString

ExtMetaScriptLinkRT
Exact single-feature discriminators: 0
Exact feature pairs: 0

===========================================================================
STEP 5P CHECKPOINT SAVED
===========================================================================
Checkpoint: /content/drive/MyDrive/PhishShield_AI/checkpoints/step_5P_rt_discriminator_search.json
[PASS] JSON checkpoint verified successfully.
No training performed.
No prediction performed.
No model modified.
===========================================================================
END STEP 5P
===========================================================================

In [ ]:
# ============================================================
# STEP 5Q — DEEP ANALYSIS OF ExtMetaScriptLinkRT CONFLICTS
# ============================================================

import os
import json
import pandas as pd
import numpy as np

from itertools import combinations
from sklearn.tree import DecisionTreeClassifier, export_text

print("=" * 75)
print("STEP 5Q — DEEP ANALYSIS OF ExtMetaScriptLinkRT CONFLICTS")
print("=" * 75)

# ------------------------------------------------------------
# 1. Load dataset
# ------------------------------------------------------------

DATA_PATH = "/content/Phishing_Legitimate_full.csv"

df = pd.read_csv(DATA_PATH)

TARGET = "ExtMetaScriptLinkRT"

print(f"\nDataset shape: {df.shape}")

# ------------------------------------------------------------
# 2. Candidate features previously used
# ------------------------------------------------------------

previous_candidates = [
    "PctExtResourceUrls",
    "PctExtHyperlinks",
    "PctNullSelfRedirectHyperlinks",
    "ExtFavicon",
    "IframeOrFrame",
    "FrequentDomainNameMismatch",
    "HostnameLength",
    "UrlLength"
]

EXCLUDED = {
    "CLASS_LABEL",
    "id",
    TARGET
}

# ------------------------------------------------------------
# 3. Identify the exact conflicting combinations
# ------------------------------------------------------------

grouped = (
    df.groupby(previous_candidates, dropna=False)[TARGET]
      .nunique()
      .reset_index(name="unique_rt")
)

conflict_groups = grouped[grouped["unique_rt"] > 1].copy()

print("\nConflicting candidate combinations:")
print(len(conflict_groups))

# Recover actual rows
conflict_df = df.merge(
    conflict_groups[previous_candidates],
    on=previous_candidates,
    how="inner"
).copy()

print(f"Rows involved: {len(conflict_df)}")

print("\nRT distribution among conflicting rows:")
print(conflict_df[TARGET].value_counts().sort_index())

# ------------------------------------------------------------
# 4. Show all 31 rows with ALL features
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("ALL CONFLICTING ROWS")
print("=" * 75)

display(
    conflict_df[
        [c for c in df.columns
         if c not in {"CLASS_LABEL", "id"}]
    ].sort_values(TARGET)
)

# ------------------------------------------------------------
# 5. Search exact SINGLE FEATURES
# ------------------------------------------------------------

remaining_features = [
    c for c in df.columns
    if c not in EXCLUDED
    and c not in previous_candidates
]

print("\n" + "=" * 75)
print("SINGLE FEATURE ANALYSIS")
print("=" * 75)

single_results = []

for feature in remaining_features:

    nunique_by_value = (
        conflict_df.groupby(feature, dropna=False)[TARGET]
                   .nunique()
    )

    conflicting_values = int((nunique_by_value > 1).sum())

    if conflicting_values == 0:

        single_results.append({
            "feature": feature,
            "unique_values": int(len(nunique_by_value))
        })

if single_results:

    print("\nExact single-feature discriminators found:")

    for r in single_results:
        print(
            f" - {r['feature']} "
            f"(unique values={r['unique_values']})"
        )

else:

    print("\n[INFO] No exact single-feature discriminator.")

# ------------------------------------------------------------
# 6. Search EXACT FEATURE TRIPLES
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("SEARCHING FEATURE TRIPLES")
print("=" * 75)

triple_results = []

# Only remaining features are used.
# CLASS_LABEL and id are excluded.
for f1, f2, f3 in combinations(remaining_features, 3):

    grouped_triplet = (
        conflict_df.groupby(
            [f1, f2, f3],
            dropna=False
        )[TARGET]
        .nunique()
    )

    if (grouped_triplet > 1).sum() == 0:

        triple_results.append({
            "feature_1": f1,
            "feature_2": f2,
            "feature_3": f3,
            "unique_combinations": int(len(grouped_triplet))
        })

print(f"\nExact feature triples found: {len(triple_results)}")

if triple_results:

    print("\nFirst 30 exact triples:")

    for r in triple_results[:30]:
        print(
            f" - {r['feature_1']} + "
            f"{r['feature_2']} + "
            f"{r['feature_3']} "
            f"(unique combinations={r['unique_combinations']})"
        )

else:

    print("[INFO] No exact feature triple found.")

# ------------------------------------------------------------
# 7. Decision-tree rule discovery
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("DECISION-TREE RULE DISCOVERY")
print("=" * 75)

X = conflict_df[remaining_features].copy()
y = conflict_df[TARGET].copy()

# Make sure all values are numeric
X = X.apply(pd.to_numeric, errors="coerce").fillna(-999)

tree_results = []

for depth in range(1, 8):

    tree = DecisionTreeClassifier(
        max_depth=depth,
        min_samples_leaf=1,
        random_state=42
    )

    tree.fit(X, y)

    accuracy = tree.score(X, y)

    tree_results.append({
        "depth": depth,
        "accuracy": float(accuracy),
        "leaves": int(tree.get_n_leaves())
    })

    print(
        f"Depth {depth}: "
        f"accuracy={accuracy * 100:.4f}% | "
        f"leaves={tree.get_n_leaves()}"
    )

# Best tree
best_tree_info = max(
    tree_results,
    key=lambda x: (x["accuracy"], -x["depth"])
)

best_depth = best_tree_info["depth"]

best_tree = DecisionTreeClassifier(
    max_depth=best_depth,
    min_samples_leaf=1,
    random_state=42
)

best_tree.fit(X, y)

print("\nBest tree:")
print(f"Depth: {best_depth}")
print(f"Accuracy: {best_tree_info['accuracy'] * 100:.4f}%")

print("\nDiscovered rule:")
print(
    export_text(
        best_tree,
        feature_names=list(X.columns)
    )
)

# ------------------------------------------------------------
# 8. Check whether the ambiguity is caused by duplicate rows
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("DUPLICATE / NEAR-DUPLICATE ANALYSIS")
print("=" * 75)

feature_columns = [
    c for c in df.columns
    if c not in {"CLASS_LABEL", "id", TARGET}
]

duplicate_groups = (
    conflict_df.groupby(
        feature_columns,
        dropna=False
    )[TARGET]
    .nunique()
)

conflicting_duplicate_groups = duplicate_groups[
    duplicate_groups > 1
]

print(
    "Exact identical non-target feature vectors "
    "with different RT values:"
)
print(len(conflicting_duplicate_groups))

if len(conflicting_duplicate_groups) > 0:

    print("\n[IMPORTANT] Identical feature vectors have different RT values.")

    display(
        conflict_df[
            feature_columns + [TARGET]
        ].merge(
            conflicting_duplicate_groups.reset_index(
                name="unique_rt"
            ),
            on=feature_columns,
            how="inner"
        )
    )

else:

    print(
        "[PASS] No identical non-target feature vectors "
        "have different RT values."
    )

# ------------------------------------------------------------
# 9. Check repeated URL-length / resource patterns
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("HIGH-VALUE PATTERN ANALYSIS")
print("=" * 75)

pattern_features = [
    "PctExtResourceUrls",
    "PctExtHyperlinks",
    "PctNullSelfRedirectHyperlinks",
    "FrequentDomainNameMismatch",
    "HostnameLength",
    "UrlLength",
    "NumDots",
    "NumNumericChars",
    "RandomString",
    "SubdomainLevel",
    "PathLevel",
    "ExtFavicon",
    "IframeOrFrame"
]

available_patterns = [
    c for c in pattern_features
    if c in conflict_df.columns
]

for feature in available_patterns:

    print(f"\n{feature}")

    print(
        conflict_df.groupby(feature)[TARGET]
        .value_counts()
        .unstack(fill_value=0)
    )

# ------------------------------------------------------------
# 10. Save checkpoint
# ------------------------------------------------------------

checkpoint_dir = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints"
)

os.makedirs(checkpoint_dir, exist_ok=True)

checkpoint_path = os.path.join(
    checkpoint_dir,
    "step_5Q_ext_meta_deep_analysis.json"
)

checkpoint = {
    "stage": "Step 5Q",
    "dataset_shape": list(df.shape),
    "target": TARGET,
    "conflicting_candidate_combinations": int(
        len(conflict_groups)
    ),
    "conflicting_rows": int(
        len(conflict_df)
    ),
    "single_feature_discriminators": [
        r["feature"]
        for r in single_results
    ],
    "exact_feature_triples_count": int(
        len(triple_results)
    ),
    "exact_feature_triples": [
        [
            r["feature_1"],
            r["feature_2"],
            r["feature_3"]
        ]
        for r in triple_results[:100]
    ],
    "tree_results": tree_results,
    "best_tree_depth": int(best_depth),
    "best_tree_accuracy": float(
        best_tree_info["accuracy"]
    ),
    "identical_non_target_vectors_with_conflicting_rt": int(
        len(conflicting_duplicate_groups)
    ),
    "class_label_used": False,
    "id_used": False,
    "training_performed": False,
    "prediction_performed": False,
    "model_modified": False
}

with open(checkpoint_path, "w") as f:
    json.dump(checkpoint, f, indent=2)

with open(checkpoint_path, "r") as f:
    json.load(f)

print("\n" + "=" * 75)
print("STEP 5Q CHECKPOINT SAVED")
print("=" * 75)
print(f"Checkpoint: {checkpoint_path}")
print("[PASS] JSON checkpoint verified successfully.")
print("No training performed.")
print("No prediction performed.")
print("No model modified.")
print("=" * 75)
print("END STEP 5Q")
print("=" * 75)

===========================================================================
STEP 5Q — DEEP ANALYSIS OF ExtMetaScriptLinkRT CONFLICTS
===========================================================================

Dataset shape: (10000, 50)

Conflicting candidate combinations:
14
Rows involved: 31

RT distribution among conflicting rows:
ExtMetaScriptLinkRT
-1    15
 0     1
 1    15
Name: count, dtype: int64

===========================================================================
ALL CONFLICTING ROWS
===========================================================================

,NumDots,SubdomainLevel,PathLevel,UrlLength,NumDash,NumDashInHostname,AtSymbol,TildeSymbol,NumUnderscore,NumPercent,...,SubmitInfoToEmail,IframeOrFrame,MissingTitle,ImagesOnlyInForm,SubdomainLevelRT,UrlLengthRT,PctExtResourceUrlsRT,AbnormalExtFormActionR,ExtMetaScriptLinkRT,PctExtNullSelfRedirectHyperlinksRT
0,3,1,3,54,1,0,0,0,0,0,...,0,1,0,0,1,0,-1,0,-1,-1
1,3,0,3,57,2,0,0,0,0,0,...,0,1,0,0,1,0,-1,1,-1,-1
2,2,0,4,52,1,1,0,0,0,0,...,0,1,0,0,1,1,-1,1,-1,-1
3,3,1,4,58,1,0,0,0,0,0,...,0,1,0,0,1,0,-1,0,-1,-1
5,3,1,4,63,1,0,0,0,0,0,...,0,1,0,0,1,0,-1,0,-1,-1
6,2,0,2,41,0,0,0,0,0,0,...,0,0,0,0,1,1,-1,1,-1,-1
7,3,1,3,57,2,1,0,0,0,0,...,0,1,0,0,1,0,-1,0,-1,-1
9,3,0,3,42,1,0,0,1,0,0,...,0,0,0,0,1,1,1,0,-1,1
14,4,1,3,53,1,0,0,0,0,0,...,0,1,0,0,1,1,-1,0,-1,-1
10,5,0,5,67,1,0,0,1,0,0,...,0,0,0,0,1,0,-1,1,-1,-1
13,4,1,3,53,1,0,0,0,0,0,...,0,1,0,0,1,1,-1,0,-1,-1
12,4,1,3,53,1,0,0,0,0,0,...,0,1,0,0,1,1,-1,0,-1,-1
25,2,0,2,42,0,0,0,0,0,0,...,0,1,0,0,1,1,-1,1,-1,-1
26,2,0,3,55,1,0,0,0,0,0,...,0,1,0,0,1,0,-1,1,-1,-1
18,3,1,2,47,0,0,0,0,1,0,...,0,0,0,0,1,1,-1,1,-1,-1
29,5,2,7,85,2,0,0,0,1,0,...,0,0,0,0,0,-1,1,1,0,1
15,4,1,4,57,1,0,0,0,0,0,...,0,1,0,0,1,0,-1,0,1,-1
11,4,0,2,57,1,0,0,0,0,0,...,0,1,1,0,1,0,-1,0,1,-1
8,4,1,3,42,0,0,0,0,0,0,...,0,0,1,0,1,1,-1,1,1,1
4,1,0,8,85,1,0,0,0,0,0,...,0,0,0,0,1,-1,1,1,1,1
20,3,1,4,63,1,0,0,0,0,0,...,0,1,0,0,1,0,-1,0,1,-1
16,4,1,3,53,1,0,0,0,0,0,...,0,1,0,0,1,1,-1,0,1,-1
17,4,1,3,52,1,0,0,0,0,0,...,0,1,0,0,1,1,-1,0,1,-1
19,4,1,5,67,0,0,0,0,1,0,...,0,0,0,0,1,0,-1,0,1,-1
23,3,1,5,58,1,0,0,0,0,0,...,0,1,0,0,1,0,-1,1,1,-1
22,3,1,4,54,1,0,0,0,0,0,...,0,1,0,0,1,0,-1,1,1,-1
21,3,1,5,58,1,0,0,0,0,0,...,0,1,0,0,1,0,-1,1,1,-1
24,3,1,3,55,1,0,0,0,0,0,...,0,1,0,0,1,0,-1,0,1,-1
27,3,1,2,42,0,0,0,0,0,0,...,0,1,1,0,1,1,-1,1,1,-1
28,2,0,3,47,0,0,0,0,0,0,...,0,0,0,0,1,1,-1,1,1,-1
30,3,1,1,41,1,0,0,0,0,0,...,0,0,0,0,1,1,-1,1,1,-1

===========================================================================
SINGLE FEATURE ANALYSIS
===========================================================================

[INFO] No exact single-feature discriminator.

===========================================================================
SEARCHING FEATURE TRIPLES
===========================================================================

Exact feature triples found: 0
[INFO] No exact feature triple found.

===========================================================================
DECISION-TREE RULE DISCOVERY
===========================================================================
Depth 1: accuracy=58.0645% | leaves=2
Depth 2: accuracy=67.7419% | leaves=3
Depth 3: accuracy=70.9677% | leaves=5
Depth 4: accuracy=83.8710% | leaves=7
Depth 5: accuracy=87.0968% | leaves=8
Depth 6: accuracy=87.0968% | leaves=9
Depth 7: accuracy=90.3226% | leaves=10

Best tree:
Depth: 7
Accuracy: 90.3226%

Discovered rule:
|--- MissingTitle <= 0.50
|   |--- PathLevel <= 4.50
|   |   |--- RandomString <= 0.50
|   |   |   |--- PathLevel <= 3.50
|   |   |   |   |--- InsecureForms <= 0.50
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- InsecureForms >  0.50
|   |   |   |   |   |--- PathLength <= 28.00
|   |   |   |   |   |   |--- DomainInPaths <= 0.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- DomainInPaths >  0.50
|   |   |   |   |   |   |   |--- class: -1
|   |   |   |   |   |--- PathLength >  28.00
|   |   |   |   |   |   |--- class: -1
|   |   |   |--- PathLevel >  3.50
|   |   |   |   |--- class: 1
|   |   |--- RandomString >  0.50
|   |   |   |--- class: -1
|   |--- PathLevel >  4.50
|   |   |--- NumNumericChars <= 6.50
|   |   |   |--- class: 1
|   |   |--- NumNumericChars >  6.50
|   |   |   |--- SubdomainLevelRT <= 0.50
|   |   |   |   |--- class: 0
|   |   |   |--- SubdomainLevelRT >  0.50
|   |   |   |   |--- class: -1
|--- MissingTitle >  0.50
|   |--- class: 1


===========================================================================
DUPLICATE / NEAR-DUPLICATE ANALYSIS
===========================================================================
Exact identical non-target feature vectors with different RT values:
0
[PASS] No identical non-target feature vectors have different RT values.

===========================================================================
HIGH-VALUE PATTERN ANALYSIS
===========================================================================

PctExtResourceUrls
ExtMetaScriptLinkRT  -1   0   1
PctExtResourceUrls
0.0                   0   1   1
1.0                  15   0  14

PctExtHyperlinks
ExtMetaScriptLinkRT  -1   0   1
PctExtHyperlinks
0.0                   1   1   2
1.0                  14   0  13

PctNullSelfRedirectHyperlinks
ExtMetaScriptLinkRT            -1   0   1
PctNullSelfRedirectHyperlinks
0.0                            15   1  15

FrequentDomainNameMismatch
ExtMetaScriptLinkRT         -1   0   1
FrequentDomainNameMismatch
0                            0   1   1
1                           15   0  14

HostnameLength
ExtMetaScriptLinkRT  -1   0   1
HostnameLength
12                    1   0   1
13                    1   0   1
14                    1   0   1
18                    0   1   1
19                    1   0   1
20                    7   0   5
22                    4   0   5

UrlLength
ExtMetaScriptLinkRT  -1   0   1
UrlLength
41                    1   0   1
42                    2   0   2
47                    1   0   1
52                    1   0   1
53                    3   0   1
54                    1   0   1
55                    1   0   1
57                    2   0   2
58                    1   0   2
63                    1   0   1
67                    1   0   1
85                    0   1   1

NumDots
ExtMetaScriptLinkRT  -1   0   1
NumDots
1                     0   0   1
2                     4   0   1
3                     7   0   7
4                     3   0   6
5                     1   1   0

NumNumericChars
ExtMetaScriptLinkRT  -1   0   1
NumNumericChars
0                    10   0  12
1                     0   0   1
2                     1   0   0
3                     0   0   1
4                     2   0   1
9                     1   0   0
11                    1   0   0
21                    0   1   0

RandomString
ExtMetaScriptLinkRT  -1   0   1
RandomString
0                     9   0  12
1                     6   1   3

SubdomainLevel
ExtMetaScriptLinkRT  -1   0   1
SubdomainLevel
0                     7   0   3
1                     8   0  12
2                     0   1   0

PathLevel
ExtMetaScriptLinkRT  -1   0   1
PathLevel
1                     0   0   1
2                     3   0   2
3                     8   0   5
4                     3   0   3
5                     1   0   3
7                     0   1   0
8                     0   0   1

ExtFavicon
ExtMetaScriptLinkRT  -1   0   1
ExtFavicon
0                    15   1  15

IframeOrFrame
ExtMetaScriptLinkRT  -1   0   1
IframeOrFrame
0                     4   1   5
1                    11   0  10

===========================================================================
STEP 5Q CHECKPOINT SAVED
===========================================================================
Checkpoint: /content/drive/MyDrive/PhishShield_AI/checkpoints/step_5Q_ext_meta_deep_analysis.json
[PASS] JSON checkpoint verified successfully.
No training performed.
No prediction performed.
No model modified.
===========================================================================
END STEP 5Q
===========================================================================

In [ ]:
# ============================================================
# STEP 5R — FINAL EXTMetaScriptLinkRT RELATIONSHIP ANALYSIS
# ============================================================

import os
import json
import numpy as np
import pandas as pd

print("=" * 75)
print("STEP 5R — FINAL ExtMetaScriptLinkRT RELATIONSHIP ANALYSIS")
print("=" * 75)

# ------------------------------------------------------------
# 1. Load dataset
# ------------------------------------------------------------

DATA_PATH = "/content/Phishing_Legitimate_full.csv"

df = pd.read_csv(DATA_PATH)

TARGET = "ExtMetaScriptLinkRT"

print(f"\nDataset shape: {df.shape}")

# ------------------------------------------------------------
# 2. Recover the exact 31 conflicting rows
# ------------------------------------------------------------

base_features = [
    "PctExtResourceUrls",
    "PctExtHyperlinks",
    "PctNullSelfRedirectHyperlinks",
    "ExtFavicon",
    "IframeOrFrame",
    "FrequentDomainNameMismatch",
    "HostnameLength",
    "UrlLength"
]

groups = (
    df.groupby(base_features, dropna=False)[TARGET]
      .nunique()
      .reset_index(name="unique_rt")
)

conflicting_groups = groups[
    groups["unique_rt"] > 1
]

conflict_df = df.merge(
    conflicting_groups[base_features],
    on=base_features,
    how="inner"
).copy()

print(f"Conflicting groups: {len(conflicting_groups)}")
print(f"Conflicting rows: {len(conflict_df)}")

# ------------------------------------------------------------
# 3. Create derived relationships
# ------------------------------------------------------------

x = conflict_df.copy()

EPS = 1e-9

# Resource/link relationships
x["Resource_to_Hyperlink"] = (
    x["PctExtResourceUrls"] /
    (x["PctExtHyperlinks"] + EPS)
)

x["Hyperlink_to_Resource"] = (
    x["PctExtHyperlinks"] /
    (x["PctExtResourceUrls"] + EPS)
)

x["Resource_minus_Hyperlink"] = (
    x["PctExtResourceUrls"] -
    x["PctExtHyperlinks"]
)

x["Resource_plus_Hyperlink"] = (
    x["PctExtResourceUrls"] +
    x["PctExtHyperlinks"]
)

# Null/self redirects relationships
x["Null_to_External"] = (
    x["PctNullSelfRedirectHyperlinks"] /
    (x["PctExtHyperlinks"] + EPS)
)

x["External_minus_Null"] = (
    x["PctExtHyperlinks"] -
    x["PctNullSelfRedirectHyperlinks"]
)

# Structural relationships
x["Url_per_Hostname"] = (
    x["UrlLength"] /
    (x["HostnameLength"] + EPS)
)

x["Path_proxy"] = (
    x["UrlLength"] -
    x["HostnameLength"]
)

x["Dots_per_Hostname"] = (
    x["NumDots"] /
    (x["HostnameLength"] + EPS)
)

x["Numeric_per_URL"] = (
    x["NumNumericChars"] /
    (x["UrlLength"] + EPS)
)

# ------------------------------------------------------------
# 4. Test exact derived-feature consistency
# ------------------------------------------------------------

derived_features = [
    "Resource_to_Hyperlink",
    "Hyperlink_to_Resource",
    "Resource_minus_Hyperlink",
    "Resource_plus_Hyperlink",
    "Null_to_External",
    "External_minus_Null",
    "Url_per_Hostname",
    "Path_proxy",
    "Dots_per_Hostname",
    "Numeric_per_URL"
]

print("\n" + "=" * 75)
print("EXACT DERIVED-FEATURE TEST")
print("=" * 75)

exact_derived = []

for feature in derived_features:

    # Round floating-point derived values to avoid
    # numerical precision artifacts.
    rounded = x[feature].round(8)

    consistency = (
        pd.DataFrame({
            "derived": rounded,
            "rt": x[TARGET]
        })
        .groupby("derived", dropna=False)["rt"]
        .nunique()
    )

    conflicts = int((consistency > 1).sum())

    print(
        f"{feature:30s} "
        f"conflicting values = {conflicts}"
    )

    if conflicts == 0:
        exact_derived.append(feature)

print("\nExact derived-feature discriminators:")

if exact_derived:
    for feature in exact_derived:
        print(" -", feature)
else:
    print(" [NONE]")

# ------------------------------------------------------------
# 5. Search threshold rules
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("THRESHOLD RULE SEARCH")
print("=" * 75)

numeric_candidates = [
    c for c in [
        "PctExtResourceUrls",
        "PctExtHyperlinks",
        "PctNullSelfRedirectHyperlinks",
        "HostnameLength",
        "UrlLength",
        "NumDots",
        "NumNumericChars",
        "PathLevel",
        "PathLength",
        "NumDash",
        "NumDashInHostname",
        "RandomString",
        "SubdomainLevel",
        "MissingTitle",
        "InsecureForms",
        "FrequentDomainNameMismatch",
        "IframeOrFrame",
        "ExtFavicon"
    ]
    if c in x.columns
]

threshold_rules = []

for feature in numeric_candidates:

    values = sorted(
        x[feature].dropna().unique()
    )

    if len(values) < 2:
        continue

    # Candidate thresholds between observed values
    thresholds = []

    for a, b in zip(values[:-1], values[1:]):

        if a != b:
            thresholds.append((a + b) / 2)

    for threshold in thresholds:

        left = x.loc[
            x[feature] <= threshold,
            TARGET
        ]

        right = x.loc[
            x[feature] > threshold,
            TARGET
        ]

        if len(left) == 0 or len(right) == 0:
            continue

        # Check whether each side contains one RT class only
        left_unique = left.nunique()
        right_unique = right.nunique()

        if left_unique == 1 and right_unique == 1:

            threshold_rules.append({
                "feature": feature,
                "threshold": float(threshold),
                "left_rt": int(left.iloc[0]),
                "right_rt": int(right.iloc[0])
            })

print(
    f"\nExact one-threshold rules found: "
    f"{len(threshold_rules)}"
)

for rule in threshold_rules[:30]:

    print(
        f" - {rule['feature']} <= "
        f"{rule['threshold']:.6f} → {rule['left_rt']} | "
        f"> {rule['threshold']:.6f} → {rule['right_rt']}"
    )

# ------------------------------------------------------------
# 6. Check whether RT is related to known binary feature
#    combinations
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("BINARY-COMBINATION ANALYSIS")
print("=" * 75)

binary_features = [
    c for c in [
        "ExtFavicon",
        "IframeOrFrame",
        "FrequentDomainNameMismatch",
        "RandomString",
        "MissingTitle",
        "InsecureForms",
        "RelativeFormAction",
        "ExtFormAction",
        "AbnormalFormAction",
        "FakeLinkInStatusBar",
        "RightClickDisabled",
        "PopUpWindow",
        "SubmitInfoToEmail",
        "ImagesOnlyInForm"
    ]
    if c in x.columns
]

binary_exact_pairs = []

for i in range(len(binary_features)):
    for j in range(i + 1, len(binary_features)):

        f1 = binary_features[i]
        f2 = binary_features[j]

        consistency = (
            x.groupby(
                [f1, f2],
                dropna=False
            )[TARGET]
            .nunique()
        )

        if (consistency > 1).sum() == 0:

            binary_exact_pairs.append(
                (f1, f2)
            )

print(
    f"Exact binary feature pairs: "
    f"{len(binary_exact_pairs)}"
)

for pair in binary_exact_pairs[:30]:
    print(" -", pair[0], "+", pair[1])

# ------------------------------------------------------------
# 7. Show every conflict group with RT distributions
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("CONFLICT GROUP BREAKDOWN")
print("=" * 75)

for idx, (_, group) in enumerate(
    conflict_df.groupby(
        base_features,
        dropna=False
    ),
    start=1
):

    if group[TARGET].nunique() <= 1:
        continue

    print("\nConflict group", idx)

    for feature in base_features:
        print(
            f"  {feature}: "
            f"{group.iloc[0][feature]}"
        )

    print("  RT distribution:")
    print(
        group[TARGET]
        .value_counts()
        .sort_index()
        .to_dict()
    )

    # Show useful secondary features
    secondary = [
        "NumDots",
        "SubdomainLevel",
        "PathLevel",
        "PathLength",
        "NumNumericChars",
        "NumDash",
        "NumDashInHostname",
        "RandomString",
        "MissingTitle",
        "InsecureForms",
        "RelativeFormAction",
        "ExtFormAction",
        "AbnormalFormAction",
        "AbnormalExtFormActionR",
        "UrlLengthRT",
        "SubdomainLevelRT",
        "PctExtResourceUrlsRT",
        "PctExtNullSelfRedirectHyperlinksRT"
    ]

    print(
        group[
            [c for c in secondary if c in group.columns]
            + [TARGET]
        ].to_string(index=False)
    )

# ------------------------------------------------------------
# 8. Final conclusion
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("STEP 5R CONCLUSION")
print("=" * 75)

print(
    f"Conflicting rows analysed: {len(conflict_df)}"
)

print(
    f"Exact derived discriminators: "
    f"{len(exact_derived)}"
)

print(
    f"Exact one-threshold rules: "
    f"{len(threshold_rules)}"
)

print(
    f"Exact binary feature pairs: "
    f"{len(binary_exact_pairs)}"
)

# ------------------------------------------------------------
# 9. Save checkpoint
# ------------------------------------------------------------

checkpoint_dir = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints"
)

os.makedirs(checkpoint_dir, exist_ok=True)

checkpoint_path = os.path.join(
    checkpoint_dir,
    "step_5R_ext_meta_relationship_analysis.json"
)

checkpoint = {
    "stage": "Step 5R",
    "dataset_shape": list(df.shape),
    "target": TARGET,
    "conflicting_groups": int(
        len(conflicting_groups)
    ),
    "conflicting_rows": int(
        len(conflict_df)
    ),
    "exact_derived_features": exact_derived,
    "exact_threshold_rule_count": int(
        len(threshold_rules)
    ),
    "exact_threshold_rules": threshold_rules[:100],
    "exact_binary_pair_count": int(
        len(binary_exact_pairs)
    ),
    "exact_binary_pairs": [
        list(pair)
        for pair in binary_exact_pairs
    ],
    "class_label_used": False,
    "id_used": False,
    "training_performed": False,
    "prediction_performed": False,
    "model_modified": False
}

with open(checkpoint_path, "w") as f:
    json.dump(checkpoint, f, indent=2)

with open(checkpoint_path, "r") as f:
    json.load(f)

print("\n" + "=" * 75)
print("STEP 5R CHECKPOINT SAVED")
print("=" * 75)
print(f"Checkpoint: {checkpoint_path}")
print("[PASS] JSON checkpoint verified successfully.")
print("No training performed.")
print("No prediction performed.")
print("No model modified.")
print("=" * 75)
print("END STEP 5R")
print("=" * 75)

===========================================================================
STEP 5R — FINAL ExtMetaScriptLinkRT RELATIONSHIP ANALYSIS
===========================================================================

Dataset shape: (10000, 50)
Conflicting groups: 14
Conflicting rows: 31

===========================================================================
EXACT DERIVED-FEATURE TEST
===========================================================================
Resource_to_Hyperlink          conflicting values = 3
Hyperlink_to_Resource          conflicting values = 2
Resource_minus_Hyperlink       conflicting values = 2
Resource_plus_Hyperlink        conflicting values = 3
Null_to_External               conflicting values = 1
External_minus_Null            conflicting values = 2
Url_per_Hostname               conflicting values = 14
Path_proxy                     conflicting values = 11
Dots_per_Hostname              conflicting values = 4
Numeric_per_URL                conflicting values = 1

Exact derived-feature discriminators:
 [NONE]

===========================================================================
THRESHOLD RULE SEARCH
===========================================================================

Exact one-threshold rules found: 0

===========================================================================
BINARY-COMBINATION ANALYSIS
===========================================================================
Exact binary feature pairs: 0

===========================================================================
CONFLICT GROUP BREAKDOWN
===========================================================================

Conflict group 1
  PctExtResourceUrls: 0.0
  PctExtHyperlinks: 0.0
  PctNullSelfRedirectHyperlinks: 0.0
  ExtFavicon: 0.0
  IframeOrFrame: 0.0
  FrequentDomainNameMismatch: 0.0
  HostnameLength: 18.0
  UrlLength: 85.0
  RT distribution:
{0: 1, 1: 1}
 NumDots  SubdomainLevel  PathLevel  PathLength  NumNumericChars  NumDash  NumDashInHostname  RandomString  MissingTitle  InsecureForms  RelativeFormAction  ExtFormAction  AbnormalFormAction  AbnormalExtFormActionR  UrlLengthRT  SubdomainLevelRT  PctExtResourceUrlsRT  PctExtNullSelfRedirectHyperlinksRT  ExtMetaScriptLinkRT
       1               0          8          60                0        1                  0             1             0              1                   0              0                   0                       1           -1                 1                     1                                   1                    1
       5               2          7          60               21        2                  0             1             0              0                   0              0                   0                       1           -1                 0                     1                                   1                    0

Conflict group 2
  PctExtResourceUrls: 1.0
  PctExtHyperlinks: 0.0
  PctNullSelfRedirectHyperlinks: 0.0
  ExtFavicon: 0.0
  IframeOrFrame: 0.0
  FrequentDomainNameMismatch: 1.0
  HostnameLength: 14.0
  UrlLength: 42.0
  RT distribution:
{-1: 1, 1: 1}
 NumDots  SubdomainLevel  PathLevel  PathLength  NumNumericChars  NumDash  NumDashInHostname  RandomString  MissingTitle  InsecureForms  RelativeFormAction  ExtFormAction  AbnormalFormAction  AbnormalExtFormActionR  UrlLengthRT  SubdomainLevelRT  PctExtResourceUrlsRT  PctExtNullSelfRedirectHyperlinksRT  ExtMetaScriptLinkRT
       4               1          3          21                1        0                  0             1             1              1                   0              0                   0                       1            1                 1                    -1                                   1                    1
       3               0          3          21               11        1                  0             0             0              1                   0              1                   0                       0            1                 1                     1                                   1                   -1

Conflict group 3
  PctExtResourceUrls: 1.0
  PctExtHyperlinks: 1.0
  PctNullSelfRedirectHyperlinks: 0.0
  ExtFavicon: 0.0
  IframeOrFrame: 0.0
  FrequentDomainNameMismatch: 1.0
  HostnameLength: 12.0
  UrlLength: 67.0
  RT distribution:
{-1: 1, 1: 1}
 NumDots  SubdomainLevel  PathLevel  PathLength  NumNumericChars  NumDash  NumDashInHostname  RandomString  MissingTitle  InsecureForms  RelativeFormAction  ExtFormAction  AbnormalFormAction  AbnormalExtFormActionR  UrlLengthRT  SubdomainLevelRT  PctExtResourceUrlsRT  PctExtNullSelfRedirectHyperlinksRT  ExtMetaScriptLinkRT
       5               0          5          48                9        1                  0             0             0              1                   0              0                   0                       1            0                 1                    -1                                  -1                   -1
       4               1          5          48                4        0                  0             1             0              0                   0              1                   0                       0            0                 1                    -1                                  -1                    1

Conflict group 4
  PctExtResourceUrls: 1.0
  PctExtHyperlinks: 1.0
  PctNullSelfRedirectHyperlinks: 0.0
  ExtFavicon: 0.0
  IframeOrFrame: 0.0
  FrequentDomainNameMismatch: 1.0
  HostnameLength: 19.0
  UrlLength: 41.0
  RT distribution:
{-1: 1, 1: 1}
 NumDots  SubdomainLevel  PathLevel  PathLength  NumNumericChars  NumDash  NumDashInHostname  RandomString  MissingTitle  InsecureForms  RelativeFormAction  ExtFormAction  AbnormalFormAction  AbnormalExtFormActionR  UrlLengthRT  SubdomainLevelRT  PctExtResourceUrlsRT  PctExtNullSelfRedirectHyperlinksRT  ExtMetaScriptLinkRT
       2               0          2          15                0        0                  0             0             0              1                   0              0                   0                       1            1                 1                    -1                                  -1                   -1
       3               1          1          15                3        1                  0             0             0              0                   0              0                   0                       1            1                 1                    -1                                  -1                    1

Conflict group 5
  PctExtResourceUrls: 1.0
  PctExtHyperlinks: 1.0
  PctNullSelfRedirectHyperlinks: 0.0
  ExtFavicon: 0.0
  IframeOrFrame: 0.0
  FrequentDomainNameMismatch: 1.0
  HostnameLength: 20.0
  UrlLength: 47.0
  RT distribution:
{-1: 1, 1: 1}
 NumDots  SubdomainLevel  PathLevel  PathLength  NumNumericChars  NumDash  NumDashInHostname  RandomString  MissingTitle  InsecureForms  RelativeFormAction  ExtFormAction  AbnormalFormAction  AbnormalExtFormActionR  UrlLengthRT  SubdomainLevelRT  PctExtResourceUrlsRT  PctExtNullSelfRedirectHyperlinksRT  ExtMetaScriptLinkRT
       3               1          2          20                2        0                  0             1             0              1                   0              0                   0                       1            1                 1                    -1                                  -1                   -1
       2               0          3          20                0        0                  0             0             0              1                   0              0                   0                       1            1                 1                    -1                                  -1                    1

Conflict group 6
  PctExtResourceUrls: 1.0
  PctExtHyperlinks: 1.0
  PctNullSelfRedirectHyperlinks: 0.0
  ExtFavicon: 0.0
  IframeOrFrame: 1.0
  FrequentDomainNameMismatch: 1.0
  HostnameLength: 13.0
  UrlLength: 57.0
  RT distribution:
{-1: 1, 1: 1}
 NumDots  SubdomainLevel  PathLevel  PathLength  NumNumericChars  NumDash  NumDashInHostname  RandomString  MissingTitle  InsecureForms  RelativeFormAction  ExtFormAction  AbnormalFormAction  AbnormalExtFormActionR  UrlLengthRT  SubdomainLevelRT  PctExtResourceUrlsRT  PctExtNullSelfRedirectHyperlinksRT  ExtMetaScriptLinkRT
       3               0          3          37                0        2                  0             0             0              1                   0              0                   0                       1            0                 1                    -1                                  -1                   -1
       4               0          2          37                0        1                  0             0             1              1                   0              1                   0                       0            0                 1                    -1                                  -1                    1

Conflict group 7
  PctExtResourceUrls: 1.0
  PctExtHyperlinks: 1.0
  PctNullSelfRedirectHyperlinks: 0.0
  ExtFavicon: 0.0
  IframeOrFrame: 1.0
  FrequentDomainNameMismatch: 1.0
  HostnameLength: 20.0
  UrlLength: 42.0
  RT distribution:
{-1: 1, 1: 1}
 NumDots  SubdomainLevel  PathLevel  PathLength  NumNumericChars  NumDash  NumDashInHostname  RandomString  MissingTitle  InsecureForms  RelativeFormAction  ExtFormAction  AbnormalFormAction  AbnormalExtFormActionR  UrlLengthRT  SubdomainLevelRT  PctExtResourceUrlsRT  PctExtNullSelfRedirectHyperlinksRT  ExtMetaScriptLinkRT
       2               0          2          15                0        0                  0             1             0              1                   0              0                   0                       1            1                 1                    -1                                  -1                   -1
       3               1          2          15                0        0                  0             0             1              1                   0              0                   0                       1            1                 1                    -1                                  -1                    1

Conflict group 8
  PctExtResourceUrls: 1.0
  PctExtHyperlinks: 1.0
  PctNullSelfRedirectHyperlinks: 0.0
  ExtFavicon: 0.0
  IframeOrFrame: 1.0
  FrequentDomainNameMismatch: 1.0
  HostnameLength: 20.0
  UrlLength: 52.0
  RT distribution:
{-1: 1, 1: 1}
 NumDots  SubdomainLevel  PathLevel  PathLength  NumNumericChars  NumDash  NumDashInHostname  RandomString  MissingTitle  InsecureForms  RelativeFormAction  ExtFormAction  AbnormalFormAction  AbnormalExtFormActionR  UrlLengthRT  SubdomainLevelRT  PctExtResourceUrlsRT  PctExtNullSelfRedirectHyperlinksRT  ExtMetaScriptLinkRT
       2               0          4          25                0        1                  1             1             0              1                   0              0                   0                       1            1                 1                    -1                                  -1                   -1
       4               1          3          25                0        1                  0             0             0              1                   0              1                   0                       0            1                 1                    -1                                  -1                    1

Conflict group 9
  PctExtResourceUrls: 1.0
  PctExtHyperlinks: 1.0
  PctNullSelfRedirectHyperlinks: 0.0
  ExtFavicon: 0.0
  IframeOrFrame: 1.0
  FrequentDomainNameMismatch: 1.0
  HostnameLength: 20.0
  UrlLength: 53.0
  RT distribution:
{-1: 3, 1: 1}
 NumDots  SubdomainLevel  PathLevel  PathLength  NumNumericChars  NumDash  NumDashInHostname  RandomString  MissingTitle  InsecureForms  RelativeFormAction  ExtFormAction  AbnormalFormAction  AbnormalExtFormActionR  UrlLengthRT  SubdomainLevelRT  PctExtResourceUrlsRT  PctExtNullSelfRedirectHyperlinksRT  ExtMetaScriptLinkRT
       4               1          3          26                0        1                  0             0             0              1                   0              1                   0                       0            1                 1                    -1                                  -1                   -1
       4               1          3          26                0        1                  0             0             0              1                   0              1                   0                       0            1                 1                    -1                                  -1                   -1
       4               1          3          26                0        1                  0             0             0              1                   0              1                   0                       0            1                 1                    -1                                  -1                   -1
       4               1          3          26                0        1                  0             0             0              1                   0              1                   0                       0            1                 1                    -1                                  -1                    1

Conflict group 10
  PctExtResourceUrls: 1.0
  PctExtHyperlinks: 1.0
  PctNullSelfRedirectHyperlinks: 0.0
  ExtFavicon: 0.0
  IframeOrFrame: 1.0
  FrequentDomainNameMismatch: 1.0
  HostnameLength: 20.0
  UrlLength: 57.0
  RT distribution:
{-1: 1, 1: 1}
 NumDots  SubdomainLevel  PathLevel  PathLength  NumNumericChars  NumDash  NumDashInHostname  RandomString  MissingTitle  InsecureForms  RelativeFormAction  ExtFormAction  AbnormalFormAction  AbnormalExtFormActionR  UrlLengthRT  SubdomainLevelRT  PctExtResourceUrlsRT  PctExtNullSelfRedirectHyperlinksRT  ExtMetaScriptLinkRT
       3               1          3          30                0        2                  1             0             0              1                   0              1                   0                       0            0                 1                    -1                                  -1                   -1
       4               1          4          30                0        1                  0             0             0              1                   0              1                   0                       0            0                 1                    -1                                  -1                    1

Conflict group 11
  PctExtResourceUrls: 1.0
  PctExtHyperlinks: 1.0
  PctNullSelfRedirectHyperlinks: 0.0
  ExtFavicon: 0.0
  IframeOrFrame: 1.0
  FrequentDomainNameMismatch: 1.0
  HostnameLength: 22.0
  UrlLength: 54.0
  RT distribution:
{-1: 1, 1: 1}
 NumDots  SubdomainLevel  PathLevel  PathLength  NumNumericChars  NumDash  NumDashInHostname  RandomString  MissingTitle  InsecureForms  RelativeFormAction  ExtFormAction  AbnormalFormAction  AbnormalExtFormActionR  UrlLengthRT  SubdomainLevelRT  PctExtResourceUrlsRT  PctExtNullSelfRedirectHyperlinksRT  ExtMetaScriptLinkRT
       3               1          3          25                0        1                  0             0             0              1                   0              1                   0                       0            0                 1                    -1                                  -1                   -1
       3               1          4          25                0        1                  0             0             0              1                   0              0                   0                       1            0                 1                    -1                                  -1                    1

Conflict group 12
  PctExtResourceUrls: 1.0
  PctExtHyperlinks: 1.0
  PctNullSelfRedirectHyperlinks: 0.0
  ExtFavicon: 0.0
  IframeOrFrame: 1.0
  FrequentDomainNameMismatch: 1.0
  HostnameLength: 22.0
  UrlLength: 55.0
  RT distribution:
{-1: 1, 1: 1}
 NumDots  SubdomainLevel  PathLevel  PathLength  NumNumericChars  NumDash  NumDashInHostname  RandomString  MissingTitle  InsecureForms  RelativeFormAction  ExtFormAction  AbnormalFormAction  AbnormalExtFormActionR  UrlLengthRT  SubdomainLevelRT  PctExtResourceUrlsRT  PctExtNullSelfRedirectHyperlinksRT  ExtMetaScriptLinkRT
       3               1          3          26                0        1                  0             0             0              1                   0              1                   0                       0            0                 1                    -1                                  -1                    1
       2               0          3          26                0        1                  0             1             0              1                   0              0                   0                       1            0                 1                    -1                                  -1                   -1

Conflict group 13
  PctExtResourceUrls: 1.0
  PctExtHyperlinks: 1.0
  PctNullSelfRedirectHyperlinks: 0.0
  ExtFavicon: 0.0
  IframeOrFrame: 1.0
  FrequentDomainNameMismatch: 1.0
  HostnameLength: 22.0
  UrlLength: 58.0
  RT distribution:
{-1: 1, 1: 2}
 NumDots  SubdomainLevel  PathLevel  PathLength  NumNumericChars  NumDash  NumDashInHostname  RandomString  MissingTitle  InsecureForms  RelativeFormAction  ExtFormAction  AbnormalFormAction  AbnormalExtFormActionR  UrlLengthRT  SubdomainLevelRT  PctExtResourceUrlsRT  PctExtNullSelfRedirectHyperlinksRT  ExtMetaScriptLinkRT
       3               1          4          29                4        1                  0             1             0              1                   0              1                   0                       0            0                 1                    -1                                  -1                   -1
       3               1          5          29                0        1                  0             0             0              1                   0              0                   0                       1            0                 1                    -1                                  -1                    1
       3               1          5          29                0        1                  0             0             0              1                   0              0                   0                       1            0                 1                    -1                                  -1                    1

Conflict group 14
  PctExtResourceUrls: 1.0
  PctExtHyperlinks: 1.0
  PctNullSelfRedirectHyperlinks: 0.0
  ExtFavicon: 0.0
  IframeOrFrame: 1.0
  FrequentDomainNameMismatch: 1.0
  HostnameLength: 22.0
  UrlLength: 63.0
  RT distribution:
{-1: 1, 1: 1}
 NumDots  SubdomainLevel  PathLevel  PathLength  NumNumericChars  NumDash  NumDashInHostname  RandomString  MissingTitle  InsecureForms  RelativeFormAction  ExtFormAction  AbnormalFormAction  AbnormalExtFormActionR  UrlLengthRT  SubdomainLevelRT  PctExtResourceUrlsRT  PctExtNullSelfRedirectHyperlinksRT  ExtMetaScriptLinkRT
       3               1          4          34                4        1                  0             1             0              1                   0              1                   0                       0            0                 1                    -1                                  -1                   -1
       3               1          4          34                0        1                  0             0             0              1                   0              1                   0                       0            0                 1                    -1                                  -1                    1

===========================================================================
STEP 5R CONCLUSION
===========================================================================

In [ ]:
# ============================================================
# STEP 5S — FROZEN XGBOOST RT-SENSITIVITY ANALYSIS
# ============================================================

import os
import json
import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

print("=" * 75)
print("STEP 5S — FROZEN XGBOOST RT-SENSITIVITY ANALYSIS")
print("=" * 75)

# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

DATA_PATH = "/content/Phishing_Legitimate_full.csv"

MODEL_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/models/xgboost.pkl"
)

FEATURE_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/feature_names.pkl"
)

CHECKPOINT_DIR = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints"
)

os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# ------------------------------------------------------------
# 2. Load frozen model + exact feature contract
# ------------------------------------------------------------

df = pd.read_csv(DATA_PATH)

model = joblib.load(MODEL_PATH)
feature_names = joblib.load(FEATURE_PATH)

feature_names = list(feature_names)

print("\nDataset:", df.shape)
print("Frozen model:", type(model).__name__)
print("Feature count:", len(feature_names))

assert len(feature_names) == 47
assert getattr(model, "n_features_in_", 47) == 47

print("[PASS] Frozen XGBoost and 47-feature contract loaded.")

# ------------------------------------------------------------
# 3. Prepare exact dataset matrix
# ------------------------------------------------------------

X = df[feature_names].copy()
y = df["CLASS_LABEL"].astype(int)

assert X.shape[1] == 47
assert list(X.columns) == feature_names

# ------------------------------------------------------------
# 4. Identify unresolved RT features
# ------------------------------------------------------------

RT_FEATURES = [
    "SubdomainLevelRT",
    "UrlLengthRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

UNRESOLVED_RT = [
    "PctExtResourceUrlsRT",
    "ExtMetaScriptLinkRT"
]

KNOWN_RT = [
    "SubdomainLevelRT",
    "UrlLengthRT",
    "AbnormalExtFormActionR",
    "PctExtNullSelfRedirectHyperlinksRT"
]

print("\nRT features:")
for f in RT_FEATURES:
    print(" -", f)

print("\nUnresolved RT features:")
for f in UNRESOLVED_RT:
    print(" -", f)

# ------------------------------------------------------------
# 5. Baseline prediction
# ------------------------------------------------------------
# IMPORTANT:
# This is NOT training.
# We are only evaluating the frozen saved model.

baseline_prob = model.predict_proba(X)[:, 1]
baseline_pred = (baseline_prob >= 0.5).astype(int)

baseline_metrics = {
    "accuracy": float(accuracy_score(y, baseline_pred)),
    "precision": float(
        precision_score(y, baseline_pred, zero_division=0)
    ),
    "recall": float(
        recall_score(y, baseline_pred, zero_division=0)
    ),
    "f1": float(
        f1_score(y, baseline_pred, zero_division=0)
    ),
    "roc_auc": float(
        roc_auc_score(y, baseline_prob)
    )
}

print("\n" + "=" * 75)
print("BASELINE FROZEN XGBOOST")
print("=" * 75)

for k, v in baseline_metrics.items():
    print(f"{k:10s}: {v:.6f}")

# ------------------------------------------------------------
# 6. Sensitivity test helper
# ------------------------------------------------------------

def evaluate_modified_matrix(X_modified, description):

    probability = model.predict_proba(
        X_modified
    )[:, 1]

    prediction = (
        probability >= 0.5
    ).astype(int)

    metrics = {
        "accuracy": float(
            accuracy_score(y, prediction)
        ),
        "precision": float(
            precision_score(
                y,
                prediction,
                zero_division=0
            )
        ),
        "recall": float(
            recall_score(
                y,
                prediction,
                zero_division=0
            )
        ),
        "f1": float(
            f1_score(
                y,
                prediction,
                zero_division=0
            )
        ),
        "roc_auc": float(
            roc_auc_score(y, probability)
        )
    }

    prediction_changes = int(
        np.sum(
            prediction != baseline_pred
        )
    )

    probability_change = float(
        np.mean(
            np.abs(
                probability -
                baseline_prob
            )
        )
    )

    max_probability_change = float(
        np.max(
            np.abs(
                probability -
                baseline_prob
            )
        )
    )

    return {
        "description": description,
        "metrics": metrics,
        "prediction_changes": prediction_changes,
        "prediction_change_pct": float(
            prediction_changes / len(y) * 100
        ),
        "mean_probability_change": probability_change,
        "max_probability_change": max_probability_change
    }

# ------------------------------------------------------------
# 7. Test ExtMetaScriptLinkRT sensitivity
# ------------------------------------------------------------

results = []

# Neutral value 0
X_meta_zero = X.copy()
X_meta_zero["ExtMetaScriptLinkRT"] = 0

results.append(
    evaluate_modified_matrix(
        X_meta_zero,
        "ExtMetaScriptLinkRT forced to 0"
    )
)

# Value -1
X_meta_minus1 = X.copy()
X_meta_minus1["ExtMetaScriptLinkRT"] = -1

results.append(
    evaluate_modified_matrix(
        X_meta_minus1,
        "ExtMetaScriptLinkRT forced to -1"
    )
)

# Value +1
X_meta_plus1 = X.copy()
X_meta_plus1["ExtMetaScriptLinkRT"] = 1

results.append(
    evaluate_modified_matrix(
        X_meta_plus1,
        "ExtMetaScriptLinkRT forced to +1"
    )
)

# ------------------------------------------------------------
# 8. Test PctExtResourceUrlsRT sensitivity
# ------------------------------------------------------------

X_resource_zero = X.copy()
X_resource_zero["PctExtResourceUrlsRT"] = 0

results.append(
    evaluate_modified_matrix(
        X_resource_zero,
        "PctExtResourceUrlsRT forced to 0"
    )
)

X_resource_minus1 = X.copy()
X_resource_minus1["PctExtResourceUrlsRT"] = -1

results.append(
    evaluate_modified_matrix(
        X_resource_minus1,
        "PctExtResourceUrlsRT forced to -1"
    )
)

X_resource_plus1 = X.copy()
X_resource_plus1["PctExtResourceUrlsRT"] = 1

results.append(
    evaluate_modified_matrix(
        X_resource_plus1,
        "PctExtResourceUrlsRT forced to +1"
    )
)

# ------------------------------------------------------------
# 9. Test both unresolved RT features together
# ------------------------------------------------------------

for value in [-1, 0, 1]:

    X_both = X.copy()

    X_both["ExtMetaScriptLinkRT"] = value
    X_both["PctExtResourceUrlsRT"] = value

    results.append(
        evaluate_modified_matrix(
            X_both,
            f"Both unresolved RT features forced to {value}"
        )
    )

# ------------------------------------------------------------
# 10. Display sensitivity results
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("RT SENSITIVITY RESULTS")
print("=" * 75)

for result in results:

    print("\n" + result["description"])

    print(
        f"  Prediction changes : "
        f"{result['prediction_changes']} "
        f"({result['prediction_change_pct']:.4f}%)"
    )

    print(
        f"  Mean probability Δ : "
        f"{result['mean_probability_change']:.6f}"
    )

    print(
        f"  Max probability Δ  : "
        f"{result['max_probability_change']:.6f}"
    )

    print(
        f"  Accuracy           : "
        f"{result['metrics']['accuracy']:.6f}"
    )

    print(
        f"  F1                 : "
        f"{result['metrics']['f1']:.6f}"
    )

# ------------------------------------------------------------
# 11. Determine feature sensitivity
# ------------------------------------------------------------

meta_results = [
    r for r in results
    if "ExtMetaScriptLinkRT forced" in r["description"]
]

resource_results = [
    r for r in results
    if "PctExtResourceUrlsRT forced" in r["description"]
]

max_meta_change = max(
    r["prediction_change_pct"]
    for r in meta_results
)

max_resource_change = max(
    r["prediction_change_pct"]
    for r in resource_results
)

print("\n" + "=" * 75)
print("SENSITIVITY SUMMARY")
print("=" * 75)

print(
    f"Maximum prediction-change percentage "
    f"from ExtMetaScriptLinkRT: "
    f"{max_meta_change:.4f}%"
)

print(
    f"Maximum prediction-change percentage "
    f"from PctExtResourceUrlsRT: "
    f"{max_resource_change:.4f}%"
)

# ------------------------------------------------------------
# 12. Save checkpoint
# ------------------------------------------------------------

checkpoint_path = os.path.join(
    CHECKPOINT_DIR,
    "step_5S_xgboost_rt_sensitivity.json"
)

checkpoint = {
    "stage": "Step 5S",
    "dataset_shape": list(df.shape),
    "feature_count": len(feature_names),
    "model_type": type(model).__name__,
    "model_path": MODEL_PATH,
    "feature_path": FEATURE_PATH,
    "baseline_metrics": baseline_metrics,
    "unresolved_rt_features": UNRESOLVED_RT,
    "known_rt_features": KNOWN_RT,
    "sensitivity_results": results,
    "max_meta_prediction_change_pct": max_meta_change,
    "max_resource_prediction_change_pct": max_resource_change,
    "class_label_used": True,
    "class_label_used_only_for_evaluation": True,
    "training_performed": False,
    "prediction_performed": True,
    "model_modified": False
}

with open(checkpoint_path, "w") as f:
    json.dump(checkpoint, f, indent=2)

# Verify checkpoint
with open(checkpoint_path, "r") as f:
    verified = json.load(f)

assert verified["stage"] == "Step 5S"
assert verified["model_modified"] is False
assert verified["training_performed"] is False

print("\n" + "=" * 75)
print("STEP 5S CHECKPOINT SAVED")
print("=" * 75)

print(f"Checkpoint: {checkpoint_path}")
print("[PASS] JSON checkpoint verified successfully.")
print("Frozen XGBoost only.")
print("No training performed.")
print("No model modified.")
print("=" * 75)
print("END STEP 5S")
print("=" * 75)

===========================================================================
STEP 5S — FROZEN XGBOOST RT-SENSITIVITY ANALYSIS
===========================================================================

Dataset: (10000, 50)
Frozen model: XGBClassifier
Feature count: 47
[PASS] Frozen XGBoost and 47-feature contract loaded.

RT features:
 - SubdomainLevelRT
 - UrlLengthRT
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

Unresolved RT features:
 - PctExtResourceUrlsRT
 - ExtMetaScriptLinkRT

===========================================================================
BASELINE FROZEN XGBOOST
===========================================================================
accuracy  : 0.996000
precision : 0.995010
recall    : 0.997000
f1        : 0.996004
roc_auc   : 0.999721

===========================================================================
RT SENSITIVITY RESULTS
===========================================================================

ExtMetaScriptLinkRT forced to 0
  Prediction changes : 4 (0.0400%)
  Mean probability Δ : 0.001857
  Max probability Δ  : 0.472937
  Accuracy           : 0.995600
  F1                 : 0.995603

ExtMetaScriptLinkRT forced to -1
  Prediction changes : 19 (0.1900%)
  Mean probability Δ : 0.005363
  Max probability Δ  : 0.460710
  Accuracy           : 0.994700
  F1                 : 0.994715

ExtMetaScriptLinkRT forced to +1
  Prediction changes : 7 (0.0700%)
  Mean probability Δ : 0.001720
  Max probability Δ  : 0.464373
  Accuracy           : 0.995300
  F1                 : 0.995304

PctExtResourceUrlsRT forced to 0
  Prediction changes : 5 (0.0500%)
  Mean probability Δ : 0.000513
  Max probability Δ  : 0.144115
  Accuracy           : 0.995500
  F1                 : 0.995503

PctExtResourceUrlsRT forced to -1
  Prediction changes : 5 (0.0500%)
  Mean probability Δ : 0.000570
  Max probability Δ  : 0.128131
  Accuracy           : 0.995500
  F1                 : 0.995503

PctExtResourceUrlsRT forced to +1
  Prediction changes : 2 (0.0200%)
  Mean probability Δ : 0.000350
  Max probability Δ  : 0.070267
  Accuracy           : 0.995800
  F1                 : 0.995804

Both unresolved RT features forced to -1
  Prediction changes : 19 (0.1900%)
  Mean probability Δ : 0.004819
  Max probability Δ  : 0.443963
  Accuracy           : 0.994700
  F1                 : 0.994714

Both unresolved RT features forced to 0
  Prediction changes : 9 (0.0900%)
  Mean probability Δ : 0.002276
  Max probability Δ  : 0.485228
  Accuracy           : 0.995100
  F1                 : 0.995100

Both unresolved RT features forced to 1
  Prediction changes : 8 (0.0800%)
  Mean probability Δ : 0.001827
  Max probability Δ  : 0.464373
  Accuracy           : 0.995200
  F1                 : 0.995204

===========================================================================
SENSITIVITY SUMMARY
===========================================================================
Maximum prediction-change percentage from ExtMetaScriptLinkRT: 0.1900%
Maximum prediction-change percentage from PctExtResourceUrlsRT: 0.0500%

===========================================================================
STEP 5S CHECKPOINT SAVED
===========================================================================
Checkpoint: /content/drive/MyDrive/PhishShield_AI/checkpoints/step_5S_xgboost_rt_sensitivity.json
[PASS] JSON checkpoint verified successfully.
Frozen XGBoost only.
No training performed.
No model modified.
===========================================================================
END STEP 5S
===========================================================================

In [ ]:
# ============================================================
# STEP 5T — FINAL 47-FEATURE PRODUCTION CONTRACT
# ============================================================

import os
import json
import joblib
import pandas as pd

print("=" * 75)
print("STEP 5T — FINAL 47-FEATURE PRODUCTION CONTRACT")
print("=" * 75)

# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

FEATURE_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/feature_names.pkl"
)

CHECKPOINT_DIR = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints"
)

os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# ------------------------------------------------------------
# 2. Load exact frozen feature contract
# ------------------------------------------------------------

feature_names = list(
    joblib.load(FEATURE_PATH)
)

print("\nFrozen feature count:", len(feature_names))

assert len(feature_names) == 47

print("[PASS] Exact 47-feature contract loaded.")

# ------------------------------------------------------------
# 3. Define feature ownership
# ------------------------------------------------------------

URL_FEATURES = [
    "NumDots",
    "SubdomainLevel",
    "PathLevel",
    "UrlLength",
    "NumDash",
    "NumDashInHostname",
    "AtSymbol",
    "TildeSymbol",
    "NumUnderscore",
    "NumPercent",
    "NumQueryComponents",
    "NumAmpersand",
    "NumHash",
    "NumNumericChars",
    "NoHttps",
    "RandomString",
    "IpAddress",
    "DomainInSubdomains",
    "DomainInPaths",
    "HostnameLength",
    "PathLength",
    "QueryLength",
    "DoubleSlashInPath",
    "NumSensitiveWords",
    "EmbeddedBrandName"
]

HTML_FEATURES = [
    "PctExtHyperlinks",
    "PctExtResourceUrls",
    "ExtFavicon",
    "InsecureForms",
    "RelativeFormAction",
    "ExtFormAction",
    "AbnormalFormAction",
    "PctNullSelfRedirectHyperlinks",
    "FrequentDomainNameMismatch",
    "FakeLinkInStatusBar",
    "RightClickDisabled",
    "PopUpWindow",
    "SubmitInfoToEmail",
    "IframeOrFrame",
    "MissingTitle",
    "ImagesOnlyInForm"
]

RT_FEATURES = [
    "SubdomainLevelRT",
    "UrlLengthRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

# ------------------------------------------------------------
# 4. RT status
# ------------------------------------------------------------

RECONSTRUCTED_RT = [
    "SubdomainLevelRT",
    "UrlLengthRT",
    "AbnormalExtFormActionR",
    "PctExtNullSelfRedirectHyperlinksRT"
]

UNRESOLVED_RT = [
    "PctExtResourceUrlsRT",
    "ExtMetaScriptLinkRT"
]

# ------------------------------------------------------------
# 5. Verify feature ownership
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("FEATURE OWNERSHIP")
print("=" * 75)

print(
    f"URL features  : {len(URL_FEATURES)}"
)

print(
    f"HTML features : {len(HTML_FEATURES)}"
)

print(
    f"RT features   : {len(RT_FEATURES)}"
)

print(
    f"Total listed  : "
    f"{len(URL_FEATURES) + len(HTML_FEATURES) + len(RT_FEATURES)}"
)

# Every feature must belong to exactly one category
all_owned = (
    URL_FEATURES +
    HTML_FEATURES +
    RT_FEATURES
)

assert len(all_owned) == 47
assert len(set(all_owned)) == 47

assert set(all_owned) == set(feature_names)

print(
    "\n[PASS] Every frozen feature belongs to "
    "exactly one production category."
)

# ------------------------------------------------------------
# 6. Verify reconstructed RT features
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("RECONSTRUCTED RT FEATURES")
print("=" * 75)

reconstruction_status = {
    "SubdomainLevelRT": {
        "status": "reconstructed",
        "basis": (
            "Exact mapping from retained dataset "
            "non-target features; 100% consistency."
        )
    },
    "UrlLengthRT": {
        "status": "reconstructed",
        "basis": (
            "Verified deterministic thresholds: "
            "12–53 => 1, 54–75 => 0, "
            "76–253 => -1."
        )
    },
    "AbnormalExtFormActionR": {
        "status": "reconstructed",
        "basis": (
            "Exact mapping from retained dataset "
            "form-action features; 100% consistency."
        )
    },
    "PctExtNullSelfRedirectHyperlinksRT": {
        "status": "reconstructed",
        "basis": (
            "Exact mapping from retained dataset "
            "non-target features; 100% consistency."
        )
    }
}

for feature, info in reconstruction_status.items():

    print(
        f"\n{feature}"
    )

    print(
        f"  Status : {info['status']}"
    )

    print(
        f"  Basis  : {info['basis']}"
    )

# ------------------------------------------------------------
# 7. Verify unresolved RT features
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("UNRESOLVED RT FEATURES")
print("=" * 75)

unresolved_status = {
    "PctExtResourceUrlsRT": {
        "status": "unresolved",
        "reason": (
            "Original exact transformation cannot be "
            "uniquely reconstructed from retained "
            "47-feature information."
        ),
        "sensitivity": "Maximum prediction change 0.05%"
    },
    "ExtMetaScriptLinkRT": {
        "status": "unresolved",
        "reason": (
            "Original exact transformation cannot be "
            "uniquely reconstructed from retained "
            "47-feature information."
        ),
        "sensitivity": "Maximum prediction change 0.19%"
    }
}

for feature, info in unresolved_status.items():

    print(
        f"\n{feature}"
    )

    print(
        f"  Status      : {info['status']}"
    )

    print(
        f"  Reason      : {info['reason']}"
    )

    print(
        f"  Sensitivity : {info['sensitivity']}"
    )

# ------------------------------------------------------------
# 8. Production handling policy
# ------------------------------------------------------------

production_policy = {
    "silent_zero_fallback": False,
    "invented_rt_formula": False,
    "model_retraining": False,
    "unresolved_rt_handling": "explicit_unknown",
    "frozen_model": "XGBoost",
    "feature_count": 47,
    "missing_feature_policy": "fail_validation",
    "extra_feature_policy": "fail_validation"
}

print("\n" + "=" * 75)
print("PRODUCTION POLICY")
print("=" * 75)

for key, value in production_policy.items():

    print(
        f"{key:25s}: {value}"
    )

# ------------------------------------------------------------
# 9. Final contract validation
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("FINAL CONTRACT VALIDATION")
print("=" * 75)

assert len(feature_names) == 47
assert len(URL_FEATURES) == 25
assert len(HTML_FEATURES) == 16
assert len(RT_FEATURES) == 6

assert len(RECONSTRUCTED_RT) == 4
assert len(UNRESOLVED_RT) == 2

assert (
    set(RECONSTRUCTED_RT)
    .isdisjoint(set(UNRESOLVED_RT))
)

assert (
    set(RECONSTRUCTED_RT + UNRESOLVED_RT)
    == set(RT_FEATURES)
)

assert (
    set(URL_FEATURES)
    .isdisjoint(set(HTML_FEATURES))
)

assert (
    set(URL_FEATURES + HTML_FEATURES + RT_FEATURES)
    == set(feature_names)
)

print("[PASS] 47 features accounted for.")
print("[PASS] 25 URL features accounted for.")
print("[PASS] 16 HTML features accounted for.")
print("[PASS] 6 RT features accounted for.")
print("[PASS] 4 RT features reconstructed.")
print("[PASS] 2 RT features explicitly unresolved.")
print("[PASS] No silent zero fallback.")
print("[PASS] No invented formula.")
print("[PASS] Frozen XGBoost unchanged.")

# ------------------------------------------------------------
# 10. Save production contract
# ------------------------------------------------------------

checkpoint_path = os.path.join(
    CHECKPOINT_DIR,
    "step_5T_final_47_feature_production_contract.json"
)

contract = {
    "stage": "Step 5T",
    "feature_count": 47,
    "feature_names": feature_names,

    "categories": {
        "url_features": URL_FEATURES,
        "html_features": HTML_FEATURES,
        "rt_features": RT_FEATURES
    },

    "rt_status": {
        "reconstructed": reconstruction_status,
        "unresolved": unresolved_status
    },

    "production_policy": production_policy,

    "model": {
        "type": "XGBClassifier",
        "frozen": True,
        "retrained": False,
        "modified": False
    },

    "validation": {
        "class_label_used": False,
        "id_used": False,
        "training_performed": False,
        "prediction_performed": False
    }
}

with open(checkpoint_path, "w") as f:
    json.dump(
        contract,
        f,
        indent=2
    )

# ------------------------------------------------------------
# 11. Verify saved contract
# ------------------------------------------------------------

with open(checkpoint_path, "r") as f:
    verified = json.load(f)

assert verified["feature_count"] == 47
assert len(
    verified["feature_names"]
) == 47

assert (
    verified["model"]["modified"]
    is False
)

assert (
    verified["model"]["retrained"]
    is False
)

print("\n" + "=" * 75)
print("STEP 5T CHECKPOINT SAVED")
print("=" * 75)

print(
    f"Checkpoint: {checkpoint_path}"
)

print(
    "[PASS] Production contract verified successfully."
)

print("\nFINAL CONTRACT:")
print("  47 total features")
print("  25 URL-derived")
print("  16 HTML-derived")
print("   6 RT-derived")
print("   4 RT reconstructed")
print("   2 RT unresolved")
print("   0 silent fallback")
print("   0 model retraining")

print("\n" + "=" * 75)
print("END STEP 5T")
print("=" * 75)

===========================================================================
STEP 5T — FINAL 47-FEATURE PRODUCTION CONTRACT
===========================================================================

Frozen feature count: 47
[PASS] Exact 47-feature contract loaded.

===========================================================================
FEATURE OWNERSHIP
===========================================================================
URL features  : 25
HTML features : 16
RT features   : 6
Total listed  : 47

[PASS] Every frozen feature belongs to exactly one production category.

===========================================================================
RECONSTRUCTED RT FEATURES
===========================================================================

SubdomainLevelRT
  Status : reconstructed
  Basis  : Exact mapping from retained dataset non-target features; 100% consistency.

UrlLengthRT
  Status : reconstructed
  Basis  : Verified deterministic thresholds: 12–53 => 1, 54–75 => 0, 76–253 => -1.

AbnormalExtFormActionR
  Status : reconstructed
  Basis  : Exact mapping from retained dataset form-action features; 100% consistency.

PctExtNullSelfRedirectHyperlinksRT
  Status : reconstructed
  Basis  : Exact mapping from retained dataset non-target features; 100% consistency.

===========================================================================
UNRESOLVED RT FEATURES
===========================================================================

PctExtResourceUrlsRT
  Status      : unresolved
  Reason      : Original exact transformation cannot be uniquely reconstructed from retained 47-feature information.
  Sensitivity : Maximum prediction change 0.05%

ExtMetaScriptLinkRT
  Status      : unresolved
  Reason      : Original exact transformation cannot be uniquely reconstructed from retained 47-feature information.
  Sensitivity : Maximum prediction change 0.19%

===========================================================================
PRODUCTION POLICY
===========================================================================
silent_zero_fallback     : False
invented_rt_formula      : False
model_retraining         : False
unresolved_rt_handling   : explicit_unknown
frozen_model             : XGBoost
feature_count            : 47
missing_feature_policy   : fail_validation
extra_feature_policy     : fail_validation

===========================================================================
FINAL CONTRACT VALIDATION
===========================================================================
[PASS] 47 features accounted for.
[PASS] 25 URL features accounted for.
[PASS] 16 HTML features accounted for.
[PASS] 6 RT features accounted for.
[PASS] 4 RT features reconstructed.
[PASS] 2 RT features explicitly unresolved.
[PASS] No silent zero fallback.
[PASS] No invented formula.
[PASS] Frozen XGBoost unchanged.

===========================================================================
STEP 5T CHECKPOINT SAVED
===========================================================================
Checkpoint: /content/drive/MyDrive/PhishShield_AI/checkpoints/step_5T_final_47_feature_production_contract.json
[PASS] Production contract verified successfully.

FINAL CONTRACT:
  47 total features
  25 URL-derived
  16 HTML-derived
   6 RT-derived
   4 RT reconstructed
   2 RT unresolved
   0 silent fallback
   0 model retraining

===========================================================================
END STEP 5T
===========================================================================

In [ ]:
# ============================================================
# STEP 6 — LIVE FEATURE VALIDATION
# ============================================================

import os
import json
import sys
import joblib
import numpy as np
import pandas as pd

print("=" * 75)
print("STEP 6 — LIVE FEATURE VALIDATION")
print("=" * 75)

# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

FEATURE_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/feature_names.pkl"
)

CHECKPOINT_DIR = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints"
)

os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# ------------------------------------------------------------
# 2. Load frozen feature contract
# ------------------------------------------------------------

feature_names = list(
    joblib.load(FEATURE_PATH)
)

assert len(feature_names) == 47

print("\n[PASS] Frozen 47-feature contract loaded.")

# ------------------------------------------------------------
# 3. Import production extractor
# ------------------------------------------------------------
# Step 5I/5M extractor definitions should already exist
# in the current Colab runtime.

required_functions = [
    "extract_url_features",
    "fetch_html",
    "extract_html_features"
]

missing_functions = [
    name
    for name in required_functions
    if name not in globals()
]

if missing_functions:

    print("\n[ERROR] Required extractor functions missing:")
    for name in missing_functions:
        print(" -", name)

    raise RuntimeError(
        "Please make sure the Step 5I/5M extractor "
        "definitions have been executed in this runtime."
    )

print(
    "[PASS] Production extractor functions "
    "available."
)

# ------------------------------------------------------------
# 4. Test URLs
# ------------------------------------------------------------

TEST_URLS = {
    "Google": "https://www.google.com",
    "Microsoft": "https://www.microsoft.com",
    "GitHub": "https://github.com",
    "Python": "https://www.python.org"
}

# ------------------------------------------------------------
# 5. RT classification
# ------------------------------------------------------------

RECONSTRUCTED_RT = [
    "SubdomainLevelRT",
    "UrlLengthRT",
    "AbnormalExtFormActionR",
    "PctExtNullSelfRedirectHyperlinksRT"
]

UNRESOLVED_RT = [
    "PctExtResourceUrlsRT",
    "ExtMetaScriptLinkRT"
]

HTML_FEATURES = [
    "PctExtHyperlinks",
    "PctExtResourceUrls",
    "ExtFavicon",
    "InsecureForms",
    "RelativeFormAction",
    "ExtFormAction",
    "AbnormalFormAction",
    "PctNullSelfRedirectHyperlinks",
    "FrequentDomainNameMismatch",
    "FakeLinkInStatusBar",
    "RightClickDisabled",
    "PopUpWindow",
    "SubmitInfoToEmail",
    "IframeOrFrame",
    "MissingTitle",
    "ImagesOnlyInForm"
]

# ------------------------------------------------------------
# 6. Validation function
# ------------------------------------------------------------

def validate_live_url(name, url):

    print("\n" + "-" * 75)
    print(f"TESTING: {name}")
    print(f"URL    : {url}")
    print("-" * 75)

    # --------------------------------------------------------
    # URL features
    # --------------------------------------------------------

    url_result = extract_url_features(url)

    assert isinstance(url_result, dict)

    assert "features" in url_result

    url_features = url_result["features"]

    assert isinstance(url_features, dict)

    print(
        f"\nURL extractor features : "
        f"{len(url_features)}"
    )

    print(
        f"URL extractor missing  : "
        f"{len(url_result.get('missing_features', []))}"
    )

    print(
        f"URL extractor unknown  : "
        f"{len(url_result.get('unknown_features', []))}"
    )

    # --------------------------------------------------------
    # Fetch HTML
    # --------------------------------------------------------

    final_url, html = fetch_html(url)

    assert isinstance(final_url, str)
    assert isinstance(html, str)

    print(
        f"Final URL              : "
        f"{final_url}"
    )

    print(
        f"HTML length             : "
        f"{len(html)}"
    )

    assert len(html) > 0

    # --------------------------------------------------------
    # HTML features
    # --------------------------------------------------------

    html_features = extract_html_features(
        html,
        final_url
    )

    assert isinstance(html_features, dict)

    print(
        f"HTML extractor features: "
        f"{len(html_features)}"
    )

    # --------------------------------------------------------
    # Verify HTML feature ownership
    # --------------------------------------------------------

    missing_html_keys = [
        f for f in HTML_FEATURES
        if f not in html_features
    ]

    extra_html_keys = [
        f for f in html_features
        if f not in HTML_FEATURES
    ]

    print(
        f"Missing HTML keys      : "
        f"{len(missing_html_keys)}"
    )

    print(
        f"Extra HTML keys        : "
        f"{len(extra_html_keys)}"
    )

    if missing_html_keys:
        print(
            "Missing HTML features:"
        )
        for f in missing_html_keys:
            print(" -", f)

    if extra_html_keys:
        print(
            "Extra HTML features:"
        )
        for f in extra_html_keys:
            print(" -", f)

    assert not missing_html_keys
    assert not extra_html_keys

    # --------------------------------------------------------
    # Correct merge
    # --------------------------------------------------------

    combined = dict(url_features)

    replaced_none = []

    for feature, value in html_features.items():

        if feature not in combined:
            combined[feature] = value

        elif combined[feature] is None:
            combined[feature] = value
            replaced_none.append(feature)

    # --------------------------------------------------------
    # Validate exact feature contract
    # --------------------------------------------------------

    missing_features = [
        f for f in feature_names
        if f not in combined
    ]

    extra_features = [
        f for f in combined
        if f not in feature_names
    ]

    none_features = [
        f for f in feature_names
        if combined.get(f) is None
    ]

    print(
        f"\nCombined feature count : "
        f"{len(combined)}"
    )

    print(
        f"Missing frozen features: "
        f"{len(missing_features)}"
    )

    print(
        f"Extra features         : "
        f"{len(extra_features)}"
    )

    print(
        f"None-valued features   : "
        f"{len(none_features)}"
    )

    print(
        f"HTML values inserted   : "
        f"{len(replaced_none)}"
    )

    # --------------------------------------------------------
    # Expected unresolved RT behaviour
    # --------------------------------------------------------

    unexpected_none = [
        f for f in none_features
        if f not in UNRESOLVED_RT
    ]

    unresolved_not_none = [
        f for f in UNRESOLVED_RT
        if combined.get(f) is not None
    ]

    reconstructed_none = [
        f for f in RECONSTRUCTED_RT
        if combined.get(f) is None
    ]

    print(
        f"Unexpected None values : "
        f"{len(unexpected_none)}"
    )

    print(
        f"Unresolved RT populated: "
        f"{len(unresolved_not_none)}"
    )

    print(
        f"Reconstructed RT None  : "
        f"{len(reconstructed_none)}"
    )

    if none_features:
        print("\nNone-valued features:")
        for f in none_features:
            print(" -", f)

    # --------------------------------------------------------
    # Structural assertions
    # --------------------------------------------------------

    assert len(combined) == 47
    assert len(missing_features) == 0
    assert len(extra_features) == 0

    # Only the two deliberately unresolved RT
    # features may remain None.
    assert set(none_features).issubset(
        set(UNRESOLVED_RT)
    )

    # All reconstructed RT features must be populated.
    assert len(reconstructed_none) == 0

    # Both unresolved features must remain explicitly unknown.
    assert set(unresolved_not_none) == set()

    # --------------------------------------------------------
    # Verify exact vector order
    # --------------------------------------------------------

    vector = [
        combined[f]
        for f in feature_names
    ]

    assert len(vector) == 47

    # --------------------------------------------------------
    # Verify no accidental NaN
    # --------------------------------------------------------

    nan_features = []

    for feature, value in combined.items():

        if value is None:
            continue

        try:
            if pd.isna(value):
                nan_features.append(feature)
        except Exception:
            pass

    print(
        f"NaN-valued features     : "
        f"{len(nan_features)}"
    )

    assert len(nan_features) == 0

    # --------------------------------------------------------
    # Show RT values
    # --------------------------------------------------------

    print("\nRT values:")

    for feature in [
        "SubdomainLevelRT",
        "UrlLengthRT",
        "PctExtResourceUrlsRT",
        "AbnormalExtFormActionR",
        "ExtMetaScriptLinkRT",
        "PctExtNullSelfRedirectHyperlinksRT"
    ]:

        print(
            f"  {feature:38s}: "
            f"{combined.get(feature)}"
        )

    # --------------------------------------------------------
    # Show HTML values
    # --------------------------------------------------------

    print("\nHTML-derived values:")

    for feature in HTML_FEATURES:

        print(
            f"  {feature:38s}: "
            f"{combined.get(feature)}"
        )

    print("\n[PASS] Exact 47-feature structural validation.")

    return {
        "name": name,
        "input_url": url,
        "final_url": final_url,
        "html_length": int(len(html)),
        "url_feature_count": int(len(url_features)),
        "html_feature_count": int(len(html_features)),
        "combined_feature_count": int(len(combined)),
        "missing_features": missing_features,
        "extra_features": extra_features,
        "none_features": none_features,
        "replaced_none_features": replaced_none,
        "unexpected_none": unexpected_none,
        "reconstructed_rt": {
            f: combined[f]
            for f in RECONSTRUCTED_RT
        },
        "unresolved_rt": {
            f: combined[f]
            for f in UNRESOLVED_RT
        },
        "vector_length": int(len(vector)),
        "nan_features": nan_features,
        "validation_passed": True
    }

# ------------------------------------------------------------
# 7. Run all live tests
# ------------------------------------------------------------

results = {}

for name, url in TEST_URLS.items():

    try:

        results[name] = validate_live_url(
            name,
            url
        )

    except Exception as e:

        print(
            f"\n[FAIL] {name}: "
            f"{type(e).__name__}: {e}"
        )

        results[name] = {
            "name": name,
            "input_url": url,
            "validation_passed": False,
            "error_type": type(e).__name__,
            "error": str(e)
        }

# ------------------------------------------------------------
# 8. Overall result
# ------------------------------------------------------------

passed = [
    name
    for name, result in results.items()
    if result.get("validation_passed") is True
]

failed = [
    name
    for name, result in results.items()
    if result.get("validation_passed") is not True
]

print("\n" + "=" * 75)
print("STEP 6 OVERALL RESULT")
print("=" * 75)

print(
    f"Tests passed : "
    f"{len(passed)}/{len(TEST_URLS)}"
)

print(
    f"Tests failed : "
    f"{len(failed)}/{len(TEST_URLS)}"
)

if passed:
    print("\nPassed:")
    for name in passed:
        print(" -", name)

if failed:
    print("\nFailed:")
    for name in failed:
        print(" -", name)

# ------------------------------------------------------------
# 9. Save checkpoint
# ------------------------------------------------------------

checkpoint_path = os.path.join(
    CHECKPOINT_DIR,
    "step_6_live_feature_validation.json"
)

checkpoint = {
    "stage": "Step 6",
    "feature_count": 47,
    "test_urls": TEST_URLS,
    "results": results,
    "passed_count": len(passed),
    "failed_count": len(failed),
    "reconstructed_rt": RECONSTRUCTED_RT,
    "unresolved_rt": UNRESOLVED_RT,
    "class_label_used": False,
    "id_used": False,
    "training_performed": False,
    "prediction_performed": False,
    "model_modified": False
}

with open(checkpoint_path, "w") as f:
    json.dump(
        checkpoint,
        f,
        indent=2
    )

# Verify checkpoint
with open(checkpoint_path, "r") as f:
    verified = json.load(f)

assert verified["stage"] == "Step 6"
assert verified["feature_count"] == 47
assert verified["model_modified"] is False
assert verified["training_performed"] is False
assert verified["prediction_performed"] is False

print("\n" + "=" * 75)
print("STEP 6 CHECKPOINT SAVED")
print("=" * 75)

print(
    f"Checkpoint: {checkpoint_path}"
)

print(
    "[PASS] JSON checkpoint verified successfully."
)

print("\nNo training performed.")
print("No prediction performed.")
print("No model modified.")

print("=" * 75)
print("END STEP 6")
print("=" * 75)

===========================================================================
STEP 6 — LIVE FEATURE VALIDATION
===========================================================================

[PASS] Frozen 47-feature contract loaded.
[PASS] Production extractor functions available.

---------------------------------------------------------------------------
TESTING: Google
URL    : https://www.google.com
---------------------------------------------------------------------------

URL extractor features : 47
URL extractor missing  : 0
URL extractor unknown  : 21
Final URL              : https://www.google.com/
HTML length             : 224272
HTML extractor features: 16
Missing HTML keys      : 0
Extra HTML keys        : 0

Combined feature count : 47
Missing frozen features: 0
Extra features         : 0
None-valued features   : 5
HTML values inserted   : 16
Unexpected None values : 3
Unresolved RT populated: 0
Reconstructed RT None  : 3

None-valued features:
 - SubdomainLevelRT
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

[FAIL] Google: AssertionError:

---------------------------------------------------------------------------
TESTING: Microsoft
URL    : https://www.microsoft.com
---------------------------------------------------------------------------

URL extractor features : 47
URL extractor missing  : 0
URL extractor unknown  : 21
Final URL              : https://www.microsoft.com/
HTML length             : 201253
HTML extractor features: 16
Missing HTML keys      : 0
Extra HTML keys        : 0

Combined feature count : 47
Missing frozen features: 0
Extra features         : 0
None-valued features   : 5
HTML values inserted   : 16
Unexpected None values : 3
Unresolved RT populated: 0
Reconstructed RT None  : 3

None-valued features:
 - SubdomainLevelRT
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

[FAIL] Microsoft: AssertionError:

---------------------------------------------------------------------------
TESTING: GitHub
URL    : https://github.com
---------------------------------------------------------------------------

URL extractor features : 47
URL extractor missing  : 0
URL extractor unknown  : 21
Final URL              : https://github.com/
HTML length             : 573359
HTML extractor features: 16
Missing HTML keys      : 0
Extra HTML keys        : 0

Combined feature count : 47
Missing frozen features: 0
Extra features         : 0
None-valued features   : 5
HTML values inserted   : 16
Unexpected None values : 3
Unresolved RT populated: 0
Reconstructed RT None  : 3

None-valued features:
 - SubdomainLevelRT
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

[FAIL] GitHub: AssertionError:

---------------------------------------------------------------------------
TESTING: Python
URL    : https://www.python.org
---------------------------------------------------------------------------

URL extractor features : 47
URL extractor missing  : 0
URL extractor unknown  : 21
Final URL              : https://www.python.org/
HTML length             : 52746
HTML extractor features: 16
Missing HTML keys      : 0
Extra HTML keys        : 0

Combined feature count : 47
Missing frozen features: 0
Extra features         : 0
None-valued features   : 5
HTML values inserted   : 16
Unexpected None values : 3
Unresolved RT populated: 0
Reconstructed RT None  : 3

None-valued features:
 - SubdomainLevelRT
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

[FAIL] Python: AssertionError:

===========================================================================
STEP 6 OVERALL RESULT
===========================================================================
Tests passed : 0/4
Tests failed : 4/4

Failed:
 - Google
 - Microsoft
 - GitHub
 - Python

===========================================================================
STEP 6 CHECKPOINT SAVED
===========================================================================
Checkpoint: /content/drive/MyDrive/PhishShield_AI/checkpoints/step_6_live_feature_validation.json
[PASS] JSON checkpoint verified successfully.

No training performed.
No prediction performed.
No model modified.
===========================================================================
END STEP 6
===========================================================================

In [ ]:
# ============================================================
# STEP 6A — DIAGNOSE RECONSTRUCTED RT FEATURES
# ============================================================

print("=" * 75)
print("STEP 6A — DIAGNOSE RECONSTRUCTED RT FEATURES")
print("=" * 75)

RECONSTRUCTED_RT = [
    "SubdomainLevelRT",
    "UrlLengthRT",
    "AbnormalExtFormActionR",
    "PctExtNullSelfRedirectHyperlinksRT"
]

TEST_URLS = {
    "Google": "https://www.google.com",
    "Microsoft": "https://www.microsoft.com",
    "GitHub": "https://github.com",
    "Python": "https://www.python.org"
}

# ------------------------------------------------------------
# 1. Inspect currently defined RT-related objects
# ------------------------------------------------------------

print("\nRT-related functions/objects currently in runtime:")

rt_objects = [
    name for name in globals()
    if "rt" in name.lower()
    or "subdomain" in name.lower()
    or "abnormal" in name.lower()
    or "redirect" in name.lower()
]

if rt_objects:
    for name in sorted(rt_objects):
        obj = globals()[name]
        print(
            f" - {name}: "
            f"{type(obj).__name__}"
        )
else:
    print(" [NONE FOUND]")

# ------------------------------------------------------------
# 2. Inspect live URL extractor output
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("CURRENT EXTRACTOR OUTPUT")
print("=" * 75)

for name, url in TEST_URLS.items():

    print(f"\n{name}: {url}")

    result = extract_url_features(url)

    assert isinstance(result, dict)
    assert "features" in result

    features = result["features"]

    print("\nReconstructed RT values:")

    for feature in RECONSTRUCTED_RT:

        value = features.get(feature)

        print(
            f"  {feature:38s}: "
            f"{value!r} "
            f"(type={type(value).__name__})"
        )

    print("\nOther relevant URL values:")

    relevant = [
        "NumDots",
        "SubdomainLevel",
        "PathLevel",
        "UrlLength",
        "NumDash",
        "NumDashInHostname",
        "NumNumericChars",
        "HostnameLength",
        "PathLength",
        "DomainInSubdomains",
        "DomainInPaths",
        "RandomString",
        "UrlLengthRT"
    ]

    for feature in relevant:

        if feature in features:

            print(
                f"  {feature:38s}: "
                f"{features[feature]!r}"
            )

# ------------------------------------------------------------
# 3. Inspect source of extractor functions
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("EXTRACTOR SOURCE INSPECTION")
print("=" * 75)

import inspect

for function_name in [
    "extract_url_features",
    "fetch_html",
    "extract_html_features"
]:

    if function_name in globals():

        print(
            f"\n--- {function_name} ---"
        )

        try:
            source = inspect.getsource(
                globals()[function_name]
            )

            lines = source.splitlines()

            # Print only RT-related lines plus
            # surrounding context.
            for i, line in enumerate(lines):

                lower = line.lower()

                if (
                    "rt" in lower
                    or "subdomainlevel" in lower
                    or "abnormalextform" in lower
                    or "nullself" in lower
                ):

                    start = max(0, i - 3)
                    end = min(
                        len(lines),
                        i + 4
                    )

                    for j in range(start, end):

                        print(
                            f"{j+1:4d}: "
                            f"{lines[j]}"
                        )

                    print("...")

        except Exception as e:

            print(
                f"Could not inspect source: "
                f"{type(e).__name__}: {e}"
            )

# ------------------------------------------------------------
# 4. Diagnostic conclusion
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("STEP 6A DIAGNOSTIC CONCLUSION")
print("=" * 75)

print(
    "The four reconstructed RT features must be "
    "populated by the production extractor before "
    "live validation can pass."
)

print(
    "\nNo model training."
)

print(
    "No XGBoost prediction."
)

print(
    "No model modification."
)

print("=" * 75)
print("END STEP 6A")
print("=" * 75)

===========================================================================
STEP 6A — DIAGNOSE RECONSTRUCTED RT FEATURES
===========================================================================

RT-related functions/objects currently in runtime:
 - KNOWN_RT: list
 - RECONSTRUCTED_RT: list
 - RT_FEATURES: list
 - UNRESOLVED_RT: list
 - export_text: function
 - hostname_parts: function
 - importance: Series
 - important_features: Series
 - rt: str
 - rt_feature: str
 - rt_features: list
 - rt_targets: list
 - rt_unique: int
 - sorted_values: list
 - target_rt: str
 - unresolved_rt: list
 - url_length_rt: function

===========================================================================
CURRENT EXTRACTOR OUTPUT
===========================================================================

Google: https://www.google.com

Reconstructed RT values:
  SubdomainLevelRT                      : None (type=NoneType)
  UrlLengthRT                           : 1 (type=int)
  AbnormalExtFormActionR                : None (type=NoneType)
  PctExtNullSelfRedirectHyperlinksRT    : None (type=NoneType)

Other relevant URL values:
  NumDots                               : 2
  SubdomainLevel                        : 1
  PathLevel                             : 0
  UrlLength                             : 22
  NumDash                               : 0
  NumDashInHostname                     : 0
  NumNumericChars                       : 0
  HostnameLength                        : 14
  PathLength                            : 0
  DomainInSubdomains                    : 0
  DomainInPaths                         : 0
  RandomString                          : 0
  UrlLengthRT                           : 1

Microsoft: https://www.microsoft.com

Reconstructed RT values:
  SubdomainLevelRT                      : None (type=NoneType)
  UrlLengthRT                           : 1 (type=int)
  AbnormalExtFormActionR                : None (type=NoneType)
  PctExtNullSelfRedirectHyperlinksRT    : None (type=NoneType)

Other relevant URL values:
  NumDots                               : 2
  SubdomainLevel                        : 1
  PathLevel                             : 0
  UrlLength                             : 25
  NumDash                               : 0
  NumDashInHostname                     : 0
  NumNumericChars                       : 0
  HostnameLength                        : 17
  PathLength                            : 0
  DomainInSubdomains                    : 0
  DomainInPaths                         : 0
  RandomString                          : 0
  UrlLengthRT                           : 1

GitHub: https://github.com

Reconstructed RT values:
  SubdomainLevelRT                      : None (type=NoneType)
  UrlLengthRT                           : 1 (type=int)
  AbnormalExtFormActionR                : None (type=NoneType)
  PctExtNullSelfRedirectHyperlinksRT    : None (type=NoneType)

Other relevant URL values:
  NumDots                               : 1
  SubdomainLevel                        : 0
  PathLevel                             : 0
  UrlLength                             : 18
  NumDash                               : 0
  NumDashInHostname                     : 0
  NumNumericChars                       : 0
  HostnameLength                        : 10
  PathLength                            : 0
  DomainInSubdomains                    : 0
  DomainInPaths                         : 0
  RandomString                          : 0
  UrlLengthRT                           : 1

Python: https://www.python.org

Reconstructed RT values:
  SubdomainLevelRT                      : None (type=NoneType)
  UrlLengthRT                           : 1 (type=int)
  AbnormalExtFormActionR                : None (type=NoneType)
  PctExtNullSelfRedirectHyperlinksRT    : None (type=NoneType)

Other relevant URL values:
  NumDots                               : 2
  SubdomainLevel                        : 1
  PathLevel                             : 0
  UrlLength                             : 22
  NumDash                               : 0
  NumDashInHostname                     : 0
  NumNumericChars                       : 0
  HostnameLength                        : 14
  PathLength                            : 0
  DomainInSubdomains                    : 0
  DomainInPaths                         : 0
  RandomString                          : 0
  UrlLengthRT                           : 1

===========================================================================
EXTRACTOR SOURCE INSPECTION
===========================================================================

--- extract_url_features ---
   7:     # -----------------------------
   8:     # Basic URL structure
   9:     # -----------------------------
  10:     host_parts = hostname_parts(hostname)
  11:
  12:     subdomain_level = max(len(host_parts) - 2, 0)
  13:
...
   9:     # -----------------------------
  10:     host_parts = hostname_parts(hostname)
  11:
  12:     subdomain_level = max(len(host_parts) - 2, 0)
  13:
  14:     path_parts = [
  15:         p for p in path.split("/")
...
  11:
  12:     subdomain_level = max(len(host_parts) - 2, 0)
  13:
  14:     path_parts = [
  15:         p for p in path.split("/")
  16:         if p
  17:     ]
...
  84:     # -----------------------------
  85:     domain_in_subdomains = int(
  86:         any(
  87:             brand in host_parts[:-2]
  88:             for brand in BRANDS
  89:         )
  90:     )
...
 147:         "RelativeFormAction": None,
 148:         "ExtFormAction": None,
 149:         "AbnormalFormAction": None,
 150:         "PctNullSelfRedirectHyperlinks": None,
 151:         "FrequentDomainNameMismatch": None,
 152:         "FakeLinkInStatusBar": None,
 153:         "RightClickDisabled": None,
...
 159:     }
 160:
 161:     # --------------------------------------------------------
 162:     # RT features
 163:     # --------------------------------------------------------
 164:     rt_values = {
 165:         "SubdomainLevelRT": None,
...
 161:     # --------------------------------------------------------
 162:     # RT features
 163:     # --------------------------------------------------------
 164:     rt_values = {
 165:         "SubdomainLevelRT": None,
 166:         "UrlLengthRT": url_length_rt(url_length),
 167:         "PctExtResourceUrlsRT": None,
...
 162:     # RT features
 163:     # --------------------------------------------------------
 164:     rt_values = {
 165:         "SubdomainLevelRT": None,
 166:         "UrlLengthRT": url_length_rt(url_length),
 167:         "PctExtResourceUrlsRT": None,
 168:         "AbnormalExtFormActionR": None,
...
 163:     # --------------------------------------------------------
 164:     rt_values = {
 165:         "SubdomainLevelRT": None,
 166:         "UrlLengthRT": url_length_rt(url_length),
 167:         "PctExtResourceUrlsRT": None,
 168:         "AbnormalExtFormActionR": None,
 169:         "ExtMetaScriptLinkRT": None,
...
 164:     rt_values = {
 165:         "SubdomainLevelRT": None,
 166:         "UrlLengthRT": url_length_rt(url_length),
 167:         "PctExtResourceUrlsRT": None,
 168:         "AbnormalExtFormActionR": None,
 169:         "ExtMetaScriptLinkRT": None,
 170:         "PctExtNullSelfRedirectHyperlinksRT": None
...
 165:         "SubdomainLevelRT": None,
 166:         "UrlLengthRT": url_length_rt(url_length),
 167:         "PctExtResourceUrlsRT": None,
 168:         "AbnormalExtFormActionR": None,
 169:         "ExtMetaScriptLinkRT": None,
 170:         "PctExtNullSelfRedirectHyperlinksRT": None
 171:     }
...
 166:         "UrlLengthRT": url_length_rt(url_length),
 167:         "PctExtResourceUrlsRT": None,
 168:         "AbnormalExtFormActionR": None,
 169:         "ExtMetaScriptLinkRT": None,
 170:         "PctExtNullSelfRedirectHyperlinksRT": None
 171:     }
 172:
...
 167:         "PctExtResourceUrlsRT": None,
 168:         "AbnormalExtFormActionR": None,
 169:         "ExtMetaScriptLinkRT": None,
 170:         "PctExtNullSelfRedirectHyperlinksRT": None
 171:     }
 172:
 173:     # --------------------------------------------------------
...
 175:     # --------------------------------------------------------
 176:     features = {
 177:         "NumDots": num_dots,
 178:         "SubdomainLevel": subdomain_level,
 179:         "PathLevel": len(path_parts),
 180:         "UrlLength": url_length,
 181:         "NumDash": num_dash,
...
 176:     features = {
 177:         "NumDots": num_dots,
 178:         "SubdomainLevel": subdomain_level,
 179:         "PathLevel": len(path_parts),
 180:         "UrlLength": url_length,
 181:         "NumDash": num_dash,
 182:         "NumDashInHostname": num_dash_hostname,
...
 202:     }
 203:
 204:     features.update(unavailable_html)
 205:     features.update(rt_values)
 206:
 207:     # --------------------------------------------------------
 208:     # STRICT 47-feature validation
...

--- fetch_html ---

--- extract_html_features ---
  37:         if (
  38:             href == ""
  39:             or href == "#"
  40:             or href.lower().startswith("javascript:void")
  41:             or href.lower().startswith("javascript:;")
  42:         ):
  43:             null_self_redirect_links += 1
...
  38:             href == ""
  39:             or href == "#"
  40:             or href.lower().startswith("javascript:void")
  41:             or href.lower().startswith("javascript:;")
  42:         ):
  43:             null_self_redirect_links += 1
  44:
...
 186:         action = str(action).strip()
 187:
 188:         # Insecure HTTP form
 189:         if action.lower().startswith("http://"):
 190:             insecure_forms += 1
 191:
 192:         # Relative action
...
 217:         if (
 218:             action == ""
 219:             or action.lower() == "about:blank"
 220:             or action.lower().startswith("javascript:")
 221:         ):
 222:             abnormal_form_action += 1
 223:
...
 309:             form.get("action", "")
 310:         ).lower()
 311:
 312:         if action.startswith(
 313:             "mailto:"
 314:         ):
 315:             submit_info_email = 1
...
 374:         "RelativeFormAction": relative_form_action,
 375:         "ExtFormAction": external_form_action,
 376:         "AbnormalFormAction": abnormal_form_action,
 377:         "PctNullSelfRedirectHyperlinks": pct_null_self_redirect,
 378:         "FrequentDomainNameMismatch": frequent_domain_mismatch,
 379:         "FakeLinkInStatusBar": fake_status_bar,
 380:         "RightClickDisabled": right_click_disabled,
...

===========================================================================
STEP 6A DIAGNOSTIC CONCLUSION
===========================================================================
The four reconstructed RT features must be populated by the production extractor before live validation can pass.

No model training.
No XGBoost prediction.
No model modification.
===========================================================================
END STEP 6A
===========================================================================

In [ ]:
# ============================================================
# STEP 6B — CHECK VERIFIED RT MAPPING OBJECTS (CORRECTED)
# ============================================================

print("=" * 75)
print("STEP 6B — CHECK VERIFIED RT MAPPING OBJECTS")
print("=" * 75)

TARGETS = [
    "SubdomainLevelRT",
    "AbnormalExtFormActionR",
    "PctExtNullSelfRedirectHyperlinksRT"
]

# IMPORTANT:
# Take a snapshot so globals() cannot change during iteration.
runtime_objects = list(globals().items())

# ------------------------------------------------------------
# 1. Search runtime for mapping-like objects
# ------------------------------------------------------------

print("\nSearching runtime for existing mapping objects...")

mapping_candidates = []

for name, obj in runtime_objects:

    if isinstance(obj, dict):

        lname = name.lower()

        if (
            "map" in lname
            or "rule" in lname
            or "lookup" in lname
            or "rt" in lname
            or "subdomain" in lname
            or "abnormal" in lname
            or "null" in lname
        ):
            mapping_candidates.append(
                (name, len(obj))
            )

if mapping_candidates:

    for name, size in sorted(mapping_candidates):
        print(
            f" - {name}: dict with {size} entries"
        )

else:
    print(" [NONE FOUND]")

# ------------------------------------------------------------
# 2. Search specifically for target-related objects
# ------------------------------------------------------------

print("\nTarget-specific runtime objects:")

for target in TARGETS:

    target_lower = target.lower()

    matches = [
        name
        for name, obj in runtime_objects
        if target_lower in name.lower()
    ]

    if matches:

        print(f"\n{target}:")

        for name in matches:

            obj = globals()[name]

            print(
                f"  - {name}: "
                f"{type(obj).__name__}"
            )

            if isinstance(obj, dict):

                print(
                    f"      entries = {len(obj)}"
                )

                for i, (k, v) in enumerate(
                    obj.items()
                ):

                    if i >= 3:
                        break

                    print(
                        f"      sample[{i}] "
                        f"key={k!r}, value={v!r}"
                    )

    else:

        print(
            f"\n{target}: [NO DIRECT OBJECT FOUND]"
        )

# ------------------------------------------------------------
# 3. Common mapping variable names
# ------------------------------------------------------------

COMMON_NAMES = [
    "rt_mappings",
    "rt_mapping",
    "rt_lookup",
    "rt_rules",
    "verified_rt_mappings",
    "exact_rt_mappings",
    "subdomain_rt_mapping",
    "abnormal_form_rt_mapping",
    "null_self_redirect_rt_mapping",
    "subdomain_mapping",
    "abnormal_mapping",
    "null_redirect_mapping"
]

print("\nCommon mapping names:")

common_found = False

for name in COMMON_NAMES:

    if name in globals():

        common_found = True

        obj = globals()[name]

        print(
            f" - {name}: "
            f"{type(obj).__name__}"
        )

        if isinstance(obj, dict):
            print(
                f"   entries = {len(obj)}"
            )

if not common_found:
    print(" [NONE FOUND]")

# ------------------------------------------------------------
# 4. Check Step 5O checkpoint
# ------------------------------------------------------------

checkpoint_path = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints/"
    "step_5O_exact_rt_mapping_test.json"
)

print("\nStep 5O checkpoint:")

import os
import json

if os.path.exists(checkpoint_path):

    print("[PASS] Checkpoint exists.")

    with open(checkpoint_path, "r") as f:
        checkpoint = json.load(f)

    print(
        "Top-level keys:"
    )

    for key in checkpoint.keys():
        print(
            f" - {key}"
        )

else:

    print(
        "[ERROR] Step 5O checkpoint not found."
    )

# ------------------------------------------------------------
# 5. Status
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("STEP 6B STATUS")
print("=" * 75)

print("No extractor modified.")
print("No model prediction.")
print("No training performed.")
print("=" * 75)
print("END STEP 6B")
print("=" * 75)

===========================================================================
STEP 6B — CHECK VERIFIED RT MAPPING OBJECTS
===========================================================================

Searching runtime for existing mapping objects...
 - MAPPINGS: dict with 6 entries

Target-specific runtime objects:

SubdomainLevelRT: [NO DIRECT OBJECT FOUND]

AbnormalExtFormActionR: [NO DIRECT OBJECT FOUND]

PctExtNullSelfRedirectHyperlinksRT: [NO DIRECT OBJECT FOUND]

Common mapping names:
 [NONE FOUND]

Step 5O checkpoint:
[PASS] Checkpoint exists.
Top-level keys:
 - stage
 - purpose
 - dataset_rows
 - training_performed
 - retraining_performed
 - prediction_performed
 - model_modified
 - target_used_for_mapping
 - id_used_for_mapping
 - candidate_groups
 - results

===========================================================================
STEP 6B STATUS
===========================================================================
No extractor modified.
No model prediction.
No training performed.
===========================================================================
END STEP 6B
===========================================================================

In [ ]:
# ============================================================
# STEP 6C — INSPECT VERIFIED RT MAPPINGS
# ============================================================

print("=" * 75)
print("STEP 6C — INSPECT VERIFIED RT MAPPINGS")
print("=" * 75)

assert "MAPPINGS" in globals(), \
    "MAPPINGS object not found."

MAPPINGS_OBJ = MAPPINGS

print(
    "\nMAPPINGS type:",
    type(MAPPINGS_OBJ).__name__
)

print(
    "Number of mapping entries:",
    len(MAPPINGS_OBJ)
)

print("\nMapping names:")
for key in MAPPINGS_OBJ.keys():
    print(
        f" - {key}"
    )

# ------------------------------------------------------------
# Inspect each mapping safely
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("MAPPING DETAILS")
print("=" * 75)

for key, mapping in MAPPINGS_OBJ.items():

    print(
        f"\n[{key}]"
    )

    print(
        "Type:",
        type(mapping).__name__
    )

    if isinstance(mapping, dict):

        print(
            "Entries:",
            len(mapping)
        )

        # Show first 5 entries only.
        for i, (k, v) in enumerate(
            mapping.items()
        ):

            if i >= 5:
                break

            print(
                f"  sample[{i}] "
                f"key={k!r} "
                f"-> value={v!r}"
            )

    else:

        print(
            "Representation:",
            repr(mapping)[:500]
        )

# ------------------------------------------------------------
# Identify the six expected RT targets
# ------------------------------------------------------------

EXPECTED_RT = {
    "SubdomainLevelRT",
    "UrlLengthRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
}

print("\n" + "=" * 75)
print("EXPECTED RT MAPPING CHECK")
print("=" * 75)

mapping_keys = set(MAPPINGS_OBJ.keys())

print(
    "Expected RT names:",
    EXPECTED_RT
)

print(
    "MAPPINGS names:",
    mapping_keys
)

print(
    "\nMissing expected mapping names:"
)

missing = EXPECTED_RT - mapping_keys

if missing:

    for item in sorted(missing):
        print(
            f" - {item}"
        )

else:

    print(" NONE")

print(
    "\nUnexpected mapping names:"
)

extra = mapping_keys - EXPECTED_RT

if extra:

    for item in sorted(extra):
        print(
            f" - {item}"
        )

else:

    print(" NONE")

# ------------------------------------------------------------
# Do NOT modify anything
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("STEP 6C STATUS")
print("=" * 75)

print(
    "[PASS] MAPPINGS inspected."
)

print(
    "No extractor modified."
)

print(
    "No model modified."
)

print(
    "No training performed."
)

print(
    "No prediction performed."
)

print("=" * 75)
print("END STEP 6C")
print("=" * 75)

===========================================================================
STEP 6C — INSPECT VERIFIED RT MAPPINGS
===========================================================================

MAPPINGS type: dict
Number of mapping entries: 6

Mapping names:
 - SubdomainLevelRT
 - UrlLengthRT
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

===========================================================================
MAPPING DETAILS
===========================================================================

[SubdomainLevelRT]
Type: str
Representation: 'SubdomainLevel'

[UrlLengthRT]
Type: str
Representation: 'UrlLength'

[PctExtResourceUrlsRT]
Type: str
Representation: 'PctExtResourceUrls'

[AbnormalExtFormActionR]
Type: str
Representation: 'ExtFormAction'

[ExtMetaScriptLinkRT]
Type: str
Representation: 'PctExtResourceUrls'

[PctExtNullSelfRedirectHyperlinksRT]
Type: str
Representation: 'PctExtHyperlinks'

===========================================================================
EXPECTED RT MAPPING CHECK
===========================================================================
Expected RT names: {'PctExtResourceUrlsRT', 'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'ExtMetaScriptLinkRT', 'AbnormalExtFormActionR', 'UrlLengthRT'}
MAPPINGS names: {'ExtMetaScriptLinkRT', 'UrlLengthRT', 'PctExtResourceUrlsRT', 'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'AbnormalExtFormActionR'}

Missing expected mapping names:
 NONE

Unexpected mapping names:
 NONE

===========================================================================
STEP 6C STATUS
===========================================================================
[PASS] MAPPINGS inspected.
No extractor modified.
No model modified.
No training performed.
No prediction performed.
===========================================================================
END STEP 6C
===========================================================================

In [ ]:
# ============================================================
# STEP 6D — BUILD VERIFIED RT LOOKUP ARTIFACT
# ============================================================

print("=" * 75)
print("STEP 6D — BUILD VERIFIED RT LOOKUP ARTIFACT")
print("=" * 75)

import os
import json
import joblib
import pandas as pd
import numpy as np
from collections import defaultdict

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

DATASET_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/"
    "Phishing_Legitimate_full(4).csv"
)

CHECKPOINT_DIR = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints"
)

ARTIFACT_DIR = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data"
)

os.makedirs(CHECKPOINT_DIR, exist_ok=True)
os.makedirs(ARTIFACT_DIR, exist_ok=True)

ARTIFACT_PATH = os.path.join(
    ARTIFACT_DIR,
    "verified_rt_lookup_mappings.pkl"
)

CHECKPOINT_PATH = os.path.join(
    CHECKPOINT_DIR,
    "step_6D_verified_rt_lookup_artifact.json"
)

# ------------------------------------------------------------
# Load dataset
# ------------------------------------------------------------

print("\nLoading frozen dataset...")

df = pd.read_csv("/content/Phishing_Legitimate_full.csv")

print(
    "Dataset shape:",
    df.shape
)

assert df.shape == (10000, 50), (
    f"Unexpected dataset shape: {df.shape}"
)

# ------------------------------------------------------------
# Safety checks
# ------------------------------------------------------------

assert "CLASS_LABEL" in df.columns
assert "id" in df.columns

print(
    "[PASS] CLASS_LABEL present."
)

print(
    "[PASS] id present."
)

# ------------------------------------------------------------
# IMPORTANT:
# CLASS_LABEL and id are NEVER used as mapping keys.
# They are excluded from all lookup construction.
# ------------------------------------------------------------

# ============================================================
# 1. SUBDOMAIN LEVEL RT
# ============================================================

print("\n" + "-" * 75)
print("1. SubdomainLevelRT")
print("-" * 75)

subdomain_candidates = [
    "SubdomainLevel",
    "NumDots",
    "HostnameLength",
    "UrlLength",
    "NumDashInHostname",
    "DomainInSubdomains",
    "DomainInPaths",
    "PathLevel",
    "NumNumericChars"
]

sub_rt = df[
    subdomain_candidates + ["SubdomainLevelRT"]
].copy()

sub_key_cols = subdomain_candidates

sub_groups = (
    sub_rt
    .groupby(sub_key_cols, dropna=False)
    ["SubdomainLevelRT"]
    .agg(
        unique_values=lambda x: sorted(
            set(int(v) for v in x)
        ),
        count="size"
    )
)

sub_conflicts = sub_groups[
    sub_groups["unique_values"].apply(
        lambda x: len(x) > 1
    )
]

print(
    "Unique combinations:",
    len(sub_groups)
)

print(
    "Conflicting combinations:",
    len(sub_conflicts)
)

assert len(sub_conflicts) == 0, (
    "SubdomainLevelRT is not deterministic "
    "for the selected verified feature set."
)

# Build exact lookup
sub_mapping = {}

for row in sub_rt.itertuples(index=False):

    key = tuple(
        getattr(row, col)
        for col in sub_key_cols
    )

    value = int(
        getattr(row, "SubdomainLevelRT")
    )

    sub_mapping[key] = value

print(
    "[PASS] SubdomainLevelRT mapping:",
    len(sub_mapping),
    "entries"
)

# ============================================================
# 2. ABNORMAL EXT FORM ACTION RT
# ============================================================

print("\n" + "-" * 75)
print("2. AbnormalExtFormActionR")
print("-" * 75)

abnormal_candidates = [
    "AbnormalFormAction",
    "ExtFormAction",
    "RelativeFormAction",
    "InsecureForms",
    "PctExtHyperlinks",
    "PctExtResourceUrls",
    "HostnameLength",
    "UrlLength"
]

ab_rt = df[
    abnormal_candidates + ["AbnormalExtFormActionR"]
].copy()

ab_key_cols = abnormal_candidates

ab_groups = (
    ab_rt
    .groupby(ab_key_cols, dropna=False)
    ["AbnormalExtFormActionR"]
    .agg(
        unique_values=lambda x: sorted(
            set(int(v) for v in x)
        ),
        count="size"
    )
)

ab_conflicts = ab_groups[
    ab_groups["unique_values"].apply(
        lambda x: len(x) > 1
    )
]

print(
    "Unique combinations:",
    len(ab_groups)
)

print(
    "Conflicting combinations:",
    len(ab_conflicts)
)

assert len(ab_conflicts) == 0, (
    "AbnormalExtFormActionR is not deterministic "
    "for the selected verified feature set."
)

ab_mapping = {}

for row in ab_rt.itertuples(index=False):

    key = tuple(
        getattr(row, col)
        for col in ab_key_cols
    )

    value = int(
        getattr(row, "AbnormalExtFormActionR")
    )

    ab_mapping[key] = value

print(
    "[PASS] AbnormalExtFormActionR mapping:",
    len(ab_mapping),
    "entries"
)

# ============================================================
# 3. PCT EXT NULL SELF REDIRECT HYPERLINKS RT
# ============================================================

print("\n" + "-" * 75)
print("3. PctExtNullSelfRedirectHyperlinksRT")
print("-" * 75)

null_candidates = [
    "PctExtHyperlinks",
    "PctNullSelfRedirectHyperlinks",
    "FrequentDomainNameMismatch",
    "PctExtResourceUrls",
    "NumDots",
    "HostnameLength",
    "UrlLength"
]

null_rt = df[
    null_candidates
    + ["PctExtNullSelfRedirectHyperlinksRT"]
].copy()

null_key_cols = null_candidates

null_groups = (
    null_rt
    .groupby(null_key_cols, dropna=False)
    ["PctExtNullSelfRedirectHyperlinksRT"]
    .agg(
        unique_values=lambda x: sorted(
            set(int(v) for v in x)
        ),
        count="size"
    )
)

null_conflicts = null_groups[
    null_groups["unique_values"].apply(
        lambda x: len(x) > 1
    )
]

print(
    "Unique combinations:",
    len(null_groups)
)

print(
    "Conflicting combinations:",
    len(null_conflicts)
)

assert len(null_conflicts) == 0, (
    "PctExtNullSelfRedirectHyperlinksRT "
    "is not deterministic for the selected "
    "verified feature set."
)

null_mapping = {}

for row in null_rt.itertuples(index=False):

    key = tuple(
        getattr(row, col)
        for col in null_key_cols
    )

    value = int(
        getattr(
            row,
            "PctExtNullSelfRedirectHyperlinksRT"
        )
    )

    null_mapping[key] = value

print(
    "[PASS] PctExtNullSelfRedirectHyperlinksRT mapping:",
    len(null_mapping),
    "entries"
)

# ============================================================
# 4. VERIFIED URL LENGTH RT
# ============================================================

print("\n" + "-" * 75)
print("4. UrlLengthRT")
print("-" * 75)

url_length_mapping = {
    "rules": [
        {
            "min": 12,
            "max": 53,
            "value": 1
        },
        {
            "min": 54,
            "max": 75,
            "value": 0
        },
        {
            "min": 76,
            "max": 253,
            "value": -1
        }
    ]
}

# Verify the rule against the dataset.
def verified_url_length_rt(value):

    value = int(value)

    if 12 <= value <= 53:
        return 1

    if 54 <= value <= 75:
        return 0

    if 76 <= value <= 253:
        return -1

    return None


url_test = df[
    ["UrlLength", "UrlLengthRT"]
].copy()

url_test["predicted"] = (
    url_test["UrlLength"]
    .apply(verified_url_length_rt)
)

url_matches = (
    url_test["predicted"]
    == url_test["UrlLengthRT"]
)

print(
    "Exact dataset matches:",
    int(url_matches.sum()),
    "/",
    len(url_test)
)

assert url_matches.all(), (
    "Verified UrlLengthRT rule does not "
    "exactly reproduce the dataset."
)

print(
    "[PASS] UrlLengthRT verified at 100%."
)

# ============================================================
# 5. SAVE ARTIFACT
# ============================================================

rt_artifact = {
    "version": "step_6D_v1",

    "source_dataset": (
        "Phishing_Legitimate_full(4).csv"
    ),

    "dataset_rows": int(len(df)),

    "class_label_used": False,

    "id_used": False,

    "mappings": {
        "SubdomainLevelRT": {
            "key_features": sub_key_cols,
            "lookup": sub_mapping
        },

        "UrlLengthRT": {
            "rules": url_length_mapping["rules"]
        },

        "AbnormalExtFormActionR": {
            "key_features": ab_key_cols,
            "lookup": ab_mapping
        },

        "PctExtNullSelfRedirectHyperlinksRT": {
            "key_features": null_key_cols,
            "lookup": null_mapping
        }
    },

    "unresolved_rt": [
        "PctExtResourceUrlsRT",
        "ExtMetaScriptLinkRT"
    ],

    "silent_zero_fallback": False,

    "unknown_mapping_returns": None
}

joblib.dump(
    rt_artifact,
    ARTIFACT_PATH
)

assert os.path.exists(ARTIFACT_PATH)

print("\n" + "=" * 75)
print("ARTIFACT SAVED")
print("=" * 75)

print(
    "Path:",
    ARTIFACT_PATH
)

print(
    "File size:",
    os.path.getsize(ARTIFACT_PATH),
    "bytes"
)

# ============================================================
# 6. RELOAD VERIFICATION
# ============================================================

print("\nReload verification...")

reloaded = joblib.load(
    ARTIFACT_PATH
)

assert (
    reloaded["version"]
    == "step_6D_v1"
)

assert (
    reloaded["class_label_used"]
    is False
)

assert (
    reloaded["id_used"]
    is False
)

assert (
    len(
        reloaded["mappings"]
        ["SubdomainLevelRT"]["lookup"]
    )
    == len(sub_mapping)
)

assert (
    len(
        reloaded["mappings"]
        ["AbnormalExtFormActionR"]["lookup"]
    )
    == len(ab_mapping)
)

assert (
    len(
        reloaded["mappings"]
        ["PctExtNullSelfRedirectHyperlinksRT"]["lookup"]
    )
    == len(null_mapping)
)

print(
    "[PASS] Artifact reload verified."
)

# ============================================================
# 7. CHECKPOINT
# ============================================================

checkpoint = {
    "stage": "Step 6D",
    "purpose": (
        "Build exact verified RT lookup artifact "
        "for reconstructed runtime features."
    ),
    "dataset_rows": int(len(df)),
    "class_label_used": False,
    "id_used": False,
    "training_performed": False,
    "retraining_performed": False,
    "prediction_performed": False,
    "model_modified": False,

    "results": {
        "SubdomainLevelRT": {
            "mapping_entries": len(sub_mapping),
            "conflicting_combinations": len(
                sub_conflicts
            ),
            "verified": True
        },

        "UrlLengthRT": {
            "rule": (
                "12-53 => 1, "
                "54-75 => 0, "
                "76-253 => -1"
            ),
            "dataset_exact_match": True
        },

        "AbnormalExtFormActionR": {
            "mapping_entries": len(ab_mapping),
            "conflicting_combinations": len(
                ab_conflicts
            ),
            "verified": True
        },

        "PctExtNullSelfRedirectHyperlinksRT": {
            "mapping_entries": len(null_mapping),
            "conflicting_combinations": len(
                null_conflicts
            ),
            "verified": True
        },

        "unresolved_rt": [
            "PctExtResourceUrlsRT",
            "ExtMetaScriptLinkRT"
        ],

        "artifact_path": ARTIFACT_PATH
    }
}

with open(
    CHECKPOINT_PATH,
    "w"
) as f:

    json.dump(
        checkpoint,
        f,
        indent=2
    )

print("\n" + "=" * 75)
print("STEP 6D CHECKPOINT SAVED")
print("=" * 75)

print(
    "Checkpoint:",
    CHECKPOINT_PATH
)

print(
    "[PASS] JSON checkpoint verified:",
    os.path.exists(CHECKPOINT_PATH)
)

print("\nNo training performed.")
print("No prediction performed.")
print("No model modified.")

print("=" * 75)
print("END STEP 6D")
print("=" * 75)

===========================================================================
STEP 6D — BUILD VERIFIED RT LOOKUP ARTIFACT
===========================================================================

Loading frozen dataset...
Dataset shape: (10000, 50)
[PASS] CLASS_LABEL present.
[PASS] id present.

---------------------------------------------------------------------------
1. SubdomainLevelRT
---------------------------------------------------------------------------
Unique combinations: 9123
Conflicting combinations: 0
[PASS] SubdomainLevelRT mapping: 9123 entries

---------------------------------------------------------------------------
2. AbnormalExtFormActionR
---------------------------------------------------------------------------
Unique combinations: 8730
Conflicting combinations: 0
[PASS] AbnormalExtFormActionR mapping: 8730 entries

---------------------------------------------------------------------------
3. PctExtNullSelfRedirectHyperlinksRT
---------------------------------------------------------------------------
Unique combinations: 9003
Conflicting combinations: 0
[PASS] PctExtNullSelfRedirectHyperlinksRT mapping: 9003 entries

---------------------------------------------------------------------------
4. UrlLengthRT
---------------------------------------------------------------------------
Exact dataset matches: 10000 / 10000
[PASS] UrlLengthRT verified at 100%.

===========================================================================
ARTIFACT SAVED
===========================================================================
Path: /content/drive/MyDrive/PhishShield_AI/data/verified_rt_lookup_mappings.pkl
File size: 885621 bytes

Reload verification...
[PASS] Artifact reload verified.

===========================================================================
STEP 6D CHECKPOINT SAVED
===========================================================================
Checkpoint: /content/drive/MyDrive/PhishShield_AI/checkpoints/step_6D_verified_rt_lookup_artifact.json
[PASS] JSON checkpoint verified: True

No training performed.
No prediction performed.
No model modified.
===========================================================================
END STEP 6D
===========================================================================

In [ ]:
# ============================================================
# STEP 6E — WIRE VERIFIED RT MAPPINGS INTO URL EXTRACTOR
# ============================================================

print("=" * 75)
print("STEP 6E — WIRE VERIFIED RT MAPPINGS")
print("=" * 75)

import os
import joblib
import numpy as np

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

RT_ARTIFACT_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/"
    "verified_rt_lookup_mappings.pkl"
)

FEATURE_NAMES_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/"
    "feature_names.pkl"
)

assert os.path.exists(RT_ARTIFACT_PATH), (
    "Verified RT artifact not found."
)

assert os.path.exists(FEATURE_NAMES_PATH), (
    "Frozen feature_names.pkl not found."
)

# ------------------------------------------------------------
# Load verified RT artifact
# ------------------------------------------------------------

rt_artifact = joblib.load(
    RT_ARTIFACT_PATH
)

print(
    "\n[PASS] Verified RT artifact loaded."
)

print(
    "Artifact version:",
    rt_artifact["version"]
)

# Safety checks
assert (
    rt_artifact["class_label_used"]
    is False
)

assert (
    rt_artifact["id_used"]
    is False
)

assert (
    rt_artifact["silent_zero_fallback"]
    is False
)

# ------------------------------------------------------------
# Extract verified lookup tables
# ------------------------------------------------------------

SUBDOMAIN_RT_LOOKUP = (
    rt_artifact["mappings"]
    ["SubdomainLevelRT"]["lookup"]
)

ABNORMAL_RT_LOOKUP = (
    rt_artifact["mappings"]
    ["AbnormalExtFormActionR"]["lookup"]
)

NULL_REDIRECT_RT_LOOKUP = (
    rt_artifact["mappings"]
    ["PctExtNullSelfRedirectHyperlinksRT"]["lookup"]
)

URL_LENGTH_RULES = (
    rt_artifact["mappings"]
    ["UrlLengthRT"]["rules"]
)

SUBDOMAIN_RT_KEYS = (
    rt_artifact["mappings"]
    ["SubdomainLevelRT"]["key_features"]
)

ABNORMAL_RT_KEYS = (
    rt_artifact["mappings"]
    ["AbnormalExtFormActionR"]["key_features"]
)

NULL_REDIRECT_RT_KEYS = (
    rt_artifact["mappings"]
    ["PctExtNullSelfRedirectHyperlinksRT"]
    ["key_features"]
)

print(
    "SubdomainLevelRT lookup:",
    len(SUBDOMAIN_RT_LOOKUP)
)

print(
    "AbnormalExtFormActionR lookup:",
    len(ABNORMAL_RT_LOOKUP)
)

print(
    "PctExtNullSelfRedirectHyperlinksRT lookup:",
    len(NULL_REDIRECT_RT_LOOKUP)
)

# ------------------------------------------------------------
# Verified UrlLengthRT function
# ------------------------------------------------------------

def verified_url_length_rt(value):
    """
    Exact UrlLengthRT rule verified against
    all 10,000 dataset rows.
    """

    if value is None:
        return None

    try:
        value = int(value)
    except Exception:
        return None

    for rule in URL_LENGTH_RULES:

        if (
            rule["min"]
            <= value
            <= rule["max"]
        ):
            return int(rule["value"])

    # Explicit unknown outside observed dataset range.
    return None


# ------------------------------------------------------------
# Generic exact lookup helper
# ------------------------------------------------------------

def exact_rt_lookup(
    features,
    key_features,
    lookup
):
    """
    Perform an exact lookup using only the
    verified non-target feature combination.

    If any required feature is unavailable,
    or the combination was not observed in the
    verified dataset, return None.

    NEVER returns an arbitrary fallback value.
    """

    values = []

    for feature_name in key_features:

        if feature_name not in features:
            return None

        value = features[feature_name]

        if value is None:
            return None

        # Convert NumPy scalar values to native
        # Python values for stable dictionary keys.
        if isinstance(
            value,
            np.generic
        ):
            value = value.item()

        values.append(value)

    key = tuple(values)

    return lookup.get(key, None)


# ------------------------------------------------------------
# Save reference to current extractor
# ------------------------------------------------------------

assert "extract_url_features" in globals(), (
    "Existing extract_url_features() not found."
)

_previous_extract_url_features = (
    extract_url_features
)

# ------------------------------------------------------------
# New production wrapper
# ------------------------------------------------------------

def extract_url_features(url):

    """
    Production URL feature extractor.

    Existing URL feature extraction is preserved.

    Verified RT features are populated from the
    exact Step 6D artifact.

    Unresolved RT features remain None.
    """

    # --------------------------------------------------------
    # Run existing production extractor.
    #
    # This preserves all existing URL calculations.
    # --------------------------------------------------------

    result = _previous_extract_url_features(url)

    assert isinstance(result, dict), (
        "URL extractor must return a dictionary."
    )

    assert "features" in result, (
        "URL extractor result must contain 'features'."
    )

    features = dict(
        result["features"]
    )

    # --------------------------------------------------------
    # 1. SubdomainLevelRT
    # --------------------------------------------------------

    features[
        "SubdomainLevelRT"
    ] = exact_rt_lookup(
        features,
        SUBDOMAIN_RT_KEYS,
        SUBDOMAIN_RT_LOOKUP
    )

    # --------------------------------------------------------
    # 2. UrlLengthRT
    # --------------------------------------------------------

    features[
        "UrlLengthRT"
    ] = verified_url_length_rt(
        features.get("UrlLength")
    )

    # --------------------------------------------------------
    # 3. PctExtResourceUrlsRT
    #
    # UNRESOLVED — deliberately None.
    # --------------------------------------------------------

    features[
        "PctExtResourceUrlsRT"
    ] = None

    # --------------------------------------------------------
    # 4. AbnormalExtFormActionR
    #
    # This depends on HTML-derived features.
    # Those features are currently None at the
    # URL-extraction stage, so do NOT attempt lookup here.
    #
    # It will be populated after HTML extraction
    # in the combined production pipeline.
    # --------------------------------------------------------

    features[
        "AbnormalExtFormActionR"
    ] = None

    # --------------------------------------------------------
    # 5. ExtMetaScriptLinkRT
    #
    # UNRESOLVED — deliberately None.
    # --------------------------------------------------------

    features[
        "ExtMetaScriptLinkRT"
    ] = None

    # --------------------------------------------------------
    # 6. PctExtNullSelfRedirectHyperlinksRT
    #
    # Depends on HTML-derived features, therefore
    # populated later during the combined pipeline.
    # --------------------------------------------------------

    features[
        "PctExtNullSelfRedirectHyperlinksRT"
    ] = None

    # --------------------------------------------------------
    # Rebuild result
    # --------------------------------------------------------

    result["features"] = features

    # Recalculate missing/unknown information
    # according to the extractor's existing contract.

    return result


# ------------------------------------------------------------
# Test URL extraction
# ------------------------------------------------------------

TEST_URLS = {
    "Google": "https://www.google.com",
    "Microsoft": "https://www.microsoft.com",
    "GitHub": "https://github.com",
    "Python": "https://www.python.org"
}

print("\n" + "=" * 75)
print("URL EXTRACTOR RT TEST")
print("=" * 75)

for name, url in TEST_URLS.items():

    result = extract_url_features(url)

    features = result["features"]

    print(
        f"\n{name}:"
    )

    print(
        "  SubdomainLevel:",
        features.get(
            "SubdomainLevel"
        )
    )

    print(
        "  UrlLength:",
        features.get(
            "UrlLength"
        )
    )

    print(
        "  SubdomainLevelRT:",
        features.get(
            "SubdomainLevelRT"
        )
    )

    print(
        "  UrlLengthRT:",
        features.get(
            "UrlLengthRT"
        )
    )

    print(
        "  AbnormalExtFormActionR:",
        features.get(
            "AbnormalExtFormActionR"
        )
    )

    print(
        "  PctExtNullSelfRedirectHyperlinksRT:",
        features.get(
            "PctExtNullSelfRedirectHyperlinksRT"
        )
    )

    print(
        "  PctExtResourceUrlsRT:",
        features.get(
            "PctExtResourceUrlsRT"
        )
    )

    print(
        "  ExtMetaScriptLinkRT:",
        features.get(
            "ExtMetaScriptLinkRT"
        )
    )

# ------------------------------------------------------------
# Verify Google specifically
# ------------------------------------------------------------

google = extract_url_features(
    TEST_URLS["Google"]
)["features"]

assert (
    google["SubdomainLevelRT"]
    is not None
), (
    "SubdomainLevelRT was not reconstructed."
)

assert (
    google["UrlLengthRT"]
    is not None
), (
    "UrlLengthRT was not reconstructed."
)

# These remain unresolved at URL-only stage because
# they depend on HTML-derived features.
assert (
    google["AbnormalExtFormActionR"]
    is None
)

assert (
    google["PctExtNullSelfRedirectHyperlinksRT"]
    is None
)

assert (
    google["PctExtResourceUrlsRT"]
    is None
)

assert (
    google["ExtMetaScriptLinkRT"]
    is None
)

print("\n" + "=" * 75)
print("STEP 6E RESULT")
print("=" * 75)

print(
    "[PASS] Verified URL-level RT mappings wired."
)

print(
    "[PASS] SubdomainLevelRT populated "
    "from exact lookup."
)

print(
    "[PASS] UrlLengthRT populated "
    "from verified rule."
)

print(
    "[PASS] Unresolved RT features remain "
    "explicitly unknown."
)

print(
    "[PASS] No silent zero fallback."
)

print(
    "[PASS] No invented RT formula."
)

print(
    "[PASS] No training performed."
)

print(
    "[PASS] No prediction performed."
)

print(
    "[PASS] No model modified."
)

print("=" * 75)
print("END STEP 6E")
print("=" * 75)

===========================================================================
STEP 6E — WIRE VERIFIED RT MAPPINGS
===========================================================================

[PASS] Verified RT artifact loaded.
Artifact version: step_6D_v1
SubdomainLevelRT lookup: 9123
AbnormalExtFormActionR lookup: 8730
PctExtNullSelfRedirectHyperlinksRT lookup: 9003

===========================================================================
URL EXTRACTOR RT TEST
===========================================================================

Google:
  SubdomainLevel: 1
  UrlLength: 22
  SubdomainLevelRT: 1
  UrlLengthRT: 1
  AbnormalExtFormActionR: None
  PctExtNullSelfRedirectHyperlinksRT: None
  PctExtResourceUrlsRT: None
  ExtMetaScriptLinkRT: None

Microsoft:
  SubdomainLevel: 1
  UrlLength: 25
  SubdomainLevelRT: 1
  UrlLengthRT: 1
  AbnormalExtFormActionR: None
  PctExtNullSelfRedirectHyperlinksRT: None
  PctExtResourceUrlsRT: None
  ExtMetaScriptLinkRT: None

GitHub:
  SubdomainLevel: 0
  UrlLength: 18
  SubdomainLevelRT: 1
  UrlLengthRT: 1
  AbnormalExtFormActionR: None
  PctExtNullSelfRedirectHyperlinksRT: None
  PctExtResourceUrlsRT: None
  ExtMetaScriptLinkRT: None

Python:
  SubdomainLevel: 1
  UrlLength: 22
  SubdomainLevelRT: 1
  UrlLengthRT: 1
  AbnormalExtFormActionR: None
  PctExtNullSelfRedirectHyperlinksRT: None
  PctExtResourceUrlsRT: None
  ExtMetaScriptLinkRT: None

===========================================================================
STEP 6E RESULT
===========================================================================
[PASS] Verified URL-level RT mappings wired.
[PASS] SubdomainLevelRT populated from exact lookup.
[PASS] UrlLengthRT populated from verified rule.
[PASS] Unresolved RT features remain explicitly unknown.
[PASS] No silent zero fallback.
[PASS] No invented RT formula.
[PASS] No training performed.
[PASS] No prediction performed.
[PASS] No model modified.
===========================================================================
END STEP 6E
===========================================================================

In [ ]:
# ============================================================
# STEP 6F — COMPLETE LIVE 47-FEATURE PIPELINE
# ============================================================

print("=" * 75)
print("STEP 6F — COMPLETE LIVE 47-FEATURE PIPELINE")
print("=" * 75)

import os
import json
import joblib
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

RT_ARTIFACT_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/"
    "verified_rt_lookup_mappings.pkl"
)

FEATURE_NAMES_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/"
    "feature_names.pkl"
)

CHECKPOINT_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints/"
    "step_6F_complete_live_feature_pipeline.json"
)

assert os.path.exists(RT_ARTIFACT_PATH)
assert os.path.exists(FEATURE_NAMES_PATH)

# ------------------------------------------------------------
# Load frozen feature contract
# ------------------------------------------------------------

feature_names = joblib.load(
    FEATURE_NAMES_PATH
)

feature_names = list(feature_names)

assert len(feature_names) == 47
assert len(set(feature_names)) == 47

print(
    "\n[PASS] Frozen 47-feature contract loaded."
)

# ------------------------------------------------------------
# Load verified RT artifact
# ------------------------------------------------------------

rt_artifact = joblib.load(
    RT_ARTIFACT_PATH
)

assert (
    rt_artifact["class_label_used"]
    is False
)

assert (
    rt_artifact["id_used"]
    is False
)

assert (
    rt_artifact["silent_zero_fallback"]
    is False
)

# Exact verified mappings
ABNORMAL_RT_LOOKUP = (
    rt_artifact["mappings"]
    ["AbnormalExtFormActionR"]["lookup"]
)

ABNORMAL_RT_KEYS = (
    rt_artifact["mappings"]
    ["AbnormalExtFormActionR"]
    ["key_features"]
)

NULL_RT_LOOKUP = (
    rt_artifact["mappings"]
    ["PctExtNullSelfRedirectHyperlinksRT"]
    ["lookup"]
)

NULL_RT_KEYS = (
    rt_artifact["mappings"]
    ["PctExtNullSelfRedirectHyperlinksRT"]
    ["key_features"]
)

print(
    "[PASS] Verified RT lookup artifact loaded."
)

# ------------------------------------------------------------
# Generic exact lookup
# ------------------------------------------------------------

def live_exact_rt_lookup(
    features,
    key_features,
    lookup
):
    """
    Exact lookup against verified dataset-derived
    mappings.

    Returns None when the live combination was not
    present in the verified mapping.

    No fallback.
    No target usage.
    """

    values = []

    for key_feature in key_features:

        if key_feature not in features:
            return None

        value = features[key_feature]

        if value is None:
            return None

        if isinstance(
            value,
            np.generic
        ):
            value = value.item()

        values.append(value)

    return lookup.get(
        tuple(values),
        None
    )


# ------------------------------------------------------------
# Complete live pipeline
# ------------------------------------------------------------

def build_live_feature_vector(url):
    """
    Build the complete live 47-feature dictionary.

    Pipeline:

        URL
          ↓
        URL extraction
          ↓
        HTML fetch
          ↓
        HTML extraction
          ↓
        verified RT reconstruction
          ↓
        exact 47-feature contract
    """

    # --------------------------------------------------------
    # URL features
    # --------------------------------------------------------

    url_result = extract_url_features(url)

    assert isinstance(
        url_result,
        dict
    )

    assert "features" in url_result

    url_features = dict(
        url_result["features"]
    )

    # --------------------------------------------------------
    # Fetch HTML
    # --------------------------------------------------------

    fetched = fetch_html(url)

    assert isinstance(
        fetched,
        tuple
    ), (
        "fetch_html() must return "
        "(final_url, html)"
    )

    assert len(fetched) == 2

    final_url, html = fetched

    assert isinstance(
        final_url,
        str
    )

    assert isinstance(
        html,
        str
    )

    # --------------------------------------------------------
    # HTML feature extraction
    # --------------------------------------------------------

    html_features = extract_html_features(
        html,
        final_url
    )

    assert isinstance(
        html_features,
        dict
    )

    # Exactly 16 HTML features are expected.
    assert len(html_features) == 16, (
        f"Expected 16 HTML features, "
        f"got {len(html_features)}"
    )

    # --------------------------------------------------------
    # Merge URL + HTML
    # --------------------------------------------------------

    combined = dict(
        url_features
    )

    for key, value in html_features.items():

        # HTML owns these features.
        combined[key] = value

    # --------------------------------------------------------
    # Populate reconstructed HTML-dependent RT features
    # --------------------------------------------------------

    combined[
        "AbnormalExtFormActionR"
    ] = live_exact_rt_lookup(
        combined,
        ABNORMAL_RT_KEYS,
        ABNORMAL_RT_LOOKUP
    )

    combined[
        "PctExtNullSelfRedirectHyperlinksRT"
    ] = live_exact_rt_lookup(
        combined,
        NULL_RT_KEYS,
        NULL_RT_LOOKUP
    )

    # --------------------------------------------------------
    # Explicitly unresolved RT features
    # --------------------------------------------------------

    combined[
        "PctExtResourceUrlsRT"
    ] = None

    combined[
        "ExtMetaScriptLinkRT"
    ] = None

    # --------------------------------------------------------
    # Exact feature contract
    # --------------------------------------------------------

    missing = [
        f
        for f in feature_names
        if f not in combined
    ]

    extra = [
        f
        for f in combined
        if f not in feature_names
    ]

    assert len(missing) == 0, (
        f"Missing frozen features: {missing}"
    )

    assert len(extra) == 0, (
        f"Extra features: {extra}"
    )

    # --------------------------------------------------------
    # Ordered feature dictionary
    # --------------------------------------------------------

    ordered = {
        f: combined[f]
        for f in feature_names
    }

    return {
        "url": url,
        "final_url": final_url,
        "features": ordered,
        "html_feature_count": len(
            html_features
        )
    }


# ============================================================
# TEST LIVE SITES
# ============================================================

TEST_URLS = {
    "Google": "https://www.google.com",
    "Microsoft": "https://www.microsoft.com",
    "GitHub": "https://github.com",
    "Python": "https://www.python.org"
}

results = {}

print("\n" + "=" * 75)
print("LIVE SITE TESTS")
print("=" * 75)

for name, url in TEST_URLS.items():

    print("\n" + "-" * 75)
    print(
        f"TESTING: {name}"
    )
    print(
        f"URL: {url}"
    )
    print("-" * 75)

    try:

        result = build_live_feature_vector(
            url
        )

        features = result[
            "features"
        ]

        none_features = [
            f
            for f, v in features.items()
            if v is None
        ]

        nan_features = [
            f
            for f, v in features.items()
            if (
                isinstance(v, float)
                and np.isnan(v)
            )
        ]

        # Expected unknowns ONLY.
        expected_none = {
            "PctExtResourceUrlsRT",
            "ExtMetaScriptLinkRT"
        }

        unexpected_none = (
            set(none_features)
            - expected_none
        )

        # Reconstructed RTs
        reconstructed_rt = {
            "SubdomainLevelRT":
                features[
                    "SubdomainLevelRT"
                ],

            "UrlLengthRT":
                features[
                    "UrlLengthRT"
                ],

            "AbnormalExtFormActionR":
                features[
                    "AbnormalExtFormActionR"
                ],

            "PctExtNullSelfRedirectHyperlinksRT":
                features[
                    "PctExtNullSelfRedirectHyperlinksRT"
                ]
        }

        print(
            "Final URL:",
            result["final_url"]
        )

        print(
            "HTML features:",
            result["html_feature_count"]
        )

        print(
            "Final feature count:",
            len(features)
        )

        print(
            "Missing features:",
            47 - len(features)
        )

        print(
            "None-valued features:",
            len(none_features)
        )

        print(
            "None features:"
        )

        for feature in none_features:
            print(
                " -",
                feature
            )

        print(
            "\nReconstructed RT values:"
        )

        for feature, value in (
            reconstructed_rt.items()
        ):
            print(
                f" - {feature}: {value!r}"
            )

        # ----------------------------------------------------
        # Assertions
        # ----------------------------------------------------

        assert len(features) == 47

        assert not nan_features, (
            f"NaN values found: "
            f"{nan_features}"
        )

        assert not unexpected_none, (
            f"Unexpected None values: "
            f"{sorted(unexpected_none)}"
        )

        for feature in reconstructed_rt:

            assert (
                features[feature]
                is not None
            ), (
                f"Reconstructed RT missing: "
                f"{feature}"
            )

        # The only unknowns must be the two
        # unresolved RT features.
        assert (
            set(none_features)
            == expected_none
        )

        # Verify values are finite / scalar.
        for feature, value in features.items():

            if value is not None:

                if isinstance(
                    value,
                    (float, np.floating)
                ):

                    assert np.isfinite(
                        value
                    ), (
                        f"Non-finite value "
                        f"for {feature}"
                    )

        results[name] = {
            "status": "PASS",
            "final_url": result["final_url"],
            "feature_count": len(features),
            "none_features": none_features,
            "reconstructed_rt": {
                k: int(v)
                for k, v in reconstructed_rt.items()
            }
        }

        print(
            "\n[PASS]",
            name
        )

    except Exception as e:

        results[name] = {
            "status": "FAIL",
            "error": (
                f"{type(e).__name__}: {e}"
            )
        }

        print(
            "\n[FAIL]",
            name,
            ":",
            f"{type(e).__name__}: {e}"
        )


# ============================================================
# OVERALL RESULT
# ============================================================

passed = sum(
    1
    for r in results.values()
    if r["status"] == "PASS"
)

failed = len(results) - passed

print("\n" + "=" * 75)
print("STEP 6F OVERALL RESULT")
print("=" * 75)

print(
    f"Tests passed : {passed}/4"
)

print(
    f"Tests failed : {failed}/4"
)

if failed:

    print("\nFailed sites:")

    for name, result in results.items():

        if result["status"] == "FAIL":

            print(
                f" - {name}: "
                f"{result['error']}"
            )

# ============================================================
# CHECKPOINT
# ============================================================

checkpoint = {
    "stage": "Step 6F",

    "purpose": (
        "Validate complete live 47-feature "
        "URL + HTML + verified RT pipeline."
    ),

    "feature_count": 47,

    "training_performed": False,

    "retraining_performed": False,

    "prediction_performed": False,

    "model_modified": False,

    "silent_zero_fallback": False,

    "invented_rt_formula": False,

    "unresolved_rt": [
        "PctExtResourceUrlsRT",
        "ExtMetaScriptLinkRT"
    ],

    "results": results,

    "artifact_used": RT_ARTIFACT_PATH
}

with open(
    CHECKPOINT_PATH,
    "w"
) as f:

    json.dump(
        checkpoint,
        f,
        indent=2
    )

print("\n" + "=" * 75)
print("STEP 6F CHECKPOINT")
print("=" * 75)

print(
    "Checkpoint:",
    CHECKPOINT_PATH
)

assert os.path.exists(
    CHECKPOINT_PATH
)

# Reload checkpoint
with open(
    CHECKPOINT_PATH,
    "r"
) as f:

    checkpoint_check = json.load(f)

assert (
    checkpoint_check["stage"]
    == "Step 6F"
)

print(
    "[PASS] Checkpoint verified."
)

print(
    "\nNo training performed."
)

print(
    "No prediction performed."
)

print(
    "No model modified."
)

print("=" * 75)
print("END STEP 6F")
print("=" * 75)

===========================================================================
STEP 6F — COMPLETE LIVE 47-FEATURE PIPELINE
===========================================================================

[PASS] Frozen 47-feature contract loaded.
[PASS] Verified RT lookup artifact loaded.

===========================================================================
LIVE SITE TESTS
===========================================================================

---------------------------------------------------------------------------
TESTING: Google
URL: https://www.google.com
---------------------------------------------------------------------------
Final URL: https://www.google.com/
HTML features: 16
Final feature count: 47
Missing features: 0
None-valued features: 4
None features:
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

Reconstructed RT values:
 - SubdomainLevelRT: 1
 - UrlLengthRT: 1
 - AbnormalExtFormActionR: None
 - PctExtNullSelfRedirectHyperlinksRT: None

[FAIL] Google : AssertionError: Unexpected None values: ['AbnormalExtFormActionR', 'PctExtNullSelfRedirectHyperlinksRT']

---------------------------------------------------------------------------
TESTING: Microsoft
URL: https://www.microsoft.com
---------------------------------------------------------------------------
Final URL: https://www.microsoft.com/
HTML features: 16
Final feature count: 47
Missing features: 0
None-valued features: 4
None features:
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

Reconstructed RT values:
 - SubdomainLevelRT: 1
 - UrlLengthRT: 1
 - AbnormalExtFormActionR: None
 - PctExtNullSelfRedirectHyperlinksRT: None

[FAIL] Microsoft : AssertionError: Unexpected None values: ['AbnormalExtFormActionR', 'PctExtNullSelfRedirectHyperlinksRT']

---------------------------------------------------------------------------
TESTING: GitHub
URL: https://github.com
---------------------------------------------------------------------------
Final URL: https://github.com/
HTML features: 16
Final feature count: 47
Missing features: 0
None-valued features: 4
None features:
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

Reconstructed RT values:
 - SubdomainLevelRT: 1
 - UrlLengthRT: 1
 - AbnormalExtFormActionR: None
 - PctExtNullSelfRedirectHyperlinksRT: None

[FAIL] GitHub : AssertionError: Unexpected None values: ['AbnormalExtFormActionR', 'PctExtNullSelfRedirectHyperlinksRT']

---------------------------------------------------------------------------
TESTING: Python
URL: https://www.python.org
---------------------------------------------------------------------------
Final URL: https://www.python.org/
HTML features: 16
Final feature count: 47
Missing features: 0
None-valued features: 4
None features:
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

Reconstructed RT values:
 - SubdomainLevelRT: 1
 - UrlLengthRT: 1
 - AbnormalExtFormActionR: None
 - PctExtNullSelfRedirectHyperlinksRT: None

[FAIL] Python : AssertionError: Unexpected None values: ['AbnormalExtFormActionR', 'PctExtNullSelfRedirectHyperlinksRT']

===========================================================================
STEP 6F OVERALL RESULT
===========================================================================
Tests passed : 0/4
Tests failed : 4/4

Failed sites:
 - Google: AssertionError: Unexpected None values: ['AbnormalExtFormActionR', 'PctExtNullSelfRedirectHyperlinksRT']
 - Microsoft: AssertionError: Unexpected None values: ['AbnormalExtFormActionR', 'PctExtNullSelfRedirectHyperlinksRT']
 - GitHub: AssertionError: Unexpected None values: ['AbnormalExtFormActionR', 'PctExtNullSelfRedirectHyperlinksRT']
 - Python: AssertionError: Unexpected None values: ['AbnormalExtFormActionR', 'PctExtNullSelfRedirectHyperlinksRT']

===========================================================================
STEP 6F CHECKPOINT
===========================================================================
Checkpoint: /content/drive/MyDrive/PhishShield_AI/checkpoints/step_6F_complete_live_feature_pipeline.json
[PASS] Checkpoint verified.

No training performed.
No prediction performed.
No model modified.
===========================================================================
END STEP 6F
===========================================================================

In [ ]:
# ============================================================
# STEP 6G — DIAGNOSE UNSEEN RT LOOKUP COMBINATIONS
# ============================================================

print("=" * 75)
print("STEP 6G — DIAGNOSE UNSEEN RT LOOKUP COMBINATIONS")
print("=" * 75)

import os
import joblib
import numpy as np
import json

RT_ARTIFACT_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/"
    "verified_rt_lookup_mappings.pkl"
)

assert os.path.exists(RT_ARTIFACT_PATH)

rt_artifact = joblib.load(
    RT_ARTIFACT_PATH
)

# ------------------------------------------------------------
# Load mappings
# ------------------------------------------------------------

mappings = rt_artifact["mappings"]

ABNORMAL_INFO = mappings[
    "AbnormalExtFormActionR"
]

NULL_INFO = mappings[
    "PctExtNullSelfRedirectHyperlinksRT"
]

ABNORMAL_LOOKUP = (
    ABNORMAL_INFO["lookup"]
)

ABNORMAL_KEYS = (
    ABNORMAL_INFO["key_features"]
)

NULL_LOOKUP = (
    NULL_INFO["lookup"]
)

NULL_KEYS = (
    NULL_INFO["key_features"]
)

print("\nAbnormalExtFormActionR")
print(
    "Key features:",
    ABNORMAL_KEYS
)
print(
    "Lookup entries:",
    len(ABNORMAL_LOOKUP)
)

print("\nPctExtNullSelfRedirectHyperlinksRT")
print(
    "Key features:",
    NULL_KEYS
)
print(
    "Lookup entries:",
    len(NULL_LOOKUP)
)

# ------------------------------------------------------------
# Helper
# ------------------------------------------------------------

def make_key(features, key_features):
    values = []

    for feature in key_features:

        value = features.get(feature)

        if isinstance(
            value,
            np.generic
        ):
            value = value.item()

        values.append(value)

    return tuple(values)


def inspect_lookup(
    name,
    features,
    key_features,
    lookup
):

    key = make_key(
        features,
        key_features
    )

    print("\n" + "-" * 75)
    print(name)
    print("-" * 75)

    print("\nLive key values:")

    for feature, value in zip(
        key_features,
        key
    ):
        print(
            f"  {feature}: "
            f"{value!r} "
            f"({type(value).__name__})"
        )

    print("\nGenerated lookup key:")
    print(key)

    print(
        "\nExact key exists:",
        key in lookup
    )

    if key in lookup:

        print(
            "Stored RT value:",
            lookup[key]
        )

    else:

        print(
            "RESULT: LIVE COMBINATION "
            "WAS NOT FOUND IN VERIFIED DATASET."
        )

    return key


# ============================================================
# Test all four live sites
# ============================================================

TEST_URLS = {
    "Google": "https://www.google.com",
    "Microsoft": "https://www.microsoft.com",
    "GitHub": "https://github.com",
    "Python": "https://www.python.org"
}

diagnostic_results = {}

for name, url in TEST_URLS.items():

    print("\n" + "=" * 75)
    print("SITE:", name)
    print("URL :", url)
    print("=" * 75)

    # URL extraction
    url_result = extract_url_features(url)

    url_features = dict(
        url_result["features"]
    )

    # HTML extraction
    final_url, html = fetch_html(url)

    html_features = extract_html_features(
        html,
        final_url
    )

    # Combine
    combined = dict(
        url_features
    )

    combined.update(
        html_features
    )

    # Keep unresolved RTs explicitly unknown
    combined[
        "PctExtResourceUrlsRT"
    ] = None

    combined[
        "ExtMetaScriptLinkRT"
    ] = None

    # Diagnose
    abnormal_key = inspect_lookup(
        "AbnormalExtFormActionR",
        combined,
        ABNORMAL_KEYS,
        ABNORMAL_LOOKUP
    )

    null_key = inspect_lookup(
        "PctExtNullSelfRedirectHyperlinksRT",
        combined,
        NULL_KEYS,
        NULL_LOOKUP
    )

    diagnostic_results[name] = {
        "abnormal_key_exists":
            abnormal_key in ABNORMAL_LOOKUP,

        "null_redirect_key_exists":
            null_key in NULL_LOOKUP,

        "abnormal_key":
            [
                x.item()
                if isinstance(x, np.generic)
                else x
                for x in abnormal_key
            ],

        "null_redirect_key":
            [
                x.item()
                if isinstance(x, np.generic)
                else x
                for x in null_key
            ]
    }


# ============================================================
# Compare live key uniqueness
# ============================================================

print("\n" + "=" * 75)
print("LIVE LOOKUP COVERAGE SUMMARY")
print("=" * 75)

abnormal_hits = sum(
    1
    for result in diagnostic_results.values()
    if result["abnormal_key_exists"]
)

null_hits = sum(
    1
    for result in diagnostic_results.values()
    if result["null_redirect_key_exists"]
)

print(
    "\nAbnormalExtFormActionR:"
)

print(
    f"  Exact lookup hits: "
    f"{abnormal_hits}/4"
)

print(
    f"  Unseen combinations: "
    f"{4 - abnormal_hits}/4"
)

print(
    "\nPctExtNullSelfRedirectHyperlinksRT:"
)

print(
    f"  Exact lookup hits: "
    f"{null_hits}/4"
)

print(
    f"  Unseen combinations: "
    f"{4 - null_hits}/4"
)

# ============================================================
# IMPORTANT SAFETY CHECK
# ============================================================

print("\n" + "=" * 75)
print("SAFETY CHECK")
print("=" * 75)

print(
    "[PASS] No CLASS_LABEL used."
)

print(
    "[PASS] No ID used."
)

print(
    "[PASS] No nearest-neighbor approximation used."
)

print(
    "[PASS] No threshold invented."
)

print(
    "[PASS] No RT value guessed."
)

print(
    "[PASS] No model loaded."
)

print(
    "[PASS] No prediction performed."
)

print(
    "[PASS] No training performed."
)

# ------------------------------------------------------------
# Checkpoint
# ------------------------------------------------------------

CHECKPOINT_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints/"
    "step_6G_rt_lookup_coverage_diagnostic.json"
)

checkpoint = {
    "stage": "Step 6G",

    "purpose": (
        "Diagnose exact lookup coverage for "
        "HTML-dependent reconstructed RT features."
    ),

    "training_performed": False,

    "retraining_performed": False,

    "prediction_performed": False,

    "model_modified": False,

    "nearest_neighbor_used": False,

    "invented_formula": False,

    "results": diagnostic_results
}

with open(
    CHECKPOINT_PATH,
    "w"
) as f:

    json.dump(
        checkpoint,
        f,
        indent=2
    )

print(
    "\n[PASS] Checkpoint saved:"
)

print(
    CHECKPOINT_PATH
)

print("=" * 75)
print("END STEP 6G")
print("=" * 75)

===========================================================================
STEP 6G — DIAGNOSE UNSEEN RT LOOKUP COMBINATIONS
===========================================================================

AbnormalExtFormActionR
Key features: ['AbnormalFormAction', 'ExtFormAction', 'RelativeFormAction', 'InsecureForms', 'PctExtHyperlinks', 'PctExtResourceUrls', 'HostnameLength', 'UrlLength']
Lookup entries: 8730

PctExtNullSelfRedirectHyperlinksRT
Key features: ['PctExtHyperlinks', 'PctNullSelfRedirectHyperlinks', 'FrequentDomainNameMismatch', 'PctExtResourceUrls', 'NumDots', 'HostnameLength', 'UrlLength']
Lookup entries: 9003

===========================================================================
SITE: Google
URL : https://www.google.com
===========================================================================

---------------------------------------------------------------------------
AbnormalExtFormActionR
---------------------------------------------------------------------------

Live key values:
  AbnormalFormAction: 0 (int)
  ExtFormAction: 0 (int)
  RelativeFormAction: 1 (int)
  InsecureForms: 0 (int)
  PctExtHyperlinks: 0.1111111111111111 (float)
  PctExtResourceUrls: 0.6 (float)
  HostnameLength: 14 (int)
  UrlLength: 22 (int)

Generated lookup key:
(0, 0, 1, 0, 0.1111111111111111, 0.6, 14, 22)

Exact key exists: False
RESULT: LIVE COMBINATION WAS NOT FOUND IN VERIFIED DATASET.

---------------------------------------------------------------------------
PctExtNullSelfRedirectHyperlinksRT
---------------------------------------------------------------------------

Live key values:
  PctExtHyperlinks: 0.1111111111111111 (float)
  PctNullSelfRedirectHyperlinks: 0.0 (float)
  FrequentDomainNameMismatch: 0 (int)
  PctExtResourceUrls: 0.6 (float)
  NumDots: 2 (int)
  HostnameLength: 14 (int)
  UrlLength: 22 (int)

Generated lookup key:
(0.1111111111111111, 0.0, 0, 0.6, 2, 14, 22)

Exact key exists: False
RESULT: LIVE COMBINATION WAS NOT FOUND IN VERIFIED DATASET.

===========================================================================
SITE: Microsoft
URL : https://www.microsoft.com
===========================================================================

---------------------------------------------------------------------------
AbnormalExtFormActionR
---------------------------------------------------------------------------

Live key values:
  AbnormalFormAction: 0 (int)
  ExtFormAction: 0 (int)
  RelativeFormAction: 0 (int)
  InsecureForms: 0 (int)
  PctExtHyperlinks: 0.07079646017699115 (float)
  PctExtResourceUrls: 0.6666666666666666 (float)
  HostnameLength: 17 (int)
  UrlLength: 25 (int)

Generated lookup key:
(0, 0, 0, 0, 0.07079646017699115, 0.6666666666666666, 17, 25)

Exact key exists: False
RESULT: LIVE COMBINATION WAS NOT FOUND IN VERIFIED DATASET.

---------------------------------------------------------------------------
PctExtNullSelfRedirectHyperlinksRT
---------------------------------------------------------------------------

Live key values:
  PctExtHyperlinks: 0.07079646017699115 (float)
  PctNullSelfRedirectHyperlinks: 0.017699115044247787 (float)
  FrequentDomainNameMismatch: 0 (int)
  PctExtResourceUrls: 0.6666666666666666 (float)
  NumDots: 2 (int)
  HostnameLength: 17 (int)
  UrlLength: 25 (int)

Generated lookup key:
(0.07079646017699115, 0.017699115044247787, 0, 0.6666666666666666, 2, 17, 25)

Exact key exists: False
RESULT: LIVE COMBINATION WAS NOT FOUND IN VERIFIED DATASET.

===========================================================================
SITE: GitHub
URL : https://github.com
===========================================================================

---------------------------------------------------------------------------
AbnormalExtFormActionR
---------------------------------------------------------------------------

Live key values:
  AbnormalFormAction: 0 (int)
  ExtFormAction: 0 (int)
  RelativeFormAction: 2 (int)
  InsecureForms: 0 (int)
  PctExtHyperlinks: 0.09929078014184398 (float)
  PctExtResourceUrls: 0.9225806451612903 (float)
  HostnameLength: 10 (int)
  UrlLength: 18 (int)

Generated lookup key:
(0, 0, 2, 0, 0.09929078014184398, 0.9225806451612903, 10, 18)

Exact key exists: False
RESULT: LIVE COMBINATION WAS NOT FOUND IN VERIFIED DATASET.

---------------------------------------------------------------------------
PctExtNullSelfRedirectHyperlinksRT
---------------------------------------------------------------------------

Live key values:
  PctExtHyperlinks: 0.09929078014184398 (float)
  PctNullSelfRedirectHyperlinks: 0.02127659574468085 (float)
  FrequentDomainNameMismatch: 0 (int)
  PctExtResourceUrls: 0.9225806451612903 (float)
  NumDots: 1 (int)
  HostnameLength: 10 (int)
  UrlLength: 18 (int)

Generated lookup key:
(0.09929078014184398, 0.02127659574468085, 0, 0.9225806451612903, 1, 10, 18)

Exact key exists: False
RESULT: LIVE COMBINATION WAS NOT FOUND IN VERIFIED DATASET.

===========================================================================
SITE: Python
URL : https://www.python.org
===========================================================================

---------------------------------------------------------------------------
AbnormalExtFormActionR
---------------------------------------------------------------------------

Live key values:
  AbnormalFormAction: 0 (int)
  ExtFormAction: 0 (int)
  RelativeFormAction: 1 (int)
  InsecureForms: 0 (int)
  PctExtHyperlinks: 0.22325581395348837 (float)
  PctExtResourceUrls: 0.25925925925925924 (float)
  HostnameLength: 14 (int)
  UrlLength: 22 (int)

Generated lookup key:
(0, 0, 1, 0, 0.22325581395348837, 0.25925925925925924, 14, 22)

Exact key exists: False
RESULT: LIVE COMBINATION WAS NOT FOUND IN VERIFIED DATASET.

---------------------------------------------------------------------------
PctExtNullSelfRedirectHyperlinksRT
---------------------------------------------------------------------------

Live key values:
  PctExtHyperlinks: 0.22325581395348837 (float)
  PctNullSelfRedirectHyperlinks: 0.023255813953488372 (float)
  FrequentDomainNameMismatch: 0 (int)
  PctExtResourceUrls: 0.25925925925925924 (float)
  NumDots: 2 (int)
  HostnameLength: 14 (int)
  UrlLength: 22 (int)

Generated lookup key:
(0.22325581395348837, 0.023255813953488372, 0, 0.25925925925925924, 2, 14, 22)

Exact key exists: False
RESULT: LIVE COMBINATION WAS NOT FOUND IN VERIFIED DATASET.

===========================================================================
LIVE LOOKUP COVERAGE SUMMARY
===========================================================================

AbnormalExtFormActionR:
  Exact lookup hits: 0/4
  Unseen combinations: 4/4

PctExtNullSelfRedirectHyperlinksRT:
  Exact lookup hits: 0/4
  Unseen combinations: 4/4

===========================================================================
SAFETY CHECK
===========================================================================
[PASS] No CLASS_LABEL used.
[PASS] No ID used.
[PASS] No nearest-neighbor approximation used.
[PASS] No threshold invented.
[PASS] No RT value guessed.
[PASS] No model loaded.
[PASS] No prediction performed.
[PASS] No training performed.

[PASS] Checkpoint saved:
/content/drive/MyDrive/PhishShield_AI/checkpoints/step_6G_rt_lookup_coverage_diagnostic.json
===========================================================================
END STEP 6G
===========================================================================

In [ ]:
# ============================================================
# STEP 7A — FROZEN XGBOOST MISSING-RT BEHAVIOR TEST
# ============================================================

print("=" * 75)
print("STEP 7A — FROZEN XGBOOST MISSING-RT BEHAVIOR TEST")
print("=" * 75)

import os
import json
import joblib
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

MODEL_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/models/xgboost.pkl"
)

FEATURE_NAMES_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/feature_names.pkl"
)

X_TEST_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/X_test.pkl"
)

Y_TEST_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/y_test.pkl"
)

CHECKPOINT_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints/"
    "step_7A_xgboost_missing_rt_test.json"
)

# ------------------------------------------------------------
# Verify files
# ------------------------------------------------------------

for path in [
    MODEL_PATH,
    FEATURE_NAMES_PATH,
    X_TEST_PATH,
    Y_TEST_PATH
]:
    assert os.path.exists(path), (
        f"Required file not found: {path}"
    )

# ------------------------------------------------------------
# Load frozen model and test data
# ------------------------------------------------------------

model = joblib.load(
    MODEL_PATH
)

feature_names = joblib.load(
    FEATURE_NAMES_PATH
)

feature_names = list(
    feature_names
)

X_test = joblib.load(
    X_TEST_PATH
)

y_test = joblib.load(
    Y_TEST_PATH
)

# Normalize X_test to DataFrame
if not isinstance(
    X_test,
    pd.DataFrame
):
    X_test = pd.DataFrame(
        X_test,
        columns=feature_names
    )

# Normalize y_test
if isinstance(
    y_test,
    pd.DataFrame
):
    y_test = y_test.iloc[:, 0]

if isinstance(
    y_test,
    np.ndarray
):
    y_test = pd.Series(
        y_test
    )

# ------------------------------------------------------------
# Contract checks
# ------------------------------------------------------------

assert len(feature_names) == 47

assert list(
    X_test.columns
) == feature_names

assert model.n_features_in_ == 47

print(
    "\n[PASS] Frozen XGBoost loaded."
)

print(
    "Model type:",
    type(model).__name__
)

print(
    "Test shape:",
    X_test.shape
)

print(
    "Feature count:",
    len(feature_names)
)

# ------------------------------------------------------------
# RT features
# ------------------------------------------------------------

RT_FEATURES = [
    "SubdomainLevelRT",
    "UrlLengthRT",
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

UNRESOLVED_RT = [
    "PctExtResourceUrlsRT",
    "ExtMetaScriptLinkRT"
]

LIVE_UNAVAILABLE_RT = [
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

for feature in RT_FEATURES:

    assert feature in feature_names

# ------------------------------------------------------------
# Baseline prediction
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("BASELINE — ALL DATASET RT VALUES PRESENT")
print("=" * 75)

X_baseline = X_test[
    feature_names
].copy()

baseline_probability = model.predict_proba(
    X_baseline
)[:, 1]

baseline_prediction = (
    baseline_probability >= 0.5
).astype(int)

baseline_accuracy = (
    baseline_prediction
    == y_test.to_numpy()
).mean()

print(
    "Baseline accuracy:",
    f"{baseline_accuracy:.6f}"
)

print(
    "Baseline probability range:",
    f"{baseline_probability.min():.6f}",
    "to",
    f"{baseline_probability.max():.6f}"
)

# ------------------------------------------------------------
# Missing RT experiment
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("MISSING RT EXPERIMENT")
print("=" * 75)

X_missing = X_test[
    feature_names
].copy()

for feature in LIVE_UNAVAILABLE_RT:

    X_missing[
        feature
    ] = np.nan

print(
    "\nRT features replaced with NaN:"
)

for feature in LIVE_UNAVAILABLE_RT:

    print(
        " -",
        feature
    )

# ------------------------------------------------------------
# Verify NaN injection
# ------------------------------------------------------------

nan_counts = {
    feature: int(
        X_missing[feature]
        .isna()
        .sum()
    )
    for feature in LIVE_UNAVAILABLE_RT
}

print(
    "\nNaN counts:"
)

for feature, count in nan_counts.items():

    print(
        f" - {feature}: {count}"
    )

# ------------------------------------------------------------
# Attempt prediction
# ------------------------------------------------------------

missing_prediction_success = False
missing_prediction_error = None

try:

    missing_probability = (
        model.predict_proba(
            X_missing
        )[:, 1]
    )

    missing_prediction = (
        missing_probability >= 0.5
    ).astype(int)

    missing_prediction_success = True

    print(
        "\n[PASS] Frozen XGBoost accepted NaN values."
    )

except Exception as e:

    missing_prediction_success = False

    missing_prediction_error = (
        f"{type(e).__name__}: {e}"
    )

    print(
        "\n[FAIL] Frozen XGBoost rejected NaN values."
    )

    print(
        "Error:",
        missing_prediction_error
    )

# ------------------------------------------------------------
# If accepted, analyze prediction sensitivity
# ------------------------------------------------------------

results = {
    "model_loaded": True,
    "prediction_with_nan_success":
        missing_prediction_success,
    "baseline_accuracy":
        float(baseline_accuracy),
    "nan_counts":
        nan_counts
}

if missing_prediction_success:

    # Probability changes
    probability_delta = (
        np.abs(
            missing_probability
            - baseline_probability
        )
    )

    prediction_changes = (
        missing_prediction
        != baseline_prediction
    )

    changed_count = int(
        prediction_changes.sum()
    )

    total_count = len(
        baseline_prediction
    )

    changed_percentage = (
        changed_count
        / total_count
        * 100
    )

    missing_accuracy = (
        missing_prediction
        == y_test.to_numpy()
    ).mean()

    print(
        "\n" + "=" * 75
    )

    print(
        "MISSING-RT PREDICTION RESULTS"
    )

    print(
        "=" * 75
    )

    print(
        "Missing-RT accuracy:",
        f"{missing_accuracy:.6f}"
    )

    print(
        "Prediction changes:",
        f"{changed_count}/{total_count}"
    )

    print(
        "Prediction change rate:",
        f"{changed_percentage:.4f}%"
    )

    print(
        "Mean probability delta:",
        f"{probability_delta.mean():.6f}"
    )

    print(
        "Median probability delta:",
        f"{np.median(probability_delta):.6f}"
    )

    print(
        "Maximum probability delta:",
        f"{probability_delta.max():.6f}"
    )

    # --------------------------------------------------------
    # Prediction changes by direction
    # --------------------------------------------------------

    baseline_to_missing = {}

    for old_class in [0, 1]:

        for new_class in [0, 1]:

            count = int(
                (
                    (baseline_prediction == old_class)
                    &
                    (missing_prediction == new_class)
                ).sum()
            )

            baseline_to_missing[
                f"{old_class}_to_{new_class}"
            ] = count

    print(
        "\nPrediction transition:"
    )

    for transition, count in (
        baseline_to_missing.items()
    ):

        print(
            f" - {transition}: {count}"
        )

    results.update({
        "missing_accuracy":
            float(missing_accuracy),

        "prediction_changes":
            changed_count,

        "prediction_change_rate_percent":
            float(changed_percentage),

        "mean_probability_delta":
            float(probability_delta.mean()),

        "median_probability_delta":
            float(np.median(probability_delta)),

        "max_probability_delta":
            float(probability_delta.max()),

        "prediction_transition":
            baseline_to_missing
    })

# ------------------------------------------------------------
# Safety checks
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("SAFETY CHECK")
print("=" * 75)

print(
    "[PASS] Model loaded from frozen checkpoint."
)

print(
    "[PASS] No model.fit() called."
)

print(
    "[PASS] No retraining performed."
)

print(
    "[PASS] No model parameters changed."
)

print(
    "[PASS] No RT values guessed."
)

print(
    "[PASS] No zero fallback used."
)

print(
    "[PASS] NaN used only as explicit missing value."
)

# ------------------------------------------------------------
# Checkpoint
# ------------------------------------------------------------

checkpoint = {
    "stage": "Step 7A",

    "purpose": (
        "Test whether the frozen XGBoost model "
        "accepts explicit NaN values for live-unavailable "
        "RT features."
    ),

    "model_path": MODEL_PATH,

    "feature_count": 47,

    "rt_features": RT_FEATURES,

    "live_unavailable_rt": LIVE_UNAVAILABLE_RT,

    "training_performed": False,

    "retraining_performed": False,

    "model_modified": False,

    "target_used_for_feature_generation": False,

    "nan_used_as_fallback_value": False,

    "results": results
}

with open(
    CHECKPOINT_PATH,
    "w"
) as f:

    json.dump(
        checkpoint,
        f,
        indent=2
    )

assert os.path.exists(
    CHECKPOINT_PATH
)

# Verify checkpoint
with open(
    CHECKPOINT_PATH,
    "r"
) as f:

    checkpoint_check = json.load(f)

assert (
    checkpoint_check["stage"]
    == "Step 7A"
)

print(
    "\n[PASS] Checkpoint saved and verified:"
)

print(
    CHECKPOINT_PATH
)

print("=" * 75)
print("END STEP 7A")
print("=" * 75)

===========================================================================
STEP 7A — FROZEN XGBOOST MISSING-RT BEHAVIOR TEST
===========================================================================

[PASS] Frozen XGBoost loaded.
Model type: XGBClassifier
Test shape: (1500, 47)
Feature count: 47

===========================================================================
BASELINE — ALL DATASET RT VALUES PRESENT
===========================================================================
Baseline accuracy: 0.988000
Baseline probability range: 0.000012 to 0.999964

===========================================================================
MISSING RT EXPERIMENT
===========================================================================

RT features replaced with NaN:
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

NaN counts:
 - PctExtResourceUrlsRT: 1500
 - AbnormalExtFormActionR: 1500
 - ExtMetaScriptLinkRT: 1500
 - PctExtNullSelfRedirectHyperlinksRT: 1500

[PASS] Frozen XGBoost accepted NaN values.

===========================================================================
MISSING-RT PREDICTION RESULTS
===========================================================================
Missing-RT accuracy: 0.979333
Prediction changes: 19/1500
Prediction change rate: 1.2667%
Mean probability delta: 0.017975
Median probability delta: 0.000210
Maximum probability delta: 0.855588

Prediction transition:
 - 0_to_0: 751
 - 0_to_1: 1
 - 1_to_0: 18
 - 1_to_1: 730

===========================================================================
SAFETY CHECK
===========================================================================
[PASS] Model loaded from frozen checkpoint.
[PASS] No model.fit() called.
[PASS] No retraining performed.
[PASS] No model parameters changed.
[PASS] No RT values guessed.
[PASS] No zero fallback used.
[PASS] NaN used only as explicit missing value.

[PASS] Checkpoint saved and verified:
/content/drive/MyDrive/PhishShield_AI/checkpoints/step_7A_xgboost_missing_rt_test.json
===========================================================================
END STEP 7A
===========================================================================

In [ ]:
# ============================================================
# STEP 7B — INDIVIDUAL RT MISSING-VALUE ABLATION
# ============================================================

print("=" * 75)
print("STEP 7B — INDIVIDUAL RT MISSING-VALUE ABLATION")
print("=" * 75)

import os
import json
import joblib
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

MODEL_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/models/xgboost.pkl"
)

FEATURE_NAMES_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/feature_names.pkl"
)

X_TEST_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/X_test.pkl"
)

Y_TEST_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/y_test.pkl"
)

CHECKPOINT_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints/"
    "step_7B_rt_ablation_analysis.json"
)

# ------------------------------------------------------------
# Load frozen artifacts
# ------------------------------------------------------------

model = joblib.load(
    MODEL_PATH
)

feature_names = list(
    joblib.load(
        FEATURE_NAMES_PATH
    )
)

X_test = joblib.load(
    X_TEST_PATH
)

y_test = joblib.load(
    Y_TEST_PATH
)

if not isinstance(
    X_test,
    pd.DataFrame
):
    X_test = pd.DataFrame(
        X_test,
        columns=feature_names
    )

if isinstance(
    y_test,
    pd.DataFrame
):
    y_test = y_test.iloc[:, 0]

if isinstance(
    y_test,
    np.ndarray
):
    y_test = pd.Series(
        y_test
    )

# ------------------------------------------------------------
# Contract checks
# ------------------------------------------------------------

assert len(feature_names) == 47
assert list(X_test.columns) == feature_names
assert model.n_features_in_ == 47

# ------------------------------------------------------------
# RT features
# ------------------------------------------------------------

UNAVAILABLE_RT = [
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

for feature in UNAVAILABLE_RT:
    assert feature in feature_names

# ------------------------------------------------------------
# Metric helper
# ------------------------------------------------------------

def calculate_metrics(
    y_true,
    predictions,
    probabilities
):

    y_true = np.asarray(
        y_true
    )

    predictions = np.asarray(
        predictions
    )

    tp = int(
        (
            (predictions == 1)
            &
            (y_true == 1)
        ).sum()
    )

    tn = int(
        (
            (predictions == 0)
            &
            (y_true == 0)
        ).sum()
    )

    fp = int(
        (
            (predictions == 1)
            &
            (y_true == 0)
        ).sum()
    )

    fn = int(
        (
            (predictions == 0)
            &
            (y_true == 1)
        ).sum()
    )

    accuracy = (
        (predictions == y_true)
        .mean()
    )

    precision = (
        tp / (tp + fp)
        if (tp + fp) > 0
        else 0.0
    )

    recall = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0.0
    )

    f1 = (
        2 * precision * recall
        / (precision + recall)
        if (precision + recall) > 0
        else 0.0
    )

    return {
        "accuracy": float(
            accuracy
        ),
        "precision": float(
            precision
        ),
        "recall": float(
            recall
        ),
        "f1": float(
            f1
        ),
        "tp": tp,
        "tn": tn,
        "fp": fp,
        "fn": fn
    }


# ============================================================
# BASELINE
# ============================================================

print("\n" + "=" * 75)
print("BASELINE")
print("=" * 75)

X_baseline = X_test[
    feature_names
].copy()

baseline_probability = (
    model.predict_proba(
        X_baseline
    )[:, 1]
)

baseline_prediction = (
    baseline_probability >= 0.5
).astype(int)

baseline_metrics = calculate_metrics(
    y_test,
    baseline_prediction,
    baseline_probability
)

print(
    "Accuracy :",
    f"{baseline_metrics['accuracy']:.6f}"
)

print(
    "Precision:",
    f"{baseline_metrics['precision']:.6f}"
)

print(
    "Recall   :",
    f"{baseline_metrics['recall']:.6f}"
)

print(
    "F1       :",
    f"{baseline_metrics['f1']:.6f}"
)

# ============================================================
# INDIVIDUAL ABLATION
# ============================================================

print("\n" + "=" * 75)
print("INDIVIDUAL RT ABLATION")
print("=" * 75)

individual_results = {}

for feature in UNAVAILABLE_RT:

    X_variant = X_baseline.copy()

    X_variant[
        feature
    ] = np.nan

    probability = (
        model.predict_proba(
            X_variant
        )[:, 1]
    )

    prediction = (
        probability >= 0.5
    ).astype(int)

    metrics = calculate_metrics(
        y_test,
        prediction,
        probability
    )

    changed = (
        prediction
        != baseline_prediction
    )

    probability_delta = np.abs(
        probability
        - baseline_probability
    )

    changed_count = int(
        changed.sum()
    )

    result = {
        **metrics,

        "prediction_changes":
            changed_count,

        "prediction_change_rate_percent":
            float(
                changed_count
                / len(prediction)
                * 100
            ),

        "mean_probability_delta":
            float(
                probability_delta.mean()
            ),

        "median_probability_delta":
            float(
                np.median(
                    probability_delta
                )
            ),

        "max_probability_delta":
            float(
                probability_delta.max()
            )
    }

    individual_results[
        feature
    ] = result

    print(
        f"\n{feature}"
    )

    print(
        "  Accuracy:",
        f"{result['accuracy']:.6f}"
    )

    print(
        "  Precision:",
        f"{result['precision']:.6f}"
    )

    print(
        "  Recall:",
        f"{result['recall']:.6f}"
    )

    print(
        "  F1:",
        f"{result['f1']:.6f}"
    )

    print(
        "  Prediction changes:",
        f"{changed_count}/"
        f"{len(prediction)}"
    )

    print(
        "  Change rate:",
        f"{result['prediction_change_rate_percent']:.4f}%"
    )

    print(
        "  Mean probability delta:",
        f"{result['mean_probability_delta']:.6f}"
    )

    print(
        "  Max probability delta:",
        f"{result['max_probability_delta']:.6f}"
    )

# ============================================================
# PAIRWISE ABLATION
# ============================================================

print("\n" + "=" * 75)
print("PAIRWISE RT ABLATION")
print("=" * 75)

pairs = [
    [
        "PctExtResourceUrlsRT",
        "AbnormalExtFormActionR"
    ],

    [
        "PctExtResourceUrlsRT",
        "ExtMetaScriptLinkRT"
    ],

    [
        "PctExtResourceUrlsRT",
        "PctExtNullSelfRedirectHyperlinksRT"
    ],

    [
        "AbnormalExtFormActionR",
        "ExtMetaScriptLinkRT"
    ],

    [
        "AbnormalExtFormActionR",
        "PctExtNullSelfRedirectHyperlinksRT"
    ],

    [
        "ExtMetaScriptLinkRT",
        "PctExtNullSelfRedirectHyperlinksRT"
    ]
]

pair_results = {}

for pair in pairs:

    X_variant = X_baseline.copy()

    for feature in pair:
        X_variant[
            feature
        ] = np.nan

    probability = (
        model.predict_proba(
            X_variant
        )[:, 1]
    )

    prediction = (
        probability >= 0.5
    ).astype(int)

    metrics = calculate_metrics(
        y_test,
        prediction,
        probability
    )

    changed = (
        prediction
        != baseline_prediction
    )

    probability_delta = np.abs(
        probability
        - baseline_probability
    )

    pair_name = " + ".join(
        pair
    )

    result = {
        **metrics,

        "prediction_changes":
            int(changed.sum()),

        "prediction_change_rate_percent":
            float(
                changed.mean()
                * 100
            ),

        "mean_probability_delta":
            float(
                probability_delta.mean()
            ),

        "max_probability_delta":
            float(
                probability_delta.max()
            )
    }

    pair_results[
        pair_name
    ] = result

    print(
        f"\n{pair_name}"
    )

    print(
        "  Accuracy:",
        f"{result['accuracy']:.6f}"
    )

    print(
        "  F1:",
        f"{result['f1']:.6f}"
    )

    print(
        "  Prediction changes:",
        result["prediction_changes"]
    )

    print(
        "  Change rate:",
        f"{result['prediction_change_rate_percent']:.4f}%"
    )

    print(
        "  Max probability delta:",
        f"{result['max_probability_delta']:.6f}"
    )

# ============================================================
# ALL FOUR ABLATION
# ============================================================

print("\n" + "=" * 75)
print("ALL FOUR UNAVAILABLE RT FEATURES")
print("=" * 75)

X_all_missing = X_baseline.copy()

for feature in UNAVAILABLE_RT:

    X_all_missing[
        feature
    ] = np.nan

all_probability = (
    model.predict_proba(
        X_all_missing
    )[:, 1]
)

all_prediction = (
    all_probability >= 0.5
).astype(int)

all_metrics = calculate_metrics(
    y_test,
    all_prediction,
    all_probability
)

all_changed = (
    all_prediction
    != baseline_prediction
)

all_probability_delta = np.abs(
    all_probability
    - baseline_probability
)

all_result = {
    **all_metrics,

    "prediction_changes":
        int(all_changed.sum()),

    "prediction_change_rate_percent":
        float(
            all_changed.mean()
            * 100
        ),

    "mean_probability_delta":
        float(
            all_probability_delta.mean()
        ),

    "median_probability_delta":
        float(
            np.median(
                all_probability_delta
            )
        ),

    "max_probability_delta":
        float(
            all_probability_delta.max()
        )
}

print(
    "Accuracy:",
    f"{all_result['accuracy']:.6f}"
)

print(
    "Precision:",
    f"{all_result['precision']:.6f}"
)

print(
    "Recall:",
    f"{all_result['recall']:.6f}"
)

print(
    "F1:",
    f"{all_result['f1']:.6f}"
)

print(
    "Prediction changes:",
    all_result["prediction_changes"]
)

print(
    "Change rate:",
    f"{all_result['prediction_change_rate_percent']:.4f}%"
)

print(
    "Mean probability delta:",
    f"{all_result['mean_probability_delta']:.6f}"
)

print(
    "Max probability delta:",
    f"{all_result['max_probability_delta']:.6f}"
)

# ============================================================
# SAFETY CHECKS
# ============================================================

print("\n" + "=" * 75)
print("SAFETY CHECK")
print("=" * 75)

print(
    "[PASS] Frozen XGBoost only."
)

print(
    "[PASS] No model.fit() called."
)

print(
    "[PASS] No retraining."
)

print(
    "[PASS] No model modification."
)

print(
    "[PASS] No target used to generate features."
)

print(
    "[PASS] No arbitrary RT values inserted."
)

print(
    "[PASS] NaN represents missing information only."
)

# ============================================================
# CHECKPOINT
# ============================================================

checkpoint = {
    "stage": "Step 7B",

    "purpose": (
        "Measure individual and pairwise "
        "sensitivity of frozen XGBoost "
        "to unavailable RT features."
    ),

    "model_path": MODEL_PATH,

    "feature_count": 47,

    "baseline": baseline_metrics,

    "individual_ablation":
        individual_results,

    "pairwise_ablation":
        pair_results,

    "all_four_missing":
        all_result,

    "training_performed": False,

    "retraining_performed": False,

    "model_modified": False,

    "target_used_for_feature_generation":
        False,

    "arbitrary_fallback_used":
        False
}

with open(
    CHECKPOINT_PATH,
    "w"
) as f:

    json.dump(
        checkpoint,
        f,
        indent=2
    )

assert os.path.exists(
    CHECKPOINT_PATH
)

with open(
    CHECKPOINT_PATH,
    "r"
) as f:

    checkpoint_check = json.load(f)

assert (
    checkpoint_check["stage"]
    == "Step 7B"
)

print(
    "\n[PASS] Checkpoint saved and verified:"
)

print(
    CHECKPOINT_PATH
)

print("=" * 75)
print("END STEP 7B")
print("=" * 75)

===========================================================================
STEP 7B — INDIVIDUAL RT MISSING-VALUE ABLATION
===========================================================================

===========================================================================
BASELINE
===========================================================================
Accuracy : 0.988000
Precision: 0.989305
Recall   : 0.986667
F1       : 0.987984

===========================================================================
INDIVIDUAL RT ABLATION
===========================================================================

PctExtResourceUrlsRT
  Accuracy: 0.988000
  Precision: 0.989305
  Recall: 0.986667
  F1: 0.987984
  Prediction changes: 0/1500
  Change rate: 0.0000%
  Mean probability delta: 0.000390
  Max probability delta: 0.047298

AbnormalExtFormActionR
  Accuracy: 0.988000
  Precision: 0.988000
  Recall: 0.988000
  F1: 0.988000
  Prediction changes: 2/1500
  Change rate: 0.1333%
  Mean probability delta: 0.001059
  Max probability delta: 0.374608

ExtMetaScriptLinkRT
  Accuracy: 0.986667
  Precision: 0.989276
  Recall: 0.984000
  F1: 0.986631
  Prediction changes: 2/1500
  Change rate: 0.1333%
  Mean probability delta: 0.002266
  Max probability delta: 0.464373

PctExtNullSelfRedirectHyperlinksRT
  Accuracy: 0.979333
  Precision: 0.990450
  Recall: 0.968000
  F1: 0.979096
  Prediction changes: 17/1500
  Change rate: 1.1333%
  Mean probability delta: 0.016028
  Max probability delta: 0.894768

===========================================================================
PAIRWISE RT ABLATION
===========================================================================

PctExtResourceUrlsRT + AbnormalExtFormActionR
  Accuracy: 0.988000
  F1: 0.988000
  Prediction changes: 2
  Change rate: 0.1333%
  Max probability delta: 0.361454

PctExtResourceUrlsRT + ExtMetaScriptLinkRT
  Accuracy: 0.986667
  F1: 0.986631
  Prediction changes: 2
  Change rate: 0.1333%
  Max probability delta: 0.464373

PctExtResourceUrlsRT + PctExtNullSelfRedirectHyperlinksRT
  Accuracy: 0.979333
  F1: 0.979096
  Prediction changes: 17
  Change rate: 1.1333%
  Max probability delta: 0.894768

AbnormalExtFormActionR + ExtMetaScriptLinkRT
  Accuracy: 0.986667
  F1: 0.986649
  Prediction changes: 4
  Change rate: 0.2667%
  Max probability delta: 0.464373

AbnormalExtFormActionR + PctExtNullSelfRedirectHyperlinksRT
  Accuracy: 0.980000
  F1: 0.979784
  Prediction changes: 16
  Change rate: 1.0667%
  Max probability delta: 0.894768

ExtMetaScriptLinkRT + PctExtNullSelfRedirectHyperlinksRT
  Accuracy: 0.978000
  F1: 0.977688
  Prediction changes: 21
  Change rate: 1.4000%
  Max probability delta: 0.855588

===========================================================================
ALL FOUR UNAVAILABLE RT FEATURES
===========================================================================
Accuracy: 0.979333
Precision: 0.991792
Recall: 0.966667
F1: 0.979068
Prediction changes: 19
Change rate: 1.2667%
Mean probability delta: 0.017975
Max probability delta: 0.855588

===========================================================================
SAFETY CHECK
===========================================================================
[PASS] Frozen XGBoost only.
[PASS] No model.fit() called.
[PASS] No retraining.
[PASS] No model modification.
[PASS] No target used to generate features.
[PASS] No arbitrary RT values inserted.
[PASS] NaN represents missing information only.

[PASS] Checkpoint saved and verified:
/content/drive/MyDrive/PhishShield_AI/checkpoints/step_7B_rt_ablation_analysis.json
===========================================================================
END STEP 7B
===========================================================================

In [ ]:
# ============================================================
# STEP 7C — PRODUCTION-LIKE 47-FEATURE XGBOOST INPUT TEST
# ============================================================

print("=" * 75)
print("STEP 7C — PRODUCTION-LIKE 47-FEATURE XGBOOST INPUT TEST")
print("=" * 75)

import os
import json
import joblib
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

MODEL_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/models/xgboost.pkl"
)

FEATURE_NAMES_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/feature_names.pkl"
)

CHECKPOINT_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints/"
    "step_7C_production_like_xgboost_input.json"
)

assert os.path.exists(MODEL_PATH)
assert os.path.exists(FEATURE_NAMES_PATH)

# ------------------------------------------------------------
# Load frozen model + contract
# ------------------------------------------------------------

model = joblib.load(
    MODEL_PATH
)

feature_names = list(
    joblib.load(
        FEATURE_NAMES_PATH
    )
)

assert len(feature_names) == 47
assert model.n_features_in_ == 47

print(
    "\n[PASS] Frozen XGBoost loaded."
)

print(
    "[PASS] 47-feature contract loaded."
)

# ------------------------------------------------------------
# Live test URLs
# ------------------------------------------------------------

TEST_URLS = {
    "Google": "https://www.google.com",
    "Microsoft": "https://www.microsoft.com",
    "GitHub": "https://github.com",
    "Python": "https://www.python.org"
}

# ------------------------------------------------------------
# Features that are genuinely unavailable
# in the current production pipeline
# ------------------------------------------------------------

UNAVAILABLE_RT = [
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

# ------------------------------------------------------------
# Build production-like model input
# ------------------------------------------------------------

production_results = {}

for name, url in TEST_URLS.items():

    print("\n" + "=" * 75)
    print("SITE:", name)
    print("=" * 75)

    try:

        # ----------------------------------------------------
        # Build live feature dictionary
        # ----------------------------------------------------

        live_result = (
            build_live_feature_vector(url)
        )

        features = dict(
            live_result["features"]
        )

        # ----------------------------------------------------
        # Verify exact feature contract
        # ----------------------------------------------------

        assert len(features) == 47

        assert set(features.keys()) == set(
            feature_names
        )

        # ----------------------------------------------------
        # Identify None values BEFORE conversion
        # ----------------------------------------------------

        none_before = [
            feature
            for feature in feature_names
            if features[feature] is None
        ]

        print(
            "None values before NaN conversion:",
            len(none_before)
        )

        for feature in none_before:

            print(
                " -",
                feature
            )

        # ----------------------------------------------------
        # Safety:
        # Only known unavailable RT features
        # may be None.
        # ----------------------------------------------------

        unexpected_none = (
            set(none_before)
            - set(UNAVAILABLE_RT)
        )

        assert not unexpected_none, (
            "Unexpected None values: "
            f"{sorted(unexpected_none)}"
        )

        # ----------------------------------------------------
        # Convert only unavailable values to NaN
        # ----------------------------------------------------

        model_input = []

        for feature in feature_names:

            value = features[feature]

            if value is None:

                assert feature in (
                    UNAVAILABLE_RT
                )

                value = np.nan

            model_input.append(
                value
            )

        # ----------------------------------------------------
        # Create single-row DataFrame
        # ----------------------------------------------------

        X_live = pd.DataFrame(
            [model_input],
            columns=feature_names
        )

        # ----------------------------------------------------
        # Contract checks
        # ----------------------------------------------------

        assert X_live.shape == (
            1,
            47
        )

        assert list(
            X_live.columns
        ) == feature_names

        # Count NaN
        nan_features = [
            feature
            for feature in feature_names
            if pd.isna(
                X_live.loc[
                    0,
                    feature
                ]
            )
        ]

        print(
            "\nNaN values sent to XGBoost:",
            len(nan_features)
        )

        for feature in nan_features:

            print(
                " -",
                feature
            )

        assert (
            set(nan_features)
            == set(UNAVAILABLE_RT)
        )

        # ----------------------------------------------------
        # Verify all remaining features are real values
        # ----------------------------------------------------

        available_features = [
            feature
            for feature in feature_names
            if feature not in UNAVAILABLE_RT
        ]

        remaining_nan = [
            feature
            for feature in available_features
            if pd.isna(
                X_live.loc[
                    0,
                    feature
                ]
            )
        ]

        assert not remaining_nan, (
            "Unexpected NaN in available feature: "
            f"{remaining_nan}"
        )

        # ----------------------------------------------------
        # Verify XGBoost accepts the actual live vector
        # ----------------------------------------------------

        probability = (
            model.predict_proba(
                X_live
            )[0, 1]
        )

        prediction = int(
            probability >= 0.5
        )

        assert np.isfinite(
            probability
        )

        print(
            "\nXGBoost probability:",
            f"{probability:.6f}"
        )

        print(
            "XGBoost prediction:",
            prediction
        )

        # ----------------------------------------------------
        # Save result
        # ----------------------------------------------------

        production_results[name] = {
            "status": "PASS",
            "url": url,
            "feature_count": 47,
            "none_before_nan":
                none_before,
            "nan_features":
                nan_features,
            "probability":
                float(probability),
            "prediction":
                prediction
        }

        print(
            "\n[PASS]",
            name
        )

    except Exception as e:

        production_results[name] = {
            "status": "FAIL",
            "url": url,
            "error":
                f"{type(e).__name__}: {e}"
        }

        print(
            "\n[FAIL]",
            name,
            ":",
            f"{type(e).__name__}: {e}"
        )


# ============================================================
# OVERALL RESULT
# ============================================================

print("\n" + "=" * 75)
print("STEP 7C OVERALL RESULT")
print("=" * 75)

passed = sum(
    1
    for result in production_results.values()
    if result["status"] == "PASS"
)

failed = len(
    production_results
) - passed

print(
    f"Passed: {passed}/4"
)

print(
    f"Failed: {failed}/4"
)

# ============================================================
# SAFETY CHECKS
# ============================================================

print("\n" + "=" * 75)
print("SAFETY CHECK")
print("=" * 75)

print(
    "[PASS] Frozen XGBoost used."
)

print(
    "[PASS] Exactly 47 features supplied."
)

print(
    "[PASS] Feature order matches frozen contract."
)

print(
    "[PASS] None converted only to explicit NaN."
)

print(
    "[PASS] No zero fallback."
)

print(
    "[PASS] No guessed RT values."
)

print(
    "[PASS] No training performed."
)

print(
    "[PASS] No model modification."
)

# ============================================================
# CHECKPOINT
# ============================================================

checkpoint = {
    "stage": "Step 7C",

    "purpose": (
        "Validate production-like live 47-feature "
        "vector construction and frozen XGBoost "
        "inference with explicit missing RT values."
    ),

    "feature_count": 47,

    "unavailable_rt_features":
        UNAVAILABLE_RT,

    "training_performed": False,

    "retraining_performed": False,

    "model_modified": False,

    "arbitrary_zero_fallback": False,

    "invented_rt_formula": False,

    "results":
        production_results
}

with open(
    CHECKPOINT_PATH,
    "w"
) as f:

    json.dump(
        checkpoint,
        f,
        indent=2
    )

assert os.path.exists(
    CHECKPOINT_PATH
)

with open(
    CHECKPOINT_PATH,
    "r"
) as f:

    checkpoint_check = json.load(f)

assert (
    checkpoint_check["stage"]
    == "Step 7C"
)

print(
    "\n[PASS] Checkpoint saved and verified:"
)

print(
    CHECKPOINT_PATH
)

print("=" * 75)
print("END STEP 7C")
print("=" * 75)

===========================================================================
STEP 7C — PRODUCTION-LIKE 47-FEATURE XGBOOST INPUT TEST
===========================================================================

[PASS] Frozen XGBoost loaded.
[PASS] 47-feature contract loaded.

===========================================================================
SITE: Google
===========================================================================
None values before NaN conversion: 4
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

NaN values sent to XGBoost: 4
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

XGBoost probability: 0.054917
XGBoost prediction: 0

[PASS] Google

===========================================================================
SITE: Microsoft
===========================================================================
None values before NaN conversion: 4
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

NaN values sent to XGBoost: 4
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

XGBoost probability: 0.000662
XGBoost prediction: 0

[PASS] Microsoft

===========================================================================
SITE: GitHub
===========================================================================
None values before NaN conversion: 4
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

NaN values sent to XGBoost: 4
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

XGBoost probability: 0.001644
XGBoost prediction: 0

[PASS] GitHub

===========================================================================
SITE: Python
===========================================================================
None values before NaN conversion: 4
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

NaN values sent to XGBoost: 4
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

XGBoost probability: 0.001053
XGBoost prediction: 0

[PASS] Python

===========================================================================
STEP 7C OVERALL RESULT
===========================================================================
Passed: 4/4
Failed: 0/4

===========================================================================
SAFETY CHECK
===========================================================================
[PASS] Frozen XGBoost used.
[PASS] Exactly 47 features supplied.
[PASS] Feature order matches frozen contract.
[PASS] None converted only to explicit NaN.
[PASS] No zero fallback.
[PASS] No guessed RT values.
[PASS] No training performed.
[PASS] No model modification.

[PASS] Checkpoint saved and verified:
/content/drive/MyDrive/PhishShield_AI/checkpoints/step_7C_production_like_xgboost_input.json
===========================================================================
END STEP 7C
===========================================================================

In [ ]:
# ============================================================
# STEP 7D — PRODUCTION INFERENCE CONTRACT TEST
# ============================================================

print("=" * 75)
print("STEP 7D — PRODUCTION INFERENCE CONTRACT TEST")
print("=" * 75)

import os
import json
import joblib
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

MODEL_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/models/xgboost.pkl"
)

FEATURE_NAMES_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/feature_names.pkl"
)

X_TEST_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/X_test.pkl"
)

Y_TEST_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/y_test.pkl"
)

CHECKPOINT_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints/"
    "step_7D_production_inference_contract.json"
)

# ------------------------------------------------------------
# Load frozen artifacts
# ------------------------------------------------------------

model = joblib.load(
    MODEL_PATH
)

feature_names = list(
    joblib.load(
        FEATURE_NAMES_PATH
    )
)

X_test = joblib.load(
    X_TEST_PATH
)

y_test = joblib.load(
    Y_TEST_PATH
)

if not isinstance(
    X_test,
    pd.DataFrame
):
    X_test = pd.DataFrame(
        X_test,
        columns=feature_names
    )

if isinstance(
    y_test,
    pd.DataFrame
):
    y_test = y_test.iloc[:, 0]

if isinstance(
    y_test,
    np.ndarray
):
    y_test = pd.Series(
        y_test
    )

# ------------------------------------------------------------
# Contract checks
# ------------------------------------------------------------

assert len(feature_names) == 47

assert list(
    X_test.columns
) == feature_names

assert model.n_features_in_ == 47

print(
    "\n[PASS] Frozen model loaded."
)

print(
    "[PASS] Frozen feature contract loaded."
)

# ============================================================
# DEFINE PRODUCTION-STYLE INFERENCE FUNCTION
# ============================================================

def production_predict(
    feature_dict,
    model,
    feature_names,
    threshold=0.5
):
    """
    Production-style inference.

    Guarantees:

    1. Exactly the frozen 47-feature contract.
    2. Exact feature order.
    3. None -> NaN only.
    4. No missing feature silently created.
    5. No extra feature accepted.
    6. Probability returned as float.
    7. Binary decision uses fixed threshold.
    """

    # --------------------------------------------------------
    # Feature contract
    # --------------------------------------------------------

    supplied_features = set(
        feature_dict.keys()
    )

    expected_features = set(
        feature_names
    )

    missing = (
        expected_features
        - supplied_features
    )

    extra = (
        supplied_features
        - expected_features
    )

    if missing:

        raise ValueError(
            "Missing required features: "
            f"{sorted(missing)}"
        )

    if extra:

        raise ValueError(
            "Unexpected extra features: "
            f"{sorted(extra)}"
        )

    # --------------------------------------------------------
    # Ordered values
    # --------------------------------------------------------

    values = []

    for feature in feature_names:

        value = feature_dict[
            feature
        ]

        # Explicit missing-value handling.
        if value is None:

            value = np.nan

        elif isinstance(
            value,
            np.generic
        ):

            value = value.item()

        values.append(
            value
        )

    # --------------------------------------------------------
    # Create one-row DataFrame
    # --------------------------------------------------------

    X = pd.DataFrame(
        [values],
        columns=feature_names
    )

    assert X.shape == (
        1,
        47
    )

    assert list(
        X.columns
    ) == feature_names

    # --------------------------------------------------------
    # Prediction
    # --------------------------------------------------------

    probability = float(
        model.predict_proba(
            X
        )[0, 1]
    )

    prediction = int(
        probability >= threshold
    )

    return {
        "probability":
            probability,

        "prediction":
            prediction
    }


# ============================================================
# TEST 1 — RANDOM COMPLETE ROWS
# ============================================================

print("\n" + "=" * 75)
print("TEST 1 — COMPLETE DATASET ROWS")
print("=" * 75)

# Fixed indices for reproducibility.
test_indices = [
    0,
    10,
    100,
    500,
    999,
    1200,
    1499
]

complete_results = []

for index in test_indices:

    # --------------------------------------------------------
    # Reference prediction
    # --------------------------------------------------------

    X_row = X_test.iloc[
        index:index + 1
    ][feature_names]

    reference_probability = float(
        model.predict_proba(
            X_row
        )[0, 1]
    )

    reference_prediction = int(
        reference_probability >= 0.5
    )

    # --------------------------------------------------------
    # Convert row to feature dictionary
    # --------------------------------------------------------

    feature_dict = {}

    for feature in feature_names:

        value = X_test.iloc[
            index
        ][feature]

        if isinstance(
            value,
            np.generic
        ):
            value = value.item()

        feature_dict[
            feature
        ] = value

    # --------------------------------------------------------
    # Production inference
    # --------------------------------------------------------

    result = production_predict(
        feature_dict,
        model,
        feature_names
    )

    probability_difference = abs(
        result["probability"]
        - reference_probability
    )

    prediction_same = (
        result["prediction"]
        == reference_prediction
    )

    complete_results.append({
        "index": index,
        "reference_probability":
            reference_probability,
        "production_probability":
            result["probability"],
        "probability_difference":
            probability_difference,
        "reference_prediction":
            reference_prediction,
        "production_prediction":
            result["prediction"],
        "prediction_same":
            prediction_same
    })

    print(
        f"\nRow {index}"
    )

    print(
        "  Reference probability:",
        f"{reference_probability:.10f}"
    )

    print(
        "  Production probability:",
        f"{result['probability']:.10f}"
    )

    print(
        "  Difference:",
        f"{probability_difference:.12f}"
    )

    print(
        "  Reference prediction:",
        reference_prediction
    )

    print(
        "  Production prediction:",
        result["prediction"]
    )

    print(
        "  Match:",
        prediction_same
    )


# ============================================================
# TEST 2 — ALL TEST ROWS
# ============================================================

print("\n" + "=" * 75)
print("TEST 2 — FULL TEST SET CONTRACT EQUIVALENCE")
print("=" * 75)

# Reference predictions
reference_probabilities = (
    model.predict_proba(
        X_test[feature_names]
    )[:, 1]
)

reference_predictions = (
    reference_probabilities >= 0.5
).astype(int)

production_probabilities = []
production_predictions = []

for index in range(
    len(X_test)
):

    feature_dict = {}

    for feature in feature_names:

        value = X_test.iloc[
            index
        ][feature]

        if isinstance(
            value,
            np.generic
        ):
            value = value.item()

        feature_dict[
            feature
        ] = value

    result = production_predict(
        feature_dict,
        model,
        feature_names
    )

    production_probabilities.append(
        result["probability"]
    )

    production_predictions.append(
        result["prediction"]
    )

production_probabilities = np.array(
    production_probabilities
)

production_predictions = np.array(
    production_predictions
)

# ------------------------------------------------------------
# Compare
# ------------------------------------------------------------

probability_difference = np.abs(
    production_probabilities
    - reference_probabilities
)

prediction_difference = (
    production_predictions
    != reference_predictions
)

max_probability_difference = (
    probability_difference.max()
)

prediction_mismatches = int(
    prediction_difference.sum()
)

print(
    "\nTest rows:",
    len(X_test)
)

print(
    "Maximum probability difference:",
    f"{max_probability_difference:.15f}"
)

print(
    "Prediction mismatches:",
    prediction_mismatches
)

assert (
    max_probability_difference
    < 1e-12
), (
    "Production inference probability "
    "does not exactly reproduce frozen model."
)

assert (
    prediction_mismatches == 0
), (
    "Production inference predictions "
    "do not exactly match frozen model."
)

print(
    "\n[PASS] Production inference exactly "
    "matches frozen-model predictions."
)

# ============================================================
# TEST 3 — MISSING VALUE HANDLING
# ============================================================

print("\n" + "=" * 75)
print("TEST 3 — EXPLICIT NaN HANDLING")
print("=" * 75)

# Take one real test row.
sample_index = 100

sample_dict = {}

for feature in feature_names:

    value = X_test.iloc[
        sample_index
    ][feature]

    if isinstance(
        value,
        np.generic
    ):
        value = value.item()

    sample_dict[
        feature
    ] = value

# Make four RT features explicitly unavailable.
unavailable_rt = [
    "PctExtResourceUrlsRT",
    "AbnormalExtFormActionR",
    "ExtMetaScriptLinkRT",
    "PctExtNullSelfRedirectHyperlinksRT"
]

for feature in unavailable_rt:

    sample_dict[
        feature
    ] = None

missing_result = production_predict(
    sample_dict,
    model,
    feature_names
)

print(
    "Sample row:",
    sample_index
)

print(
    "Unavailable RT features:"
)

for feature in unavailable_rt:

    print(
        " -",
        feature
    )

print(
    "\nProbability with missing RT:",
    f"{missing_result['probability']:.10f}"
)

print(
    "Prediction with missing RT:",
    missing_result["prediction"]
)

assert np.isfinite(
    missing_result["probability"]
)

assert missing_result[
    "prediction"
] in [0, 1]

print(
    "\n[PASS] Explicit missing RT values "
    "successfully reach XGBoost as NaN."
)

# ============================================================
# TEST 4 — CONTRACT REJECTION
# ============================================================

print("\n" + "=" * 75)
print("TEST 4 — FEATURE CONTRACT REJECTION")
print("=" * 75)

# Missing feature test
broken_missing = dict(
    sample_dict
)

broken_missing.pop(
    feature_names[0]
)

missing_rejected = False

try:

    production_predict(
        broken_missing,
        model,
        feature_names
    )

except ValueError:

    missing_rejected = True

assert missing_rejected

print(
    "[PASS] Missing feature correctly rejected."
)

# Extra feature test
broken_extra = dict(
    sample_dict
)

broken_extra[
    "UNEXPECTED_FEATURE"
] = 123

extra_rejected = False

try:

    production_predict(
        broken_extra,
        model,
        feature_names
    )

except ValueError:

    extra_rejected = True

assert extra_rejected

print(
    "[PASS] Extra feature correctly rejected."
)

# ============================================================
# SAFETY CHECK
# ============================================================

print("\n" + "=" * 75)
print("SAFETY CHECK")
print("=" * 75)

print(
    "[PASS] Frozen XGBoost used."
)

print(
    "[PASS] No model.fit() called."
)

print(
    "[PASS] No retraining."
)

print(
    "[PASS] No model modification."
)

print(
    "[PASS] Exact 47-feature contract enforced."
)

print(
    "[PASS] Exact feature order enforced."
)

print(
    "[PASS] Missing features fail validation."
)

print(
    "[PASS] Extra features fail validation."
)

print(
    "[PASS] None -> NaN only."
)

print(
    "[PASS] No zero fallback."
)

# ============================================================
# CHECKPOINT
# ============================================================

checkpoint = {
    "stage": "Step 7D",

    "purpose": (
        "Verify production-style inference exactly "
        "matches frozen XGBoost behavior."
    ),

    "feature_count": 47,

    "test_rows": len(X_test),

    "complete_row_probability_max_difference":
        float(max_probability_difference),

    "complete_row_prediction_mismatches":
        prediction_mismatches,

    "missing_rt_features":
        unavailable_rt,

    "training_performed": False,

    "retraining_performed": False,

    "model_modified": False,

    "zero_fallback": False,

    "feature_contract_enforced": True,

    "results": {
        "complete_rows":
            complete_results,

        "missing_rt_test":
            missing_result
    }
}

with open(
    CHECKPOINT_PATH,
    "w"
) as f:

    json.dump(
        checkpoint,
        f,
        indent=2
    )

assert os.path.exists(
    CHECKPOINT_PATH
)

with open(
    CHECKPOINT_PATH,
    "r"
) as f:

    checkpoint_check = json.load(f)

assert (
    checkpoint_check["stage"]
    == "Step 7D"
)

print(
    "\n[PASS] Checkpoint saved and verified:"
)

print(
    CHECKPOINT_PATH
)

print("=" * 75)
print("END STEP 7D")
print("=" * 75)

===========================================================================
STEP 7D — PRODUCTION INFERENCE CONTRACT TEST
===========================================================================

[PASS] Frozen model loaded.
[PASS] Frozen feature contract loaded.

===========================================================================
TEST 1 — COMPLETE DATASET ROWS
===========================================================================

Row 0
  Reference probability: 0.9036412239
  Production probability: 0.9036412239
  Difference: 0.000000000000
  Reference prediction: 1
  Production prediction: 1
  Match: True

Row 10
  Reference probability: 0.0002344486
  Production probability: 0.0002344486
  Difference: 0.000000000000
  Reference prediction: 0
  Production prediction: 0
  Match: True

Row 100
  Reference probability: 0.9996149540
  Production probability: 0.9996149540
  Difference: 0.000000000000
  Reference prediction: 1
  Production prediction: 1
  Match: True

Row 500
  Reference probability: 0.9997585416
  Production probability: 0.9997585416
  Difference: 0.000000000000
  Reference prediction: 1
  Production prediction: 1
  Match: True

Row 999
  Reference probability: 0.0356252603
  Production probability: 0.0356252603
  Difference: 0.000000000000
  Reference prediction: 0
  Production prediction: 0
  Match: True

Row 1200
  Reference probability: 0.9872980118
  Production probability: 0.9872980118
  Difference: 0.000000000000
  Reference prediction: 1
  Production prediction: 1
  Match: True

Row 1499
  Reference probability: 0.0002188641
  Production probability: 0.0002188641
  Difference: 0.000000000000
  Reference prediction: 0
  Production prediction: 0
  Match: True

===========================================================================
TEST 2 — FULL TEST SET CONTRACT EQUIVALENCE
===========================================================================

Test rows: 1500
Maximum probability difference: 0.000000000000000
Prediction mismatches: 0

[PASS] Production inference exactly matches frozen-model predictions.

===========================================================================
TEST 3 — EXPLICIT NaN HANDLING
===========================================================================
Sample row: 100
Unavailable RT features:
 - PctExtResourceUrlsRT
 - AbnormalExtFormActionR
 - ExtMetaScriptLinkRT
 - PctExtNullSelfRedirectHyperlinksRT

Probability with missing RT: 0.9295887351
Prediction with missing RT: 1

[PASS] Explicit missing RT values successfully reach XGBoost as NaN.

===========================================================================
TEST 4 — FEATURE CONTRACT REJECTION
===========================================================================
[PASS] Missing feature correctly rejected.
[PASS] Extra feature correctly rejected.

===========================================================================
SAFETY CHECK
===========================================================================
[PASS] Frozen XGBoost used.
[PASS] No model.fit() called.
[PASS] No retraining.
[PASS] No model modification.
[PASS] Exact 47-feature contract enforced.
[PASS] Exact feature order enforced.
[PASS] Missing features fail validation.
[PASS] Extra features fail validation.
[PASS] None -> NaN only.
[PASS] No zero fallback.

[PASS] Checkpoint saved and verified:
/content/drive/MyDrive/PhishShield_AI/checkpoints/step_7D_production_inference_contract.json
===========================================================================
END STEP 7D
===========================================================================

In [ ]:
# ============================================================
# STEP 7E — XGBOOST PROBABILITY & CLASS SEMANTICS VERIFICATION
# ============================================================

print("=" * 75)
print("STEP 7E — XGBOOST PROBABILITY & CLASS SEMANTICS VERIFICATION")
print("=" * 75)

import os
import json
import joblib
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

MODEL_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/models/xgboost.pkl"
)

FEATURE_NAMES_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/feature_names.pkl"
)

X_TEST_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/X_test.pkl"
)

Y_TEST_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/data/y_test.pkl"
)

CHECKPOINT_PATH = (
    "/content/drive/MyDrive/"
    "PhishShield_AI/checkpoints/"
    "step_7E_probability_semantics.json"
)

# ------------------------------------------------------------
# Load frozen artifacts
# ------------------------------------------------------------

model = joblib.load(
    MODEL_PATH
)

feature_names = list(
    joblib.load(
        FEATURE_NAMES_PATH
    )
)

X_test = joblib.load(
    X_TEST_PATH
)

y_test = joblib.load(
    Y_TEST_PATH
)

if not isinstance(
    X_test,
    pd.DataFrame
):
    X_test = pd.DataFrame(
        X_test,
        columns=feature_names
    )

if isinstance(
    y_test,
    pd.DataFrame
):
    y_test = y_test.iloc[:, 0]

if isinstance(
    y_test,
    np.ndarray
):
    y_test = pd.Series(
        y_test
    )

# ------------------------------------------------------------
# Basic checks
# ------------------------------------------------------------

assert model.n_features_in_ == 47
assert list(X_test.columns) == feature_names

print(
    "\n[PASS] Frozen XGBoost loaded."
)

print(
    "[PASS] 47-feature contract verified."
)

# ============================================================
# TEST 1 — CLASS ORDER
# ============================================================

print("\n" + "=" * 75)
print("TEST 1 — MODEL CLASS ORDER")
print("=" * 75)

print(
    "model.classes_:",
    model.classes_
)

assert list(
    model.classes_
) == [0, 1]

print(
    "\n[PASS] Class order is exactly [0, 1]."
)

# ============================================================
# TEST 2 — PROBABILITY COLUMN SEMANTICS
# ============================================================

print("\n" + "=" * 75)
print("TEST 2 — PROBABILITY COLUMN SEMANTICS")
print("=" * 75)

probabilities = model.predict_proba(
    X_test
)

assert probabilities.shape == (
    len(X_test),
    2
)

prob_class_0 = probabilities[:, 0]
prob_class_1 = probabilities[:, 1]

print(
    "Probability matrix shape:",
    probabilities.shape
)

print(
    "Class 0 probability range:",
    f"{prob_class_0.min():.10f}",
    "to",
    f"{prob_class_0.max():.10f}"
)

print(
    "Class 1 probability range:",
    f"{prob_class_1.min():.10f}",
    "to",
    f"{prob_class_1.max():.10f}"
)

# Probabilities must sum to 1.
probability_sums = (
    prob_class_0
    + prob_class_1
)

max_sum_error = np.max(
    np.abs(
        probability_sums - 1.0
    )
)

print(
    "Maximum probability sum error:",
    f"{max_sum_error:.15f}"
)

assert np.all(
    prob_class_0 >= 0
)

assert np.all(
    prob_class_0 <= 1
)

assert np.all(
    prob_class_1 >= 0
)

assert np.all(
    prob_class_1 <= 1
)

assert (
    max_sum_error < 1e-12
)

print(
    "\n[PASS] Probability outputs are valid."
)

# ============================================================
# TEST 3 — CLASS 1 PROBABILITY VS TRUE LABEL
# ============================================================

print("\n" + "=" * 75)
print("TEST 3 — CLASS 1 PROBABILITY VS TRUE LABEL")
print("=" * 75)

y_array = np.asarray(
    y_test
).astype(int)

mean_probability_class_0 = (
    prob_class_1[
        y_array == 0
    ].mean()
)

mean_probability_class_1 = (
    prob_class_1[
        y_array == 1
    ].mean()
)

print(
    "Mean P(class=1) for true class 0:",
    f"{mean_probability_class_0:.6f}"
)

print(
    "Mean P(class=1) for true class 1:",
    f"{mean_probability_class_1:.6f}"
)

assert (
    mean_probability_class_0
    <
    mean_probability_class_1
)

print(
    "\n[PASS] P(class=1) correctly separates "
    "the two dataset classes."
)

# ============================================================
# TEST 4 — 0.5 DECISION THRESHOLD
# ============================================================

print("\n" + "=" * 75)
print("TEST 4 — 0.5 DECISION THRESHOLD")
print("=" * 75)

manual_predictions = (
    prob_class_1 >= 0.5
).astype(int)

model_predictions = (
    model.predict(
        X_test
    ).astype(int)
)

threshold_mismatches = int(
    np.sum(
        manual_predictions
        !=
        model_predictions
    )
)

print(
    "Threshold mismatches:",
    threshold_mismatches
)

assert (
    threshold_mismatches == 0
)

print(
    "\n[PASS] 0.5 threshold exactly reproduces "
    "model.predict()."
)

# ============================================================
# TEST 5 — EXTREME PROBABILITY EXAMPLES
# ============================================================

print("\n" + "=" * 75)
print("TEST 5 — REPRESENTATIVE PROBABILITY EXAMPLES")
print("=" * 75)

# Lowest class-1 probability
low_index = int(
    np.argmin(
        prob_class_1
    )
)

# Highest class-1 probability
high_index = int(
    np.argmax(
        prob_class_1
    )
)

# Probability closest to 0.5
middle_index = int(
    np.argmin(
        np.abs(
            prob_class_1 - 0.5
        )
    )
)

representative_indices = [
    ("LOW", low_index),
    ("MIDDLE", middle_index),
    ("HIGH", high_index)
]

representatives = {}

for label, index in representative_indices:

    probability = float(
        prob_class_1[index]
    )

    prediction = int(
        probability >= 0.5
    )

    true_label = int(
        y_array[index]
    )

    print(
        f"\n{label} probability example"
    )

    print(
        "  Test index:",
        index
    )

    print(
        "  P(class=1):",
        f"{probability:.10f}"
    )

    print(
        "  Model prediction:",
        prediction
    )

    print(
        "  True class:",
        true_label
    )

    representatives[label] = {
        "index": index,
        "probability":
            probability,
        "prediction":
            prediction,
        "true_label":
            true_label
    }

# ============================================================
# TEST 6 — ML OUTPUT CONTRACT
# ============================================================

print("\n" + "=" * 75)
print("TEST 6 — ML OUTPUT CONTRACT")
print("=" * 75)

# Test the production-style contract on
# representative complete rows.

def ml_output_contract(
    feature_row,
    model,
    feature_names,
    threshold=0.5
):

    supplied = set(
        feature_row.keys()
    )

    expected = set(
        feature_names
    )

    missing = (
        expected - supplied
    )

    extra = (
        supplied - expected
    )

    if missing:

        raise ValueError(
            "Missing features: "
            f"{sorted(missing)}"
        )

    if extra:

        raise ValueError(
            "Extra features: "
            f"{sorted(extra)}"
        )

    ordered_values = []

    for feature in feature_names:

        value = feature_row[
            feature
        ]

        if value is None:

            value = np.nan

        elif isinstance(
            value,
            np.generic
        ):

            value = value.item()

        ordered_values.append(
            value
        )

    X = pd.DataFrame(
        [ordered_values],
        columns=feature_names
    )

    probability = float(
        model.predict_proba(
            X
        )[0, 1]
    )

    prediction = int(
        probability >= threshold
    )

    return {
        "ml_probability":
            probability,

        "ml_prediction":
            prediction,

        "threshold":
            threshold,

        "class_0_probability":
            float(
                1.0 - probability
            ),

        "class_1_probability":
            probability
    }


contract_results = []

for label, index in representative_indices:

    row = {}

    for feature in feature_names:

        value = X_test.iloc[
            index
        ][feature]

        if isinstance(
            value,
            np.generic
        ):
            value = value.item()

        row[
            feature
        ] = value

    result = ml_output_contract(
        row,
        model,
        feature_names
    )

    reference_probability = float(
        prob_class_1[index]
    )

    reference_prediction = int(
        model_predictions[index]
    )

    probability_difference = abs(
        result["ml_probability"]
        - reference_probability
    )

    prediction_same = (
        result["ml_prediction"]
        == reference_prediction
    )

    assert (
        probability_difference
        < 1e-12
    )

    assert prediction_same

    contract_results.append({
        "label": label,
        "index": index,
        "ml_probability":
            result["ml_probability"],
        "ml_prediction":
            result["ml_prediction"],
        "probability_difference":
            probability_difference,
        "prediction_same":
            prediction_same
    })

    print(
        f"\n[{label}]"
    )

    print(
        "  ML probability:",
        f"{result['ml_probability']:.10f}"
    )

    print(
        "  ML prediction:",
        result["ml_prediction"]
    )

    print(
        "  Contract match:",
        prediction_same
    )

print(
    "\n[PASS] ML output contract verified."
)

# ============================================================
# SAFETY CHECK
# ============================================================

print("\n" + "=" * 75)
print("SAFETY CHECK")
print("=" * 75)

print(
    "[PASS] Frozen XGBoost used."
)

print(
    "[PASS] No model.fit() called."
)

print(
    "[PASS] No retraining."
)

print(
    "[PASS] No model modification."
)

print(
    "[PASS] Class order verified."
)

print(
    "[PASS] Probability semantics verified."
)

print(
    "[PASS] 0.5 threshold verified."
)

print(
    "[PASS] Probability range verified."
)

# ============================================================
# CHECKPOINT
# ============================================================

checkpoint = {
    "stage": "Step 7E",

    "purpose": (
        "Verify frozen XGBoost class ordering, "
        "probability semantics, threshold behavior, "
        "and ML output contract."
    ),

    "classes":
        model.classes_.tolist(),

    "feature_count": 47,

    "probability_sum_max_error":
        float(max_sum_error),

    "mean_p_class1_true_class0":
        float(mean_probability_class_0),

    "mean_p_class1_true_class1":
        float(mean_probability_class_1),

    "threshold":
        0.5,

    "threshold_mismatches":
        threshold_mismatches,

    "training_performed": False,

    "retraining_performed": False,

    "model_modified": False,

    "results": {
        "representatives":
            representatives,

        "contract_tests":
            contract_results
    }
}

with open(
    CHECKPOINT_PATH,
    "w"
) as f:

    json.dump(
        checkpoint,
        f,
        indent=2
    )

assert os.path.exists(
    CHECKPOINT_PATH
)

with open(
    CHECKPOINT_PATH,
    "r"
) as f:

    checkpoint_check = json.load(f)

assert (
    checkpoint_check["stage"]
    == "Step 7E"
)

print(
    "\n[PASS] Checkpoint saved and verified:"
)

print(
    CHECKPOINT_PATH
)

print("=" * 75)
print("END STEP 7E")
print("=" * 75)

===========================================================================
STEP 7E — XGBOOST PROBABILITY & CLASS SEMANTICS VERIFICATION
===========================================================================

[PASS] Frozen XGBoost loaded.
[PASS] 47-feature contract verified.

===========================================================================
TEST 1 — MODEL CLASS ORDER
===========================================================================
model.classes_: [0 1]

[PASS] Class order is exactly [0, 1].

===========================================================================
TEST 2 — PROBABILITY COLUMN SEMANTICS
===========================================================================
Probability matrix shape: (1500, 2)
Class 0 probability range: 0.0000358820 to 0.9999877810
Class 1 probability range: 0.0000122074 to 0.9999641180
Maximum probability sum error: 0.000000000000000

[PASS] Probability outputs are valid.

===========================================================================
TEST 3 — CLASS 1 PROBABILITY VS TRUE LABEL
===========================================================================
Mean P(class=1) for true class 0: 0.019754
Mean P(class=1) for true class 1: 0.978378

[PASS] P(class=1) correctly separates the two dataset classes.

===========================================================================
TEST 4 — 0.5 DECISION THRESHOLD
===========================================================================
Threshold mismatches: 0

[PASS] 0.5 threshold exactly reproduces model.predict().

===========================================================================
TEST 5 — REPRESENTATIVE PROBABILITY EXAMPLES
===========================================================================

LOW probability example
  Test index: 961
  P(class=1): 0.0000122074
  Model prediction: 0
  True class: 0

MIDDLE probability example
  Test index: 1298
  P(class=1): 0.4792812169
  Model prediction: 0
  True class: 1

HIGH probability example
  Test index: 234
  P(class=1): 0.9999641180
  Model prediction: 1
  True class: 1

===========================================================================
TEST 6 — ML OUTPUT CONTRACT
===========================================================================

[LOW]
  ML probability: 0.0000122074
  ML prediction: 0
  Contract match: True

[MIDDLE]
  ML probability: 0.4792812169
  ML prediction: 0
  Contract match: True

[HIGH]
  ML probability: 0.9999641180
  ML prediction: 1
  Contract match: True

[PASS] ML output contract verified.

===========================================================================
SAFETY CHECK
===========================================================================
[PASS] Frozen XGBoost used.
[PASS] No model.fit() called.
[PASS] No retraining.
[PASS] No model modification.
[PASS] Class order verified.
[PASS] Probability semantics verified.
[PASS] 0.5 threshold verified.
[PASS] Probability range verified.

[PASS] Checkpoint saved and verified:
/content/drive/MyDrive/PhishShield_AI/checkpoints/step_7E_probability_semantics.json
===========================================================================
END STEP 7E
===========================================================================

In [ ]:
# ============================================================
# PHISHSHIELD AI — FINAL XGBOOST MODEL FREEZE
# ============================================================

import os
import shutil
import joblib
import hashlib
import json
from datetime import datetime

# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

SOURCE_MODEL = "/content/drive/MyDrive/PhishShield_AI/models/xgboost.pkl"
SOURCE_FEATURES = "/content/drive/MyDrive/PhishShield_AI/data/feature_names.pkl"
SOURCE_RT = "/content/drive/MyDrive/PhishShield_AI/data/verified_rt_lookup_mappings.pkl"

FROZEN_DIR = "/content/drive/MyDrive/PhishShield_AI/frozen_production"
os.makedirs(FROZEN_DIR, exist_ok=True)

FROZEN_MODEL = os.path.join(FROZEN_DIR, "xgboost_frozen.pkl")
FROZEN_FEATURES = os.path.join(FROZEN_DIR, "feature_names.pkl")
FROZEN_RT = os.path.join(FROZEN_DIR, "verified_rt_lookup_mappings.pkl")
FROZEN_METADATA = os.path.join(FROZEN_DIR, "model_metadata.json")


# ------------------------------------------------------------
# 2. Verify source files exist
# ------------------------------------------------------------

required_files = {
    "XGBoost model": SOURCE_MODEL,
    "Feature names": SOURCE_FEATURES,
    "Verified RT mappings": SOURCE_RT
}

for name, path in required_files.items():
    if not os.path.exists(path):
        raise FileNotFoundError(f"{name} not found: {path}")

print("✓ All required source artifacts found")


# ------------------------------------------------------------
# 3. Load and verify model
# ------------------------------------------------------------

model = joblib.load(SOURCE_MODEL)
feature_names = joblib.load(SOURCE_FEATURES)
rt_mappings = joblib.load(SOURCE_RT)

print(f"✓ XGBoost model loaded: {type(model).__name__}")
print(f"✓ Feature count: {len(feature_names)}")
print(f"✓ RT mapping artifact loaded: {type(rt_mappings).__name__}")


# ------------------------------------------------------------
# 4. Validate frozen model contract
# ------------------------------------------------------------

assert len(feature_names) == 47, (
    f"Expected 47 features, found {len(feature_names)}"
)

assert hasattr(model, "predict"), "Model does not support predict()"
assert hasattr(model, "predict_proba"), "Model does not support predict_proba()"

if hasattr(model, "n_features_in_"):
    assert model.n_features_in_ == 47, (
        f"Model expects {model.n_features_in_} features, not 47"
    )

if hasattr(model, "classes_"):
    print(f"✓ Model classes: {model.classes_}")

print("✓ 47-feature model contract verified")


# ------------------------------------------------------------
# 5. Copy artifacts into dedicated frozen-production folder
# ------------------------------------------------------------

shutil.copy2(SOURCE_MODEL, FROZEN_MODEL)
shutil.copy2(SOURCE_FEATURES, FROZEN_FEATURES)
shutil.copy2(SOURCE_RT, FROZEN_RT)

print("✓ Frozen production artifacts copied")


# ------------------------------------------------------------
# 6. Generate SHA-256 hashes
# ------------------------------------------------------------

def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


model_hash = sha256_file(FROZEN_MODEL)
features_hash = sha256_file(FROZEN_FEATURES)
rt_hash = sha256_file(FROZEN_RT)


# ------------------------------------------------------------
# 7. Save production metadata
# ------------------------------------------------------------

metadata = {
    "project": "PhishShield AI",
    "status": "FROZEN_PRODUCTION_MODEL",
    "primary_model": "XGBoost",
    "model_file": "xgboost_frozen.pkl",
    "feature_file": "feature_names.pkl",
    "rt_mapping_file": "verified_rt_lookup_mappings.pkl",

    "feature_count": 47,
    "classification_threshold": 0.5,
    "phishing_probability": "predict_proba(X)[:, 1]",
    "model_classes": (
        model.classes_.tolist()
        if hasattr(model, "classes_")
        else None
    ),

    "feature_contract": {
        "exact_feature_count": 47,
        "missing_feature_policy": "fail_validation",
        "extra_feature_policy": "fail_validation",
        "silent_zero_fallback": False,
        "invented_rt_formula": False,
        "unavailable_rt_representation": "NaN"
    },

    "validation": {
        "held_out_test_accuracy": 0.988000,
        "held_out_test_precision": 0.989305,
        "held_out_test_recall": 0.986667,
        "held_out_test_f1": 0.987984,
        "roc_auc": 0.9995
    },

    "sha256": {
        "xgboost_frozen.pkl": model_hash,
        "feature_names.pkl": features_hash,
        "verified_rt_lookup_mappings.pkl": rt_hash
    },

    "frozen_at": datetime.now().isoformat()
}

with open(FROZEN_METADATA, "w") as f:
    json.dump(metadata, f, indent=2)

print("✓ Production metadata saved")


# ------------------------------------------------------------
# 8. Reload frozen model and verify it is usable
# ------------------------------------------------------------

frozen_model = joblib.load(FROZEN_MODEL)

assert type(frozen_model).__name__ == type(model).__name__

if hasattr(frozen_model, "n_features_in_"):
    assert frozen_model.n_features_in_ == 47

if hasattr(frozen_model, "classes_"):
    assert frozen_model.classes_.tolist() == [0, 1]

print("✓ Frozen model successfully reloaded and verified")


# ------------------------------------------------------------
# 9. Final output
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("PHISHSHIELD AI — MODEL FREEZE COMPLETE")
print("=" * 65)

print(f"Model       : {FROZEN_MODEL}")
print(f"Features    : {FROZEN_FEATURES}")
print(f"RT mappings : {FROZEN_RT}")
print(f"Metadata    : {FROZEN_METADATA}")

print("\nModel       : XGBoost")
print("Features    : 47")
print("Threshold   : 0.5")
print("Class 1     : Phishing")
print("Status      : FROZEN — DO NOT RETRAIN")

print("\nSHA-256:")
print(f"XGBoost     : {model_hash}")
print(f"Features    : {features_hash}")
print(f"RT mappings : {rt_hash}")

print("\n✓ READY FOR ANTIGRAVITY BACKEND INTEGRATION")

✓ All required source artifacts found
✓ XGBoost model loaded: XGBClassifier
✓ Feature count: 47
✓ RT mapping artifact loaded: dict
✓ Model classes: [0 1]
✓ 47-feature model contract verified
✓ Frozen production artifacts copied
✓ Production metadata saved
✓ Frozen model successfully reloaded and verified

=================================================================
PHISHSHIELD AI — MODEL FREEZE COMPLETE
=================================================================
Model       : /content/drive/MyDrive/PhishShield_AI/frozen_production/xgboost_frozen.pkl
Features    : /content/drive/MyDrive/PhishShield_AI/frozen_production/feature_names.pkl
RT mappings : /content/drive/MyDrive/PhishShield_AI/frozen_production/verified_rt_lookup_mappings.pkl
Metadata    : /content/drive/MyDrive/PhishShield_AI/frozen_production/model_metadata.json

Model       : XGBoost
Features    : 47
Threshold   : 0.5
Class 1     : Phishing
Status      : FROZEN — DO NOT RETRAIN

SHA-256:
XGBoost     : 9b30e6fd823d7e490a08f69a61eff4f36e49ada5bbe434b126a84d685acf8a80
Features    : e5090fdc7c5b6396ccdd48b3f21442fb4a88dbc6b5fed6c6e361aee33955c514
RT mappings : 4dae1e27d0423a37ed39eea52998f56e6ef7c6f56f8de05befa2fd9b67030bf9

✓ READY FOR ANTIGRAVITY BACKEND INTEGRATION